"""Validate destinations before redirecting an authenticated user to the frontend."""

import posixpath
import re
from urllib.parse import parse_qs, unquote, urlparse, urlsplit

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.http import HttpRequest, HttpResponse

from mozilla_django_oidc.views import OIDCAuthenticationCallbackView


def validate_login_destination(destination: str | None) -> str:
    """Allow local application paths while preventing external redirects and loops."""
    if not destination or not destination.startswith("/"):
        return "/home"
    try:
        decoded = unquote(destination, errors="strict")
        if (
            decoded.startswith("//")
            or re.search(r"[\x00-\x1f\x7f\\]", decoded)
            or re.search(r"%(?![0-9a-fA-F]{2})", destination)
        ):
            return "/home"
        url = urlsplit(decoded)
        pathname = posixpath.normpath(url.path).rstrip("/").lower()
        if url.netloc or url.scheme or pathname in ("", "/login"):
            return "/home"
    except (ValueError, UnicodeError):
        return "/home"
    return destination


def frontend_login_url(user: AbstractUser, destination: str | None) -> str:
    """Keep the existing admin handoff for OCIO users; send others to their page."""
    path = validate_login_destination(destination)
    if user.groups.filter(name="ACF OCIO").exists():
        path = "/login"
    return settings.FRONTEND_BASE_URL.rstrip("/") + path


class LoginDestinationMixin:
    """Attach destinations to individual Keycloak states, including concurrent logins."""

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """Store the destination with the state generated by the OIDC library."""
        response = super().get(request, *args, **kwargs)
        state = parse_qs(urlparse(response["Location"]).query).get("state", [None])[0]
        states = request.session.get("oidc_states", {}).copy()
        if state in states:
            states[state] = {
                **states[state],
                "next": validate_login_destination(request.GET.get("next")),
            }
            request.session["oidc_states"] = states
        return response


class KeycloakOIDCCallbackView(OIDCAuthenticationCallbackView):
    """Redirect to the destination only after the library validates authentication."""

    def get(self, request: HttpRequest) -> HttpResponse:
        """Capture the destination before the OIDC library consumes its state."""
        state = request.GET.get("state")
        tracker = request.session.get("oidc_states", {}).get(state, {})
        self.has_login_destination = "next" in tracker
        self.login_destination = tracker.get("next")
        return super().get(request)

    @property
    def success_url(self) -> str:
        """Use the authenticated user's destination instead of a shared next value."""
        if not self.has_login_destination:
            # Silent session refresh uses the library's existing return URL.
            return super().success_url
        return frontend_login_url(self.user, self.login_destination)
