# Base Docker compose for all environments
version: "3.4"

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081" # Web interface
      - "8082:8082" # Docker registry

volumes:
  nexus-data:


networks:
  default:
      name: external-net
      external: true
