CREATE ROLE readaccess;
GRANT CONNECT ON DATABASE $DB_NAME TO readaccess;
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;
CREATE USER $GRAFANA_USER WITH PASSWORD '$GRAFANA_PASSWORD';
GRANT readaccess TO $GRAFANA_USER;