CREATE ROLE readaccess;
GRANT CONNECT ON DATABASE $DB_NAME TO readaccess;
GRANT USAGE ON SCHEMA public TO readaccess;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;
CREATE USER $GRAFANA_USER WITH PASSWORD '$GRAFANA_PASSWORD';
GRANT readaccess TO $GRAFANA_USER;

CREATE ROLE OFA_DB_ADMIN;
GRANT CONNECT ON DATABASE $DB_NAME TO OFA_DB_ADMIN;
GRANT USAGE ON SCHEMA public TO OFA_DB_ADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA public TO OFA_DB_ADMIN;
GRANT pg_read_all_data TO OFA_DB_ADMIN;
GRANT pg_write_all_data TO OFA_DB_ADMIN;
CREATE USER $OFA_DB_USER WITH PASSWORD '$OFA_DB_PASSWORD';
GRANT OFA_DB_ADMIN TO $OFA_DB_USER;

CREATE ROLE DIGIT_READONLY;
GRANT CONNECT ON DATABASE $DB_NAME TO DIGIT_READONLY;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM DIGIT_READONLY;
CREATE USER $DIGIT_READONLY_USER WITH PASSWORD '$DIGIT_READONLY_PASSWORD';
GRANT DIGIT_READONLY TO $DIGIT_READONLY_USER;
