site_name: tdpservice
site_description: Backend API Service TDP
repo_url: https://github.com/raft-tech/TANF-app/raft-tdp-main
site_dir: site
copyright: Copyright &copy; 2020.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
