package converter

import (
	"go-parser/internal/db"
	"go-parser/internal/schema"
)

// SSP M1 Converter - Case-level data for active SSP cases

func convertSspM1(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesSspM1{
		RecordType:               toText(f["RecordType"]),
		RPTMONTHYEAR:             toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:               toText(f["CASE_NUMBER"]),
		FIPSCODE:                 toText(f["FIPS_CODE"]),
		COUNTYFIPSCODE:           toText(f["COUNTY_FIPS_CODE"]),
		STRATUM:                  toText(f["STRATUM"]),
		ZIPCODE:                  toText(f["ZIP_CODE"]),
		DISPOSITION:              toInt4(f["DISPOSITION"]),
		NBRFAMILYMEMBERS:         toInt4(f["NBR_FAMILY_MEMBERS"]),
		FAMILYTYPE:               toInt4(f["FAMILY_TYPE"]),
		TANFASSTIN6MONTHS:        toInt4(f["TANF_ASST_IN_6MONTHS"]),
		RECEIVESSUBHOUSING:       toInt4(f["RECEIVES_SUB_HOUSING"]),
		RECEIVESMEDASSISTANCE:    toInt4(f["RECEIVES_MED_ASSISTANCE"]),
		RECEIVESFOODSTAMPS:       toInt4(f["RECEIVES_FOOD_STAMPS"]),
		AMTFOODSTAMPASSISTANCE:   toInt4(f["AMT_FOOD_STAMP_ASSISTANCE"]),
		RECEIVESSUBCC:            toInt4(f["RECEIVES_SUB_CC"]),
		AMTSUBCC:                 toInt4(f["AMT_SUB_CC"]),
		CHILDSUPPORTAMT:          toInt4(f["CHILD_SUPPORT_AMT"]),
		FAMILYCASHRESOURCES:      toInt4(f["FAMILY_CASH_RESOURCES"]),
		CASHAMOUNT:               toInt4(f["CASH_AMOUNT"]),
		NBRMONTHS:                toInt4(f["NBR_MONTHS"]),
		CCAMOUNT:                 toInt4(f["CC_AMOUNT"]),
		CHILDRENCOVERED:          toInt4(f["CHILDREN_COVERED"]),
		CCNBRMONTHS:              toInt4(f["CC_NBR_MONTHS"]),
		TRANSPAMOUNT:             toInt4(f["TRANSP_AMOUNT"]),
		TRANSPNBRMONTHS:          toInt4(f["TRANSP_NBR_MONTHS"]),
		TRANSITIONSERVICESAMOUNT: toInt4(f["TRANSITION_SERVICES_AMOUNT"]),
		TRANSITIONNBRMONTHS:      toInt4(f["TRANSITION_NBR_MONTHS"]),
		OTHERAMOUNT:              toInt4(f["OTHER_AMOUNT"]),
		OTHERNBRMONTHS:           toInt4(f["OTHER_NBR_MONTHS"]),
		SANCREDUCTIONAMT:         toInt4(f["SANC_REDUCTION_AMT"]),
		WORKREQSANCTION:          toInt4(f["WORK_REQ_SANCTION"]),
		FAMILYSANCADULT:          toInt4(f["FAMILY_SANC_ADULT"]),
		SANCTEENPARENT:           toInt4(f["SANC_TEEN_PARENT"]),
		NONCOOPERATIONCSE:        toInt4(f["NON_COOPERATION_CSE"]),
		FAILURETOCOMPLY:          toInt4(f["FAILURE_TO_COMPLY"]),
		OTHERSANCTION:            toInt4(f["OTHER_SANCTION"]),
		RECOUPMENTPRIOROVRPMT:    toInt4(f["RECOUPMENT_PRIOR_OVRPMT"]),
		OTHERTOTALREDUCTIONS:     toInt4(f["OTHER_TOTAL_REDUCTIONS"]),
		FAMILYCAP:                toInt4(f["FAMILY_CAP"]),
		REDUCTIONSONRECEIPTS:     toInt4(f["REDUCTIONS_ON_RECEIPTS"]),
		OTHERNONSANCTION:         toInt4(f["OTHER_NON_SANCTION"]),
		WAIVEREVALCONTROLGRPS:    toInt4(f["WAIVER_EVAL_CONTROL_GRPS"]),
		ID:                       newUUID(),
		DatafileID:               toDatafileID(datafileID),
		LineNumber:               toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FIPSCODE,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.DISPOSITION,
		rec.NBRFAMILYMEMBERS,
		rec.FAMILYTYPE,
		rec.TANFASSTIN6MONTHS,
		rec.RECEIVESSUBHOUSING,
		rec.RECEIVESMEDASSISTANCE,
		rec.RECEIVESFOODSTAMPS,
		rec.AMTFOODSTAMPASSISTANCE,
		rec.RECEIVESSUBCC,
		rec.AMTSUBCC,
		rec.CHILDSUPPORTAMT,
		rec.FAMILYCASHRESOURCES,
		rec.CASHAMOUNT,
		rec.NBRMONTHS,
		rec.CCAMOUNT,
		rec.CHILDRENCOVERED,
		rec.CCNBRMONTHS,
		rec.TRANSPAMOUNT,
		rec.TRANSPNBRMONTHS,
		rec.TRANSITIONSERVICESAMOUNT,
		rec.TRANSITIONNBRMONTHS,
		rec.OTHERAMOUNT,
		rec.OTHERNBRMONTHS,
		rec.SANCREDUCTIONAMT,
		rec.WORKREQSANCTION,
		rec.FAMILYSANCADULT,
		rec.SANCTEENPARENT,
		rec.NONCOOPERATIONCSE,
		rec.FAILURETOCOMPLY,
		rec.OTHERSANCTION,
		rec.RECOUPMENTPRIOROVRPMT,
		rec.OTHERTOTALREDUCTIONS,
		rec.FAMILYCAP,
		rec.REDUCTIONSONRECEIPTS,
		rec.OTHERNONSANCTION,
		rec.WAIVEREVALCONTROLGRPS,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M2 Converter - Adult-level data for active SSP cases

func convertSspM2(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesSspM2{
		RecordType:              toText(f["RecordType"]),
		RPTMONTHYEAR:            toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:              toText(f["CASE_NUMBER"]),
		FIPSCODE:                toText(f["FIPS_CODE"]),
		FAMILYAFFILIATION:       toInt4(f["FAMILY_AFFILIATION"]),
		NONCUSTODIALPARENT:      toInt4(f["NONCUSTODIAL_PARENT"]),
		DATEOFBIRTH:             toText(f["DATE_OF_BIRTH"]),
		SSN:                     toText(f["SSN"]),
		RACEHISPANIC:            toInt4(f["RACE_HISPANIC"]),
		RACEAMERINDIAN:          toInt4(f["RACE_AMER_INDIAN"]),
		RACEASIAN:               toInt4(f["RACE_ASIAN"]),
		RACEBLACK:               toInt4(f["RACE_BLACK"]),
		RACEHAWAIIAN:            toInt4(f["RACE_HAWAIIAN"]),
		RACEWHITE:               toInt4(f["RACE_WHITE"]),
		SEX:                     toInt4(f["SEX"]),
		FEDOASDIPROGRAM:         toInt4(f["FED_OASDI_PROGRAM"]),
		FEDDISABILITYSTATUS:     toInt4(f["FED_DISABILITY_STATUS"]),
		DISABLEDTITLEXIVAPDT:    toInt4(f["DISABLED_TITLE_XIVAPDT"]),
		AIDAGEDBLIND:            toInt4(f["AID_AGED_BLIND"]),
		RECEIVESSI:              toInt4(f["RECEIVE_SSI"]),
		MARITALSTATUS:           toInt4(f["MARITAL_STATUS"]),
		RELATIONSHIPHOH:         toInt4(f["RELATIONSHIP_HOH"]),
		PARENTMINORCHILD:        toInt4(f["PARENT_MINOR_CHILD"]),
		NEEDSPREGNANTWOMAN:      toInt4(f["NEEDS_PREGNANT_WOMAN"]),
		EDUCATIONLEVEL:          toText(f["EDUCATION_LEVEL"]),
		CITIZENSHIPSTATUS:       toInt4(f["CITIZENSHIP_STATUS"]),
		COOPERATIONCHILDSUPPORT: toInt4(f["COOPERATION_CHILD_SUPPORT"]),
		EMPLOYMENTSTATUS:        toInt4(f["EMPLOYMENT_STATUS"]),
		WORKELIGIBLEINDICATOR:   toInt4(f["WORK_ELIGIBLE_INDICATOR"]),
		WORKPARTSTATUS:          toInt4(f["WORK_PART_STATUS"]),
		UNSUBEMPLOYMENT:         toInt4(f["UNSUB_EMPLOYMENT"]),
		SUBPRIVATEEMPLOYMENT:    toInt4(f["SUB_PRIVATE_EMPLOYMENT"]),
		SUBPUBLICEMPLOYMENT:     toInt4(f["SUB_PUBLIC_EMPLOYMENT"]),
		WORKEXPERIENCEHOP:       toInt4(f["WORK_EXPERIENCE_HOP"]),
		WORKEXPERIENCEEA:        toInt4(f["WORK_EXPERIENCE_EA"]),
		WORKEXPERIENCEHOL:       toInt4(f["WORK_EXPERIENCE_HOL"]),
		OJT:                     toInt4(f["OJT"]),
		JOBSEARCHHOP:            toInt4(f["JOB_SEARCH_HOP"]),
		JOBSEARCHEA:             toInt4(f["JOB_SEARCH_EA"]),
		JOBSEARCHHOL:            toInt4(f["JOB_SEARCH_HOL"]),
		COMMSERVICESHOP:         toInt4(f["COMM_SERVICES_HOP"]),
		COMMSERVICESEA:          toInt4(f["COMM_SERVICES_EA"]),
		COMMSERVICESHOL:         toInt4(f["COMM_SERVICES_HOL"]),
		VOCATIONALEDTRAININGHOP: toInt4(f["VOCATIONAL_ED_TRAINING_HOP"]),
		VOCATIONALEDTRAININGEA:  toInt4(f["VOCATIONAL_ED_TRAINING_EA"]),
		VOCATIONALEDTRAININGHOL: toInt4(f["VOCATIONAL_ED_TRAINING_HOL"]),
		JOBSKILLSTRAININGHOP:    toInt4(f["JOB_SKILLS_TRAINING_HOP"]),
		JOBSKILLSTRAININGEA:     toInt4(f["JOB_SKILLS_TRAINING_EA"]),
		JOBSKILLSTRAININGHOL:    toInt4(f["JOB_SKILLS_TRAINING_HOL"]),
		EDNOHIGHSCHOOLDIPLHOP:   toInt4(f["ED_NO_HIGH_SCHOOL_DIPL_HOP"]),
		EDNOHIGHSCHOOLDIPLEA:    toInt4(f["ED_NO_HIGH_SCHOOL_DIPL_EA"]),
		EDNOHIGHSCHOOLDIPLHOL:   toInt4(f["ED_NO_HIGH_SCHOOL_DIPL_HOL"]),
		SCHOOLATTENDENCEHOP:     toInt4(f["SCHOOL_ATTENDENCE_HOP"]),
		SCHOOLATTENDENCEEA:      toInt4(f["SCHOOL_ATTENDENCE_EA"]),
		SCHOOLATTENDENCEHOL:     toInt4(f["SCHOOL_ATTENDENCE_HOL"]),
		PROVIDECCHOP:            toInt4(f["PROVIDE_CC_HOP"]),
		PROVIDECCEA:             toInt4(f["PROVIDE_CC_EA"]),
		PROVIDECCHOL:            toInt4(f["PROVIDE_CC_HOL"]),
		OTHERWORKACTIVITIES:     toInt4(f["OTHER_WORK_ACTIVITIES"]),
		DEEMEDHOURSFOROVERALL:   toInt4(f["DEEMED_HOURS_FOR_OVERALL"]),
		DEEMEDHOURSFORTWOPARENT: toInt4(f["DEEMED_HOURS_FOR_TWO_PARENT"]),
		EARNEDINCOME:            toInt4(f["EARNED_INCOME"]),
		UNEARNEDINCOMETAXCREDIT: toInt4(f["UNEARNED_INCOME_TAX_CREDIT"]),
		UNEARNEDSOCIALSECURITY:  toInt4(f["UNEARNED_SOCIAL_SECURITY"]),
		UNEARNEDSSI:             toInt4(f["UNEARNED_SSI"]),
		UNEARNEDWORKERSCOMP:     toInt4(f["UNEARNED_WORKERS_COMP"]),
		OTHERUNEARNEDINCOME:     toInt4(f["OTHER_UNEARNED_INCOME"]),
		ID:                      newUUID(),
		DatafileID:              toDatafileID(datafileID),
		LineNumber:              toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FIPSCODE,
		rec.FAMILYAFFILIATION,
		rec.NONCUSTODIALPARENT,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.FEDOASDIPROGRAM,
		rec.FEDDISABILITYSTATUS,
		rec.DISABLEDTITLEXIVAPDT,
		rec.AIDAGEDBLIND,
		rec.RECEIVESSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.COOPERATIONCHILDSUPPORT,
		rec.EMPLOYMENTSTATUS,
		rec.WORKELIGIBLEINDICATOR,
		rec.WORKPARTSTATUS,
		rec.UNSUBEMPLOYMENT,
		rec.SUBPRIVATEEMPLOYMENT,
		rec.SUBPUBLICEMPLOYMENT,
		rec.WORKEXPERIENCEHOP,
		rec.WORKEXPERIENCEEA,
		rec.WORKEXPERIENCEHOL,
		rec.OJT,
		rec.JOBSEARCHHOP,
		rec.JOBSEARCHEA,
		rec.JOBSEARCHHOL,
		rec.COMMSERVICESHOP,
		rec.COMMSERVICESEA,
		rec.COMMSERVICESHOL,
		rec.VOCATIONALEDTRAININGHOP,
		rec.VOCATIONALEDTRAININGEA,
		rec.VOCATIONALEDTRAININGHOL,
		rec.JOBSKILLSTRAININGHOP,
		rec.JOBSKILLSTRAININGEA,
		rec.JOBSKILLSTRAININGHOL,
		rec.EDNOHIGHSCHOOLDIPLHOP,
		rec.EDNOHIGHSCHOOLDIPLEA,
		rec.EDNOHIGHSCHOOLDIPLHOL,
		rec.SCHOOLATTENDENCEHOP,
		rec.SCHOOLATTENDENCEEA,
		rec.SCHOOLATTENDENCEHOL,
		rec.PROVIDECCHOP,
		rec.PROVIDECCEA,
		rec.PROVIDECCHOL,
		rec.OTHERWORKACTIVITIES,
		rec.DEEMEDHOURSFOROVERALL,
		rec.DEEMEDHOURSFORTWOPARENT,
		rec.EARNEDINCOME,
		rec.UNEARNEDINCOMETAXCREDIT,
		rec.UNEARNEDSOCIALSECURITY,
		rec.UNEARNEDSSI,
		rec.UNEARNEDWORKERSCOMP,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M3 Converter - Child-level data for active SSP cases

func convertSspM3(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesSspM3{
		RecordType:            toText(f["RecordType"]),
		RPTMONTHYEAR:          toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:            toText(f["CASE_NUMBER"]),
		FIPSCODE:              toText(f["FIPS_CODE"]),
		FAMILYAFFILIATION:     toInt4(f["FAMILY_AFFILIATION"]),
		DATEOFBIRTH:           toText(f["DATE_OF_BIRTH"]),
		SSN:                   toText(f["SSN"]),
		RACEHISPANIC:          toInt4(f["RACE_HISPANIC"]),
		RACEAMERINDIAN:        toInt4(f["RACE_AMER_INDIAN"]),
		RACEASIAN:             toInt4(f["RACE_ASIAN"]),
		RACEBLACK:             toInt4(f["RACE_BLACK"]),
		RACEHAWAIIAN:          toInt4(f["RACE_HAWAIIAN"]),
		RACEWHITE:             toInt4(f["RACE_WHITE"]),
		SEX:                   toInt4(f["SEX"]),
		RECEIVENONSSIBENEFITS: toInt4(f["RECEIVE_NONSSI_BENEFITS"]),
		RECEIVESSI:            toInt4(f["RECEIVE_SSI"]),
		RELATIONSHIPHOH:       toInt4(f["RELATIONSHIP_HOH"]),
		PARENTMINORCHILD:      toInt4(f["PARENT_MINOR_CHILD"]),
		EDUCATIONLEVEL:        toText(f["EDUCATION_LEVEL"]),
		CITIZENSHIPSTATUS:     toInt4(f["CITIZENSHIP_STATUS"]),
		UNEARNEDSSI:           toInt4(f["UNEARNED_SSI"]),
		OTHERUNEARNEDINCOME:   toInt4(f["OTHER_UNEARNED_INCOME"]),
		ID:                    newUUID(),
		DatafileID:            toDatafileID(datafileID),
		LineNumber:            toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FIPSCODE,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECEIVENONSSIBENEFITS,
		rec.RECEIVESSI,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.UNEARNEDSSI,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M4 Converter - Case-level data for closed SSP cases

func convertSspM4(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesSspM4{
		RecordType:     toText(f["RecordType"]),
		RPTMONTHYEAR:   toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:     toText(f["CASE_NUMBER"]),
		COUNTYFIPSCODE: toText(f["COUNTY_FIPS_CODE"]),
		STRATUM:        toText(f["STRATUM"]),
		ZIPCODE:        toText(f["ZIP_CODE"]),
		DISPOSITION:    toInt4(f["DISPOSITION"]),
		CLOSUREREASON:  toText(f["CLOSURE_REASON"]),
		RECSUBHOUSING:  toInt4(f["REC_SUB_HOUSING"]),
		RECMEDASSIST:   toInt4(f["REC_MED_ASSIST"]),
		RECFOODSTAMPS:  toInt4(f["REC_FOOD_STAMPS"]),
		RECSUBCC:       toInt4(f["REC_SUB_CC"]),
		ID:             newUUID(),
		DatafileID:     toDatafileID(datafileID),
		LineNumber:     toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.DISPOSITION,
		rec.CLOSUREREASON,
		rec.RECSUBHOUSING,
		rec.RECMEDASSIST,
		rec.RECFOODSTAMPS,
		rec.RECSUBCC,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M5 Converter - Adult-level data for closed SSP cases

func convertSspM5(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesSspM5{
		RecordType:            toText(f["RecordType"]),
		RPTMONTHYEAR:          toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:            toText(f["CASE_NUMBER"]),
		FAMILYAFFILIATION:     toInt4(f["FAMILY_AFFILIATION"]),
		DATEOFBIRTH:           toText(f["DATE_OF_BIRTH"]),
		SSN:                   toText(f["SSN"]),
		RACEHISPANIC:          toInt4(f["RACE_HISPANIC"]),
		RACEAMERINDIAN:        toInt4(f["RACE_AMER_INDIAN"]),
		RACEASIAN:             toInt4(f["RACE_ASIAN"]),
		RACEBLACK:             toInt4(f["RACE_BLACK"]),
		RACEHAWAIIAN:          toInt4(f["RACE_HAWAIIAN"]),
		RACEWHITE:             toInt4(f["RACE_WHITE"]),
		SEX:                   toInt4(f["SEX"]),
		RECOASDIINSURANCE:     toInt4(f["REC_OASDI_INSURANCE"]),
		RECFEDERALDISABILITY:  toInt4(f["REC_FEDERAL_DISABILITY"]),
		RECAIDTOTALLYDISABLED: toInt4(f["REC_AID_TOTALLY_DISABLED"]),
		RECAIDAGEDBLIND:       toInt4(f["REC_AID_AGED_BLIND"]),
		RECSSI:                toInt4(f["REC_SSI"]),
		MARITALSTATUS:         toInt4(f["MARITAL_STATUS"]),
		RELATIONSHIPHOH:       toText(f["RELATIONSHIP_HOH"]),
		PARENTMINORCHILD:      toInt4(f["PARENT_MINOR_CHILD"]),
		NEEDSOFPREGNANTWOMAN:  toInt4(f["NEEDS_OF_PREGNANT_WOMAN"]),
		EDUCATIONLEVEL:        toText(f["EDUCATION_LEVEL"]),
		CITIZENSHIPSTATUS:     toInt4(f["CITIZENSHIP_STATUS"]),
		EMPLOYMENTSTATUS:      toInt4(f["EMPLOYMENT_STATUS"]),
		AMOUNTEARNEDINCOME:    toText(f["AMOUNT_EARNED_INCOME"]),
		AMOUNTUNEARNEDINCOME:  toText(f["AMOUNT_UNEARNED_INCOME"]),
		ID:                    newUUID(),
		DatafileID:            toDatafileID(datafileID),
		LineNumber:            toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECOASDIINSURANCE,
		rec.RECFEDERALDISABILITY,
		rec.RECAIDTOTALLYDISABLED,
		rec.RECAIDAGEDBLIND,
		rec.RECSSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSOFPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.EMPLOYMENTSTATUS,
		rec.AMOUNTEARNEDINCOME,
		rec.AMOUNTUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M6 Converter - Aggregate data

func convertSspM6(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesSspM6{
		RecordType:      toText(f["RecordType"]),
		CALENDARQUARTER: toInt4(f["CALENDAR_QUARTER"]),
		RPTMONTHYEAR:    toInt4(f["RPT_MONTH_YEAR"]),
		SSPMOEFAMILIES:  toInt4(f["SSP_MOE_FAMILIES"]),
		NUM2PARENTS:     toInt4(f["NUM_2_PARENTS"]),
		NUM1PARENTS:     toInt4(f["NUM_1_PARENTS"]),
		NUMNOPARENTS:    toInt4(f["NUM_NO_PARENTS"]),
		NUMRECIPIENTS:   toInt4(f["NUM_RECIPIENTS"]),
		ADULTRECIPIENTS: toInt4(f["ADULT_RECIPIENTS"]),
		CHILDRECIPIENTS: toInt4(f["CHILD_RECIPIENTS"]),
		NONCUSTODIALS:   toInt4(f["NONCUSTODIALS"]),
		AMTASSISTANCE:   toInt4(f["AMT_ASSISTANCE"]),
		CLOSEDCASES:     toInt4(f["CLOSED_CASES"]),
		ID:              newUUID(),
		DatafileID:      toDatafileID(datafileID),
		LineNumber:      toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.SSPMOEFAMILIES,
		rec.NUM2PARENTS,
		rec.NUM1PARENTS,
		rec.NUMNOPARENTS,
		rec.NUMRECIPIENTS,
		rec.ADULTRECIPIENTS,
		rec.CHILDRECIPIENTS,
		rec.NONCUSTODIALS,
		rec.AMTASSISTANCE,
		rec.CLOSEDCASES,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M7 Converter - Stratum data

func convertSspM7(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesSspM7{
		RecordType:      toText(f["RecordType"]),
		CALENDARQUARTER: toInt4(f["CALENDAR_QUARTER"]),
		RPTMONTHYEAR:    toInt4(f["RPT_MONTH_YEAR"]),
		TDRSSECTIONIND:  toText(f["TDRS_SECTION_IND"]),
		STRATUM:         toText(f["STRATUM"]),
		FAMILIESMONTH:   toInt4(f["FAMILIES_MONTH"]),
		ID:              newUUID(),
		DatafileID:      toDatafileID(datafileID),
		LineNumber:      toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.TDRSSECTIONIND,
		rec.STRATUM,
		rec.FAMILIESMONTH,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}
