package converter

import (
	"go-parser/internal/db"
	"go-parser/internal/schema"
)

// SSP M1 Converter - Case-level data for active SSP cases

func convertSspM1(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesSspM1{
		RecordType:               toText(record.Get("RecordType")),
		RPTMONTHYEAR:             toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:               toText(record.Get("CASE_NUMBER")),
		FIPSCODE:                 toText(record.Get("FIPS_CODE")),
		COUNTYFIPSCODE:           toText(record.Get("COUNTY_FIPS_CODE")),
		STRATUM:                  toText(record.Get("STRATUM")),
		ZIPCODE:                  toText(record.Get("ZIP_CODE")),
		DISPOSITION:              toInt4(record.Get("DISPOSITION")),
		NBRFAMILYMEMBERS:         toInt4(record.Get("NBR_FAMILY_MEMBERS")),
		FAMILYTYPE:               toInt4(record.Get("FAMILY_TYPE")),
		TANFASSTIN6MONTHS:        toInt4(record.Get("TANF_ASST_IN_6MONTHS")),
		RECEIVESSUBHOUSING:       toInt4(record.Get("RECEIVES_SUB_HOUSING")),
		RECEIVESMEDASSISTANCE:    toInt4(record.Get("RECEIVES_MED_ASSISTANCE")),
		RECEIVESFOODSTAMPS:       toInt4(record.Get("RECEIVES_FOOD_STAMPS")),
		AMTFOODSTAMPASSISTANCE:   toInt4(record.Get("AMT_FOOD_STAMP_ASSISTANCE")),
		RECEIVESSUBCC:            toInt4(record.Get("RECEIVES_SUB_CC")),
		AMTSUBCC:                 toInt4(record.Get("AMT_SUB_CC")),
		CHILDSUPPORTAMT:          toInt4(record.Get("CHILD_SUPPORT_AMT")),
		FAMILYCASHRESOURCES:      toInt4(record.Get("FAMILY_CASH_RESOURCES")),
		CASHAMOUNT:               toInt4(record.Get("CASH_AMOUNT")),
		NBRMONTHS:                toInt4(record.Get("NBR_MONTHS")),
		CCAMOUNT:                 toInt4(record.Get("CC_AMOUNT")),
		CHILDRENCOVERED:          toInt4(record.Get("CHILDREN_COVERED")),
		CCNBRMONTHS:              toInt4(record.Get("CC_NBR_MONTHS")),
		TRANSPAMOUNT:             toInt4(record.Get("TRANSP_AMOUNT")),
		TRANSPNBRMONTHS:          toInt4(record.Get("TRANSP_NBR_MONTHS")),
		TRANSITIONSERVICESAMOUNT: toInt4(record.Get("TRANSITION_SERVICES_AMOUNT")),
		TRANSITIONNBRMONTHS:      toInt4(record.Get("TRANSITION_NBR_MONTHS")),
		OTHERAMOUNT:              toInt4(record.Get("OTHER_AMOUNT")),
		OTHERNBRMONTHS:           toInt4(record.Get("OTHER_NBR_MONTHS")),
		SANCREDUCTIONAMT:         toInt4(record.Get("SANC_REDUCTION_AMT")),
		WORKREQSANCTION:          toInt4(record.Get("WORK_REQ_SANCTION")),
		FAMILYSANCADULT:          toInt4(record.Get("FAMILY_SANC_ADULT")),
		SANCTEENPARENT:           toInt4(record.Get("SANC_TEEN_PARENT")),
		NONCOOPERATIONCSE:        toInt4(record.Get("NON_COOPERATION_CSE")),
		FAILURETOCOMPLY:          toInt4(record.Get("FAILURE_TO_COMPLY")),
		OTHERSANCTION:            toInt4(record.Get("OTHER_SANCTION")),
		RECOUPMENTPRIOROVRPMT:    toInt4(record.Get("RECOUPMENT_PRIOR_OVRPMT")),
		OTHERTOTALREDUCTIONS:     toInt4(record.Get("OTHER_TOTAL_REDUCTIONS")),
		FAMILYCAP:                toInt4(record.Get("FAMILY_CAP")),
		REDUCTIONSONRECEIPTS:     toInt4(record.Get("REDUCTIONS_ON_RECEIPTS")),
		OTHERNONSANCTION:         toInt4(record.Get("OTHER_NON_SANCTION")),
		WAIVEREVALCONTROLGRPS:    toInt4(record.Get("WAIVER_EVAL_CONTROL_GRPS")),
		ID:                       newUUID(),
		DatafileID:               toDatafileID(datafileID),
		LineNumber:               toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FIPSCODE,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.DISPOSITION,
		rec.NBRFAMILYMEMBERS,
		rec.FAMILYTYPE,
		rec.TANFASSTIN6MONTHS,
		rec.RECEIVESSUBHOUSING,
		rec.RECEIVESMEDASSISTANCE,
		rec.RECEIVESFOODSTAMPS,
		rec.AMTFOODSTAMPASSISTANCE,
		rec.RECEIVESSUBCC,
		rec.AMTSUBCC,
		rec.CHILDSUPPORTAMT,
		rec.FAMILYCASHRESOURCES,
		rec.CASHAMOUNT,
		rec.NBRMONTHS,
		rec.CCAMOUNT,
		rec.CHILDRENCOVERED,
		rec.CCNBRMONTHS,
		rec.TRANSPAMOUNT,
		rec.TRANSPNBRMONTHS,
		rec.TRANSITIONSERVICESAMOUNT,
		rec.TRANSITIONNBRMONTHS,
		rec.OTHERAMOUNT,
		rec.OTHERNBRMONTHS,
		rec.SANCREDUCTIONAMT,
		rec.WORKREQSANCTION,
		rec.FAMILYSANCADULT,
		rec.SANCTEENPARENT,
		rec.NONCOOPERATIONCSE,
		rec.FAILURETOCOMPLY,
		rec.OTHERSANCTION,
		rec.RECOUPMENTPRIOROVRPMT,
		rec.OTHERTOTALREDUCTIONS,
		rec.FAMILYCAP,
		rec.REDUCTIONSONRECEIPTS,
		rec.OTHERNONSANCTION,
		rec.WAIVEREVALCONTROLGRPS,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M2 Converter - Adult-level data for active SSP cases

func convertSspM2(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesSspM2{
		RecordType:              toText(record.Get("RecordType")),
		RPTMONTHYEAR:            toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:              toText(record.Get("CASE_NUMBER")),
		FIPSCODE:                toText(record.Get("FIPS_CODE")),
		FAMILYAFFILIATION:       toInt4(record.Get("FAMILY_AFFILIATION")),
		NONCUSTODIALPARENT:      toInt4(record.Get("NONCUSTODIAL_PARENT")),
		DATEOFBIRTH:             toText(record.Get("DATE_OF_BIRTH")),
		SSN:                     toText(record.Get("SSN")),
		RACEHISPANIC:            toInt4(record.Get("RACE_HISPANIC")),
		RACEAMERINDIAN:          toInt4(record.Get("RACE_AMER_INDIAN")),
		RACEASIAN:               toInt4(record.Get("RACE_ASIAN")),
		RACEBLACK:               toInt4(record.Get("RACE_BLACK")),
		RACEHAWAIIAN:            toInt4(record.Get("RACE_HAWAIIAN")),
		RACEWHITE:               toInt4(record.Get("RACE_WHITE")),
		SEX:                     toInt4(record.Get("SEX")),
		FEDOASDIPROGRAM:         toInt4(record.Get("FED_OASDI_PROGRAM")),
		FEDDISABILITYSTATUS:     toInt4(record.Get("FED_DISABILITY_STATUS")),
		DISABLEDTITLEXIVAPDT:    toInt4(record.Get("DISABLED_TITLE_XIVAPDT")),
		AIDAGEDBLIND:            toInt4(record.Get("AID_AGED_BLIND")),
		RECEIVESSI:              toInt4(record.Get("RECEIVE_SSI")),
		MARITALSTATUS:           toInt4(record.Get("MARITAL_STATUS")),
		RELATIONSHIPHOH:         toInt4(record.Get("RELATIONSHIP_HOH")),
		PARENTMINORCHILD:        toInt4(record.Get("PARENT_MINOR_CHILD")),
		NEEDSPREGNANTWOMAN:      toInt4(record.Get("NEEDS_PREGNANT_WOMAN")),
		EDUCATIONLEVEL:          toText(record.Get("EDUCATION_LEVEL")),
		CITIZENSHIPSTATUS:       toInt4(record.Get("CITIZENSHIP_STATUS")),
		COOPERATIONCHILDSUPPORT: toInt4(record.Get("COOPERATION_CHILD_SUPPORT")),
		EMPLOYMENTSTATUS:        toInt4(record.Get("EMPLOYMENT_STATUS")),
		WORKELIGIBLEINDICATOR:   toInt4(record.Get("WORK_ELIGIBLE_INDICATOR")),
		WORKPARTSTATUS:          toInt4(record.Get("WORK_PART_STATUS")),
		UNSUBEMPLOYMENT:         toInt4(record.Get("UNSUB_EMPLOYMENT")),
		SUBPRIVATEEMPLOYMENT:    toInt4(record.Get("SUB_PRIVATE_EMPLOYMENT")),
		SUBPUBLICEMPLOYMENT:     toInt4(record.Get("SUB_PUBLIC_EMPLOYMENT")),
		WORKEXPERIENCEHOP:       toInt4(record.Get("WORK_EXPERIENCE_HOP")),
		WORKEXPERIENCEEA:        toInt4(record.Get("WORK_EXPERIENCE_EA")),
		WORKEXPERIENCEHOL:       toInt4(record.Get("WORK_EXPERIENCE_HOL")),
		OJT:                     toInt4(record.Get("OJT")),
		JOBSEARCHHOP:            toInt4(record.Get("JOB_SEARCH_HOP")),
		JOBSEARCHEA:             toInt4(record.Get("JOB_SEARCH_EA")),
		JOBSEARCHHOL:            toInt4(record.Get("JOB_SEARCH_HOL")),
		COMMSERVICESHOP:         toInt4(record.Get("COMM_SERVICES_HOP")),
		COMMSERVICESEA:          toInt4(record.Get("COMM_SERVICES_EA")),
		COMMSERVICESHOL:         toInt4(record.Get("COMM_SERVICES_HOL")),
		VOCATIONALEDTRAININGHOP: toInt4(record.Get("VOCATIONAL_ED_TRAINING_HOP")),
		VOCATIONALEDTRAININGEA:  toInt4(record.Get("VOCATIONAL_ED_TRAINING_EA")),
		VOCATIONALEDTRAININGHOL: toInt4(record.Get("VOCATIONAL_ED_TRAINING_HOL")),
		JOBSKILLSTRAININGHOP:    toInt4(record.Get("JOB_SKILLS_TRAINING_HOP")),
		JOBSKILLSTRAININGEA:     toInt4(record.Get("JOB_SKILLS_TRAINING_EA")),
		JOBSKILLSTRAININGHOL:    toInt4(record.Get("JOB_SKILLS_TRAINING_HOL")),
		EDNOHIGHSCHOOLDIPLHOP:   toInt4(record.Get("ED_NO_HIGH_SCHOOL_DIPL_HOP")),
		EDNOHIGHSCHOOLDIPLEA:    toInt4(record.Get("ED_NO_HIGH_SCHOOL_DIPL_EA")),
		EDNOHIGHSCHOOLDIPLHOL:   toInt4(record.Get("ED_NO_HIGH_SCHOOL_DIPL_HOL")),
		SCHOOLATTENDENCEHOP:     toInt4(record.Get("SCHOOL_ATTENDENCE_HOP")),
		SCHOOLATTENDENCEEA:      toInt4(record.Get("SCHOOL_ATTENDENCE_EA")),
		SCHOOLATTENDENCEHOL:     toInt4(record.Get("SCHOOL_ATTENDENCE_HOL")),
		PROVIDECCHOP:            toInt4(record.Get("PROVIDE_CC_HOP")),
		PROVIDECCEA:             toInt4(record.Get("PROVIDE_CC_EA")),
		PROVIDECCHOL:            toInt4(record.Get("PROVIDE_CC_HOL")),
		OTHERWORKACTIVITIES:     toInt4(record.Get("OTHER_WORK_ACTIVITIES")),
		DEEMEDHOURSFOROVERALL:   toInt4(record.Get("DEEMED_HOURS_FOR_OVERALL")),
		DEEMEDHOURSFORTWOPARENT: toInt4(record.Get("DEEMED_HOURS_FOR_TWO_PARENT")),
		EARNEDINCOME:            toInt4(record.Get("EARNED_INCOME")),
		UNEARNEDINCOMETAXCREDIT: toInt4(record.Get("UNEARNED_INCOME_TAX_CREDIT")),
		UNEARNEDSOCIALSECURITY:  toInt4(record.Get("UNEARNED_SOCIAL_SECURITY")),
		UNEARNEDSSI:             toInt4(record.Get("UNEARNED_SSI")),
		UNEARNEDWORKERSCOMP:     toInt4(record.Get("UNEARNED_WORKERS_COMP")),
		OTHERUNEARNEDINCOME:     toInt4(record.Get("OTHER_UNEARNED_INCOME")),
		ID:                      newUUID(),
		DatafileID:              toDatafileID(datafileID),
		LineNumber:              toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FIPSCODE,
		rec.FAMILYAFFILIATION,
		rec.NONCUSTODIALPARENT,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.FEDOASDIPROGRAM,
		rec.FEDDISABILITYSTATUS,
		rec.DISABLEDTITLEXIVAPDT,
		rec.AIDAGEDBLIND,
		rec.RECEIVESSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.COOPERATIONCHILDSUPPORT,
		rec.EMPLOYMENTSTATUS,
		rec.WORKELIGIBLEINDICATOR,
		rec.WORKPARTSTATUS,
		rec.UNSUBEMPLOYMENT,
		rec.SUBPRIVATEEMPLOYMENT,
		rec.SUBPUBLICEMPLOYMENT,
		rec.WORKEXPERIENCEHOP,
		rec.WORKEXPERIENCEEA,
		rec.WORKEXPERIENCEHOL,
		rec.OJT,
		rec.JOBSEARCHHOP,
		rec.JOBSEARCHEA,
		rec.JOBSEARCHHOL,
		rec.COMMSERVICESHOP,
		rec.COMMSERVICESEA,
		rec.COMMSERVICESHOL,
		rec.VOCATIONALEDTRAININGHOP,
		rec.VOCATIONALEDTRAININGEA,
		rec.VOCATIONALEDTRAININGHOL,
		rec.JOBSKILLSTRAININGHOP,
		rec.JOBSKILLSTRAININGEA,
		rec.JOBSKILLSTRAININGHOL,
		rec.EDNOHIGHSCHOOLDIPLHOP,
		rec.EDNOHIGHSCHOOLDIPLEA,
		rec.EDNOHIGHSCHOOLDIPLHOL,
		rec.SCHOOLATTENDENCEHOP,
		rec.SCHOOLATTENDENCEEA,
		rec.SCHOOLATTENDENCEHOL,
		rec.PROVIDECCHOP,
		rec.PROVIDECCEA,
		rec.PROVIDECCHOL,
		rec.OTHERWORKACTIVITIES,
		rec.DEEMEDHOURSFOROVERALL,
		rec.DEEMEDHOURSFORTWOPARENT,
		rec.EARNEDINCOME,
		rec.UNEARNEDINCOMETAXCREDIT,
		rec.UNEARNEDSOCIALSECURITY,
		rec.UNEARNEDSSI,
		rec.UNEARNEDWORKERSCOMP,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M3 Converter - Child-level data for active SSP cases

func convertSspM3(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesSspM3{
		RecordType:            toText(record.Get("RecordType")),
		RPTMONTHYEAR:          toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:            toText(record.Get("CASE_NUMBER")),
		FIPSCODE:              toText(record.Get("FIPS_CODE")),
		FAMILYAFFILIATION:     toInt4(record.Get("FAMILY_AFFILIATION")),
		DATEOFBIRTH:           toText(record.Get("DATE_OF_BIRTH")),
		SSN:                   toText(record.Get("SSN")),
		RACEHISPANIC:          toInt4(record.Get("RACE_HISPANIC")),
		RACEAMERINDIAN:        toInt4(record.Get("RACE_AMER_INDIAN")),
		RACEASIAN:             toInt4(record.Get("RACE_ASIAN")),
		RACEBLACK:             toInt4(record.Get("RACE_BLACK")),
		RACEHAWAIIAN:          toInt4(record.Get("RACE_HAWAIIAN")),
		RACEWHITE:             toInt4(record.Get("RACE_WHITE")),
		SEX:                   toInt4(record.Get("SEX")),
		RECEIVENONSSIBENEFITS: toInt4(record.Get("RECEIVE_NONSSI_BENEFITS")),
		RECEIVESSI:            toInt4(record.Get("RECEIVE_SSI")),
		RELATIONSHIPHOH:       toInt4(record.Get("RELATIONSHIP_HOH")),
		PARENTMINORCHILD:      toInt4(record.Get("PARENT_MINOR_CHILD")),
		EDUCATIONLEVEL:        toText(record.Get("EDUCATION_LEVEL")),
		CITIZENSHIPSTATUS:     toInt4(record.Get("CITIZENSHIP_STATUS")),
		UNEARNEDSSI:           toInt4(record.Get("UNEARNED_SSI")),
		OTHERUNEARNEDINCOME:   toInt4(record.Get("OTHER_UNEARNED_INCOME")),
		ID:                    newUUID(),
		DatafileID:            toDatafileID(datafileID),
		LineNumber:            toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FIPSCODE,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECEIVENONSSIBENEFITS,
		rec.RECEIVESSI,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.UNEARNEDSSI,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M4 Converter - Case-level data for closed SSP cases

func convertSspM4(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesSspM4{
		RecordType:     toText(record.Get("RecordType")),
		RPTMONTHYEAR:   toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:     toText(record.Get("CASE_NUMBER")),
		COUNTYFIPSCODE: toText(record.Get("COUNTY_FIPS_CODE")),
		STRATUM:        toText(record.Get("STRATUM")),
		ZIPCODE:        toText(record.Get("ZIP_CODE")),
		DISPOSITION:    toInt4(record.Get("DISPOSITION")),
		CLOSUREREASON:  toText(record.Get("CLOSURE_REASON")),
		RECSUBHOUSING:  toInt4(record.Get("REC_SUB_HOUSING")),
		RECMEDASSIST:   toInt4(record.Get("REC_MED_ASSIST")),
		RECFOODSTAMPS:  toInt4(record.Get("REC_FOOD_STAMPS")),
		RECSUBCC:       toInt4(record.Get("REC_SUB_CC")),
		ID:             newUUID(),
		DatafileID:     toDatafileID(datafileID),
		LineNumber:     toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.DISPOSITION,
		rec.CLOSUREREASON,
		rec.RECSUBHOUSING,
		rec.RECMEDASSIST,
		rec.RECFOODSTAMPS,
		rec.RECSUBCC,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M5 Converter - Adult-level data for closed SSP cases

func convertSspM5(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesSspM5{
		RecordType:            toText(record.Get("RecordType")),
		RPTMONTHYEAR:          toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:            toText(record.Get("CASE_NUMBER")),
		FAMILYAFFILIATION:     toInt4(record.Get("FAMILY_AFFILIATION")),
		DATEOFBIRTH:           toText(record.Get("DATE_OF_BIRTH")),
		SSN:                   toText(record.Get("SSN")),
		RACEHISPANIC:          toInt4(record.Get("RACE_HISPANIC")),
		RACEAMERINDIAN:        toInt4(record.Get("RACE_AMER_INDIAN")),
		RACEASIAN:             toInt4(record.Get("RACE_ASIAN")),
		RACEBLACK:             toInt4(record.Get("RACE_BLACK")),
		RACEHAWAIIAN:          toInt4(record.Get("RACE_HAWAIIAN")),
		RACEWHITE:             toInt4(record.Get("RACE_WHITE")),
		SEX:                   toInt4(record.Get("SEX")),
		RECOASDIINSURANCE:     toInt4(record.Get("REC_OASDI_INSURANCE")),
		RECFEDERALDISABILITY:  toInt4(record.Get("REC_FEDERAL_DISABILITY")),
		RECAIDTOTALLYDISABLED: toInt4(record.Get("REC_AID_TOTALLY_DISABLED")),
		RECAIDAGEDBLIND:       toInt4(record.Get("REC_AID_AGED_BLIND")),
		RECSSI:                toInt4(record.Get("REC_SSI")),
		MARITALSTATUS:         toInt4(record.Get("MARITAL_STATUS")),
		RELATIONSHIPHOH:       toText(record.Get("RELATIONSHIP_HOH")),
		PARENTMINORCHILD:      toInt4(record.Get("PARENT_MINOR_CHILD")),
		NEEDSOFPREGNANTWOMAN:  toInt4(record.Get("NEEDS_OF_PREGNANT_WOMAN")),
		EDUCATIONLEVEL:        toText(record.Get("EDUCATION_LEVEL")),
		CITIZENSHIPSTATUS:     toInt4(record.Get("CITIZENSHIP_STATUS")),
		EMPLOYMENTSTATUS:      toInt4(record.Get("EMPLOYMENT_STATUS")),
		AMOUNTEARNEDINCOME:    toText(record.Get("AMOUNT_EARNED_INCOME")),
		AMOUNTUNEARNEDINCOME:  toText(record.Get("AMOUNT_UNEARNED_INCOME")),
		ID:                    newUUID(),
		DatafileID:            toDatafileID(datafileID),
		LineNumber:            toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECOASDIINSURANCE,
		rec.RECFEDERALDISABILITY,
		rec.RECAIDTOTALLYDISABLED,
		rec.RECAIDAGEDBLIND,
		rec.RECSSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSOFPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.EMPLOYMENTSTATUS,
		rec.AMOUNTEARNEDINCOME,
		rec.AMOUNTUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M6 Converter - Aggregate data

func convertSspM6(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesSspM6{
		RecordType:      toText(record.Get("RecordType")),
		CALENDARQUARTER: toInt4(record.Get("CALENDAR_QUARTER")),
		RPTMONTHYEAR:    toInt4(record.Get("RPT_MONTH_YEAR")),
		SSPMOEFAMILIES:  toInt4(record.Get("SSP_MOE_FAMILIES")),
		NUM2PARENTS:     toInt4(record.Get("NUM_2_PARENTS")),
		NUM1PARENTS:     toInt4(record.Get("NUM_1_PARENTS")),
		NUMNOPARENTS:    toInt4(record.Get("NUM_NO_PARENTS")),
		NUMRECIPIENTS:   toInt4(record.Get("NUM_RECIPIENTS")),
		ADULTRECIPIENTS: toInt4(record.Get("ADULT_RECIPIENTS")),
		CHILDRECIPIENTS: toInt4(record.Get("CHILD_RECIPIENTS")),
		NONCUSTODIALS:   toInt4(record.Get("NONCUSTODIALS")),
		AMTASSISTANCE:   toInt4(record.Get("AMT_ASSISTANCE")),
		CLOSEDCASES:     toInt4(record.Get("CLOSED_CASES")),
		ID:              newUUID(),
		DatafileID:      toDatafileID(datafileID),
		LineNumber:      toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.SSPMOEFAMILIES,
		rec.NUM2PARENTS,
		rec.NUM1PARENTS,
		rec.NUMNOPARENTS,
		rec.NUMRECIPIENTS,
		rec.ADULTRECIPIENTS,
		rec.CHILDRECIPIENTS,
		rec.NONCUSTODIALS,
		rec.AMTASSISTANCE,
		rec.CLOSEDCASES,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// SSP M7 Converter - Stratum data

func convertSspM7(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesSspM7{
		RecordType:      toText(record.Get("RecordType")),
		CALENDARQUARTER: toInt4(record.Get("CALENDAR_QUARTER")),
		RPTMONTHYEAR:    toInt4(record.Get("RPT_MONTH_YEAR")),
		TDRSSECTIONIND:  toText(record.Get("TDRS_SECTION_IND")),
		STRATUM:         toText(record.Get("STRATUM")),
		FAMILIESMONTH:   toInt4(record.Get("FAMILIES_MONTH")),
		ID:              newUUID(),
		DatafileID:      toDatafileID(datafileID),
		LineNumber:      toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.TDRSSECTIONIND,
		rec.STRATUM,
		rec.FAMILIESMONTH,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}
