package converter

import (
	"go-parser/internal/db"
	"go-parser/internal/schema"
)

// TANF T1 Converter - Case-level data for active TANF cases

func convertTanfT1(record *schema.ParsedRecord, datafileID int32) [][]any {
	// Build SQLC type for type safety, using Get() accessor
	rec := &db.SearchIndexesTanfT1{
		RecordType:               toText(record.Get("RecordType")),
		RPTMONTHYEAR:             toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:               toText(record.Get("CASE_NUMBER")),
		COUNTYFIPSCODE:           toText(record.Get("COUNTY_FIPS_CODE")),
		STRATUM:                  toText(record.Get("STRATUM")),
		ZIPCODE:                  toText(record.Get("ZIP_CODE")),
		FUNDINGSTREAM:            toInt4(record.Get("FUNDING_STREAM")),
		DISPOSITION:              toInt4(record.Get("DISPOSITION")),
		NEWAPPLICANT:             toInt4(record.Get("NEW_APPLICANT")),
		NBRFAMILYMEMBERS:         toInt4(record.Get("NBR_FAMILY_MEMBERS")),
		FAMILYTYPE:               toInt4(record.Get("FAMILY_TYPE")),
		RECEIVESSUBHOUSING:       toInt4(record.Get("RECEIVES_SUB_HOUSING")),
		RECEIVESMEDASSISTANCE:    toInt4(record.Get("RECEIVES_MED_ASSISTANCE")),
		RECEIVESFOODSTAMPS:       toInt4(record.Get("RECEIVES_FOOD_STAMPS")),
		AMTFOODSTAMPASSISTANCE:   toInt4(record.Get("AMT_FOOD_STAMP_ASSISTANCE")),
		RECEIVESSUBCC:            toInt4(record.Get("RECEIVES_SUB_CC")),
		AMTSUBCC:                 toInt4(record.Get("AMT_SUB_CC")),
		CHILDSUPPORTAMT:          toInt4(record.Get("CHILD_SUPPORT_AMT")),
		FAMILYCASHRESOURCES:      toInt4(record.Get("FAMILY_CASH_RESOURCES")),
		CASHAMOUNT:               toInt4(record.Get("CASH_AMOUNT")),
		NBRMONTHS:                toInt4(record.Get("NBR_MONTHS")),
		CCAMOUNT:                 toInt4(record.Get("CC_AMOUNT")),
		CHILDRENCOVERED:          toInt4(record.Get("CHILDREN_COVERED")),
		CCNBRMONTHS:              toInt4(record.Get("CC_NBR_MONTHS")),
		TRANSPAMOUNT:             toInt4(record.Get("TRANSP_AMOUNT")),
		TRANSPNBRMONTHS:          toInt4(record.Get("TRANSP_NBR_MONTHS")),
		TRANSITIONSERVICESAMOUNT: toInt4(record.Get("TRANSITION_SERVICES_AMOUNT")),
		TRANSITIONNBRMONTHS:      toInt4(record.Get("TRANSITION_NBR_MONTHS")),
		OTHERAMOUNT:              toInt4(record.Get("OTHER_AMOUNT")),
		OTHERNBRMONTHS:           toInt4(record.Get("OTHER_NBR_MONTHS")),
		SANCREDUCTIONAMT:         toInt4(record.Get("SANC_REDUCTION_AMT")),
		WORKREQSANCTION:          toInt4(record.Get("WORK_REQ_SANCTION")),
		FAMILYSANCADULT:          toInt4(record.Get("FAMILY_SANC_ADULT")),
		SANCTEENPARENT:           toInt4(record.Get("SANC_TEEN_PARENT")),
		NONCOOPERATIONCSE:        toInt4(record.Get("NON_COOPERATION_CSE")),
		FAILURETOCOMPLY:          toInt4(record.Get("FAILURE_TO_COMPLY")),
		OTHERSANCTION:            toInt4(record.Get("OTHER_SANCTION")),
		RECOUPMENTPRIOROVRPMT:    toInt4(record.Get("RECOUPMENT_PRIOR_OVRPMT")),
		OTHERTOTALREDUCTIONS:     toInt4(record.Get("OTHER_TOTAL_REDUCTIONS")),
		FAMILYCAP:                toInt4(record.Get("FAMILY_CAP")),
		REDUCTIONSONRECEIPTS:     toInt4(record.Get("REDUCTIONS_ON_RECEIPTS")),
		OTHERNONSANCTION:         toInt4(record.Get("OTHER_NON_SANCTION")),
		WAIVEREVALCONTROLGRPS:    toInt4(record.Get("WAIVER_EVAL_CONTROL_GRPS")),
		FAMILYEXEMPTTIMELIMITS:   toInt4(record.Get("FAMILY_EXEMPT_TIME_LIMITS")),
		FAMILYNEWCHILD:           toInt4(record.Get("FAMILY_NEW_CHILD")),
		ID:                       newUUID(),
		DatafileID:               toDatafileID(datafileID),
		LineNumber:               toLineNumber(record.LineNumber),
	}

	// Return values in schema field order + id, datafile_id, line_number
	// This order must match the columns array from SchemaMetadata
	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.FUNDINGSTREAM,
		rec.DISPOSITION,
		rec.NEWAPPLICANT,
		rec.NBRFAMILYMEMBERS,
		rec.FAMILYTYPE,
		rec.RECEIVESSUBHOUSING,
		rec.RECEIVESMEDASSISTANCE,
		rec.RECEIVESFOODSTAMPS,
		rec.AMTFOODSTAMPASSISTANCE,
		rec.RECEIVESSUBCC,
		rec.AMTSUBCC,
		rec.CHILDSUPPORTAMT,
		rec.FAMILYCASHRESOURCES,
		rec.CASHAMOUNT,
		rec.NBRMONTHS,
		rec.CCAMOUNT,
		rec.CHILDRENCOVERED,
		rec.CCNBRMONTHS,
		rec.TRANSPAMOUNT,
		rec.TRANSPNBRMONTHS,
		rec.TRANSITIONSERVICESAMOUNT,
		rec.TRANSITIONNBRMONTHS,
		rec.OTHERAMOUNT,
		rec.OTHERNBRMONTHS,
		rec.SANCREDUCTIONAMT,
		rec.WORKREQSANCTION,
		rec.FAMILYSANCADULT,
		rec.SANCTEENPARENT,
		rec.NONCOOPERATIONCSE,
		rec.FAILURETOCOMPLY,
		rec.OTHERSANCTION,
		rec.RECOUPMENTPRIOROVRPMT,
		rec.OTHERTOTALREDUCTIONS,
		rec.FAMILYCAP,
		rec.REDUCTIONSONRECEIPTS,
		rec.OTHERNONSANCTION,
		rec.WAIVEREVALCONTROLGRPS,
		rec.FAMILYEXEMPTTIMELIMITS,
		rec.FAMILYNEWCHILD,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// TANF T2 Converter - Adult-level data for active TANF cases

func convertTanfT2(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesTanfT2{
		RecordType:              toText(record.Get("RecordType")),
		RPTMONTHYEAR:            toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:              toText(record.Get("CASE_NUMBER")),
		FAMILYAFFILIATION:       toInt4(record.Get("FAMILY_AFFILIATION")),
		NONCUSTODIALPARENT:      toInt4(record.Get("NONCUSTODIAL_PARENT")),
		DATEOFBIRTH:             toText(record.Get("DATE_OF_BIRTH")),
		SSN:                     toText(record.Get("SSN")),
		RACEHISPANIC:            toInt4(record.Get("RACE_HISPANIC")),
		RACEAMERINDIAN:          toInt4(record.Get("RACE_AMER_INDIAN")),
		RACEASIAN:               toInt4(record.Get("RACE_ASIAN")),
		RACEBLACK:               toInt4(record.Get("RACE_BLACK")),
		RACEHAWAIIAN:            toInt4(record.Get("RACE_HAWAIIAN")),
		RACEWHITE:               toInt4(record.Get("RACE_WHITE")),
		SEX:                     toInt4(record.Get("SEX")),
		FEDOASDIPROGRAM:         toInt4(record.Get("FED_OASDI_PROGRAM")),
		FEDDISABILITYSTATUS:     toInt4(record.Get("FED_DISABILITY_STATUS")),
		DISABLEDTITLEXIVAPDT:    toInt4(record.Get("DISABLED_TITLE_XIVAPDT")),
		AIDAGEDBLIND:            toInt4(record.Get("AID_AGED_BLIND")),
		RECEIVESSI:              toInt4(record.Get("RECEIVE_SSI")),
		MARITALSTATUS:           toInt4(record.Get("MARITAL_STATUS")),
		RELATIONSHIPHOH:         toText(record.Get("RELATIONSHIP_HOH")),
		PARENTMINORCHILD:        toInt4(record.Get("PARENT_MINOR_CHILD")),
		NEEDSPREGNANTWOMAN:      toInt4(record.Get("NEEDS_PREGNANT_WOMAN")),
		EDUCATIONLEVEL:          toText(record.Get("EDUCATION_LEVEL")),
		CITIZENSHIPSTATUS:       toInt4(record.Get("CITIZENSHIP_STATUS")),
		COOPERATIONCHILDSUPPORT: toInt4(record.Get("COOPERATION_CHILD_SUPPORT")),
		MONTHSFEDTIMELIMIT:      toText(record.Get("MONTHS_FED_TIME_LIMIT")),
		MONTHSSTATETIMELIMIT:    toText(record.Get("MONTHS_STATE_TIME_LIMIT")),
		CURRENTMONTHSTATEEXEMPT: toInt4(record.Get("CURRENT_MONTH_STATE_EXEMPT")),
		EMPLOYMENTSTATUS:        toInt4(record.Get("EMPLOYMENT_STATUS")),
		WORKELIGIBLEINDICATOR:   toText(record.Get("WORK_ELIGIBLE_INDICATOR")),
		WORKPARTSTATUS:          toText(record.Get("WORK_PART_STATUS")),
		UNSUBEMPLOYMENT:         toText(record.Get("UNSUB_EMPLOYMENT")),
		SUBPRIVATEEMPLOYMENT:    toText(record.Get("SUB_PRIVATE_EMPLOYMENT")),
		SUBPUBLICEMPLOYMENT:     toText(record.Get("SUB_PUBLIC_EMPLOYMENT")),
		WORKEXPERIENCEHOP:       toText(record.Get("WORK_EXPERIENCE_HOP")),
		WORKEXPERIENCEEA:        toText(record.Get("WORK_EXPERIENCE_EA")),
		WORKEXPERIENCEHOL:       toText(record.Get("WORK_EXPERIENCE_HOL")),
		OJT:                     toText(record.Get("OJT")),
		JOBSEARCHHOP:            toText(record.Get("JOB_SEARCH_HOP")),
		JOBSEARCHEA:             toText(record.Get("JOB_SEARCH_EA")),
		JOBSEARCHHOL:            toText(record.Get("JOB_SEARCH_HOL")),
		COMMSERVICESHOP:         toText(record.Get("COMM_SERVICES_HOP")),
		COMMSERVICESEA:          toText(record.Get("COMM_SERVICES_EA")),
		COMMSERVICESHOL:         toText(record.Get("COMM_SERVICES_HOL")),
		VOCATIONALEDTRAININGHOP: toText(record.Get("VOCATIONAL_ED_TRAINING_HOP")),
		VOCATIONALEDTRAININGEA:  toText(record.Get("VOCATIONAL_ED_TRAINING_EA")),
		VOCATIONALEDTRAININGHOL: toText(record.Get("VOCATIONAL_ED_TRAINING_HOL")),
		JOBSKILLSTRAININGHOP:    toText(record.Get("JOB_SKILLS_TRAINING_HOP")),
		JOBSKILLSTRAININGEA:     toText(record.Get("JOB_SKILLS_TRAINING_EA")),
		JOBSKILLSTRAININGHOL:    toText(record.Get("JOB_SKILLS_TRAINING_HOL")),
		EDNOHIGHSCHOOLDIPLHOP:   toText(record.Get("ED_NO_HIGH_SCHOOL_DIPL_HOP")),
		EDNOHIGHSCHOOLDIPLEA:    toText(record.Get("ED_NO_HIGH_SCHOOL_DIPL_EA")),
		EDNOHIGHSCHOOLDIPLHOL:   toText(record.Get("ED_NO_HIGH_SCHOOL_DIPL_HOL")),
		SCHOOLATTENDENCEHOP:     toText(record.Get("SCHOOL_ATTENDENCE_HOP")),
		SCHOOLATTENDENCEEA:      toText(record.Get("SCHOOL_ATTENDENCE_EA")),
		SCHOOLATTENDENCEHOL:     toText(record.Get("SCHOOL_ATTENDENCE_HOL")),
		PROVIDECCHOP:            toText(record.Get("PROVIDE_CC_HOP")),
		PROVIDECCEA:             toText(record.Get("PROVIDE_CC_EA")),
		PROVIDECCHOL:            toText(record.Get("PROVIDE_CC_HOL")),
		OTHERWORKACTIVITIES:     toText(record.Get("OTHER_WORK_ACTIVITIES")),
		DEEMEDHOURSFOROVERALL:   toText(record.Get("DEEMED_HOURS_FOR_OVERALL")),
		DEEMEDHOURSFORTWOPARENT: toText(record.Get("DEEMED_HOURS_FOR_TWO_PARENT")),
		EARNEDINCOME:            toText(record.Get("EARNED_INCOME")),
		UNEARNEDINCOMETAXCREDIT: toText(record.Get("UNEARNED_INCOME_TAX_CREDIT")),
		UNEARNEDSOCIALSECURITY:  toText(record.Get("UNEARNED_SOCIAL_SECURITY")),
		UNEARNEDSSI:             toText(record.Get("UNEARNED_SSI")),
		UNEARNEDWORKERSCOMP:     toText(record.Get("UNEARNED_WORKERS_COMP")),
		OTHERUNEARNEDINCOME:     toText(record.Get("OTHER_UNEARNED_INCOME")),
		ID:                      newUUID(),
		DatafileID:              toDatafileID(datafileID),
		LineNumber:              toLineNumber(record.LineNumber),
	}

	// Return values in schema field order + id, datafile_id, line_number
	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.NONCUSTODIALPARENT,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.FEDOASDIPROGRAM,
		rec.FEDDISABILITYSTATUS,
		rec.DISABLEDTITLEXIVAPDT,
		rec.AIDAGEDBLIND,
		rec.RECEIVESSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.COOPERATIONCHILDSUPPORT,
		rec.MONTHSFEDTIMELIMIT,
		rec.MONTHSSTATETIMELIMIT,
		rec.CURRENTMONTHSTATEEXEMPT,
		rec.EMPLOYMENTSTATUS,
		rec.WORKELIGIBLEINDICATOR,
		rec.WORKPARTSTATUS,
		rec.UNSUBEMPLOYMENT,
		rec.SUBPRIVATEEMPLOYMENT,
		rec.SUBPUBLICEMPLOYMENT,
		rec.WORKEXPERIENCEHOP,
		rec.WORKEXPERIENCEEA,
		rec.WORKEXPERIENCEHOL,
		rec.OJT,
		rec.JOBSEARCHHOP,
		rec.JOBSEARCHEA,
		rec.JOBSEARCHHOL,
		rec.COMMSERVICESHOP,
		rec.COMMSERVICESEA,
		rec.COMMSERVICESHOL,
		rec.VOCATIONALEDTRAININGHOP,
		rec.VOCATIONALEDTRAININGEA,
		rec.VOCATIONALEDTRAININGHOL,
		rec.JOBSKILLSTRAININGHOP,
		rec.JOBSKILLSTRAININGEA,
		rec.JOBSKILLSTRAININGHOL,
		rec.EDNOHIGHSCHOOLDIPLHOP,
		rec.EDNOHIGHSCHOOLDIPLEA,
		rec.EDNOHIGHSCHOOLDIPLHOL,
		rec.SCHOOLATTENDENCEHOP,
		rec.SCHOOLATTENDENCEEA,
		rec.SCHOOLATTENDENCEHOL,
		rec.PROVIDECCHOP,
		rec.PROVIDECCEA,
		rec.PROVIDECCHOL,
		rec.OTHERWORKACTIVITIES,
		rec.DEEMEDHOURSFOROVERALL,
		rec.DEEMEDHOURSFORTWOPARENT,
		rec.EARNEDINCOME,
		rec.UNEARNEDINCOMETAXCREDIT,
		rec.UNEARNEDSOCIALSECURITY,
		rec.UNEARNEDSSI,
		rec.UNEARNEDWORKERSCOMP,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// TANF T3 Converter - Child-level data for active TANF cases
// T3 records contain data for TWO children per line. This converter
// produces 1 or 2 rows depending on whether Child 2 data is present.

func convertTanfT3(record *schema.ParsedRecord, datafileID int32) [][]any {
	// Child 1 row (always present)
	rec := &db.SearchIndexesTanfT3{
		RecordType:            toText(record.Get("RecordType")),
		RPTMONTHYEAR:          toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:            toText(record.Get("CASE_NUMBER")),
		FAMILYAFFILIATION:     toInt4(record.Get("FAMILY_AFFILIATION")),
		DATEOFBIRTH:           toText(record.Get("DATE_OF_BIRTH")),
		SSN:                   toText(record.Get("SSN")),
		RACEHISPANIC:          toInt4(record.Get("RACE_HISPANIC")),
		RACEAMERINDIAN:        toInt4(record.Get("RACE_AMER_INDIAN")),
		RACEASIAN:             toInt4(record.Get("RACE_ASIAN")),
		RACEBLACK:             toInt4(record.Get("RACE_BLACK")),
		RACEHAWAIIAN:          toInt4(record.Get("RACE_HAWAIIAN")),
		RACEWHITE:             toInt4(record.Get("RACE_WHITE")),
		SEX:                   toInt4(record.Get("SEX")),
		RECEIVENONSSABENEFITS: toInt4(record.Get("RECEIVE_NONSSA_BENEFITS")),
		RECEIVESSI:            toInt4(record.Get("RECEIVE_SSI")),
		RELATIONSHIPHOH:       toText(record.Get("RELATIONSHIP_HOH")),
		PARENTMINORCHILD:      toInt4(record.Get("PARENT_MINOR_CHILD")),
		EDUCATIONLEVEL:        toText(record.Get("EDUCATION_LEVEL")),
		CITIZENSHIPSTATUS:     toInt4(record.Get("CITIZENSHIP_STATUS")),
		UNEARNEDSSI:           toText(record.Get("UNEARNED_SSI")),
		OTHERUNEARNEDINCOME:   toText(record.Get("OTHER_UNEARNED_INCOME")),
		ID:                    newUUID(),
		DatafileID:            toDatafileID(datafileID),
		LineNumber:            toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECEIVENONSSABENEFITS,
		rec.RECEIVESSI,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.UNEARNEDSSI,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// TANF T4 Converter - Case-level data for closed TANF cases

func convertTanfT4(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesTanfT4{
		RecordType:     toText(record.Get("RecordType")),
		RPTMONTHYEAR:   toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:     toText(record.Get("CASE_NUMBER")),
		COUNTYFIPSCODE: toText(record.Get("COUNTY_FIPS_CODE")),
		STRATUM:        toText(record.Get("STRATUM")),
		ZIPCODE:        toText(record.Get("ZIP_CODE")),
		DISPOSITION:    toInt4(record.Get("DISPOSITION")),
		CLOSUREREASON:  toText(record.Get("CLOSURE_REASON")),
		RECSUBHOUSING:  toInt4(record.Get("REC_SUB_HOUSING")),
		RECMEDASSIST:   toInt4(record.Get("REC_MED_ASSIST")),
		RECFOODSTAMPS:  toInt4(record.Get("REC_FOOD_STAMPS")),
		RECSUBCC:       toInt4(record.Get("REC_SUB_CC")),
		ID:             newUUID(),
		DatafileID:     toDatafileID(datafileID),
		LineNumber:     toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.DISPOSITION,
		rec.CLOSUREREASON,
		rec.RECSUBHOUSING,
		rec.RECMEDASSIST,
		rec.RECFOODSTAMPS,
		rec.RECSUBCC,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// TANF T5 Converter - Adult-level data for closed TANF cases

func convertTanfT5(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesTanfT5{
		RecordType:                toText(record.Get("RecordType")),
		RPTMONTHYEAR:              toInt4(record.Get("RPT_MONTH_YEAR")),
		CASENUMBER:                toText(record.Get("CASE_NUMBER")),
		FAMILYAFFILIATION:         toInt4(record.Get("FAMILY_AFFILIATION")),
		DATEOFBIRTH:               toText(record.Get("DATE_OF_BIRTH")),
		SSN:                       toText(record.Get("SSN")),
		RACEHISPANIC:              toInt4(record.Get("RACE_HISPANIC")),
		RACEAMERINDIAN:            toInt4(record.Get("RACE_AMER_INDIAN")),
		RACEASIAN:                 toInt4(record.Get("RACE_ASIAN")),
		RACEBLACK:                 toInt4(record.Get("RACE_BLACK")),
		RACEHAWAIIAN:              toInt4(record.Get("RACE_HAWAIIAN")),
		RACEWHITE:                 toInt4(record.Get("RACE_WHITE")),
		SEX:                       toInt4(record.Get("SEX")),
		RECOASDIINSURANCE:         toInt4(record.Get("REC_OASDI_INSURANCE")),
		RECFEDERALDISABILITY:      toInt4(record.Get("REC_FEDERAL_DISABILITY")),
		RECAIDTOTALLYDISABLED:     toInt4(record.Get("REC_AID_TOTALLY_DISABLED")),
		RECAIDAGEDBLIND:           toInt4(record.Get("REC_AID_AGED_BLIND")),
		RECSSI:                    toInt4(record.Get("REC_SSI")),
		MARITALSTATUS:             toInt4(record.Get("MARITAL_STATUS")),
		RELATIONSHIPHOH:           toText(record.Get("RELATIONSHIP_HOH")),
		PARENTMINORCHILD:          toInt4(record.Get("PARENT_MINOR_CHILD")),
		NEEDSOFPREGNANTWOMAN:      toInt4(record.Get("NEEDS_OF_PREGNANT_WOMAN")),
		EDUCATIONLEVEL:            toText(record.Get("EDUCATION_LEVEL")),
		CITIZENSHIPSTATUS:         toInt4(record.Get("CITIZENSHIP_STATUS")),
		COUNTABLEMONTHFEDTIME:     toText(record.Get("COUNTABLE_MONTH_FED_TIME")),
		COUNTABLEMONTHSSTATETRIBE: toText(record.Get("COUNTABLE_MONTHS_STATE_TRIBE")),
		EMPLOYMENTSTATUS:          toInt4(record.Get("EMPLOYMENT_STATUS")),
		AMOUNTEARNEDINCOME:        toText(record.Get("AMOUNT_EARNED_INCOME")),
		AMOUNTUNEARNEDINCOME:      toText(record.Get("AMOUNT_UNEARNED_INCOME")),
		ID:                        newUUID(),
		DatafileID:                toDatafileID(datafileID),
		LineNumber:                toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECOASDIINSURANCE,
		rec.RECFEDERALDISABILITY,
		rec.RECAIDTOTALLYDISABLED,
		rec.RECAIDAGEDBLIND,
		rec.RECSSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSOFPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.COUNTABLEMONTHFEDTIME,
		rec.COUNTABLEMONTHSSTATETRIBE,
		rec.EMPLOYMENTSTATUS,
		rec.AMOUNTEARNEDINCOME,
		rec.AMOUNTUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// TANF T6 Converter - Aggregate data

func convertTanfT6(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesTanfT6{
		RecordType:          toText(record.Get("RecordType")),
		CALENDARQUARTER:     toInt4(record.Get("CALENDAR_QUARTER")),
		RPTMONTHYEAR:        toInt4(record.Get("RPT_MONTH_YEAR")),
		NUMAPPLICATIONS:     toInt4(record.Get("NUM_APPLICATIONS")),
		NUMAPPROVED:         toInt4(record.Get("NUM_APPROVED")),
		NUMDENIED:           toInt4(record.Get("NUM_DENIED")),
		ASSISTANCE:          toInt4(record.Get("ASSISTANCE")),
		NUMFAMILIES:         toInt4(record.Get("NUM_FAMILIES")),
		NUM2PARENTS:         toInt4(record.Get("NUM_2_PARENTS")),
		NUM1PARENTS:         toInt4(record.Get("NUM_1_PARENTS")),
		NUMNOPARENTS:        toInt4(record.Get("NUM_NO_PARENTS")),
		NUMRECIPIENTS:       toInt4(record.Get("NUM_RECIPIENTS")),
		NUMADULTRECIPIENTS:  toInt4(record.Get("NUM_ADULT_RECIPIENTS")),
		NUMCHILDRECIPIENTS:  toInt4(record.Get("NUM_CHILD_RECIPIENTS")),
		NUMNONCUSTODIALS:    toInt4(record.Get("NUM_NONCUSTODIALS")),
		NUMBIRTHS:           toInt4(record.Get("NUM_BIRTHS")),
		NUMOUTWEDLOCKBIRTHS: toInt4(record.Get("NUM_OUTWEDLOCK_BIRTHS")),
		NUMCLOSEDCASES:      toInt4(record.Get("NUM_CLOSED_CASES")),
		ID:                  newUUID(),
		DatafileID:          toDatafileID(datafileID),
		LineNumber:          toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.NUMAPPLICATIONS,
		rec.NUMAPPROVED,
		rec.NUMDENIED,
		rec.ASSISTANCE,
		rec.NUMFAMILIES,
		rec.NUM2PARENTS,
		rec.NUM1PARENTS,
		rec.NUMNOPARENTS,
		rec.NUMRECIPIENTS,
		rec.NUMADULTRECIPIENTS,
		rec.NUMCHILDRECIPIENTS,
		rec.NUMNONCUSTODIALS,
		rec.NUMBIRTHS,
		rec.NUMOUTWEDLOCKBIRTHS,
		rec.NUMCLOSEDCASES,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// TANF T7 Converter - Stratum data

func convertTanfT7(record *schema.ParsedRecord, datafileID int32) [][]any {
	rec := &db.SearchIndexesTanfT7{
		RecordType:      toText(record.Get("RecordType")),
		CALENDARQUARTER: toInt4(record.Get("CALENDAR_QUARTER")),
		RPTMONTHYEAR:    toInt4(record.Get("RPT_MONTH_YEAR")),
		TDRSSECTIONIND:  toText(record.Get("TDRS_SECTION_IND")),
		STRATUM:         toText(record.Get("STRATUM")),
		FAMILIESMONTH:   toInt4(record.Get("FAMILIES_MONTH")),
		ID:              newUUID(),
		DatafileID:      toDatafileID(datafileID),
		LineNumber:      toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.TDRSSECTIONIND,
		rec.STRATUM,
		rec.FAMILIESMONTH,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}
