package converter

import (
	"go-parser/internal/db"
	"go-parser/internal/schema"
)

// Tribal TANF T1 Converter - Case-level data for active Tribal TANF cases

func convertTribalT1(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesTribalTanfT1{
		RecordType:               toText(f["RecordType"]),
		RPTMONTHYEAR:             toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:               toText(f["CASE_NUMBER"]),
		COUNTYFIPSCODE:           toText(f["COUNTY_FIPS_CODE"]),
		STRATUM:                  toText(f["STRATUM"]),
		ZIPCODE:                  toText(f["ZIP_CODE"]),
		FUNDINGSTREAM:            toInt4(f["FUNDING_STREAM"]),
		DISPOSITION:              toInt4(f["DISPOSITION"]),
		NEWAPPLICANT:             toInt4(f["NEW_APPLICANT"]),
		NBRFAMILYMEMBERS:         toInt4(f["NBR_FAMILY_MEMBERS"]),
		FAMILYTYPE:               toInt4(f["FAMILY_TYPE"]),
		RECEIVESSUBHOUSING:       toInt4(f["RECEIVES_SUB_HOUSING"]),
		RECEIVESMEDASSISTANCE:    toInt4(f["RECEIVES_MED_ASSISTANCE"]),
		RECEIVESFOODSTAMPS:       toInt4(f["RECEIVES_FOOD_STAMPS"]),
		AMTFOODSTAMPASSISTANCE:   toInt4(f["AMT_FOOD_STAMP_ASSISTANCE"]),
		RECEIVESSUBCC:            toInt4(f["RECEIVES_SUB_CC"]),
		AMTSUBCC:                 toInt4(f["AMT_SUB_CC"]),
		CHILDSUPPORTAMT:          toInt4(f["CHILD_SUPPORT_AMT"]),
		FAMILYCASHRESOURCES:      toInt4(f["FAMILY_CASH_RESOURCES"]),
		CASHAMOUNT:               toInt4(f["CASH_AMOUNT"]),
		NBRMONTHS:                toInt4(f["NBR_MONTHS"]),
		CCAMOUNT:                 toInt4(f["CC_AMOUNT"]),
		CHILDRENCOVERED:          toInt4(f["CHILDREN_COVERED"]),
		CCNBRMONTHS:              toInt4(f["CC_NBR_MONTHS"]),
		TRANSPAMOUNT:             toInt4(f["TRANSP_AMOUNT"]),
		TRANSPNBRMONTHS:          toInt4(f["TRANSP_NBR_MONTHS"]),
		TRANSITIONSERVICESAMOUNT: toInt4(f["TRANSITION_SERVICES_AMOUNT"]),
		TRANSITIONNBRMONTHS:      toInt4(f["TRANSITION_NBR_MONTHS"]),
		OTHERAMOUNT:              toInt4(f["OTHER_AMOUNT"]),
		OTHERNBRMONTHS:           toInt4(f["OTHER_NBR_MONTHS"]),
		SANCREDUCTIONAMT:         toInt4(f["SANC_REDUCTION_AMT"]),
		WORKREQSANCTION:          toInt4(f["WORK_REQ_SANCTION"]),
		FAMILYSANCADULT:          toInt4(f["FAMILY_SANC_ADULT"]),
		SANCTEENPARENT:           toInt4(f["SANC_TEEN_PARENT"]),
		NONCOOPERATIONCSE:        toInt4(f["NON_COOPERATION_CSE"]),
		FAILURETOCOMPLY:          toInt4(f["FAILURE_TO_COMPLY"]),
		OTHERSANCTION:            toInt4(f["OTHER_SANCTION"]),
		RECOUPMENTPRIOROVRPMT:    toInt4(f["RECOUPMENT_PRIOR_OVRPMT"]),
		OTHERTOTALREDUCTIONS:     toInt4(f["OTHER_TOTAL_REDUCTIONS"]),
		FAMILYCAP:                toInt4(f["FAMILY_CAP"]),
		REDUCTIONSONRECEIPTS:     toInt4(f["REDUCTIONS_ON_RECEIPTS"]),
		OTHERNONSANCTION:         toInt4(f["OTHER_NON_SANCTION"]),
		WAIVEREVALCONTROLGRPS:    toInt4(f["WAIVER_EVAL_CONTROL_GRPS"]),
		FAMILYEXEMPTTIMELIMITS:   toInt4(f["FAMILY_EXEMPT_TIME_LIMITS"]),
		FAMILYNEWCHILD:           toInt4(f["FAMILY_NEW_CHILD"]),
		ID:                       newUUID(),
		DatafileID:               toDatafileID(datafileID),
		LineNumber:               toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.FUNDINGSTREAM,
		rec.DISPOSITION,
		rec.NEWAPPLICANT,
		rec.NBRFAMILYMEMBERS,
		rec.FAMILYTYPE,
		rec.RECEIVESSUBHOUSING,
		rec.RECEIVESMEDASSISTANCE,
		rec.RECEIVESFOODSTAMPS,
		rec.AMTFOODSTAMPASSISTANCE,
		rec.RECEIVESSUBCC,
		rec.AMTSUBCC,
		rec.CHILDSUPPORTAMT,
		rec.FAMILYCASHRESOURCES,
		rec.CASHAMOUNT,
		rec.NBRMONTHS,
		rec.CCAMOUNT,
		rec.CHILDRENCOVERED,
		rec.CCNBRMONTHS,
		rec.TRANSPAMOUNT,
		rec.TRANSPNBRMONTHS,
		rec.TRANSITIONSERVICESAMOUNT,
		rec.TRANSITIONNBRMONTHS,
		rec.OTHERAMOUNT,
		rec.OTHERNBRMONTHS,
		rec.SANCREDUCTIONAMT,
		rec.WORKREQSANCTION,
		rec.FAMILYSANCADULT,
		rec.SANCTEENPARENT,
		rec.NONCOOPERATIONCSE,
		rec.FAILURETOCOMPLY,
		rec.OTHERSANCTION,
		rec.RECOUPMENTPRIOROVRPMT,
		rec.OTHERTOTALREDUCTIONS,
		rec.FAMILYCAP,
		rec.REDUCTIONSONRECEIPTS,
		rec.OTHERNONSANCTION,
		rec.WAIVEREVALCONTROLGRPS,
		rec.FAMILYEXEMPTTIMELIMITS,
		rec.FAMILYNEWCHILD,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// Tribal TANF T2 Converter - Adult-level data for active Tribal TANF cases

func convertTribalT2(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesTribalTanfT2{
		RecordType:              toText(f["RecordType"]),
		RPTMONTHYEAR:            toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:              toText(f["CASE_NUMBER"]),
		FAMILYAFFILIATION:       toInt4(f["FAMILY_AFFILIATION"]),
		NONCUSTODIALPARENT:      toInt4(f["NONCUSTODIAL_PARENT"]),
		DATEOFBIRTH:             toText(f["DATE_OF_BIRTH"]),
		SSN:                     toText(f["SSN"]),
		RACEHISPANIC:            toInt4(f["RACE_HISPANIC"]),
		RACEAMERINDIAN:          toInt4(f["RACE_AMER_INDIAN"]),
		RACEASIAN:               toInt4(f["RACE_ASIAN"]),
		RACEBLACK:               toInt4(f["RACE_BLACK"]),
		RACEHAWAIIAN:            toInt4(f["RACE_HAWAIIAN"]),
		RACEWHITE:               toInt4(f["RACE_WHITE"]),
		SEX:                     toInt4(f["SEX"]),
		FEDOASDIPROGRAM:         toInt4(f["FED_OASDI_PROGRAM"]),
		FEDDISABILITYSTATUS:     toInt4(f["FED_DISABILITY_STATUS"]),
		DISABLEDTITLEXIVAPDT:    toInt4(f["DISABLED_TITLE_XIVAPDT"]),
		AIDAGEDBLIND:            toInt4(f["AID_AGED_BLIND"]),
		RECEIVESSI:              toInt4(f["RECEIVE_SSI"]),
		MARITALSTATUS:           toInt4(f["MARITAL_STATUS"]),
		RELATIONSHIPHOH:         toText(f["RELATIONSHIP_HOH"]),
		PARENTMINORCHILD:        toInt4(f["PARENT_MINOR_CHILD"]),
		NEEDSPREGNANTWOMAN:      toInt4(f["NEEDS_PREGNANT_WOMAN"]),
		EDUCATIONLEVEL:          toText(f["EDUCATION_LEVEL"]),
		CITIZENSHIPSTATUS:       toInt4(f["CITIZENSHIP_STATUS"]),
		COOPERATIONCHILDSUPPORT: toInt4(f["COOPERATION_CHILD_SUPPORT"]),
		MONTHSFEDTIMELIMIT:      toText(f["MONTHS_FED_TIME_LIMIT"]),
		MONTHSSTATETIMELIMIT:    toText(f["MONTHS_STATE_TIME_LIMIT"]),
		CURRENTMONTHSTATEEXEMPT: toInt4(f["CURRENT_MONTH_STATE_EXEMPT"]),
		EMPLOYMENTSTATUS:        toInt4(f["EMPLOYMENT_STATUS"]),
		WORKPARTSTATUS:          toText(f["WORK_PART_STATUS"]),
		UNSUBEMPLOYMENT:         toText(f["UNSUB_EMPLOYMENT"]),
		SUBPRIVATEEMPLOYMENT:    toText(f["SUB_PRIVATE_EMPLOYMENT"]),
		SUBPUBLICEMPLOYMENT:     toText(f["SUB_PUBLIC_EMPLOYMENT"]),
		WORKEXPERIENCE:          toText(f["WORK_EXPERIENCE"]),
		OJT:                     toText(f["OJT"]),
		JOBSEARCH:               toText(f["JOB_SEARCH"]),
		COMMSERVICES:            toText(f["COMM_SERVICES"]),
		VOCATIONALEDTRAINING:    toText(f["VOCATIONAL_ED_TRAINING"]),
		JOBSKILLSTRAINING:       toText(f["JOB_SKILLS_TRAINING"]),
		EDNOHIGHSCHOOLDIPLOMA:   toText(f["ED_NO_HIGH_SCHOOL_DIPLOMA"]),
		SCHOOLATTENDENCE:        toText(f["SCHOOL_ATTENDENCE"]),
		PROVIDECC:               toText(f["PROVIDE_CC"]),
		ADDWORKACTIVITIES:       toText(f["ADD_WORK_ACTIVITIES"]),
		OTHERWORKACTIVITIES:     toText(f["OTHER_WORK_ACTIVITIES"]),
		REQHRSWAIVERDEMO:        toText(f["REQ_HRS_WAIVER_DEMO"]),
		EARNEDINCOME:            toText(f["EARNED_INCOME"]),
		UNEARNEDINCOMETAXCREDIT: toText(f["UNEARNED_INCOME_TAX_CREDIT"]),
		UNEARNEDSOCIALSECURITY:  toText(f["UNEARNED_SOCIAL_SECURITY"]),
		UNEARNEDSSI:             toText(f["UNEARNED_SSI"]),
		UNEARNEDWORKERSCOMP:     toText(f["UNEARNED_WORKERS_COMP"]),
		OTHERUNEARNEDINCOME:     toText(f["OTHER_UNEARNED_INCOME"]),
		ID:                      newUUID(),
		DatafileID:              toDatafileID(datafileID),
		LineNumber:              toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.NONCUSTODIALPARENT,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.FEDOASDIPROGRAM,
		rec.FEDDISABILITYSTATUS,
		rec.DISABLEDTITLEXIVAPDT,
		rec.AIDAGEDBLIND,
		rec.RECEIVESSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.COOPERATIONCHILDSUPPORT,
		rec.MONTHSFEDTIMELIMIT,
		rec.MONTHSSTATETIMELIMIT,
		rec.CURRENTMONTHSTATEEXEMPT,
		rec.EMPLOYMENTSTATUS,
		rec.WORKPARTSTATUS,
		rec.UNSUBEMPLOYMENT,
		rec.SUBPRIVATEEMPLOYMENT,
		rec.SUBPUBLICEMPLOYMENT,
		rec.WORKEXPERIENCE,
		rec.OJT,
		rec.JOBSEARCH,
		rec.COMMSERVICES,
		rec.VOCATIONALEDTRAINING,
		rec.JOBSKILLSTRAINING,
		rec.EDNOHIGHSCHOOLDIPLOMA,
		rec.SCHOOLATTENDENCE,
		rec.PROVIDECC,
		rec.ADDWORKACTIVITIES,
		rec.OTHERWORKACTIVITIES,
		rec.REQHRSWAIVERDEMO,
		rec.EARNEDINCOME,
		rec.UNEARNEDINCOMETAXCREDIT,
		rec.UNEARNEDSOCIALSECURITY,
		rec.UNEARNEDSSI,
		rec.UNEARNEDWORKERSCOMP,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// Tribal TANF T3 Converter - Child-level data for active Tribal TANF cases
// Note: Like TANF T3, Tribal T3 may contain data for two children per line.
// For now, this converter only handles single-row output. Multi-row support
// can be added when Tribal T3 schema is confirmed to have _2 suffix fields.

func convertTribalT3(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesTribalTanfT3{
		RecordType:            toText(f["RecordType"]),
		RPTMONTHYEAR:          toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:            toText(f["CASE_NUMBER"]),
		FAMILYAFFILIATION:     toInt4(f["FAMILY_AFFILIATION"]),
		DATEOFBIRTH:           toText(f["DATE_OF_BIRTH"]),
		SSN:                   toText(f["SSN"]),
		RACEHISPANIC:          toInt4(f["RACE_HISPANIC"]),
		RACEAMERINDIAN:        toInt4(f["RACE_AMER_INDIAN"]),
		RACEASIAN:             toInt4(f["RACE_ASIAN"]),
		RACEBLACK:             toInt4(f["RACE_BLACK"]),
		RACEHAWAIIAN:          toInt4(f["RACE_HAWAIIAN"]),
		RACEWHITE:             toInt4(f["RACE_WHITE"]),
		SEX:                   toInt4(f["SEX"]),
		RECEIVENONSSABENEFITS: toInt4(f["RECEIVE_NONSSA_BENEFITS"]),
		RECEIVESSI:            toInt4(f["RECEIVE_SSI"]),
		RELATIONSHIPHOH:       toText(f["RELATIONSHIP_HOH"]),
		PARENTMINORCHILD:      toInt4(f["PARENT_MINOR_CHILD"]),
		EDUCATIONLEVEL:        toText(f["EDUCATION_LEVEL"]),
		CITIZENSHIPSTATUS:     toInt4(f["CITIZENSHIP_STATUS"]),
		UNEARNEDSSI:           toText(f["UNEARNED_SSI"]),
		OTHERUNEARNEDINCOME:   toText(f["OTHER_UNEARNED_INCOME"]),
		ID:                    newUUID(),
		DatafileID:            toDatafileID(datafileID),
		LineNumber:            toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECEIVENONSSABENEFITS,
		rec.RECEIVESSI,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.UNEARNEDSSI,
		rec.OTHERUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// Tribal TANF T4 Converter - Case-level data for closed Tribal TANF cases

func convertTribalT4(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesTribalTanfT4{
		RecordType:     toText(f["RecordType"]),
		RPTMONTHYEAR:   toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:     toText(f["CASE_NUMBER"]),
		COUNTYFIPSCODE: toText(f["COUNTY_FIPS_CODE"]),
		STRATUM:        toText(f["STRATUM"]),
		ZIPCODE:        toText(f["ZIP_CODE"]),
		DISPOSITION:    toInt4(f["DISPOSITION"]),
		CLOSUREREASON:  toText(f["CLOSURE_REASON"]),
		RECSUBHOUSING:  toInt4(f["REC_SUB_HOUSING"]),
		RECMEDASSIST:   toInt4(f["REC_MED_ASSIST"]),
		RECFOODSTAMPS:  toInt4(f["REC_FOOD_STAMPS"]),
		RECSUBCC:       toInt4(f["REC_SUB_CC"]),
		ID:             newUUID(),
		DatafileID:     toDatafileID(datafileID),
		LineNumber:     toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.COUNTYFIPSCODE,
		rec.STRATUM,
		rec.ZIPCODE,
		rec.DISPOSITION,
		rec.CLOSUREREASON,
		rec.RECSUBHOUSING,
		rec.RECMEDASSIST,
		rec.RECFOODSTAMPS,
		rec.RECSUBCC,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// Tribal TANF T5 Converter - Adult-level data for closed Tribal TANF cases

func convertTribalT5(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesTribalTanfT5{
		RecordType:                toText(f["RecordType"]),
		RPTMONTHYEAR:              toInt4(f["RPT_MONTH_YEAR"]),
		CASENUMBER:                toText(f["CASE_NUMBER"]),
		FAMILYAFFILIATION:         toInt4(f["FAMILY_AFFILIATION"]),
		DATEOFBIRTH:               toText(f["DATE_OF_BIRTH"]),
		SSN:                       toText(f["SSN"]),
		RACEHISPANIC:              toInt4(f["RACE_HISPANIC"]),
		RACEAMERINDIAN:            toInt4(f["RACE_AMER_INDIAN"]),
		RACEASIAN:                 toInt4(f["RACE_ASIAN"]),
		RACEBLACK:                 toInt4(f["RACE_BLACK"]),
		RACEHAWAIIAN:              toInt4(f["RACE_HAWAIIAN"]),
		RACEWHITE:                 toInt4(f["RACE_WHITE"]),
		SEX:                       toInt4(f["SEX"]),
		RECOASDIINSURANCE:         toInt4(f["REC_OASDI_INSURANCE"]),
		RECFEDERALDISABILITY:      toInt4(f["REC_FEDERAL_DISABILITY"]),
		RECAIDTOTALLYDISABLED:     toInt4(f["REC_AID_TOTALLY_DISABLED"]),
		RECAIDAGEDBLIND:           toInt4(f["REC_AID_AGED_BLIND"]),
		RECSSI:                    toInt4(f["REC_SSI"]),
		MARITALSTATUS:             toInt4(f["MARITAL_STATUS"]),
		RELATIONSHIPHOH:           toText(f["RELATIONSHIP_HOH"]),
		PARENTMINORCHILD:          toInt4(f["PARENT_MINOR_CHILD"]),
		NEEDSOFPREGNANTWOMAN:      toInt4(f["NEEDS_OF_PREGNANT_WOMAN"]),
		EDUCATIONLEVEL:            toText(f["EDUCATION_LEVEL"]),
		CITIZENSHIPSTATUS:         toInt4(f["CITIZENSHIP_STATUS"]),
		COUNTABLEMONTHFEDTIME:     toText(f["COUNTABLE_MONTH_FED_TIME"]),
		COUNTABLEMONTHSSTATETRIBE: toText(f["COUNTABLE_MONTHS_STATE_TRIBE"]),
		EMPLOYMENTSTATUS:          toInt4(f["EMPLOYMENT_STATUS"]),
		AMOUNTEARNEDINCOME:        toText(f["AMOUNT_EARNED_INCOME"]),
		AMOUNTUNEARNEDINCOME:      toText(f["AMOUNT_UNEARNED_INCOME"]),
		ID:                        newUUID(),
		DatafileID:                toDatafileID(datafileID),
		LineNumber:                toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.RPTMONTHYEAR,
		rec.CASENUMBER,
		rec.FAMILYAFFILIATION,
		rec.DATEOFBIRTH,
		rec.SSN,
		rec.RACEHISPANIC,
		rec.RACEAMERINDIAN,
		rec.RACEASIAN,
		rec.RACEBLACK,
		rec.RACEHAWAIIAN,
		rec.RACEWHITE,
		rec.SEX,
		rec.RECOASDIINSURANCE,
		rec.RECFEDERALDISABILITY,
		rec.RECAIDTOTALLYDISABLED,
		rec.RECAIDAGEDBLIND,
		rec.RECSSI,
		rec.MARITALSTATUS,
		rec.RELATIONSHIPHOH,
		rec.PARENTMINORCHILD,
		rec.NEEDSOFPREGNANTWOMAN,
		rec.EDUCATIONLEVEL,
		rec.CITIZENSHIPSTATUS,
		rec.COUNTABLEMONTHFEDTIME,
		rec.COUNTABLEMONTHSSTATETRIBE,
		rec.EMPLOYMENTSTATUS,
		rec.AMOUNTEARNEDINCOME,
		rec.AMOUNTUNEARNEDINCOME,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// Tribal TANF T6 Converter - Aggregate data

func convertTribalT6(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesTribalTanfT6{
		RecordType:          toText(f["RecordType"]),
		CALENDARQUARTER:     toInt4(f["CALENDAR_QUARTER"]),
		RPTMONTHYEAR:        toInt4(f["RPT_MONTH_YEAR"]),
		NUMAPPLICATIONS:     toInt4(f["NUM_APPLICATIONS"]),
		NUMAPPROVED:         toInt4(f["NUM_APPROVED"]),
		NUMDENIED:           toInt4(f["NUM_DENIED"]),
		ASSISTANCE:          toInt4(f["ASSISTANCE"]),
		NUMFAMILIES:         toInt4(f["NUM_FAMILIES"]),
		NUM2PARENTS:         toInt4(f["NUM_2_PARENTS"]),
		NUM1PARENTS:         toInt4(f["NUM_1_PARENTS"]),
		NUMNOPARENTS:        toInt4(f["NUM_NO_PARENTS"]),
		NUMRECIPIENTS:       toInt4(f["NUM_RECIPIENTS"]),
		NUMADULTRECIPIENTS:  toInt4(f["NUM_ADULT_RECIPIENTS"]),
		NUMCHILDRECIPIENTS:  toInt4(f["NUM_CHILD_RECIPIENTS"]),
		NUMNONCUSTODIALS:    toInt4(f["NUM_NONCUSTODIALS"]),
		NUMBIRTHS:           toInt4(f["NUM_BIRTHS"]),
		NUMOUTWEDLOCKBIRTHS: toInt4(f["NUM_OUTWEDLOCK_BIRTHS"]),
		NUMCLOSEDCASES:      toInt4(f["NUM_CLOSED_CASES"]),
		ID:                  newUUID(),
		DatafileID:          toDatafileID(datafileID),
		LineNumber:          toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.NUMAPPLICATIONS,
		rec.NUMAPPROVED,
		rec.NUMDENIED,
		rec.ASSISTANCE,
		rec.NUMFAMILIES,
		rec.NUM2PARENTS,
		rec.NUM1PARENTS,
		rec.NUMNOPARENTS,
		rec.NUMRECIPIENTS,
		rec.NUMADULTRECIPIENTS,
		rec.NUMCHILDRECIPIENTS,
		rec.NUMNONCUSTODIALS,
		rec.NUMBIRTHS,
		rec.NUMOUTWEDLOCKBIRTHS,
		rec.NUMCLOSEDCASES,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}

// Tribal TANF T7 Converter - Stratum data

func convertTribalT7(record *schema.ParsedRecord, datafileID int32) [][]any {
	f := record.Fields

	rec := &db.SearchIndexesTribalTanfT7{
		RecordType:      toText(f["RecordType"]),
		CALENDARQUARTER: toInt4(f["CALENDAR_QUARTER"]),
		RPTMONTHYEAR:    toInt4(f["RPT_MONTH_YEAR"]),
		TDRSSECTIONIND:  toText(f["TDRS_SECTION_IND"]),
		STRATUM:         toText(f["STRATUM"]),
		FAMILIESMONTH:   toInt4(f["FAMILIES_MONTH"]),
		ID:              newUUID(),
		DatafileID:      toDatafileID(datafileID),
		LineNumber:      toLineNumber(record.LineNumber),
	}

	return singleRow([]any{
		rec.RecordType,
		rec.CALENDARQUARTER,
		rec.RPTMONTHYEAR,
		rec.TDRSSECTIONIND,
		rec.STRATUM,
		rec.FAMILIESMONTH,
		rec.ID,
		rec.DatafileID,
		rec.LineNumber,
	})
}
