# Generated by Django 2.2.6 on 2019-10-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191009_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanfuser',
            name='stt_code',
            field=models.CharField(default='', max_length=32, verbose_name='State, Tribe, or Territory code'),
        ),
    ]
