# Generated by Django 3.2.15 on 2023-03-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0004_parsererror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParserError',
        ),
    ]
