# Generated by Django 3.2.15 on 2023-04-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0005_delete_parsererror'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='T1',
            new_name='TANF_T1',
        ),
        migrations.RenameModel(
            old_name='T2',
            new_name='TANF_T2',
        ),
        migrations.RenameModel(
            old_name='T3',
            new_name='TANF_T3',
        ),
        migrations.RenameModel(
            old_name='T4',
            new_name='TANF_T4',
        ),
        migrations.RenameModel(
            old_name='T5',
            new_name='TANF_T5',
        ),
        migrations.RenameModel(
            old_name='T6',
            new_name='TANF_T6',
        ),
        migrations.RenameModel(
            old_name='T7',
            new_name='TANF_T7',
        ),
    ]
