# Generated by Django 3.2.15 on 2023-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0007_ssp_m1_ssp_m2_ssp_m3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanf_t2',
            name='aid_aged_blind',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='citizenship_status',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='comm_services_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='comm_services_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='comm_services_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='cooperation_child_support',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='current_month_state_exempt',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='deemed_hours_for_overall',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='deemed_hours_for_two_parent',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='disabled_title_xivapdt',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='earned_income',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='ed_no_high_school_dipl_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='ed_no_high_school_dipl_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='ed_no_high_school_dipl_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='family_affiliation',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='fed_disability_status',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='fed_oasdi_program',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='fips_code',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='job_search_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='job_search_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='job_search_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='job_skills_training_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='job_skills_training_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='job_skills_training_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='months_fed_time_limit',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='months_state_time_limit',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='needs_pregnant_woman',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='noncustodial_parent',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='ojt',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='other_unearned_income',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='other_work_activities',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='parent_minor_child',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='provide_cc_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='provide_cc_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='provide_cc_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='race_amer_indian',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='race_asian',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='race_black',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='race_hawaiian',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='race_hispanic',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='race_white',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='receive_ssi',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='record',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='relationship_hoh',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='rpt_month_year',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='school_attendence_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='school_attendence_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='school_attendence_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='sub_private_employment',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='sub_public_employment',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='unearned_income_tax_credit',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='unearned_social_security',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='unearned_ssi',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='unearned_workers_comp',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='unsub_employment',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='vocational_ed_training_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='vocational_ed_training_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='vocational_ed_training_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='work_eligible_indicator',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='work_experience_ea',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='work_experience_hol',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='work_experience_hop',
        ),
        migrations.RemoveField(
            model_name='tanf_t2',
            name='work_part_status',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='citizenship_status',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='family_affiliation',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='fips_code',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='other_unearned_income',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='parent_minor_child',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='race_amer_indian',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='race_asian',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='race_black',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='race_hawaiian',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='race_hispanic',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='race_white',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='receive_nonssa_benefits',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='receive_ssi',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='record',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='relationship_hoh',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='rpt_month_year',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='tanf_t3',
            name='unearned_ssi',
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='AID_AGED_BLIND',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CASE_NUMBER',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CITIZENSHIP_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMM_SERVICES_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMM_SERVICES_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COMM_SERVICES_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='COOPERATION_CHILD_SUPPORT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='CURRENT_MONTH_STATE_EXEMPT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DATE_OF_BIRTH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DEEMED_HOURS_FOR_OVERALL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DEEMED_HOURS_FOR_TWO_PARENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='DISABLED_TITLE_XIVAPDT',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='ED_NO_HIGH_SCHOOL_DIPL_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='ED_NO_HIGH_SCHOOL_DIPL_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='ED_NO_HIGH_SCHOOL_DIPL_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='EMPLOYMENT_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='FAMILY_AFFILIATION',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='FED_DISABILITY_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='FED_OASDI_PROGRAM',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='GENDER',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SEARCH_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_TRAINING_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_TRAINING_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='JOB_SKILLS_TRAINING_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='MARITAL_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='MONTHS_FED_TIME_LIMIT',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='MONTHS_STATE_TIME_LIMIT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NEEDS_PREGNANT_WOMAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='NONCUSTODIAL_PARENT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='OJT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='OTHER_UNEARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='OTHER_WORK_ACTIVITIES',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PARENT_WITH_MINOR_CHILD',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PROVIDE_CC_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PROVIDE_CC_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='PROVIDE_CC_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_AMER_INDIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_ASIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_BLACK',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_HAWAIIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_HISPANIC',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RACE_WHITE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RECEIVE_SSI',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RELATIONSHIP_HOH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='RecordType',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SCHOOL_ATTENDENCE_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SSN',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SUB_PRIVATE_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='SUB_PUBLIC_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_INCOME_TAX_CREDIT',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_SOCIAL_SECURITY',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_SSI',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNEARNED_WORKERS_COMP',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='UNSUB_EMPLOYMENT',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_TRAINING_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_TRAINING_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='VOCATIONAL_ED_TRAINING_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_ELIGIBLE_INDICATOR',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXPERIENCE_EA',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXPERIENCE_HOL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_EXPERIENCE_HOP',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='WORK_PART_STATUS',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='CASE_NUMBER',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='CITIZENSHIP_STATUS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='DATE_OF_BIRTH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='FAMILY_AFFILIATION',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='GENDER',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='OTHER_UNEARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='PARENT_MINOR_CHILD',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_AMER_INDIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_ASIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_BLACK',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_HAWAIIAN',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_HISPANIC',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RACE_WHITE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RECEIVE_NONSSA_BENEFITS',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RECEIVE_SSI',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RELATIONSHIP_HOH',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='RecordType',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='SSN',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='UNEARNED_SSI',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
