# Generated by Django 3.2.15 on 2023-06-01 14:38

from django.db import migrations, models
import uuid


model_names = [
    'tanf_t1',
    'tanf_t2',
    'tanf_t3',
    'tanf_t4',
    'tanf_t5',
    'tanf_t6',
    'tanf_t7',
    'ssp_m1',
    'ssp_m2',
    'ssp_m3',
]


operations = []
for model_name in model_names:
    operations.append(
        migrations.AddField(
            model_name=model_name,
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, serialize=False),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0009_auto_20230525_1959'),
    ]

    operations = operations
