# Generated by Django 3.2.15 on 2023-06-01 14:38

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    models = [
        apps.get_model("search_indexes", "TANF_T1"),
        apps.get_model("search_indexes", "TANF_T2"),
        apps.get_model("search_indexes", "TANF_T3"),
        apps.get_model("search_indexes", "TANF_T4"),
        apps.get_model("search_indexes", "TANF_T5"),
        apps.get_model("search_indexes", "TANF_T6"),
        apps.get_model("search_indexes", "TANF_T7"),
        apps.get_model("search_indexes", "SSP_M1"),
        apps.get_model("search_indexes", "SSP_M2"),
        apps.get_model("search_indexes", "SSP_M3"),
    ]

    for model in models:
        for row in model.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0010_add_tmp_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),

    ]
