# Generated by Django 3.2.15 on 2023-07-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0012_datafile_s3_versioning_id'),
        ('search_indexes', '0013_rename_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssp_m1',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m1_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='ssp_m2',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m2_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='ssp_m3',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m3_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='tanf_t1',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='tanf_t2',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='tanf_t3',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t3_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='tanf_t4',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t4_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='tanf_t5',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t5_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t6_parent', to='data_files.datafile'),
        ),
        migrations.AddField(
            model_name='tanf_t7',
            name='datafile',
            field=models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t7_parent', to='data_files.datafile'),
        ),
    ]
