# Generated by Django 3.2.15 on 2023-08-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0015_auto_20230810_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssp_m1',
            name='STRATUM',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t1',
            name='STRATUM',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
