# Generated by Django 3.2.15 on 2023-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0015_auto_20230724_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanf_t4',
            name='CLOSURE_REASON',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t4',
            name='COUNTY_FIPS_CODE',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t4',
            name='STRATUM',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='CITIZENSHIP_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='EMPLOYMENT_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='MARITAL_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='NEEDS_OF_PREGNANT_WOMAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='PARENT_MINOR_CHILD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='REC_AID_AGED_BLIND',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='REC_AID_TOTALLY_DISABLED',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='REC_FEDERAL_DISABILITY',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='REC_OASDI_INSURANCE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='REC_SSI',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='RELATIONSHIP_HOH',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
