# Generated by Django 3.2.15 on 2023-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0016_auto_20230803_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanf_t6',
            name='adult_recipients',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='assistance',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='births',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='calendar_quarter',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='child_recipients',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='closed_cases',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='families',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='fips_code',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='noncustodials',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='num_1_parents',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='num_2_parents',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='num_no_parents',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='outwedlock_births',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='record',
        ),
        migrations.RemoveField(
            model_name='tanf_t6',
            name='rpt_month_year',
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='ASSISTANCE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='CALENDAR_QUARTER',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_1_PARENTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_2_PARENTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_ADULT_RECIPIENTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_APPLICATIONS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_APPROVED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_BIRTHS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_CHILD_RECIPIENTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_CLOSED_CASES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_DENIED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_FAMILIES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_NONCUSTODIALS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_NO_PARENTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_OUTWEDLOCK_BIRTHS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='NUM_RECIPIENTS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='RecordType',
            field=models.CharField(max_length=156, null=True),
        ),
        migrations.AlterField(
            model_name='ssp_m1',
            name='STRATUM',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t1',
            name='STRATUM',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='AID_AGED_BLIND',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='CITIZENSHIP_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='COOPERATION_CHILD_SUPPORT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='CURRENT_MONTH_STATE_EXEMPT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='DISABLED_TITLE_XIVAPDT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='EMPLOYMENT_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='FED_DISABILITY_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='FED_OASDI_PROGRAM',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='MARITAL_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='NEEDS_PREGNANT_WOMAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='PARENT_WITH_MINOR_CHILD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RACE_AMER_INDIAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RACE_ASIAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RACE_BLACK',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RACE_HAWAIIAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RACE_HISPANIC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RACE_WHITE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RECEIVE_SSI',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t2',
            name='RELATIONSHIP_HOH',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='CITIZENSHIP_STATUS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='PARENT_MINOR_CHILD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RACE_AMER_INDIAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RACE_ASIAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RACE_BLACK',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RACE_HAWAIIAN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RACE_HISPANIC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RACE_WHITE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RECEIVE_NONSSA_BENEFITS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RECEIVE_SSI',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t3',
            name='RELATIONSHIP_HOH',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='AMOUNT_EARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='AMOUNT_UNEARNED_INCOME',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='COUNTABLE_MONTHS_STATE_TRIBE',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='COUNTABLE_MONTH_FED_TIME',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tanf_t5',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
