# Generated by Django 3.2.15 on 2023-08-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0017_auto_20230804_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanf_t6',
            name='CALENDAR_YEAR',
        ),
        migrations.AddField(
            model_name='tanf_t6',
            name='RPT_MONTH_YEAR',
            field=models.IntegerField(null=True),
        ),
    ]
