# Generated by Django 3.2.15 on 2023-10-18 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0012_datafile_s3_versioning_id'),
        ('search_indexes', '0018_auto_20230920_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSP_M6',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RecordType', models.CharField(max_length=156, null=True)),
                ('CALENDAR_QUARTER', models.IntegerField(blank=True, null=True)),
                ('RPT_MONTH_YEAR', models.IntegerField(null=True)),
                ('SSPMOE_FAMILIES', models.IntegerField(blank=True, null=True)),
                ('NUM_2_PARENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_1_PARENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_NO_PARENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_RECIPIENTS', models.IntegerField(blank=True, null=True)),
                ('ADULT_RECIPIENTS', models.IntegerField(blank=True, null=True)),
                ('CHILD_RECIPIENTS', models.IntegerField(blank=True, null=True)),
                ('NONCUSTODIALS', models.IntegerField(blank=True, null=True)),
                ('AMT_ASSISTANCE', models.IntegerField(blank=True, null=True)),
                ('CLOSED_CASES', models.IntegerField(blank=True, null=True)),
                ('datafile', models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m6_parent', to='data_files.datafile')),
            ],
        ),
    ]
