# Generated by Django 3.2.15 on 2023-11-21 18:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0012_datafile_s3_versioning_id'),
        ('search_indexes', '0022_tribal_tanf_t1_tribal_tanf_t2_tribal_tanf_t3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribal_TANF_T5',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RecordType', models.CharField(max_length=71, null=True)),
                ('RPT_MONTH_YEAR', models.IntegerField(null=True)),
                ('CASE_NUMBER', models.CharField(max_length=11, null=True)),
                ('FAMILY_AFFILIATION', models.IntegerField(null=True)),
                ('DATE_OF_BIRTH', models.CharField(max_length=8, null=True)),
                ('SSN', models.CharField(max_length=9, null=True)),
                ('RACE_HISPANIC', models.IntegerField(null=True)),
                ('RACE_AMER_INDIAN', models.IntegerField(null=True)),
                ('RACE_ASIAN', models.IntegerField(null=True)),
                ('RACE_BLACK', models.IntegerField(null=True)),
                ('RACE_HAWAIIAN', models.IntegerField(null=True)),
                ('RACE_WHITE', models.IntegerField(null=True)),
                ('GENDER', models.IntegerField(null=True)),
                ('REC_OASDI_INSURANCE', models.IntegerField(null=True)),
                ('REC_FEDERAL_DISABILITY', models.IntegerField(null=True)),
                ('REC_AID_TOTALLY_DISABLED', models.IntegerField(null=True)),
                ('REC_AID_AGED_BLIND', models.IntegerField(null=True)),
                ('REC_SSI', models.IntegerField(null=True)),
                ('MARITAL_STATUS', models.IntegerField(null=True)),
                ('RELATIONSHIP_HOH', models.CharField(max_length=2, null=True)),
                ('PARENT_MINOR_CHILD', models.IntegerField(null=True)),
                ('NEEDS_OF_PREGNANT_WOMAN', models.IntegerField(null=True)),
                ('EDUCATION_LEVEL', models.CharField(max_length=2, null=True)),
                ('CITIZENSHIP_STATUS', models.IntegerField(null=True)),
                ('COUNTABLE_MONTH_FED_TIME', models.CharField(max_length=3, null=True)),
                ('COUNTABLE_MONTHS_STATE_TRIBE', models.CharField(max_length=2, null=True)),
                ('EMPLOYMENT_STATUS', models.IntegerField(null=True)),
                ('AMOUNT_EARNED_INCOME', models.CharField(max_length=4, null=True)),
                ('AMOUNT_UNEARNED_INCOME', models.CharField(max_length=4, null=True)),
                ('datafile', models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribal_t5_parent', to='data_files.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='Tribal_TANF_T4',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RecordType', models.CharField(max_length=71, null=True)),
                ('RPT_MONTH_YEAR', models.IntegerField(null=True)),
                ('CASE_NUMBER', models.CharField(max_length=11, null=True)),
                ('COUNTY_FIPS_CODE', models.CharField(max_length=3, null=True)),
                ('STRATUM', models.CharField(max_length=2, null=True)),
                ('ZIP_CODE', models.CharField(max_length=5, null=True)),
                ('DISPOSITION', models.IntegerField(null=True)),
                ('CLOSURE_REASON', models.IntegerField(null=True)),
                ('REC_SUB_HOUSING', models.IntegerField(null=True)),
                ('REC_MED_ASSIST', models.IntegerField(null=True)),
                ('REC_FOOD_STAMPS', models.IntegerField(null=True)),
                ('REC_SUB_CC', models.IntegerField(null=True)),
                ('datafile', models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribal_t4_parent', to='data_files.datafile')),
            ],
        ),
    ]
