# Generated by Django 3.2.15 on 2023-11-29 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0012_datafile_s3_versioning_id'),
        ('search_indexes', '0023_tribal_tanf_t4_tribal_tanf_t5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribal_TANF_T6',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RecordType', models.CharField(max_length=156, null=True)),
                ('CALENDAR_QUARTER', models.IntegerField(blank=True, null=True)),
                ('RPT_MONTH_YEAR', models.IntegerField(null=True)),
                ('NUM_APPLICATIONS', models.IntegerField(blank=True, null=True)),
                ('NUM_APPROVED', models.IntegerField(blank=True, null=True)),
                ('NUM_DENIED', models.IntegerField(blank=True, null=True)),
                ('ASSISTANCE', models.IntegerField(blank=True, null=True)),
                ('NUM_FAMILIES', models.IntegerField(blank=True, null=True)),
                ('NUM_2_PARENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_1_PARENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_NO_PARENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_RECIPIENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_ADULT_RECIPIENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_CHILD_RECIPIENTS', models.IntegerField(blank=True, null=True)),
                ('NUM_NONCUSTODIALS', models.IntegerField(blank=True, null=True)),
                ('NUM_BIRTHS', models.IntegerField(blank=True, null=True)),
                ('NUM_OUTWEDLOCK_BIRTHS', models.IntegerField(blank=True, null=True)),
                ('NUM_CLOSED_CASES', models.IntegerField(blank=True, null=True)),
                ('datafile', models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tribal_t6_parent', to='data_files.datafile')),
            ],
        ),
    ]
