# Generated by Django 3.2.15 on 2024-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0027_tribal_ssp_tanf_dob_to_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssp_m2',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ssp_m3',
            name='EDUCATION_LEVEL',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
