# Generated by Django 3.2.15 on 2024-05-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0028_education_level_to_string'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssp_m1',
            options={'verbose_name': 'SSP M1'},
        ),
        migrations.AlterModelOptions(
            name='ssp_m2',
            options={'verbose_name': 'SSP M2'},
        ),
        migrations.AlterModelOptions(
            name='ssp_m3',
            options={'verbose_name': 'SSP M3'},
        ),
        migrations.AlterModelOptions(
            name='ssp_m4',
            options={'verbose_name': 'SSP M4'},
        ),
        migrations.AlterModelOptions(
            name='ssp_m5',
            options={'verbose_name': 'SSP M5'},
        ),
        migrations.AlterModelOptions(
            name='ssp_m6',
            options={'verbose_name': 'SSP M6'},
        ),
        migrations.AlterModelOptions(
            name='ssp_m7',
            options={'verbose_name': 'SSP M7'},
        ),
        migrations.AlterModelOptions(
            name='tanf_t1',
            options={'verbose_name': 'TANF T1'},
        ),
        migrations.AlterModelOptions(
            name='tanf_t2',
            options={'verbose_name': 'TANF T2'},
        ),
        migrations.AlterModelOptions(
            name='tanf_t3',
            options={'verbose_name': 'TANF T3'},
        ),
        migrations.AlterModelOptions(
            name='tanf_t4',
            options={'verbose_name': 'TANF T4'},
        ),
        migrations.AlterModelOptions(
            name='tanf_t5',
            options={'verbose_name': 'TANF T5'},
        ),
        migrations.AlterModelOptions(
            name='tanf_t6',
            options={'verbose_name': 'TANF T6'},
        ),
        migrations.AlterModelOptions(
            name='tanf_t7',
            options={'verbose_name': 'TANF T7'},
        ),
        migrations.AlterModelOptions(
            name='tribal_tanf_t1',
            options={'verbose_name': 'Tribal TANF T1'},
        ),
        migrations.AlterModelOptions(
            name='tribal_tanf_t2',
            options={'verbose_name': 'Tribal TANF T2'},
        ),
        migrations.AlterModelOptions(
            name='tribal_tanf_t3',
            options={'verbose_name': 'Tribal TANF T3'},
        ),
        migrations.AlterModelOptions(
            name='tribal_tanf_t4',
            options={'verbose_name': 'Tribal TANF T4'},
        ),
        migrations.AlterModelOptions(
            name='tribal_tanf_t5',
            options={'verbose_name': 'Tribal TANF T5'},
        ),
        migrations.AlterModelOptions(
            name='tribal_tanf_t6',
            options={'verbose_name': 'Tribal TANF T6'},
        ),
        migrations.AlterModelOptions(
            name='tribal_tanf_t7',
            options={'verbose_name': 'Tribal TANF T7'},
        ),
    ]
