# Generated by Django 3.2.15 on 2024-08-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0030_reparse_meta_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribal_tanf_t4',
            name='CLOSURE_REASON',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
