# Generated by Django 3.2.15 on 2025-01-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0032_auto_20241008_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssp_m2',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='ssp_m3',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='ssp_m5',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='tanf_t2',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='tanf_t3',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='tanf_t5',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='tribal_tanf_t2',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='tribal_tanf_t3',
            old_name='GENDER',
            new_name='SEX',
        ),
        migrations.RenameField(
            model_name='tribal_tanf_t5',
            old_name='GENDER',
            new_name='SEX',
        ),
    ]
