# Generated by Django 3.2.15 on 2025-02-28 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0017_alter_datafile_section'),
        ('search_indexes', '0033_auto_20250131_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TANF_Exiter1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RecordType', models.CharField(max_length=25, null=True)),
                ('EXIT_DATE', models.IntegerField(null=True)),
                ('SSN', models.CharField(max_length=9, null=True)),
                ('datafile', models.ForeignKey(blank=True, help_text='The parent file from which this record was created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tanf_exiter_1_parent', to='data_files.datafile')),
            ],
            options={
                'verbose_name': 'TANF Exiter 1',
            },
        ),
    ]
