# Generated by Django 3.2.15 on 2025-09-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search_indexes", "0034_tanf_exiter1"),
    ]

    operations = [
        migrations.AddField(
            model_name="ssp_m1",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ssp_m2",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ssp_m3",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ssp_m4",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ssp_m5",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ssp_m6",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ssp_m7",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_exiter1",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_t1",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_t2",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_t3",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_t4",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_t5",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_t6",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tanf_t7",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tribal_tanf_t1",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tribal_tanf_t2",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tribal_tanf_t3",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tribal_tanf_t4",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tribal_tanf_t5",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tribal_tanf_t6",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tribal_tanf_t7",
            name="line_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
