# Generated by Django 3.2.15 on 2025-10-10 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0022_datafile_is_program_audit"),
        ("search_indexes", "0035_add_line_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramAudit_T3",
            fields=[
                ("line_number", models.IntegerField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("RecordType", models.CharField(max_length=156, null=True)),
                ("RPT_MONTH_YEAR", models.IntegerField(null=True)),
                ("CASE_NUMBER", models.CharField(max_length=11, null=True)),
                ("FAMILY_AFFILIATION", models.IntegerField(null=True)),
                ("DATE_OF_BIRTH", models.CharField(max_length=8, null=True)),
                ("SSN", models.CharField(max_length=9, null=True)),
                ("CITIZENSHIP_STATUS", models.IntegerField(null=True)),
                (
                    "datafile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent file from which this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_audit_t3_parent",
                        to="data_files.datafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Audit T3",
            },
        ),
        migrations.CreateModel(
            name="ProgramAudit_T2",
            fields=[
                ("line_number", models.IntegerField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("RecordType", models.CharField(max_length=156, null=True)),
                ("RPT_MONTH_YEAR", models.IntegerField(null=True)),
                ("CASE_NUMBER", models.CharField(max_length=11, null=True)),
                ("FAMILY_AFFILIATION", models.IntegerField(null=True)),
                ("DATE_OF_BIRTH", models.CharField(max_length=8, null=True)),
                ("SSN", models.CharField(max_length=9, null=True)),
                ("CITIZENSHIP_STATUS", models.IntegerField(null=True)),
                (
                    "datafile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent file from which this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_audit_t2_parent",
                        to="data_files.datafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Audit T2",
            },
        ),
        migrations.CreateModel(
            name="ProgramAudit_T1",
            fields=[
                ("line_number", models.IntegerField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("RecordType", models.CharField(max_length=156, null=True)),
                ("RPT_MONTH_YEAR", models.IntegerField(null=True)),
                ("CASE_NUMBER", models.CharField(max_length=11, null=True)),
                ("FUNDING_STREAM", models.IntegerField(null=True)),
                ("CASH_AMOUNT", models.IntegerField(null=True)),
                (
                    "datafile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent file from which this record was created.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_audit_t1_parent",
                        to="data_files.datafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Audit T1",
            },
        ),
    ]
