# Generated by Django 5.2.14 on 2026-06-15 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search_indexes", "0037_shadowprogramaudit_t1_shadowprogramaudit_t2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shadowssp_m2",
            old_name="FIPS_CODE",
            new_name="COUNTY_FIPS_CODE",
        ),
        migrations.RenameField(
            model_name="ssp_m2",
            old_name="FIPS_CODE",
            new_name="COUNTY_FIPS_CODE",
        ),
        migrations.RemoveField(
            model_name="shadowssp_m1",
            name="FIPS_CODE",
        ),
        migrations.RemoveField(
            model_name="shadowssp_m3",
            name="FIPS_CODE",
        ),
        migrations.RemoveField(
            model_name="shadowtanf_t1",
            name="FIPS_CODE",
        ),
        migrations.RemoveField(
            model_name="ssp_m1",
            name="FIPS_CODE",
        ),
        migrations.RemoveField(
            model_name="ssp_m3",
            name="FIPS_CODE",
        ),
        migrations.RemoveField(
            model_name="tanf_t1",
            name="FIPS_CODE",
        ),
    ]
