# Generated by Django 3.2.15 on 2023-01-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0002_standardized_field_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t1',
            old_name='case_number',
            new_name='CASE_NUMBER',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='children_covered',
            new_name='CHILDREN_COVERED',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='child_support_amount',
            new_name='CHILD_SUPPORT_AMT',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='county_fips_code',
            new_name='COUNTY_FIPS_CODE',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='disposition',
            new_name='DISPOSITION',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='family_cash_recources',
            new_name='FAMILY_CASH_RESOURCES',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='family_type',
            new_name='FAMILY_TYPE',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='funding_stream',
            new_name='FUNDING_STREAM',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='new_applicant',
            new_name='NEW_APPLICANT',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='other_amount',
            new_name='OTHER_AMOUNT',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='other_non_sanction',
            new_name='OTHER_NON_SANCTION',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='receives_food_stamps',
            new_name='RECEIVES_FOOD_STAMPS',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='receives_medical_assistance',
            new_name='RECEIVES_MED_ASSISTANCE',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='receives_sub_housing',
            new_name='RECEIVES_SUB_HOUSING',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='stratum',
            new_name='STRATUM',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='transition_nbr_months',
            new_name='TRANSITION_NBR_MONTHS',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='transition_services_amount',
            new_name='TRANSITION_SERVICES_AMOUNT',
        ),
        migrations.RenameField(
            model_name='t1',
            old_name='zip_code',
            new_name='ZIP_CODE',
        ),
        migrations.AlterField(
            model_name='t1',
            name='FIPS_CODE',
            field=models.CharField(max_length=2),
        ),
    ]
