# commands:
  upload-codecov:
    description: Uploads testing code coverage results to Codecov
    parameters:
      component:
        description: The component of the application being tested, either backend or frontend.
        type: enum
        enum: [ "backend", "frontend" ]
      coverage-report:
        description: The path to the coverage report being uploaded.
        type: string
    steps:
      - run:
          name: Ensure Codecov uploader is installed, otherwise install it.
          command: ./scripts/codecov-check.sh
      - run:
          name: Determine Codecov metric flag
          command: |
            if [ "$CIRCLE_BRANCH" == "main" ] ; then
              CURRENT_FLAG=main-<<parameters.component>>
            elif [ "$CIRCLE_BRANCH" == "master" ] ; then
              CURRENT_FLAG=master-<<parameters.component>>
            else
              CURRENT_FLAG=dev-<<parameters.component>>
            fi
            echo "export CURRENT_FLAG=$CURRENT_FLAG" >> $BASH_ENV
      - run:
          name: Upload code coverage report of target branch
          command: codecov -t "$CODECOV_TOKEN" -f <<parameters.coverage-report>> -F "$CURRENT_FLAG"

  install-nodejs-machine:
    description: |
      Installs our target version of Node.JS using NVM (Node Version Manager)
      from the install location provided by machine executor images.
    steps:
      - run:
          name: Install Node.JS
          command: |
            sudo apt-get update
            sudo apt-get install -y libgbm-dev
            source /opt/circleci/.nvm/nvm.sh
            nvm install v22.13.0
            nvm alias default v22.13.0
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
            echo "nvm use v22.13.0" >> $BASH_ENV
            nvm use v22.13.0
            if command -v corepack >/dev/null 2>&1; then
              corepack enable
              corepack prepare yarn@4.6.0 --activate
            else
              npm install -g yarn@4.6.0
            fi
            node -v
            yarn -v

  install-yarn-packages:
    description: Install frontend dependencies using Yarn.
    parameters:
      app-dir:
        type: string
        default: tdrs-frontend
    steps:
      - run:
          name: Install Yarn packages
          command: |
            cd <<parameters.app-dir>>
            if [ -z "$NVM_DIR" ]; then
              export NVM_DIR="/opt/circleci/.nvm"
            fi
            if [ -s "$NVM_DIR/nvm.sh" ]; then
              . "$NVM_DIR/nvm.sh"
              nvm use v22.13.0
            fi
            if command -v corepack >/dev/null 2>&1; then
              corepack enable
              corepack prepare yarn@4.6.0 --activate
            elif ! command -v yarn >/dev/null 2>&1; then
              npm install -g yarn@4.6.0
            fi
            node -v
            yarn -v
            yarn install --immutable
