version: '3'

tasks:

  gitcfg:
    desc: Configure git
    cmds:
      - git config core.hooksPath .githooks

  create-network:
    desc: Create the external network
    cmds:
      - (docker network create external-net) || true

  init-backend:
    desc: Initialize the backend project
    dir: tdrs-backend
    cmds:
      - task: create-network
      - docker compose -f docker-compose.yml up -d --build
      - docker compose -f docker-compose.yml exec web sh -c "python ./manage.py makemigrations"
      - docker compose -f docker-compose.yml exec web sh -c "python ./manage.py migrate"
      - docker compose -f docker-compose.yml down

  drop-db:
    desc: Drop the backend database
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml down
      - docker volume rm tdrs-backend_postgres_data

  backend-up:
    desc: Start backend web server
    dir: tdrs-backend
    cmds:
      - task: create-network
      - docker compose -f docker-compose.yml up -d

  backend-down:
    desc: Stop backend web server
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml down

  backend-logs:
    desc: Show and follow backend web server logs
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml logs -f

  backend-clean-db:
    desc: Drop and recreate the backend database (DEV ONLY – nukes all data)
    dir: tdrs-backend
    cmds:
      # 1) Drop DB volume + stop containers
      - task: drop-db

      # 2) Bring services back up (including web) on a fresh volume
      - docker compose -f docker-compose.yml up -d --build

      # 3) Apply all migrations to initialize the new database
      - docker compose -f docker-compose.yml exec web sh -c "python manage.py migrate"


  backend-restart:
    desc: Restart backend web server
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml restart

  backend-bash:
    desc: Open a shell in the backend container
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml exec web bash

  backend-shell:
    desc: Open a Django shell in the backend container
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml exec web sh -c "python ./manage.py shell_plus"

  backend-exec:
    desc: Execute a manage.py command in the backend container."
    dir: tdrs-backend
    vars:
      CMD: '{{.CMD}}'
    cmds:
      - docker compose -f docker-compose.yml exec web sh -c "python manage.py {{.CMD}}"

  backend-exec-seed-db:
    desc: Seed DB with initial data in the backend container
    dir: tdrs-backend
    vars:
      SEED_NUM: '{{.SEED_NUM | default "100"}}'
    cmds:
      - task: backend-up
      - docker compose -f docker-compose.yml exec web sh -c "python manage.py migrate && python manage.py populate_stts && python ./manage.py seed_records --clear --num {{.SEED_NUM}}"
      - docker compose -f docker-compose.yml down

  backend-makemigrations:
    desc: Run makemigrations in backend container
    dir: tdrs-backend
    cmds:
      - task: backend-up
      - docker compose -f docker-compose.yml exec web sh -c "python manage.py makemigrations"

  backend-migrate:
    desc: Run migrate in backend container
    dir: tdrs-backend
    cmds:
      - task: backend-up
      - docker compose -f docker-compose.yml exec web sh -c "python manage.py migrate"

  backend-pytest:
    desc: 'Run pytest in the backend container. E.g: task backend-pytest PYTEST_ARGS="tdpservice/test/ -s -vv"'
    dir: tdrs-backend
    vars:
      PYTEST_ARGS: '{{.PYTEST_ARGS | default "."}}'
    cmds:
      - task: backend-up
      - docker compose -f docker-compose.yml exec web sh -c "pytest --basetemp=/home/tdpapp/ {{.PYTEST_ARGS}}"

  backend-pytest-cov:
    desc: 'Generate coverage.json file in the backend container. E.g: task backend-pytest-cov PYTEST_ARGS="tdpservice/test/ -s -vv"'
    dir: tdrs-backend
    vars:
      PYTEST_ARGS: '{{.PYTEST_ARGS | default "."}}'
    cmds:
      - task: backend-up
      - docker compose -f docker-compose.yml exec web sh -c "pytest --cov=tdpservice --cov-report=json --basetemp=/home/tdpapp/ {{.PYTEST_ARGS}}"

  backend-remove-volumes:
    desc: Remove the backend volumes
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml down -v

  backend-lint:
    desc: Run flake8 in the backend container
    dir: tdrs-backend
    cmds:
      - task: backend-up
      - docker compose -f docker-compose.yml exec -T web sh -c "flake8 . && echo 'Flake8 linter found no issues'"

  backend-test-all:
    desc: Run backend linters and tests (flake8 + pytest)
    dir: tdrs-backend
    cmds:
      - task: backend-lint
      - task: backend-pytest

  backend-pip-lock:
    desc: Lock the pip dependencies (pipenv)
    dir: tdrs-backend
    cmds:
      - task: backend-up
      - docker compose -f docker-compose.yml exec web sh -c "pipenv lock"

  psql:
    desc: Open a psql shell in the backend postgres container
    dir: tdrs-backend
    cmds:
      - task create-network || true
      - docker compose -f docker-compose.yml up -d postgres
      - sleep 5
      - docker compose -f docker-compose.yml exec postgres sh -c "psql -U tdpuser -d tdrs_test"

  clean:
    desc: Remove ALL containers, images, and volumes (DANGEROUS)
    cmds:
      - docker stop $(docker ps -aq) || true
      - docker rm $(docker ps -aq) || true
      - docker rmi $(docker images -q) || true
      - docker volume rm $(docker volume ls -q) || true

  clamav-up:
    desc: Start clamav service
    dir: tdrs-backend
    cmds:
      - docker compose -f docker-compose.yml up -d clamav-rest

  frontend-up:
    desc: Start frontend web server (nginx image)
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.yml up -d

  frontend-down:
    desc: Stop frontend web server
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.yml down

  frontend-logs:
    desc: Show and follow frontend web server logs
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.yml logs -f

  frontend-restart:
    desc: Restart frontend web server
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.yml restart

  frontend-bash:
    desc: Open a shell in the frontend container
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.yml exec tdp-frontend sh

  frontend-av:
    desc: Start frontend with optional clamav service
    cmds:
      - task: frontend-up
      - task: clamav-up

  frontend-init:
    desc: Initialize the frontend project (localdev image with node_modules)
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.local.yml up -d --build tdp-frontend
      - docker compose -f docker-compose.local.yml exec tdp-frontend sh -c "npm install"
      - docker compose -f docker-compose.local.yml down

  frontend-install:
    desc: Install frontend dependencies on host (uses local Node)
    dir: tdrs-frontend
    cmds:
      - npm install

  frontend-test:
    desc: 'Run frontend unit tests in docker (watch-less). E.g: task frontend-test JEST_ARGS="--testPathPattern=FeedbackReports"'
    dir: tdrs-frontend
    vars:
      JEST_ARGS: '{{.JEST_ARGS | default ""}}'
    cmds:
      - docker compose -f docker-compose.local.yml up -d --build tdp-frontend-test
      - docker compose -f docker-compose.local.yml exec tdp-frontend-test sh -c "npm run test -- {{.JEST_ARGS}}"

  frontend-test-cov:
    desc: 'Run frontend unit tests with coverage in docker. E.g: task frontend-test-cov JEST_ARGS="--testPathPattern=FeedbackReports"'
    dir: tdrs-frontend
    vars:
      JEST_ARGS: '{{.JEST_ARGS | default ""}}'
    cmds:
      - docker compose -f docker-compose.local.yml up -d --build tdp-frontend-test
      - docker compose -f docker-compose.local.yml exec tdp-frontend-test sh -c "npm run test:cov -- {{.JEST_ARGS}}"

  frontend-lint:
    desc: Run eslint in the frontend test container
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.local.yml up -d --build tdp-frontend-test --quiet-pull
      - docker compose -f docker-compose.local.yml exec -T tdp-frontend-test sh -c "npm run lint"

  # E2E / Cypress helpers

  e2e-env-var-setup:
    desc: Set up users and env vars for e2e test
    dir: tdrs-backend
    cmds:
      - export CYPRESS_TOKEN=local-cypress-token
      - docker-compose exec web python manage.py delete_cypress_users -usernames new-cypress@teamraft.com cypress-admin@teamraft.com
      - docker-compose exec web python manage.py loaddata cypress/users cypress/data_files cypress/regions

  frontend-e2e-local:
    desc: Run Cypress E2E tests locally (Cypress on host, app in docker)
    dir: tdrs-frontend
    cmds:
      - docker compose -f docker-compose.local.yml up -d --build tdp-frontend
      - npm run test:e2e

  k6:
    desc: Run k6 performance tests
    dir: performance-tests
    vars:
      SCRIPT: '{{.SCRIPT}}'
      CYPRESS_TOKEN: '{{.CYPRESS_TOKEN | default "local-cypress-token"}}'
      BASE_URL: '{{.BASE_URL | default "http://localhost:3000"}}'
      SCENARIO: '{{.SCENARIO}}'
    cmds:
      - k6 run -e BASE_URL={{.BASE_URL}} -e CYPRESS_TOKEN={{.CYPRESS_TOKEN}} -e SCENARIO={{.SCENARIO}} {{.SCRIPT}}

  up:
    desc: Start both frontend and backend web servers
    cmds:
      - task: backend-up
      - task: frontend-up

  down:
    desc: Stop both frontend and backend web servers
    cmds:
      - task: backend-down
      - task: frontend-down

  help:
    desc: Show this help message
    cmds:
      - task --list
