# Generated by Django 3.1.1 on 2020-10-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200822_0939"),
    ]

    operations = [
        migrations.CreateModel(
            name="TDRSAdmin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"permissions": [("tdrs_can_admin", "Can Admin Applicable STT")],},
        ),
        migrations.CreateModel(
            name="TDRSEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"permissions": [("tdrs_can_edit_data", "Can Prepare STT Data")],},
        ),
        migrations.CreateModel(
            name="TDRSRead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"permissions": [("tdrs_can_read_data", "Can Read STT Data")],},
        ),
    ]
