# Generated by Django 3.1.1 on 2020-09-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0001_initial'),
        ('users', '0002_auto_20200822_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stts.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='stt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stts.stt'),
        ),
    ]
