# Generated by Django 3.1.2 on 2020-10-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_tdrsadmin_tdrsedit_tdrsread"),
        ("users", "0003_auto_20200921_1753"),
    ]

    operations = []
