# Generated by Django 3.1.4 on 2020-12-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201117_1717'),
    ]

    operations = [
        migrations.RenameField('User', 'requested_roles', 'roles')
    ]
