# Generated by Django 3.1.4 on 2020-12-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
