# Generated by Django 3.2.1 on 2021-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_initial_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactive_account',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='inactive_account'),
        ),
    ]
