# Generated by Django 3.1.7 on 2021-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_initial_super_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_gov_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
