
# Generated by Django 3.1.4 on 2021-01-08 17:41

from django.contrib.auth.models import Group
from django.db import migrations


def change_user_groups(apps, schema_editor):
    Group.objects.filter(name='Data Prepper').update(name='Data Analyst')



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_roles'),
    ]

    operations = [
        migrations.RunPython(change_user_groups),
    ]
