# Generated by Django 3.2.5 on 2021-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_user_deactivated'),
        ('users', '0015_replace_data_analyst_role'),
    ]

    operations = [
    ]
