# Generated by Django 3.2.5 on 2021-08-13 15:26
from django.conf import settings
from django.db import migrations


def unset_superuser_flag(apps, schema_editor):
    """Set is_superuser to False for all users except initial superuser."""
    # Exclude the initial superuser if configured, as one user will still need
    # this permission in order to assign user permissions on initial startup.
    users = apps.get_model('users', 'User').objects.exclude(
        username=settings.DJANGO_SUPERUSER_NAME
    )

    # Remove the is_superuser flag from all other users
    users.update(is_superuser=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20210720_1535'),
    ]

    operations = [
        migrations.RunPython(
            unset_superuser_flag,
            # We don't have a clean way to roll this back so do nothing.
            reverse_code=migrations.RunPython.noop
        )
    ]
