# Generated by Django 3.2.5 on 2021-08-16 14:10

from django.db import migrations
from django.db.models import Q

from tdpservice.users.permissions import get_permissions_for_model


def set_ofa_admin_permissions(apps, schema_editor):
    ofa_admin = apps.get_model('auth', 'Group').objects.get(name='OFA Admin')

    view_perms_query = Q(name__contains='view')
    delete_perms_query = Q(name__contains='delete')

    # For the User model OFA Admin will have all permissions *except* delete
    user_permissions = get_permissions_for_model('users', 'user').exclude(
        delete_perms_query
    )

    # The rest of the permissions are view only
    region_permissions = get_permissions_for_model('stts', 'region').filter(
        view_perms_query
    )
    stt_permissions = get_permissions_for_model('stts', 'stt').filter(
        view_perms_query
    )
    # TODO: Update this when 755 merges
    datafile_permissions = get_permissions_for_model('reports', 'reportfile')\
        .filter(view_perms_query)

    # Clear existing permissions that may be set so we can ensure pristine state
    ofa_admin.permissions.clear()

    # Assign correct permissions
    ofa_admin.permissions.add(user_permissions)
    ofa_admin.permissions.add(region_permissions)
    ofa_admin.permissions.add(stt_permissions)
    ofa_admin.permissions.add(datafile_permissions)


def unset_ofa_admin_permissions(apps, schema_editor):
    ofa_admin = apps.get_model('auth', 'Group').objects.get(name='OFA Admin')
    ofa_admin.permissions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_unset_superuser_flag'),
    ]

    operations = [
        migrations.RunPython(
            set_ofa_admin_permissions,
            reverse_code=unset_ofa_admin_permissions
        )
    ]
