# Generated by Django 3.2.5 on 2021-08-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20210720_1535'),
        ('users', '0017_add_system_admin'),
    ]

    operations = [
    ]
