# Generated by Django 3.2.5 on 2021-08-16 14:10
from django.db import migrations

from tdpservice.users.permissions import (
    get_permission_ids_for_model,
    add_permissions_q,
    view_permissions_q
)


def set_data_analyst_permissions(apps, schema_editor):
    """Set relevant Group Permissions for Data Analyst group."""
    data_analyst = (
        apps.get_model('auth', 'Group').objects.get(name='Data Analyst')
    )

    datafile_permissions = get_permission_ids_for_model(
        'data_files',
        'datafile',
        filters=[add_permissions_q, view_permissions_q]
    )

    # Clear existing permissions that may be set so we can ensure pristine state
    data_analyst.permissions.clear()

    # Assign correct permissions
    data_analyst.permissions.add(*datafile_permissions)


def unset_data_analyst_permissions(apps, schema_editor):
    """Remove all Group Permissions added to OFA Admin."""
    data_analyst = (
        apps.get_model('auth', 'Group').objects.get(name='Data Analyst')
    )
    data_analyst.permissions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('users', '0018_ofa_admin_permissions'),
    ]

    operations = [
        migrations.RunPython(
            set_data_analyst_permissions,
            reverse_code=unset_data_analyst_permissions
        )
    ]
