# Generated by Django 3.2.5 on 2021-08-16 14:10
from django.db import migrations

from tdpservice.users.permissions import delete_permissions_q


def set_ofa_system_admin_permissions(apps, schema_editor):
    """Set relevant Group Permissions for OFA System Admin group."""
    ofa_system_admin, _ = (
        # TODO: Merge this with the migration generated for:
        # https://github.com/raft-tech/TANF-app/pull/1228
        apps.get_model('auth', 'Group')
            .objects
            .get_or_create(name='OFA System Admin')
    )

    # OFA System Admin has all permissions except delete to all models
    system_admin_permissions = (
        apps.get_model('auth', 'Permission')
            .objects
            .exclude(delete_permissions_q)
            .values_list('id', flat=True)
    )

    # Clear existing permissions that may be set so we can ensure pristine state
    ofa_system_admin.permissions.clear()

    # Assign correct permissions
    ofa_system_admin.permissions.add(*system_admin_permissions)


def unset_ofa_system_admin_permissions(apps, schema_editor):
    """Remove all Group Permissions added to OFA System Admin."""
    ofa_system_admin = (
        apps.get_model('auth', 'Group')
            .objects
            .get(name='OFA System Admin')
    )
    ofa_system_admin.permissions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('users', '0019_data_analyst_permissions'),
    ]

    operations = [
        migrations.RunPython(
            set_ofa_system_admin_permissions,
            reverse_code=unset_ofa_system_admin_permissions
        )
    ]
