# Generated by Django 3.2.5 on 2021-09-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_dev_group'),
        ('users', '0022_add_regional_staff_group'),
    ]

    operations = [
    ]
