# Generated by Django 3.2.5 on 2021-09-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_add_clam_av_file_scan_perms'),
        ('users', '0024_add_regional_staff_group'),
    ]

    operations = [
    ]
