# Generated by Django 3.2.5 on 2021-10-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_owasp_zap_scan_perms'),
        ('users', '0025_merge_20210928_0028'),
    ]

    operations = [
    ]
