# Generated by Django 3.2.5 on 2021-11-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_merge_20211018_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hhs_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
