# Generated by Django 3.2.10 on 2022-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_hhs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_request',
            field=models.BooleanField(default=False),
        ),
    ]
