# Generated by Django 3.2.10 on 2022-01-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0029_remove_add_user_permission_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'stts'), ('model', 'stt')), models.Q(('app_label', 'app'), ('model', 'region')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
