# Generated by Django 3.2.11 on 2022-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_ocio_permissions_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hhs_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
