# Generated by Django 3.2.11 on 2022-01-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0033_auto_20220125_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'stts'), ('model', 'stt')), models.Q(('app_label', 'stt'), ('model', 'region')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
