# Generated by Django 3.2.13 on 2022-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_user_hhs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_approval_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Access request', 'Access Request'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Deactivated', 'Deactivated')], default='Initial', help_text='Designates whether this user account is active and approved to access TDP. Users in an approved state are allowed access.', max_length=40),
        ),
    ]
