# Generated by Django 3.2.15 on 2023-03-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0010_alter_stt_stt_code'),
        ('users', '0035_auto_20220818_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stts.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='stt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stts.stt'),
        ),
    ]
