# Generated by Django 3.2.15 on 2023-08-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_access_requested_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk']},
        ),
    ]
