# Generated by Django 3.2.5 on 2021-08-16 14:10
from django.contrib.auth.models import Group
from django.db import migrations

from tdpservice.users.permissions import (
    get_permission_ids_for_model,
    view_permissions_q
)


def add_digit_team_group(apps, schema_editor):
    groups = [
        Group(name="DIGIT Team"),
    ]
    Group.objects.bulk_create(groups)


def remove_digit_team_group(apps, schema_editor):
    Group.objects.filter(name__in={"DIGIT Team"}).delete()


def set_digit_team_permissions(apps, schema_editor):
    """Set relevant Group Permissions for DIGIT Team group."""
    digit = (
        apps.get_model('auth', 'Group').objects.get(name='DIGIT Team')
    )

    datafile_permissions = get_permission_ids_for_model(
        'data_files',
        'datafile',
        filters=[view_permissions_q]
    )

    datafile_summary_permissions = get_permission_ids_for_model(
        'parsers',
        'datafilesummary',
        filters=[view_permissions_q]
    )

    parser_error_permissions = get_permission_ids_for_model(
        'parsers',
        'parsererror',
        filters=[view_permissions_q]
    )

    # Clear existing permissions that may be set so we can ensure pristine state
    digit.permissions.clear()

    # Assign model permissions
    digit.permissions.add(*datafile_permissions, *datafile_summary_permissions, *parser_error_permissions)

    model_sub_names = ["tanf_t", "tribal_tanf_t", "ssp_m"]
    models = [name + str(i) for name in model_sub_names for i in range(1, 8)]
    for model_name in models:
        model_permissions = get_permission_ids_for_model(
            'search_indexes',
            model_name,
            filters=[view_permissions_q]
        )
        digit.permissions.add(*model_permissions)


def unset_digit_team_permissions(apps, schema_editor):
    """Remove all Group Permissions added to DIGIT Team."""
    digit = (
        apps.get_model('auth', 'Group').objects.get(name='DIGIT Team')
    )
    digit.permissions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('users', '0039_alter_user_options'),
    ]

    operations = [
        migrations.RunPython(add_digit_team_group, remove_digit_team_group),
        migrations.RunPython(
            set_digit_team_permissions,
            reverse_code=unset_digit_team_permissions
        )
    ]
