# Generated by Django 3.2.15 on 2025-01-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_users_digit_group_add_datafile_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags for this user. This is a JSON field that can be used to store key-value pairs. E.g: {"fra_access": true}'),
        ),
    ]
