# Generated by Django 3.2.15 on 2025-01-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0010_alter_stt_stt_code'),
        ('users', '0042_auto_20250122_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Regions this user is associated with.', null=True, related_name='regions', through='users.RegionMeta', to='stts.Region'),
        ),
    ]
