# Generated by Django 3.2.5 on 2021-08-16 14:10
from django.contrib.auth.models import Group
from django.db import migrations

from tdpservice.users.permissions import (
    get_permission_ids_for_model,
    add_permissions_q,
    view_permissions_q
)


def set_ofa_regional_staff_permissions(apps, schema_editor):
    """Set relevant Group Permissions for OFA Regional Staff group."""
    regional_staff = (
        apps.get_model('auth', 'Group').objects.get(name='OFA Regional Staff')
    )

    datafile_permissions = get_permission_ids_for_model(
        'data_files',
        'datafile',
        filters=[add_permissions_q, view_permissions_q]
    )

    # Clear existing permissions that may be set so we can ensure pristine state
    regional_staff.permissions.clear()

    # Assign model permissions
    regional_staff.permissions.add(*datafile_permissions)


def unset_ofa_regional_staff_permissions(apps, schema_editor):
    """Remove all Group Permissions added to OFA Regional Staff."""
    regional_staff = (
        apps.get_model('auth', 'Group').objects.get(name='OFA Regional Staff')
    )
    regional_staff.permissions.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__latest__'),
        ('users', '0043_create_regions_m2m_del_region'),
    ]

    operations = [
        migrations.RunPython(
            set_ofa_regional_staff_permissions,
            reverse_code=unset_ofa_regional_staff_permissions
        )
    ]
