# Generated by Django 3.2.15 on 2025-05-09 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_regional_staff_permissions_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='The name of the field being changed', max_length=100)),
                ('current_value', models.TextField(blank=True, help_text='The current value of the field')),
                ('requested_value', models.TextField(blank=True, help_text='The requested new value for the field')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The current status of this change request', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When this change was requested')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this change request was reviewed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes on approval/rejection')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The admin who reviewed this change request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Change Request',
                'verbose_name_plural': 'User Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='The action performed (created, approved, rejected)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action was performed')),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.userchangerequest')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_request_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Request Audit Log',
                'verbose_name_plural': 'Change Request Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
