# Generated by Django 3.2.15 on 2025-06-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_regional_staff_permissions_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this feedback was reviewed', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('acked', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The admin who reviewed this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
