# Generated by Django 3.2.15 on 2025-06-23 18:29

from django.db import migrations, models

def migrate_fra_reports_flag(apps, schema_editor):
    User = apps.get_model('users', 'User')

    for user in User.objects.all():
        if isinstance(user.feature_flags, dict):
            has_access = user.feature_flags.get('fra_reports')
            if isinstance(has_access, bool):
                user.has_fra_access = has_access
                user.save(update_fields=['has_fra_access'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_regional_staff_permissions_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_fra_access',
            field=models.BooleanField(blank=True, help_text='Does this user submit FRA data? (null for not answered)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags for this user. This is a JSON field that can be used to store key-value pairs. E.g: {"some_feature": true}'),
        ),
        migrations.RunPython(migrate_fra_reports_flag),
    ]
