# Generated by Django 3.2.15 on 2025-06-23 18:29

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_add_fra_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags for this user. This is a JSON field that can be used to store key-value pairs. E.g: {"some_feature": true}'),
        ),
    ]
