# Generated by Django 3.2.15 on 2025-06-23 18:29

from django.db import migrations, models

def grant_fra_access_permission(apps, _):
    User = apps.get_model('users', 'User')
    Permission = apps.get_model('auth', 'Permission')

    # Get the correct permission object
    try:
        fra_permission = Permission.objects.get(codename='has_fra_access')

        # Filter users who currently have the feature flag
        users_with_flag = User.objects.filter(feature_flags__contains={'fra_reports': True})

        for user in users_with_flag:
            user.user_permissions.add(fra_permission)
            user.feature_flags.pop('fra_reports', None)
            user.save()

    except Permission.DoesNotExist:
        print("FRA permission 'has_fra_access' does not exist. Skipping migration.")
        return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_add_fra_access_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags for this user. This is a JSON field that can be used to store key-value pairs. E.g: {"some_feature": true}'),
        ),
        migrations.RunPython(grant_fra_access_permission)
    ]
