# Generated by Django 3.2.15 on 2025-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_grant_fra_access_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='component',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='data_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='program_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='widget_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
