# Generated by Django 3.2.15 on 2025-09-15 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0048_grant_fra_access_to_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="component",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="page_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="widget_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="FeedbackAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.IntegerField()),
                ("attached_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="users.feedback",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id", "feedback")},
            },
        ),
    ]
