# Generated by Django 3.2.15 on 2025-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20250821_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackattachment',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
