# Generated by Django 3.2.15 on 2025-08-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_feedbackattachment_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackattachment',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_attachments', to='users.feedback'),
        ),
    ]
