# Generated by Django 3.2.15 on 2025-11-07 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0050_feedback_addmetafields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="acked",
            new_name="read",
        ),
    ]
