# Generated by Django 3.2.15 on 2025-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0050_feedback_addmetafields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="acked",
            field=models.BooleanField(default=False, verbose_name="Marked as read"),
        ),
    ]
