# Generated by Django 3.2.15 on 2025-11-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_add_report_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deactivated',
        ),
    ]
