# Generated by Django 5.2.10 on 2026-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_historicaluser_historicalregionmeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='The current status of this change request', max_length=20),
        ),
    ]
