# Generated by Django 5.2.10 on 2026-03-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_add_regional_staff_report_permissions'),
        ('users', '0056_historicaluser_historicalregionmeta_and_more'),
    ]

    operations = [
    ]
