# Generated by Django 5.2.10 on 2026-03-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_userchangerequest_status'),
        ('users', '0057_merge_20260318_1613'),
    ]

    operations = [
    ]
