# Generated by Django 3.1.1 on 2020-09-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="STT",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("state", "State"),
                            ("territory", "Territory"),
                            ("tribe", "Tribe"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=2, null=True)),
                ("name", models.CharField(max_length=1000)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stts",
                        to="stts.region",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stts.stt",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="stt",
            constraint=models.UniqueConstraint(fields=("name",), name="stt_uniq_name"),
        ),
    ]
