# Generated by Django 3.1.1 on 2020-09-23 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stt",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stts",
                to="stts.region",
            ),
        ),
    ]
