# Generated by Django 3.2.13 on 2022-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0002_auto_20200923_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='stt',
            name='code_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
