# Generated by Django 3.2.13 on 2022-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0004_stt_filenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='stt',
            name='stt_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
