# Generated by Django 3.2.13 on 2022-06-08 14:43

import csv
import json
from pathlib import Path

from django.core.management import call_command
from django.db import migrations, models


def add_filenames(apps, schema_editor):
    call_command("populate_stts")
    data_dir = Path(__file__).resolve().parent.parent  /"management" / "commands" / "data"
    STT = apps.get_model('stts','STT')

    fieldnames = ["Code", "Name", "Region", "STT_CODE", "Sample", "SSP", "SSN_Encrypted", "filenames"]
    with open(data_dir / "states.csv", "r") as csvfile:
        reader = csv.DictReader(csvfile)
        rows=[]
        for row in reader:
            filenames = row["filenames"] = row["filenames"].replace('\'', '"')
            rows.append(row)
            state = STT.objects.get(name=row["Name"])
            state.filenames = json.loads(filenames)
            state.save()

    with open(data_dir / "tribes.csv", "r") as csvfile:
        reader = csv.DictReader(csvfile)
        rows=[]
        for row in reader:
            filenames = row["filenames"] = row["filenames"].replace('\'', '"')
            rows.append(row)
            tribe = STT.objects.get(name=row["Name"])
            tribe.filenames = json.loads(filenames)
            tribe.save()

    with open(data_dir / "territories.csv", "r") as csvfile:
        reader = csv.DictReader(csvfile)
        rows=[]
        for row in reader:
            filenames = row["filenames"] = row["filenames"].replace('\'', '"')
            rows.append(row)
            territory = STT.objects.get(name=row["Name"])
            territory.filenames = json.loads(filenames)
            territory.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0005_stt_stt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stt',
            name='filenames',
            field=models.JSONField(blank=True, max_length=512, null=True),
        ),
        migrations.RunPython(add_filenames)
    ]

