# Generated by Django 3.2.15 on 2023-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0009_stt_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stt',
            name='stt_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
