# Generated by Django 3.2.15 on 2025-01-30 22:07

from django.db import migrations, models
import csv
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / 'management/commands/data'
def populate_regions(apps, schema_editor):
    Region = apps.get_model('stts', 'Region')
    with open(DATA_DIR / "regions.csv") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            Region.objects.get_or_create(id=row["Id"], name=row["name"])
        Region.objects.get_or_create(id=1000, name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('stts', '0010_alter_stt_stt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.RunPython(populate_regions)
    ]
