"""Test appropriate permissions are assigned to each Group."""

import pytest


@pytest.mark.django_db
def test_ofa_admin_permissions(ofa_admin):
    """Test that an OFA Admin user inherits the correct permissions."""
    expected_permissions = {
        "admin.view_logentry",
        "auth.view_group",
        "data_files.add_datafile",
        "data_files.view_datafile",
        "security.view_clamavfilescan",
        "security.view_owaspzapscan",
        "stts.view_region",
        "stts.view_stt",
        "users.add_user",
        "users.change_user",
        "users.view_user",
        "users.has_fra_access",
        # Note: OFA Admin does NOT have reports permissions (removed in migration 0054)
    }
    group_permissions = ofa_admin.get_group_permissions()
    assert group_permissions == expected_permissions


@pytest.mark.django_db
def test_ofa_system_admin_permissions(ofa_system_admin):
    """Test that an OFA System Admin user inherits the correct permissions."""
    expected_permissions = {
        "auth.view_permission",
        "search_indexes.view_tribal_tanf_t2",
        "django_celery_beat.change_periodictasks",
        "django_celery_beat.change_solarschedule",
        "admin_interface.view_theme",
        "data_files.change_reparsefilemeta",
        "django_celery_beat.add_clockedschedule",
        "core.view_historicalfeatureflag",
        "auth.change_group",
        "core.change_historicalgroup",
        "search_indexes.change_tanf_t5",
        "admin.view_logentry",
        "data_files.change_legacyfiletransfer",
        "django_celery_beat.change_periodictask",
        "search_indexes.view_tribal_tanf_t4",
        "search_indexes.add_ssp_m5",
        "search_indexes.change_tanf_exiter1",
        "search_indexes.change_programaudit_t3",
        "stts.change_stt",
        "search_indexes.view_tanf_t6",
        "search_indexes.add_tribal_tanf_t5",
        "stts.change_region",
        "admin_interface.change_theme",
        "authtoken.view_tokenproxy",
        "core.view_historicalgroup_permissions",
        "django_celery_beat.change_intervalschedule",
        "django_celery_beat.view_periodictasks",
        "search_indexes.change_tribal_tanf_t5",
        "search_indexes.change_tanf_t6",
        "search_indexes.add_programaudit_t3",
        "search_indexes.add_tribal_tanf_t1",
        "parsers.change_parsererror",
        "core.add_historicalgroup",
        "search_indexes.change_ssp_m7",
        "sessions.change_session",
        "search_indexes.view_ssp_m5",
        "authtoken.add_token",
        "search_indexes.change_ssp_m6",
        "search_indexes.view_tanf_exiter1",
        "search_indexes.change_programaudit_t2",
        "search_indexes.add_tanf_t6",
        "search_indexes.change_tribal_tanf_t3",
        "core.view_featureflag",
        "search_indexes.add_ssp_m4",
        "search_indexes.view_programaudit_t3",
        "core.change_historicalfeatureflag",
        "core.add_featureflag",
        "search_indexes.add_tanf_t5",
        "security.view_owaspzapscan",
        "users.view_user",
        "search_indexes.add_ssp_m2",
        "search_indexes.add_tanf_t4",
        "users.has_fra_access",
        "parsers.add_datafilesummary",
        "search_indexes.view_tanf_t2",
        "search_indexes.change_programaudit_t1",
        "auth.add_permission",
        "reports.add_reportsource",
        "data_files.change_datafile",
        "search_indexes.view_tanf_t4",
        "search_indexes.change_tanf_t1",
        "search_indexes.view_tribal_tanf_t3",
        "search_indexes.change_tanf_t7",
        "django_celery_beat.view_clockedschedule",
        "search_indexes.add_tribal_tanf_t7",
        "sessions.add_session",
        "search_indexes.view_ssp_m3",
        "stts.view_region",
        "search_indexes.view_tanf_t1",
        "security.view_securityeventtoken",
        "search_indexes.change_ssp_m1",
        "core.view_historicalgroup",
        "search_indexes.add_tanf_t1",
        "authtoken.add_tokenproxy",
        "search_indexes.view_ssp_m6",
        "reports.view_reportfile",
        "django_celery_beat.add_crontabschedule",
        "search_indexes.change_tribal_tanf_t4",
        "search_indexes.change_ssp_m2",
        "search_indexes.view_reparsemeta",
        "reports.change_reportfile",
        "parsers.change_datafilesummary",
        "search_indexes.change_tribal_tanf_t7",
        "search_indexes.add_tribal_tanf_t4",
        "search_indexes.add_ssp_m3",
        "data_files.view_legacyfiletransfer",
        "core.change_globalpermission",
        "search_indexes.add_ssp_m7",
        "search_indexes.change_tanf_t2",
        "search_indexes.add_tanf_t2",
        "search_indexes.change_tanf_t4",
        "admin_interface.add_theme",
        "stts.view_stt",
        "parsers.view_parsererror",
        "search_indexes.change_tribal_tanf_t1",
        "django_celery_beat.change_clockedschedule",
        "sessions.view_session",
        "core.change_featureflag",
        "search_indexes.view_ssp_m1",
        "search_indexes.change_reparsemeta",
        "core.add_globalpermission",
        "search_indexes.view_tanf_t7",
        "django_celery_beat.change_crontabschedule",
        "django_celery_beat.view_periodictask",
        "search_indexes.view_tanf_t5",
        "search_indexes.view_ssp_m7",
        "search_indexes.change_ssp_m4",
        "search_indexes.add_tribal_tanf_t6",
        "search_indexes.change_ssp_m3",
        "search_indexes.add_ssp_m6",
        "search_indexes.add_tribal_tanf_t2",
        "search_indexes.view_ssp_m4",
        "django_celery_beat.add_intervalschedule",
        "search_indexes.add_tanf_exiter1",
        "data_files.add_reparsefilemeta",
        "core.view_globalpermission",
        "django_celery_beat.add_periodictasks",
        "search_indexes.add_programaudit_t2",
        "contenttypes.change_contenttype",
        "search_indexes.view_tribal_tanf_t5",
        "stts.add_stt",
        "search_indexes.view_tanf_t3",
        "admin.add_logentry",
        "search_indexes.view_ssp_m2",
        "stts.add_region",
        "search_indexes.view_programaudit_t1",
        "admin.change_logentry",
        "search_indexes.view_tribal_tanf_t7",
        "reports.add_reportfile",
        "data_files.add_datafile",
        "search_indexes.add_tanf_t7",
        "search_indexes.add_programaudit_t1",
        "core.change_historicalgroup_permissions",
        "auth.view_group",
        "django_celery_beat.add_periodictask",
        "django_celery_beat.view_intervalschedule",
        "search_indexes.add_ssp_m1",
        "search_indexes.view_tribal_tanf_t6",
        "users.change_user",
        "search_indexes.add_tribal_tanf_t3",
        "reports.change_reportsource",
        "reports.view_reportsource",
        "search_indexes.view_programaudit_t2",
        "search_indexes.add_reparsemeta",
        "security.change_securityeventtoken",
        "search_indexes.change_tribal_tanf_t6",
        "data_files.add_legacyfiletransfer",
        "django_celery_beat.add_solarschedule",
        "search_indexes.change_tanf_t3",
        "authtoken.view_token",
        "core.add_historicalgroup_permissions",
        "search_indexes.view_tribal_tanf_t1",
        "security.view_clamavfilescan",
        "django_celery_beat.view_solarschedule",
        "auth.change_permission",
        "core.add_historicalfeatureflag",
        "auth.add_group",
        "data_files.view_datafile",
        "search_indexes.add_tanf_t3",
        "django_celery_beat.view_crontabschedule",
        "contenttypes.view_contenttype",
        "parsers.view_datafilesummary",
        "search_indexes.change_ssp_m5",
        "data_files.view_reparsefilemeta",
        "search_indexes.change_tribal_tanf_t2",
        "parsers.add_parsererror",
        "security.add_securityeventtoken",
        "contenttypes.add_contenttype",
        "authtoken.change_tokenproxy",
        "authtoken.change_token",
    }
    group_permissions = ofa_system_admin.get_group_permissions()
    print(group_permissions)
    assert group_permissions == expected_permissions


@pytest.mark.django_db
def test_data_analyst_permissions(data_analyst):
    """Test that a Data Analyst user inherits the correct permissions."""
    expected_permissions = {
        "data_files.add_datafile",
        "data_files.view_datafile",
        "reports.view_reportfile",
    }
    group_permissions = data_analyst.get_group_permissions()
    assert group_permissions == expected_permissions


@pytest.mark.django_db
def test_digit_team_permissions(digit_team):
    """Test that a DIGIT Team user inherits the correct permissions."""
    expected_permissions = {
        "parsers.view_parsererror",
        "parsers.view_datafilesummary",
        "data_files.view_datafile",
        "data_files.add_datafile",
        "stts.view_stt",
        "search_indexes.view_ssp_m3",
        "search_indexes.view_tribal_tanf_t5",
        "search_indexes.view_tribal_tanf_t3",
        "search_indexes.view_ssp_m4",
        "search_indexes.view_tanf_t5",
        "search_indexes.view_tanf_t3",
        "search_indexes.view_tanf_t1",
        "search_indexes.view_tribal_tanf_t7",
        "search_indexes.view_tribal_tanf_t6",
        "search_indexes.view_ssp_m7",
        "search_indexes.view_tanf_t7",
        "search_indexes.view_ssp_m2",
        "search_indexes.view_tribal_tanf_t1",
        "search_indexes.view_tribal_tanf_t4",
        "search_indexes.view_ssp_m1",
        "search_indexes.view_ssp_m5",
        "search_indexes.view_tanf_t2",
        "search_indexes.view_tanf_t4",
        "search_indexes.view_ssp_m6",
        "search_indexes.view_tribal_tanf_t2",
        "search_indexes.view_tanf_t6",
        # Reports permissions added in migration 0054
        "reports.add_reportfile",
        "reports.add_reportsource",
        "reports.view_reportfile",
        "reports.view_reportsource",
    }
    group_permissions = digit_team.get_group_permissions()
    assert group_permissions == expected_permissions
