package metrics

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"math"
	"net"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"go-parser/internal/logging"
)

const (
	filesProcessedTotal       = "go_parser_files_processed_total"
	fileDuration              = "go_parser_file_duration_seconds"
	recordsParsedTotal        = "go_parser_records_parsed_total"
	errorsGeneratedTotal      = "go_parser_errors_generated_total"
	pipelineStageDuration     = "go_parser_pipeline_stage_duration_seconds"
	workerPoolConfigured      = "go_parser_worker_pool_configured_workers"
	workerPoolActiveDuration  = "go_parser_worker_pool_active_duration_seconds_total"
	workerPoolCapacitySeconds = "go_parser_worker_pool_capacity_seconds_total"
	flushesTotal              = "go_parser_flushes_total"
	flushDuration             = "go_parser_flush_duration_seconds"
	defaultListenAddress      = ":9809"
	defaultPath               = "/metrics"
	defaultServerMode         = "unknown"
	contentTypePrometheusText = "text/plain; version=0.0.4; charset=utf-8"
)

var durationBuckets = []float64{
	0.001, 0.005, 0.01, 0.025, 0.05,
	0.1, 0.25, 0.5, 1, 2.5,
	5, 10, 30, 60, 120, 300,
}

const (
	metricCounter   string = "counter"
	metricGauge     string = "gauge"
	metricHistogram string = "histogram"
)

type metricDef struct {
	kind string
	help string
}

var metricDefs = map[string]metricDef{
	filesProcessedTotal: {
		kind: metricCounter,
		help: "Total files processed by the Go parser.",
	},
	fileDuration: {
		kind: metricHistogram,
		help: "Go parser end-to-end file processing duration in seconds.",
	},
	recordsParsedTotal: {
		kind: metricCounter,
		help: "Total detail records parsed by the Go parser.",
	},
	errorsGeneratedTotal: {
		kind: metricCounter,
		help: "Total parser errors generated by validation category.",
	},
	pipelineStageDuration: {
		kind: metricHistogram,
		help: "Go parser pipeline stage durations in seconds.",
	},
	workerPoolConfigured: {
		kind: metricGauge,
		help: "Configured Go parser pipeline worker count.",
	},
	workerPoolActiveDuration: {
		kind: metricCounter,
		help: "Cumulative seconds that Go parser workers spent processing batches.",
	},
	workerPoolCapacitySeconds: {
		kind: metricCounter,
		help: "Cumulative worker-seconds available while Go parser worker pools were running.",
	},
	flushesTotal: {
		kind: metricCounter,
		help: "Total Go parser writer flush attempts.",
	},
	flushDuration: {
		kind: metricHistogram,
		help: "Go parser writer flush durations in seconds.",
	},
}

// Labels is a set of Prometheus label names and values.
type Labels map[string]string

// Recorder is the metrics sink used by parser packages.
type Recorder interface {
	IncCounter(name string, labels Labels, value float64)
	SetGauge(name string, labels Labels, value float64)
	ObserveHistogram(name string, labels Labels, value float64)
}

type metricInitializer interface {
	InitCounter(name string, labels Labels)
	InitHistogram(name string, labels Labels)
}

type noopRecorder struct{}

func (noopRecorder) IncCounter(string, Labels, float64)       {}
func (noopRecorder) SetGauge(string, Labels, float64)         {}
func (noopRecorder) ObserveHistogram(string, Labels, float64) {}

var (
	defaultMu       sync.RWMutex
	defaultRecorder Recorder = noopRecorder{}
)

var (
	fileStatuses    = []string{"success", "failed"}
	errorCategories = []string{
		"record_pre_check",
		"field_value",
		"value_consistency",
		"case_consistency",
	}
	pipelineStages = []string{
		"setup",
		"parse_validate",
		"flush",
		"worker_parsing",
		"worker_group_validation",
		"worker_record_validation",
		"worker_field_validation",
		"worker_routing",
	}
	flushStatuses = []string{"success", "failed"}
)

// UseDefault installs the process-wide recorder used by package-level helpers.
func UseDefault(recorder Recorder) {
	if recorder == nil {
		recorder = noopRecorder{}
	}
	defaultMu.Lock()
	defaultRecorder = recorder
	defaultMu.Unlock()
}

// ResetDefault disables process-wide metrics recording.
func ResetDefault() {
	UseDefault(noopRecorder{})
}

func recorder() Recorder {
	defaultMu.RLock()
	defer defaultMu.RUnlock()
	return defaultRecorder
}

type numberSample struct {
	labels Labels
	value  float64
}

type histogramSample struct {
	labels  Labels
	buckets []uint64
	count   uint64
	sum     float64
}

// Registry stores metrics and exposes them in Prometheus text format.
type Registry struct {
	mu         sync.RWMutex
	serverMode string
	counters   map[string]map[string]*numberSample
	gauges     map[string]map[string]*numberSample
	histograms map[string]map[string]*histogramSample
}

// NewRegistry creates a Prometheus text-format registry for one parser process.
func NewRegistry(serverMode string) *Registry {
	serverMode = strings.TrimSpace(serverMode)
	if serverMode == "" {
		serverMode = defaultServerMode
	}
	return &Registry{
		serverMode: serverMode,
		counters:   make(map[string]map[string]*numberSample),
		gauges:     make(map[string]map[string]*numberSample),
		histograms: make(map[string]map[string]*histogramSample),
	}
}

func (r *Registry) IncCounter(name string, labels Labels, value float64) {
	if r == nil || value <= 0 || !isCounter(name) {
		return
	}
	labels = r.withServerMode(labels)
	key := labelKey(labels)

	r.mu.Lock()
	defer r.mu.Unlock()
	sample := r.counterSampleLocked(name, key, labels)
	sample.value += value
}

// InitCounter creates a zero-valued counter series for the given label set.
// Prometheus can only calculate increase() from samples it has observed, so
// known parser counters are initialized before the first parse creates a large
// first increment.
func (r *Registry) InitCounter(name string, labels Labels) {
	if r == nil || !isCounter(name) {
		return
	}
	labels = r.withServerMode(labels)
	key := labelKey(labels)

	r.mu.Lock()
	defer r.mu.Unlock()
	r.counterSampleLocked(name, key, labels)
}

func (r *Registry) counterSampleLocked(name string, key string, labels Labels) *numberSample {
	samples := r.counters[name]
	if samples == nil {
		samples = make(map[string]*numberSample)
		r.counters[name] = samples
	}
	sample := samples[key]
	if sample == nil {
		sample = &numberSample{labels: labels}
		samples[key] = sample
	}
	return sample
}

func (r *Registry) SetGauge(name string, labels Labels, value float64) {
	if r == nil || !isGauge(name) || math.IsNaN(value) || math.IsInf(value, 0) {
		return
	}
	labels = r.withServerMode(labels)
	key := labelKey(labels)

	r.mu.Lock()
	defer r.mu.Unlock()
	samples := r.gauges[name]
	if samples == nil {
		samples = make(map[string]*numberSample)
		r.gauges[name] = samples
	}
	samples[key] = &numberSample{labels: labels, value: value}
}

func (r *Registry) ObserveHistogram(name string, labels Labels, value float64) {
	if r == nil || value < 0 || !isHistogram(name) || math.IsNaN(value) || math.IsInf(value, 0) {
		return
	}
	labels = r.withServerMode(labels)
	key := labelKey(labels)

	r.mu.Lock()
	defer r.mu.Unlock()
	sample := r.histogramSampleLocked(name, key, labels)
	for i, bucket := range durationBuckets {
		if value <= bucket {
			sample.buckets[i]++
		}
	}
	sample.count++
	sample.sum += value
}

// InitHistogram creates zero-valued bucket, count, and sum series for the
// given histogram label set.
func (r *Registry) InitHistogram(name string, labels Labels) {
	if r == nil || !isHistogram(name) {
		return
	}
	labels = r.withServerMode(labels)
	key := labelKey(labels)

	r.mu.Lock()
	defer r.mu.Unlock()
	r.histogramSampleLocked(name, key, labels)
}

func (r *Registry) histogramSampleLocked(name string, key string, labels Labels) *histogramSample {
	samples := r.histograms[name]
	if samples == nil {
		samples = make(map[string]*histogramSample)
		r.histograms[name] = samples
	}
	sample := samples[key]
	if sample == nil {
		sample = &histogramSample{
			labels:  labels,
			buckets: make([]uint64, len(durationBuckets)),
		}
		samples[key] = sample
	}
	return sample
}

func (r *Registry) ServeHTTP(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", contentTypePrometheusText)

	r.mu.RLock()
	defer r.mu.RUnlock()

	names := sortedMetricNames()
	for _, name := range names {
		def := metricDefs[name]
		fmt.Fprintf(w, "# HELP %s %s\n", name, def.help)
		fmt.Fprintf(w, "# TYPE %s %s\n", name, def.kind)

		switch def.kind {
		case metricCounter:
			writeNumberSamples(w, name, r.counters[name])
		case metricGauge:
			writeNumberSamples(w, name, r.gauges[name])
		case metricHistogram:
			writeHistogramSamples(w, name, r.histograms[name])
		}
	}
}

func (r *Registry) withServerMode(labels Labels) Labels {
	result := make(Labels, len(labels)+1)
	for key, value := range labels {
		result[key] = value
	}
	result["server_mode"] = r.serverMode
	return result
}

// MetricServerConfig controls the metrics HTTP endpoint.
type MetricServerConfig struct {
	ServerMode    string
	ListenAddress string
	Path          string
}

// MetricServer owns the metrics HTTP server lifecycle.
type MetricServer struct {
	httpServer *http.Server
	listener   net.Listener
	registry   *Registry
	once       sync.Once
	err        error
}

// StartMetricServer starts the metrics HTTP endpoint and installs its registry as the
// process-wide recorder.
func StartMetricServer(ctx context.Context, cfg MetricServerConfig) (*MetricServer, error) {
	listenAddress := strings.TrimSpace(cfg.ListenAddress)
	if listenAddress == "" {
		listenAddress = defaultListenAddress
	}
	path := strings.TrimSpace(cfg.Path)
	if path == "" {
		path = defaultPath
	}
	if !strings.HasPrefix(path, "/") {
		return nil, fmt.Errorf("metrics path %q must start with /", path)
	}

	listener, err := net.Listen("tcp", listenAddress)
	if err != nil {
		return nil, fmt.Errorf("listen on metrics address %s: %w", listenAddress, err)
	}

	registry := NewRegistry(cfg.ServerMode)
	UseDefault(registry)

	mux := http.NewServeMux()
	mux.Handle(path, registry)
	mux.HandleFunc("/-/healthy", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok\n"))
	})

	server := &MetricServer{
		httpServer: &http.Server{Handler: mux},
		listener:   listener,
		registry:   registry,
	}

	go func() {
		<-ctx.Done()
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := server.Shutdown(shutdownCtx); err != nil {
			logging.Error(context.Background(), "metrics server shutdown failed",
				slog.String(logging.KeyStage, "metrics"),
				slog.Any(logging.KeyError, err),
			)
		}
	}()

	go func() {
		if err := server.httpServer.Serve(listener); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logging.Error(context.Background(), "metrics server failed",
				slog.String(logging.KeyStage, "metrics"),
				slog.Any(logging.KeyError, err),
			)
		}
	}()

	return server, nil
}

// Address returns the bound metrics server address.
func (s *MetricServer) Address() string {
	if s == nil || s.listener == nil {
		return ""
	}
	return s.listener.Addr().String()
}

// Shutdown stops the metrics HTTP server and disables process-wide recording.
func (s *MetricServer) Shutdown(ctx context.Context) error {
	if s == nil || s.httpServer == nil {
		return nil
	}
	s.once.Do(func() {
		resetDefaultRegistry(s.registry)
		s.err = s.httpServer.Shutdown(ctx)
	})
	if errors.Is(s.err, http.ErrServerClosed) {
		return nil
	}
	return s.err
}

func resetDefaultRegistry(registry *Registry) {
	if registry == nil {
		return
	}
	defaultMu.Lock()
	defer defaultMu.Unlock()
	if current, ok := defaultRecorder.(*Registry); ok && current == registry {
		defaultRecorder = noopRecorder{}
	}
}

// RecordFileProcessed increments the file counter with success/failure status.
func RecordFileProcessed(program string, section int, status string) {
	recorder().IncCounter(filesProcessedTotal, parseLabels(program, section, Labels{
		"status": status,
	}), 1)
}

// ObserveFileDuration records end-to-end processing duration for one file.
func ObserveFileDuration(program string, section int, status string, duration time.Duration) {
	if duration < 0 {
		return
	}
	recorder().ObserveHistogram(fileDuration, parseLabels(program, section, Labels{
		"status": status,
	}), duration.Seconds())
}

// AddRecordsParsed increments the detail-record counter.
func AddRecordsParsed(program string, section int, count int64) {
	if count <= 0 {
		return
	}
	recorder().IncCounter(recordsParsedTotal, parseLabels(program, section, nil), float64(count))
}

// AddErrorsGenerated increments the parser error counter for one category.
func AddErrorsGenerated(program string, section int, category string, count int64) {
	if count <= 0 {
		return
	}
	recorder().IncCounter(errorsGeneratedTotal, parseLabels(program, section, Labels{
		"error_category": category,
	}), float64(count))
}

// InitializeParserMetrics exposes zero-valued parser series for a
// program/section before the first file is processed.
func InitializeParserMetrics(program string, section int) {
	initializer, ok := recorder().(metricInitializer)
	if !ok {
		return
	}

	initializer.InitCounter(recordsParsedTotal, parseLabels(program, section, nil))
	initializer.InitCounter(workerPoolActiveDuration, parseLabels(program, section, nil))
	initializer.InitCounter(workerPoolCapacitySeconds, parseLabels(program, section, nil))
	SetWorkerPoolCapacity(program, section, 0)

	for _, status := range fileStatuses {
		initializer.InitCounter(filesProcessedTotal, parseLabels(program, section, Labels{
			"status": status,
		}))
		initializer.InitHistogram(fileDuration, parseLabels(program, section, Labels{
			"status": status,
		}))
	}
	for _, category := range errorCategories {
		initializer.InitCounter(errorsGeneratedTotal, parseLabels(program, section, Labels{
			"error_category": category,
		}))
	}
	for _, stage := range pipelineStages {
		initializer.InitHistogram(pipelineStageDuration, parseLabels(program, section, Labels{
			"stage": stage,
		}))
	}
}

// InitializeWriterMetrics exposes zero-valued writer flush series for a table
// before the first flush for that table occurs.
func InitializeWriterMetrics(tableName string) {
	initializer, ok := recorder().(metricInitializer)
	if !ok {
		return
	}

	for _, status := range flushStatuses {
		labels := Labels{
			"table":  tableName,
			"status": status,
		}
		initializer.InitCounter(flushesTotal, labels)
		initializer.InitHistogram(flushDuration, labels)
	}
}

// ObservePipelineStage records a parser pipeline stage duration.
func ObservePipelineStage(program string, section int, stage string, duration time.Duration) {
	if duration < 0 {
		return
	}
	recorder().ObserveHistogram(pipelineStageDuration, parseLabels(program, section, Labels{
		"stage": stage,
	}), duration.Seconds())
}

// SetWorkerPoolCapacity records the configured worker pool size.
func SetWorkerPoolCapacity(program string, section int, workers int) {
	if workers < 0 {
		return
	}
	recorder().SetGauge(workerPoolConfigured, parseLabels(program, section, nil), float64(workers))
}

// AddWorkerPoolActiveDuration records elapsed processing time for one active worker.
func AddWorkerPoolActiveDuration(program string, section int, duration time.Duration) {
	if duration <= 0 {
		return
	}
	recorder().IncCounter(workerPoolActiveDuration, parseLabels(program, section, nil), duration.Seconds())
}

// AddWorkerPoolCapacityDuration records total available worker-seconds for a pool run.
func AddWorkerPoolCapacityDuration(program string, section int, duration time.Duration, configured int) {
	if duration <= 0 || configured <= 0 {
		return
	}
	recorder().IncCounter(workerPoolCapacitySeconds, parseLabels(program, section, nil), duration.Seconds()*float64(configured))
}

// RecordFlush records one writer flush attempt and its duration.
func RecordFlush(tableName string, status string, duration time.Duration) {
	if duration < 0 {
		return
	}
	labels := Labels{
		"table":  tableName,
		"status": status,
	}
	recorder().IncCounter(flushesTotal, labels, 1)
	recorder().ObserveHistogram(flushDuration, labels, duration.Seconds())
}

func parseLabels(program string, section int, extra Labels) Labels {
	labels := make(Labels, len(extra)+2)
	labels["program"] = program
	labels["section"] = strconv.Itoa(section)
	for key, value := range extra {
		labels[key] = value
	}
	return labels
}

func isCounter(name string) bool {
	def, ok := metricDefs[name]
	return ok && def.kind == metricCounter
}

func isGauge(name string) bool {
	def, ok := metricDefs[name]
	return ok && def.kind == metricGauge
}

func isHistogram(name string) bool {
	def, ok := metricDefs[name]
	return ok && def.kind == metricHistogram
}

func sortedMetricNames() []string {
	names := make([]string, 0, len(metricDefs))
	for name := range metricDefs {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedSampleKeys[T any](samples map[string]T) []string {
	keys := make([]string, 0, len(samples))
	for key := range samples {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func writeNumberSamples(w http.ResponseWriter, name string, samples map[string]*numberSample) {
	for _, key := range sortedSampleKeys(samples) {
		sample := samples[key]
		fmt.Fprintf(w, "%s%s %s\n", name, formatLabels(sample.labels), formatMetricValue(sample.value))
	}
}

func writeHistogramSamples(w http.ResponseWriter, name string, samples map[string]*histogramSample) {
	for _, key := range sortedSampleKeys(samples) {
		sample := samples[key]
		for i, bucket := range durationBuckets {
			labels := labelsWithExtra(sample.labels, "le", formatBucket(bucket))
			fmt.Fprintf(w, "%s_bucket%s %d\n", name, formatLabels(labels), sample.buckets[i])
		}
		labels := labelsWithExtra(sample.labels, "le", "+Inf")
		fmt.Fprintf(w, "%s_bucket%s %d\n", name, formatLabels(labels), sample.count)
		fmt.Fprintf(w, "%s_sum%s %s\n", name, formatLabels(sample.labels), formatMetricValue(sample.sum))
		fmt.Fprintf(w, "%s_count%s %d\n", name, formatLabels(sample.labels), sample.count)
	}
}

func labelsWithExtra(labels Labels, key string, value string) Labels {
	result := make(Labels, len(labels)+1)
	for labelKey, labelValue := range labels {
		result[labelKey] = labelValue
	}
	result[key] = value
	return result
}

func labelKey(labels Labels) string {
	keys := make([]string, 0, len(labels))
	for key := range labels {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		parts = append(parts, key+"="+labels[key])
	}
	return strings.Join(parts, "\xff")
}

func formatLabels(labels Labels) string {
	if len(labels) == 0 {
		return ""
	}
	keys := make([]string, 0, len(labels))
	for key := range labels {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var builder strings.Builder
	builder.WriteString("{")
	for i, key := range keys {
		if i > 0 {
			builder.WriteString(",")
		}
		builder.WriteString(key)
		builder.WriteString("=\"")
		builder.WriteString(escapeLabelValue(labels[key]))
		builder.WriteString("\"")
	}
	builder.WriteString("}")
	return builder.String()
}

func escapeLabelValue(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "\n", "\\n")
	value = strings.ReplaceAll(value, "\"", "\\\"")
	return value
}

func formatBucket(bucket float64) string {
	return strconv.FormatFloat(bucket, 'g', -1, 64)
}

func formatMetricValue(value float64) string {
	return strconv.FormatFloat(value, 'g', -1, 64)
}
