services:
  tdp-admin:
    stdin_open: true
    tty: true
    build:
      context: .
      target: runtime
    ports:
      - 3001:3000
    environment:
      - NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL:-http://localhost:8989}
      - NEXT_PUBLIC_AUTH_BROWSER_URL=${NEXT_PUBLIC_AUTH_BROWSER_URL:-http://localhost:8989}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8989/v1}
      - ADMIN_BACKEND_URL=${ADMIN_BACKEND_URL:-http://localhost:8989/admin-api/v1}
      - ADMIN_FRONTEND_ORIGIN=${ADMIN_FRONTEND_ORIGIN:-http://localhost:3001}
      - ADMIN_API_PROXY_TOKEN=${ADMIN_API_PROXY_TOKEN:-local-admin-proxy-token}
      - NEXT_PUBLIC_BACKEND_HOST=${NEXT_PUBLIC_BACKEND_HOST:-http://localhost:8989}
    networks:
      - default

networks:
  default:
    name: external-net
    external: true
