"""Define constants for the parsers module."""

TANF_ITEM_NAME = {
    "AID_AGED_BLIND": "Aid to the Aged, Blind, and Disabled",
    "AMOUNT_EARNED_INCOME": "Amount of Earned Income",
    "AMOUNT_UNEARNED_INCOME": "Amount of Unearned Income",
    "AMT_FOOD_STAMP": "Amount of Food Stamps",
    "AMT_SUB_CC": "Amount of Subsidized Child Care",
    "CC_NBR_MONTHS": "Number of Months of Subsidized Child Care",
    "CHILD_SUPPORT_AMT": "Amount of Child Support",
    "COMM_SERVICES_EA": "Community Service - excused absence",
    "COMM_SERVICES_HOL": "Community Service - holiday",
    "COMM_SERVICES_HOP": "Community Service - hours of participation",
    "COOPERATION_CHILD_SUPPORT": "Cooperation with Child Support",
    "COUNTABLE_MONTHS_STATE": "Countable Months of State Time",
    "COUNTABLE_MONTH_FED": "Countable Months of Federal Time",
    "COUNTY_FIPS_CODE": "County FIPS Code",
    "CURRENT_MONTH_STATE": "Current Month of State Time",
    "DATE_OF_BIRTH": "Date of Birth",
    "DEEMED_HOURS_FOR": "Deemed Hours for",
    "DISABLED_TITLE_XIVAPDT": "Disabled under title XIV-APDT",
    "ED_NO_HIGH": "Education - No High School Diploma",
    "FAILURE_TO_COMPLY": "Failure to Comply",
    "FAMILY_CASH_RESOURCES": "Family Cash Resources",
    "FAMILY_EXEMPT_TIME": "Family Exempt Time",
    "FAMILY_NEW_CHILD": "Family with a New Child",
    "FAMILY_SANC_ADULT": "Family Sanctioned for an Adult",
    "FED_DISABILITY_STATUS": "Federal Disability Status",
    "FED_OASDI_PROGRAM": "Federal OASDI Program",
    "JOB_SEARCH_EA": "Job Search - EA",
    "JOB_SEARCH_HOL": "Job Search - HOL",
    "JOB_SEARCH_HOP": "Job Search - HOP",
    "JOB_SKILLS_TRAINING": "Job Skills Training",
    "MONTHS_FED_TIME": "Months of Federal Time",
    "MONTHS_STATE_TIME": "Months of State Time",
    "NBR_FAMILY_MEMBERS": "Number of Family Members",
    "NEEDS_OF_PREGNANT": "",
    "NEEDS_PREGNANT_WOMAN": "Needs",
    "NON_COOPERATION_CSE": "Non-Cooperation with Child Support Enforcement",
    "NUM_ADULT_RECIPIENTS": "Number of Adult Recipients",
    "NUM_CHILD_RECIPIENTS": "Number of Child Recipients",
    "NUM_CLOSED_CASES": "Number of Closed Cases",
    "NUM_NO_PARENTS": "Number of Cases with No Parents",
    "NUM_OUTWEDLOCK_BIRTHS": "Number of Out-of-Wedlock Births",
    "OTHER_NBR_MONTHS": "Number of Months of Other Time",
    "OTHER_NON_SANCTION": "Other Non-Sanction",
    "OTHER_TOTAL_REDUCTIONS": "Other Total Reductions",
    "OTHER_UNEARNED_INCOME": "Other Unearned Income",
    "OTHER_WORK_ACTIVITIES": "Other Work Activities",
    "PARENT_MINOR_CHILD": "Parent with a Minor Child",
    "PARENT_WITH_MINOR": "Parent with a Minor Child",
    "PROVIDE_CC_EA": "Provide Child Care - excused absence",
    "PROVIDE_CC_HOL": "Provide Child Care - holiday",
    "PROVIDE_CC_HOP": "Provide Child Care - hours of participation",
    "RACE_AMER_INDIAN": "Race American Indian",
    "RECEIVES_FOOD_STAMPS": "Receives Food Stamps",
    "RECEIVES_MED_ASSISTANCE": "Receives Medical Assistance",
    "RECEIVES_SUB_CC": "Receives Subsidized Child Care",
    "RECEIVES_SUB_HOUSING": "Receives Subsidized Housing",
    "RECEIVE_NONSSA_BENEFITS": "Receives Non-SSA Benefits",
    "RECOUPMENT_PRIOR_OVRPMT": "Recoupment of Prior Overpayment",
    "REC_AID_AGED": "Receives Aid to the Aged",
    "REC_AID_TOTALLY": "Receives Aid to the Totally Disabled",
    "REC_FEDERAL_DISABILITY": "Receives Federal Disability",
    "REC_FOOD_STAMPS": "Receives Food Stamps",
    "REC_MED_ASSIST": "Receives Medical Assistance",
    "REC_OASDI_INSURANCE": "Receives OASDI Insurance",
    "REC_SUB_CC": "Receives Subsidized Child Care",
    "REC_SUB_HOUSING": "Receives Subsidized Housing",
    "REDUCTIONS_ON_RECEIPTS": "Reductions on Receipts",
    "RPT_MONTH_YEAR": "Report Month and Year",
    "SANC_REDUCTION_AMT": "Sanction Reduction Amount",
    "SANC_TEEN_PARENT": "Sanctioned Teen Parent",
    "SCHOOL_ATTENDENCE_EA": "School Attendance - excused absence",
    "SCHOOL_ATTENDENCE_HOL": "School Attendance - holiday",
    "SCHOOL_ATTENDENCE_HOP": "School Attendance - hours of participation",
    "SCHOOL_DIPL_EA": "School Diploma - excused absence",
    "SCHOOL_DIPL_HOL": "School Diploma - holiday",
    "SCHOOL_DIPL_HOP": "School Diploma - hours of participation",
    "SUB_PRIVATE_EMPLOYMENT": "Subsidized Private Employment",
    "SUB_PUBLIC_EMPLOYMENT": "Subsidized Public Employment",
    "TDRS_SECTION_IND": "TDRS Section Indicator",
    "TRANSITION_NBR_MONTHS": "Number of Months of Transition Services",
    "TRANSITION_SERVICES_AMOUNT": "Transition Services Amount",
    "TRANSP_NBR_MONTHS": "Number of Months of Transportation",
    "UNEARNED_INCOME_TAX": "Unearned Income Tax",
    "UNEARNED_SOCIAL_SECURITY": "Unearned Social Security",
    "UNEARNED_WORKERS_COMP": "Unearned Workers Compensation",
    "VOCATIONAL_ED_TRAINING": "Vocational Education Training",
    "WAIVER_EVAL_CONTROL": "Waiver Evaluation Control",
    "WORK_ELIGIBLE_INDICATOR": "Work Eligible Indicator",
    "WORK_EXPERIENCE_EA": "Work Experience - excused absence",
    "WORK_EXPERIENCE_HOL": "Work Experience - holiday",
    "WORK_EXPERIENCE_HOP": "Work Experience - hours of participation",
    "WORK_PART_STATUS": "Work Participation Status",
    "WORK_REQ_SANCTION": "Work Requirement Sanction",
}

SSP_ITEM_NAME = {
    "AID_AGED_BLIND": "Aid to the Aged, Blind, and Disabled",
    "AMT_FOOD_STAMP": "Amount of Food Stamps",
    "AMT_SUB_CC": "Amount of Subsidized Child Care",
    "CC_NBR_MONTHS": "Number of Months of Subsidized Child Care",
    "CHILD_SUPPORT_AMT": "Amount of Child Support",
    "COMM_SERVICES_EA": "Community Service - EA",
    "COMM_SERVICES_HOL": "Community Service - HOL",
    "COMM_SERVICES_HOP": "Community Service - HOP",
    "COOPERATION_CHILD_SUPPORT": "Cooperation with Child Support",
    "COUNTY_FIPS_CODE": "County FIPS Code",
    "DATE_OF_BIRTH": "Date of Birth",
    "DEEMED_HOURS_FOR": "Deemed Hours for",
    "DISABLED_TITLE_XIVAPDT": "Disabled Title XIV-A PD/T",
    "ED_NO_HIGH": "Education - No High School Diploma",
    "FAILURE_TO_COMPLY": "Failure to Comply",
    "FAMILY_CASH_RESOURCES": "Family Cash Resources",
    "FAMILY_SANC_ADULT": "Family Sanctioned for an Adult",
    "FED_DISABILITY_STATUS": "Federal Disability Status",
    "FED_OASDI_PROGRAM": "Federal OASDI Program",
    "JOB_SEARCH_EA": "Job Search - Excused Absence",
    "JOB_SEARCH_HOL": "Job Search - Holiday",
    "JOB_SEARCH_HOP": "Job Search - Hours of Participation",
    "JOB_SKILLS_TRAINING": "Job Skills Training",
    "NBR_FAMILY_MEMBERS": "Number of Family Members",
    "NEEDS_PREGNANT_WOMAN": "Needs of a pregnant woman",
    "NON_COOPERATION_CSE": "Non-Cooperation with Child Support Enforcement",
    "OTHER_NBR_MONTHS": "Number of Months of Other Time",
    "OTHER_NON_SANCTION": "Other Non-Sanction",
    "OTHER_TOTAL_REDUCTIONS": "Other Total Reductions",
    "OTHER_UNEARNED_INCOME": "Other Unearned Income",
    "OTHER_WORK_ACTIVITIES": "Other Work Activities",
    "PARENT_MINOR_CHILD": "Parent with a Minor Child",
    "PROVIDE_CC_EA": "Provide Child Care - excused absence",
    "PROVIDE_CC_HOL": "Provide Child Care - holiday",
    "PROVIDE_CC_HOP": "Provide Child Care - hours of participation",
    "RACE_AMER_INDIAN": "Race Americal Indian",
    "RECEIVES_FOOD_STAMPS": "Receives Food Stamps",
    "RECEIVES_MED_ASSISTANCE": "Receives Medical Assistance",
    "RECEIVES_SUB_CC": "Receives Subsidized Child Care",
    "RECEIVES_SUB_HOUSING": "Receives Subsidized Housing",
    "RECEIVE_NONSSI_BENEFITS": "Receives Non-SSI Benefits",
    "RECOUPMENT_PRIOR_OVRPMT": "Recoupment of Prior Overpayment",
    "REDUCTIONS_ON_RECEIPTS": "Reductions on Receipts",
    "RPT_MONTH_YEAR": "Report Month and Year",
    "SANC_REDUCTION_AMT": "Sanction Reduction Amount",
    "SANC_TEEN_PARENT": "Sanctioned Teen Parent",
    "SCHOOL_ATTENDENCE_EA": "School Attendance - Excused Absence",
    "SCHOOL_ATTENDENCE_HOL": "School Attendance - Holiday",
    "SCHOOL_ATTENDENCE_HOP": "School Attendance - Hours of Participation",
    "SCHOOL_DIPL_EA": "School Diploma - Excused Absence",
    "SCHOOL_DIPL_HOL": "School Diploma - Holiday",
    "SCHOOL_DIPL_HOP": "School Diploma - Hours of Participation",
    "SUB_PRIVATE_EMPLOYMENT": "Subsidized Private Employment",
    "SUB_PUBLIC_EMPLOYMENT": "Subsidized Public Employment",
    "TANF_ASST_IN": "TANF Assistance In",
    "TRANSITION_NBR_MONTHS": "Number of Months of Transition Services",
    "TRANSITION_SERVICES_AMOUNT": "Transition Services Amount",
    "TRANSP_NBR_MONTHS": "Number of Months of Transportation",
    "UNEARNED_INCOME_TAX": "Unearned Income Tax",
    "UNEARNED_SOCIAL_SECURITY": "Unearned Social Security",
    "UNEARNED_WORKERS_COMP": "Unearned Workers Compensation",
    "VOCATIONAL_ED_TRAINING":   "Vocational Education Training",
    "WAIVER_EVAL_CONTROL":  "Waiver Evaluation Control",
    "WORK_ELIGIBLE_INDICATOR":  "Work Eligible Indicator",
    "WORK_EXPERIENCE_EA":   "Work Experience - Excused Absence",
    "WORK_EXPERIENCE_HOL":  "Work Experience - Holiday",
    "WORK_EXPERIENCE_HOP":  "Work Experience - Hours of Participation",
    "WORK_PART_STATUS": "Work Participation Status",
    "WORK_REQ_SANCTION":    "Work Requirement Sanction",
}
