# Generated by Django 3.2.15 on 2023-05-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parsers', '0002_alter_parsererror_error_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsererror',
            name='category',
        ),
        migrations.AlterField(
            model_name='parsererror',
            name='column_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parsererror',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='parsererror',
            name='field_name',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='parsererror',
            name='item_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parsererror',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
