# Generated by Django 3.2.15 on 2023-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20230518_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsererror',
            name='object_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
