# Generated by Django 3.2.15 on 2023-06-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_auto_20230601_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsererror',
            name='item_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
