# Generated by Django 3.2.15 on 2023-07-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0012_datafile_s3_versioning_id'),
        ('parsers', '0007_datafilesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafilesummary',
            name='datafile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='data_files.datafile'),
        ),
    ]
