# Generated by Django 3.2.15 on 2023-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_alter_datafilesummary_datafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafilesummary',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Accepted with Errors', 'Accepted With Errors'), ('Partially Accepted with Errors', 'Partially Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
