# Generated by Django 3.2.15 on 2024-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0011_parsererror_row_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsererror',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
