# Generated by Django 3.2.15 on 2025-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0012_parsererror_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsererror',
            name='values_json',
            field=models.JSONField(null=True),
        ),
    ]
