# Generated by Django 3.2.15 on 2025-06-17 12:01

from django.db import migrations, models
import tdpservice.backends
import tdpservice.parsers.models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0013_parsererror_track_record_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilesummary',
            name='error_report',
            field=models.FileField(blank=True, null=True, max_length=500, storage=tdpservice.backends.DataFilesS3Storage, upload_to=tdpservice.parsers.models.get_s3_upload_path),
        ),
    ]
