# Generated by Django 3.2.15 on 2025-07-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0014_datafilesummary_error_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsererror',
            name='error_type',
            field=models.TextField(choices=[('1', 'File pre-check'), ('2', 'Record value invalid'), ('3', 'Record value consistency'), ('4', 'Case consistency'), ('5', 'Section consistency'), ('6', 'Historical consistency'), ('7', 'Record pre-check')], max_length=128),
        ),
    ]
