# Generated by Django 5.2.10 on 2026-03-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("data_files", "0024_alter_datafile_file"),
        ("parsers", "0015_record_precheck_error_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="parsererror",
            index=models.Index(
                fields=["file", "deprecated"], name="pe_file_deprecated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parsererror",
            index=models.Index(
                fields=["file", "error_type", "deprecated"],
                name="pe_file_etype_deprecated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parsererror",
            index=models.Index(
                fields=["file", "deprecated", "rpt_month_year"],
                name="pe_file_deprecated_rpt_idx",
            ),
        ),
    ]
