# Generated by Django 5.2.10 on 2026-05-04 19:09

import django.db.models.deletion
import tdpservice.backends
import tdpservice.parsers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("data_files", "0027_shadowdatafile"),
        ("parsers", "0016_parsererror_indexes"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS shadow_parsers_datafilesummary CASCADE;
            DROP TABLE IF EXISTS shadow_parser_error CASCADE;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="ShadowDataFileSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Accepted with Errors", "Accepted With Errors"),
                            ("Partially Accepted with Errors", "Partially Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "error_report",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        storage=tdpservice.backends.DataFilesS3Storage,
                        upload_to=tdpservice.parsers.models.get_s3_upload_path,
                    ),
                ),
                ("case_aggregates", models.JSONField(null=True)),
                (
                    "total_number_of_records_in_file",
                    models.IntegerField(default=0, null=True),
                ),
                (
                    "total_number_of_records_created",
                    models.IntegerField(default=0, null=True),
                ),
                (
                    "datafile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_summary",
                        to="data_files.shadowdatafile",
                    ),
                ),
            ],
            options={
                "db_table": "shadow_parsers_datafilesummary",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ShadowParserError",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("row_number", models.IntegerField(null=True)),
                ("column_number", models.CharField(max_length=8, null=True)),
                ("item_number", models.CharField(max_length=8, null=True)),
                ("field_name", models.TextField(max_length=128, null=True)),
                ("rpt_month_year", models.IntegerField(null=True)),
                ("case_number", models.TextField(max_length=128, null=True)),
                ("error_message", models.TextField(max_length=512, null=True)),
                (
                    "error_type",
                    models.TextField(
                        choices=[
                            ("1", "File pre-check"),
                            ("2", "Record value invalid"),
                            ("3", "Record value consistency"),
                            ("4", "Case consistency"),
                            ("5", "Section consistency"),
                            ("6", "Historical consistency"),
                            ("7", "Record pre-check"),
                        ],
                        max_length=128,
                    ),
                ),
                ("object_id", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fields_json", models.JSONField(null=True)),
                ("values_json", models.JSONField(null=True)),
                ("deprecated", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_parser_errors",
                        to="data_files.shadowdatafile",
                    ),
                ),
            ],
            options={
                "db_table": "shadow_parser_error",
                "managed": True,
            },
        ),
    ]
