# Generated by Django 3.2.15 on 2025-11-03 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tdpservice.backends
import tdpservice.reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_files', '0023_rename_indexes'),
        ('stts', '0011_add_region_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIngest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('extension', models.CharField(default='zip', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('quarter', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=16, null=True)),
                ('num_reports_created', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=False, null=False, storage=tdpservice.backends.DataFilesS3Storage, upload_to=tdpservice.reports.models.get_master_upload_path)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_ingests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('extension', models.CharField(default='zip', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=16)),
                ('year', models.IntegerField()),
                ('version', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, storage=tdpservice.backends.DataFilesS3Storage, upload_to=tdpservice.reports.models.get_s3_upload_path)),
                ('ingest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_files', to='reports.reportingest')),
                ('stt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='stts.stt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportfile',
            constraint=models.UniqueConstraint(fields=('version', 'quarter', 'year', 'stt'), name='unique_reports_reportfile_fields'),
        ),
    ]
