# Generated by Django 3.2.15 on 2025-10-20 14:55

# Must name the initial migratio as 0002 since data_files/migrations/0001_initial.py
# sets: replaces = [('reports','0001_initial')]
# it seems reports was historically squashed into data_files. maybe a schema change in the past

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tdpservice.backends
import tdpservice.reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data_files", "0023_rename_indexes"),
        ("stts", "0011_add_region_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256)),
                ("extension", models.CharField(default="txt", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=16,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("Active Case Data", "Active Case Data"),
                            ("Closed Case Data", "Closed Case Data"),
                            ("Aggregate Data", "Aggregate Data"),
                            ("Stratum Data", "Stratum Data"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.IntegerField()),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=tdpservice.backends.DataFilesS3Storage,
                        upload_to=tdpservice.reports.models.get_s3_upload_path,
                    ),
                ),
                (
                    "stt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_files",
                        to="stts.stt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reportfile",
            constraint=models.UniqueConstraint(
                fields=("section", "version", "quarter", "year", "stt"),
                name="unique_reports_reportfile_fields",
            ),
        ),
    ]
