# Generated by Django 3.2.15 on 2026-01-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportfile',
            name='unique_reports_reportfile_fields',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='reportsource',
            name='quarter',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='date_extracted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsource',
            name='date_extracted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reportfile',
            constraint=models.UniqueConstraint(fields=('version', 'date_extracted_on', 'year', 'stt'), name='unique_reports_reportfile_fields'),
        ),
    ]
