# Generated by Django 5.2.10 on 2026-03-31 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20260130_1950'),
        ('stts', '0012_stt_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportfile',
            name='unique_reports_reportfile_fields',
        ),
        migrations.AddField(
            model_name='reportfile',
            name='report_type',
            field=models.CharField(choices=[('TANF_SSP', 'TANF/SSP'), ('FRA', 'FRA')], default='TANF_SSP', max_length=16),
        ),
        migrations.AddField(
            model_name='reportsource',
            name='report_type',
            field=models.CharField(choices=[('TANF_SSP', 'TANF/SSP'), ('FRA', 'FRA')], default='TANF_SSP', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='reportfile',
            constraint=models.UniqueConstraint(fields=('version', 'date_extracted_on', 'year', 'stt', 'report_type'), name='unique_reports_reportfile_fields_v2'),
        ),
    ]
