# Generated by Django 3.1.7 on 2021-04-30 22:36

from django.db import migrations, models
import tdpservice.reports.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210305_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data_files', validators=[tdpservice.reports.validators.validate_data_file]),
        ),
    ]
