# Generated by Django 5.2.10 on 2026-06-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_reportfile_unique_reports_reportfile_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='report_type',
            field=models.CharField(choices=[('TANF_SSP', 'TANF/SSP'), ('TRIBAL_TANF', 'Tribal TANF'), ('FRA', 'FRA')], default='TANF_SSP', max_length=16),
        ),
        migrations.AlterField(
            model_name='reportsource',
            name='report_type',
            field=models.CharField(choices=[('TANF_SSP', 'TANF/SSP'), ('TRIBAL_TANF', 'Tribal TANF'), ('FRA', 'FRA')], default='TANF_SSP', max_length=16),
        ),
    ]
