# Generated by Django 3.1.7 on 2021-05-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210305_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='data_files'),
        ),
    ]
