# Generated by Django 3.1.7 on 2021-05-04 18:55

from django.db import migrations, models
import tdpservice.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tdpservice.reports.models.get_s3_upload_path),
        ),
    ]
