# Generated by Django 3.2.3 on 2021-05-24 19:06

from django.db import migrations, models
import tdpservice.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_update_section_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=tdpservice.reports.models.DataFilesS3Storage, upload_to=tdpservice.reports.models.get_s3_upload_path),
        ),
    ]
