# Generated by Django 5.2.14 on 2026-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_reportfile_report_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportfile",
            name="downloaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
