# Generated by Django 3.1.1 on 2020-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('reports','0002_auto_20201215_1932')]
    dependencies = [
        ("data_files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="slug",
            field=models.CharField(max_length=256),
        ),
    ]
