# Generated by Django 3.1.4 on 2021-02-17 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0002_auto_20201215_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
