# Generated by Django 3.1.4 on 2021-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('reports','0004_auto_20210305_2040')]
    dependencies = [
        ('data_files', '0003_datafile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='year',
            field=models.IntegerField(),
        ),
    ]
