# Generated by Django 3.1.4 on 2021-03-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportfile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='year',
            field=models.IntegerField(),
        ),
    ]
