# Generated by Django 3.2.3 on 2021-05-24 19:06

from django.db import migrations, models
import tdpservice.data_files.models


class Migration(migrations.Migration):

    replaces = [('reports','0006_reportfile_file')]
    dependencies = [
        ('data_files', '0005_update_section_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=tdpservice.data_files.models.DataFilesS3Storage, upload_to=tdpservice.data_files.models.get_s3_upload_path),
        ),
    ]
