
# Generated by Django 3.2.3 on 2021-05-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.RenameModel(
            "Report", "DataFile"
        ),
    ]
