# Generated by Django 3.2.5 on 2021-08-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0007_rename_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datafile',
            table=None,
        ),
    ]
