# Generated by Django 3.2.5 on 2021-07-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0006_reportfile_file'),
        ('data_files', '0007_change_report_to_data_file'),
    ]

    operations = [
    ]
