# Generated by Django 3.2.13 on 2022-05-06 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_files', '0009_update_log_entry_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyFileTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.TextField()),
                ('file_size', models.PositiveBigIntegerField(help_text='The file size in bytes')),
                ('file_shasum', models.TextField(help_text='The SHA256 checksum of the uploaded file')),
                ('result', models.CharField(choices=[('COMPLETED', 'Completed'), ('ERROR', 'Error')], help_text='Transfer result for uploaded file', max_length=12)),
                ('data_file', models.ForeignKey(blank=True, help_text='The resulting DataFile object, if this transfer was completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fileTransfer', to='data_files.datafile')),
                ('uploaded_by', models.ForeignKey(help_text='The user that uploaded the data file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fileTransfer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legacy File Transfer',
            },
        ),
    ]
