# Generated by Django 3.2.15 on 2023-01-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0011_alter_datafile_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='s3_versioning_id',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
