# Generated by Django 3.2.15 on 2024-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0030_reparse_meta_model'),
        ('data_files', '0012_datafile_s3_versioning_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='reparse_meta_models',
            field=models.ManyToManyField(help_text='Reparse events this file has been associated with.', related_name='datafiles', to='search_indexes.ReparseMeta'),
        ),
    ]
