# Generated by Django 3.2.15 on 2024-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0013_datafile_reparse_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='version',
            field=models.IntegerField(verbose_name='version number'),
        ),
    ]
