# Generated by Django 3.2.15 on 2024-10-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_indexes', '0031_alter_tribal_tanf_t4_closure_reason'),
        ('data_files', '0013_datafile_reparse_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReparseFileMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('num_records_created', models.PositiveIntegerField(default=0)),
                ('cat_4_errors_generated', models.PositiveIntegerField(default=0)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparse_file_metas', to='data_files.datafile')),
                ('reparse_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparse_file_metas', to='search_indexes.reparsemeta')),
            ],
        ),
    ]
