# Generated by Django 3.2.15 on 2024-10-04 12:17

from django.db import migrations, models
from tdpservice.data_files.models import ReparseFileMeta


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0014_reparsefilemeta'),
        ('search_indexes', '0031_alter_tribal_tanf_t4_closure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='reparses',
            field=models.ManyToManyField(help_text='Reparse events this file has been associated with.', related_name='files', through="data_files.ReparseFileMeta", to='search_indexes.ReparseMeta'),
        ),
    ]
