# Generated by Django 3.2.15 on 2025-10-06 19:29

from django.db import migrations, models


def get_program_type_from_section(section, choices):
    if section.startswith("Tribal"):
        return "TRIBAL"
    elif section.startswith("SSP"):
        return "SSP"
    elif section.startswith("Work"):
        return "FRA"
    else:
        return "TAN"


def set_program_type_based_on_section(apps, schema_editor):
    DataFile = apps.get_model("data_files", "DataFile")

    for df in DataFile.objects.all():
        df.program_type = get_program_type_from_section(df.section)
        df.save()


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0018_alter_datafile_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafile",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("TAN", "Tanf"),
                    ("SSP", "Ssp"),
                    ("TRIBAL", "Tribal"),
                    ("FRA", "Fra"),
                ],
                default="TAN",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_program_type_based_on_section,
        ),
    ]
