# Generated by Django 3.2.15 on 2025-10-08 16:22

from django.db import migrations, models


def get_new_section(section):
    if "Active Case Data" in section:
        return "Active Case Data"
    elif "Closed Case Data" in section:
        return "Closed Case Data"
    elif "Aggregate Data" in section:
        return "Aggregate Data"
    elif "Stratum Data" in section:
        return "Stratum Data"
    else:
        return section


def set_section(apps, schema_editor):
    print("migrating section")
    DataFile = apps.get_model("data_files", "DataFile")

    for df in DataFile.objects.all():
        df.section = get_new_section(df.section)
        df.save()


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0019_datafile_program_type"),
    ]

    operations = [
        # need to first remove the constraint since `section` will now be the same across all program types
        migrations.RemoveConstraint(
            model_name="datafile",
            name="constraint_name",
        ),
        migrations.AlterField(
            model_name="datafile",
            name="section",
            field=models.CharField(
                choices=[
                    ("Active Case Data", "Active Case Data"),
                    ("Closed Case Data", "Closed Case Data"),
                    ("Aggregate Data", "Aggregate Data"),
                    ("Stratum Data", "Stratum Data"),
                    ("Work Outcomes of TANF Exiters", "Fra Work Outcome Tanf Exiters"),
                    ("Secondary School Attainment", "Fra Secondry School Attainment"),
                    ("Supplemental Work Outcomes", "Fra Supplement Work Outcomes"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            set_section,
        ),
        # we add back the constraint including the new `program_type` field
        migrations.AddConstraint(
            model_name="datafile",
            constraint=models.UniqueConstraint(
                fields=("program_type", "section", "version", "quarter", "year", "stt"),
                name="constraint_name",
            ),
        ),
    ]
