# Generated by Django 3.2.15 on 2025-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0020_remove_tribal_ssp_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafile",
            name="is_program_audit",
            field=models.BooleanField(default=False),
        ),
    ]
