# Generated by Django 3.2.15 on 2025-10-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0020_alter_datafile_section"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="datafile",
            name="constraint_name",
        ),
        migrations.AddConstraint(
            model_name="datafile",
            constraint=models.UniqueConstraint(
                fields=("program_type", "section", "version", "quarter", "year", "stt"),
                name="constraint_name",
            ),
        ),
    ]
