# Generated by Django 3.2.15 on 2025-10-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0021_datafile_is_program_audit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="datafile",
            name="constraint_name",
        ),
        migrations.AddConstraint(
            model_name="datafile",
            constraint=models.UniqueConstraint(
                fields=(
                    "program_type",
                    "section",
                    "version",
                    "quarter",
                    "year",
                    "stt",
                    "is_program_audit",
                ),
                name="constraint_name",
            ),
        ),
    ]
