# Generated by Django 3.2.15 on 2026-01-29 19:24

from django.db import migrations
import tdpservice.backends
import tdpservice.common.fields
import tdpservice.data_files.models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0023_rename_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="file",
            field=tdpservice.common.fields.S3VersionedFileField(
                blank=True,
                null=True,
                storage=tdpservice.backends.DataFilesS3Storage,
                upload_to=tdpservice.data_files.models.get_s3_upload_path,
                version_id_field="s3_versioning_id",
            ),
        ),
    ]
