# Generated by Django 3.2.15 on 2026-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0024_alter_datafile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafile",
            name="state",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("virus_scan_started", "Virus scan started"),
                    ("virus_scan_failed", "Virus scan failed"),
                    ("virus_scan_completed", "Virus scan completed"),
                    ("parse_started", "Parse started"),
                    ("parse_failed", "Parse failed"),
                    ("parsed_with_errors", "Parsed with errors"),
                    ("parse_completed", "Parse completed"),
                    ("stuck", "Stuck"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="uploaded",
                max_length=32,
            ),
            preserve_default=True,
        ),
    ]
