# Generated by Django 5.2.10 on 2026-05-04 19:09

import django.db.models.deletion
import tdpservice.backends
import tdpservice.common.fields
import tdpservice.data_files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0026_reparsefilemeta_previous_summary_status"),
        ("stts", "0012_stt_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS shadow_data_files_datafile CASCADE;",
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="ShadowDataFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256)),
                ("extension", models.CharField(default="txt", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "Q1"),
                            ("Q2", "Q2"),
                            ("Q3", "Q3"),
                            ("Q4", "Q4"),
                        ],
                        max_length=16,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("TAN", "Tanf"),
                            ("SSP", "Ssp"),
                            ("TRIBAL", "Tribal"),
                            ("FRA", "Fra"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("Active Case Data", "Active Case Data"),
                            ("Closed Case Data", "Closed Case Data"),
                            ("Aggregate Data", "Aggregate Data"),
                            ("Stratum Data", "Stratum Data"),
                            (
                                "Work Outcomes of TANF Exiters",
                                "Fra Work Outcome Tanf Exiters",
                            ),
                            (
                                "Secondary School Attainment",
                                "Fra Secondry School Attainment",
                            ),
                            (
                                "Supplemental Work Outcomes",
                                "Fra Supplement Work Outcomes",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_program_audit", models.BooleanField(default=False)),
                ("version", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("virus_scan_started", "Virus scan started"),
                            ("virus_scan_failed", "Virus scan failed"),
                            ("virus_scan_completed", "Virus scan completed"),
                            ("parse_started", "Parse started"),
                            ("parse_failed", "Parse failed"),
                            ("parsed_with_errors", "Parsed with errors"),
                            ("parse_completed", "Parse completed"),
                            ("stuck", "Stuck"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    tdpservice.common.fields.S3VersionedFileField(
                        blank=True,
                        null=True,
                        storage=tdpservice.backends.DataFilesS3Storage,
                        upload_to=tdpservice.data_files.models.get_s3_upload_path,
                        version_id_field="s3_versioning_id",
                    ),
                ),
                ("s3_versioning_id", models.CharField(max_length=1024, null=True)),
                (
                    "stt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stts.stt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shadow_data_files_datafile",
                "managed": True,
            },
        ),
    ]
