# Generated by Django 5.2.14 on 2026-07-23 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0029_program_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='section_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_files', to='data_files.section'),
        ),
    ]
