# Generated by Codex on 2026-08-18

import django.db.models.deletion
from django.db import migrations, models


SUBMISSION_STATE_CHOICES = [
    ("uploaded", "Uploaded"),
    ("virus_scan_started", "Virus scan started"),
    ("virus_scan_failed", "Virus scan failed"),
    ("virus_scan_completed", "Virus scan completed"),
    ("reparse_requested", "Reparse requested"),
    ("parse_started", "Parse started"),
    ("parse_failed", "Parse failed"),
    ("parsed_with_errors", "Parsed with errors"),
    ("parse_completed", "Parse completed"),
    ("stuck", "Stuck"),
    ("completed", "Completed"),
    ("canceled", "Canceled"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_baselog"),
        ("data_files", "0031_backfill_datafile_section_ref"),
    ]

    operations = [
        # No historical rows are backfilled. Existing DataFile rows begin
        # recording transition history the next time their state changes.
        migrations.CreateModel(
            name="DataFileStateTransition",
            fields=[
                (
                    "baselog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.baselog",
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        choices=SUBMISSION_STATE_CHOICES,
                        max_length=32,
                    ),
                ),
                (
                    "next_state",
                    models.CharField(
                        choices=SUBMISSION_STATE_CHOICES,
                        max_length=32,
                    ),
                ),
                (
                    "reparse_meta_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "default_permissions": (),
                "ordering": ["-created_at", "-id"],
            },
            bases=("core.baselog",),
        ),
        migrations.AddIndex(
            model_name="datafilestatetransition",
            index=models.Index(
                fields=["reparse_meta_id"],
                name="data_files_reparse_4ba50f_idx",
            ),
        ),
    ]
