# Generated by Django 5.2.14 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_files", "0032_datafilestatetransition"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafile",
            name="parser_mode",
            field=models.CharField(
                choices=[
                    ("python-only", "Python only"),
                    ("go-shadow", "Python and Go shadow"),
                    ("go-only", "Go only"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
