{
 "title": "Uptime/Health",
 "tags": [
  "Backend",
  "Postgres",
  "Celery"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "app_env",
    "label": "Backend environment",
    "query": "prod, staging, develop, qasp, raft, local"
   },
   {
    "name": "pg_env",
    "label": "Database environment",
    "query": "production, staging, dev, local"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(celery_worker_up{}, namespace)"
   },
   {
    "name": "queue_name",
    "label": "Queue Name",
    "query": "label_values(celery_task_received_total{namespace=\"$namespace\", job=\"tdp-celery-$app_env\", name!~\"None\"}, queue_name)"
   }
  ]
 },
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Backend - Active Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Uptime (Backend)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=~\"tdp-backend-$app_env\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Fired (Backend)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=\"tdp-backend-$app_env\",alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (Backend)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{job=~\"tdp-backend-$app_env\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate (Backend)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=~\"tdp-backend-$app_env\",status!~\"2.+|3.+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Average CPU Usage (Backend)", "type": "text", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 }, "options": { "content": "# Add backend CPU here" } },
  { "title": "Average Memory Usage (Backend)", "type": "text", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 }, "options": { "content": "# Add backend Memory here" } },
  { "title": "Celery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  { "title": "Celery - Active Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Uptime (Celery)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=~\"tdp-celery-$app_env|tdp-celery-exporter-$app_env\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Fired (Celery)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=~\"tdp-celery-$app_env|tdp-celery-exporter-$app_env\", alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name)\n/(sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name)\n+sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name)\n) > -1\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_succeeded_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_failed_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_sent_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_received_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_rejected_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_retried_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    },
    {
     "expr": "sum (\n  round(\n    increase(\n      celery_task_revoked_total{\n        job=\"tdp-celery-$app_env\",\n        queue_name=~\"$queue_name\"\n      }[$__range]\n    )\n  )\n) by (name) > 0\n"
    }
   ]
  },
  {
   "title": "Task Average Runtime",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(\n  celery_task_runtime_sum{\n    job=\"tdp-celery-$app_env\",\n    queue_name=~\"$queue_name\"\n  }\n) by (name) / sum(\n  celery_task_runtime_count{\n    job=\"tdp-celery-$app_env\",\n    queue_name=~\"$queue_name\"\n  }\n) by (name)\n\n"
    }
   ]
  },
  {
   "title": "Active Celery Workers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "workers" } },
   "targets": [
    {
     "expr": "sum(celery_active_worker_count{job=\"tdp-celery-$app_env\", queue_name=\"$queue_name\"}) by (queue_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  { "title": "Database - Active Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Uptime (Database)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=~\"postgres-$pg_env\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Fired (Database)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{job=~\"postgres-$pg_env\", alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage (Database)",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=~\"postgres-$pg_env\"}[$__rate_interval]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage (Database)",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=~\"postgres-$pg_env\"}[$__rate_interval]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{job=~\"postgres-$pg_env\"}[$__rate_interval]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  }
 ]
}