{
 "title": "Keycloak Capacity",
 "tags": [
  "Keycloak",
  "Auth",
  "User"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "realm", "label": "realm", "query": { "query": "label_values(realm)" } },
   { "name": "env", "label": "Env", "query": "prod, staging, dev, local" }
  ]
 },
 "panels": [
  {
   "title": "Password validations rate",
   "type": "timeseries",
   "description": "Shows the number of password validations performed by Keycloak",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(keycloak_credentials_password_hashing_validations_total{realm=\"$realm\", job=\"keycloak-$env\"}[$__rate_interval])",
     "legendFormat": "{{pod}} => {{outcome}} - {{algorithm}}:{{hashing_strength}}"
    }
   ]
  },
  {
   "title": "Code to Token Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"code_to_token\", realm=\"$realm\", job=\"keycloak-$env\", error!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}:{{error}}"
    },
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"code_to_token\", realm=\"$realm\", job=\"keycloak-$env\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client Login Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"client_login\", realm=\"$realm\", job=\"keycloak-$env\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"client_login\", realm=\"$realm\", job=\"keycloak-$env\", error!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  },
  {
   "title": "Refresh Token Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"refresh_token\", realm=\"$realm\", job=\"keycloak-$env\", error!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}:{{error}}"
    },
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"refresh_token\", realm=\"$realm\", job=\"keycloak-$env\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Login Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"login\", realm=\"$realm\", job=\"keycloak-$env\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"login\", realm=\"$realm\", job=\"keycloak-$env\", error!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  },
  {
   "title": "Logout Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"logout\", realm=\"$realm\", job=\"keycloak-$env\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"logout\", realm=\"$realm\", job=\"keycloak-$env\", error!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  },
  {
   "title": "Token Exchange Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"token_exchange\", realm=\"$realm\", job=\"keycloak-$env\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(pod) (irate(keycloak_user_events_total{event=\"token_exchange\", realm=\"$realm\", job=\"keycloak-$env\", error!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}:{{error}}"
    }
   ]
  }
 ]
}