{
 "title": "OpenTelemetry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "user",
    "label": "User",
    "query": {}
   },
   {
    "name": "session_id",
    "label": "Session ID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(count_over_time({service_name=\"unknown_service\"}[$__range])) by (session_id))"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"unknown_service\", user_username=~\"$user\", session_id=~\"$session_id\"} | logfmt"
    }
   ]
  },
  {
   "title": "Span Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_latency_bucket[$__rate_interval])) by (le, service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Span Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "# p50 (median)\nhistogram_quantile(0.5, sum(rate(traces_spanmetrics_latency_bucket[$__rate_interval])) by (le, service_name))",
     "legendFormat": "__auto"
    },
    {
     "expr": "# p90\nhistogram_quantile(0.9, sum(rate(traces_spanmetrics_latency_bucket[$__rate_interval])) by (le, service_name))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "# p95\nhistogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket[$__rate_interval])) by (le, service_name))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{service_name=\"unknown_service\", user_username=~\"$user\", session_id=~\"$session_id\"}"
    }
   ]
  },
  {
   "title": "All Collected Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{service_name=\"unknown_service\", user_username=~\"$user\", session_id=~\"$session_id\"} | logfmt"
    }
   ]
  }
 ]
}