{
 "title": "Telemetry Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time to First Byte (TTFB)",
   "type": "stat",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.\nhttps://web.dev/ttfb/",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\", app_name=\"tdp-frontend\"} |= \"ttfb\" | logfmt | unwrap ttfb [$__range]) by (app_name)",
     "legendFormat": "TTFB"
    }
   ]
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "stat",
   "description": "The First Contentful Paint (FCP) metric measures the time from when the page starts loading to when any part of the page's content is rendered on the screen. For this metric, \"content\" refers to text, images (including background images), <svg> elements, or non-white <canvas> elements.\nhttps://web.dev/fcp/",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" fcp=\" | logfmt | unwrap fcp [$__range]) by (app_name)",
     "legendFormat": "FCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "stat",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\", app_name=\"tdp-frontend\"} |= \"cls\" | logfmt | unwrap cls [$__range]) by (app_name)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP)",
   "type": "stat",
   "description": "Largest Contentful Paint (LCP): measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.\nhttps://web.dev/lcp/",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" lcp=\" | logfmt | unwrap lcp [$__range]) by (app_name)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "stat",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" fid=\" | logfmt | unwrap fid [$__range]) by (app_name)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Page Load, p75",
   "type": "timeseries",
   "description": "p75 quantile over time for TTFB, FCP, and LCP",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" ttfb=\" | logfmt | unwrap ttfb [$__auto]) by (app_name)",
     "legendFormat": "TTFB"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" fcp=\" | logfmt | unwrap fcp [$__auto]) by (app_name)",
     "legendFormat": "FCP"
    },
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" lcp=\" | logfmt | unwrap lcp [$__auto]) by (app_name)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift, p75",
   "type": "timeseries",
   "description": "Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.\nhttps://web.dev/cls/",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" cls=\" | logfmt | unwrap cls [5m]) by (app_name)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "First Input Delay, p75",
   "type": "timeseries",
   "description": "First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of 100 milliseconds or less.\nhttps://web.dev/fid/",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.75, {kind=\"measurement\", app_name=\"tdp-frontend\"} |= \" fid=\" | logfmt | unwrap fid [5m]) by (app_name)",
     "legendFormat": "FID"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app_name=\"tdp-frontend\",kind=\"exception\"} [$__range])) by (app_name)"
    }
   ]
  },
  {
   "title": "Errors Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "sum(count_over_time({app_name=\"tdp-frontend\",kind=\"exception\"} [$__interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Top URLs by Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"exception\", app_name=\"tdp-frontend\"} | logfmt [$__range])) by (page_url))"
    }
   ]
  },
  {
   "title": "Top Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"exception\", app_name=\"tdp-frontend\"} | logfmt [$__range])) by (value))"
    }
   ]
  },
  {
   "title": "Top Browsers by Error Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({kind=\"exception\", app_name=\"tdp-frontend\"} | logfmt [$__range])))"
    }
   ]
  },
  { "title": "Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Top Browsers",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({app_name=\"tdp-frontend\",kind=\"measurement\"} |= \" ttfb=\" | logfmt [$__range])) by (browser_name, browser_version))"
    }
   ]
  },
  {
   "title": "Top Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "topk(10, count(count_over_time({kind=\"event\", app_name=\"tdp-frontend\"} | logfmt [$__range])) by (event_name))"
    }
   ]
  }
 ]
}