{
 "title": "User Drilldown",
 "tags": [
  "Frontend",
  "OTEL",
  "Faro",
  "Tempo"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "user",
    "label": "User",
    "query": {}
   },
   {
    "name": "session_id",
    "label": "Session ID",
    "query": {}
   },
   {
    "name": "stt",
    "label": "STT",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Sessions",
   "type": "gauge",
   "description": "Number of sessions for a user given the time range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count(count_over_time({service_name=\"tdp-frontend-rum\", user_name=~\"$user\"}[$__range])) by (session_id))"
    }
   ]
  },
  {
   "title": "Top 5 Views",
   "type": "bargauge",
   "description": "Displays the top 5 most visited page based on the user and session ID",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, count(count_over_time({user_name =~ \"$user\", session_id =~ \"$session_id\"} | logfmt [$__range])) by (page_url))"
    }
   ]
  },
  {
   "title": "Browsers by Use",
   "type": "table",
   "description": "Shows the top 10 browsers used grouped by version and browser name",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({user_name=~\"$user\"} | logfmt [$__range])))"
    }
   ]
  },
  {
   "title": "User Journey",
   "type": "table",
   "description": "Displays all traces associated to the user based on the session",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "456e201b", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "metricsQueryType": "range",
     "query": "{name != \"GET /prometheus/metrics\"} && {name != \"GET prometheus/metrics\"} && {span.user.name =~ \"$user\" && span.session.id =~ \"$session_id\"}",
     "spss": 94,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"tdp-frontend-rum\", user_name=~\"$user\", session_id=~\"$session_id\"} | logfmt"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"tdp-frontend-rum\", user_name=~\"$user\", session_id=~\"$session_id\"}"
    }
   ]
  },
  {
   "title": "All Collected Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"tdp-frontend-rum\", user_name=~\"$user\", session_id=~\"$session_id\"} | logfmt"
    }
   ]
  }
 ]
}