{
 "title": "User Telemetry",
 "description": "Telemetry information for users based on the FaroSDK",
 "tags": [
  "Frontend",
  "OTEL",
  "Faro",
  "Tempo",
  "Users"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": {}
   },
   {
    "name": "session_id",
    "label": "Session ID",
    "query": {}
   },
   {
    "name": "stt",
    "label": "STT",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Errors",
   "type": "stat",
   "description": "Number of exceptions the user has encountered over the time range",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({kind=\"exception\", user_name=~\"$user\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Top URLs by Errors",
   "type": "table",
   "description": "Top 5 URLs the user has encountered errors on",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count(count_over_time({kind=\"exception\", user_name=~\"$user\"} | logfmt [$__range])) by (page_url))"
    }
   ]
  },
  {
   "title": "Top Errors",
   "type": "table",
   "description": "Top 10 errors encountered",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count(count_over_time({kind=\"exception\", user_name=~\"$user\"} | logfmt [$__range])) by (value))"
    }
   ]
  },
  { "title": "Session Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Sessions Over Time",
   "type": "gauge",
   "description": "Number of sessions for a user given the time range",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count(count_over_time({service_name=\"tdp-frontend-rum\", user_name=~\"$user\"}[$__range])) by (session_id))"
    }
   ]
  },
  {
   "title": "Browsers by Use",
   "type": "table",
   "description": "Shows the top 10 browsers used grouped by version and browser name",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, count by (browser_name, browser_version) (count_over_time({user_name=~\"$user\"} | logfmt [$__range])))"
    }
   ]
  },
  {
   "title": "Top 5 Views",
   "type": "bargauge",
   "description": "Displays the top 5 most visited page based on the user and session ID",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, count(count_over_time({user_name =~ \"$user\", session_id =~ \"$session_id\"} | logfmt [$__range])) by (page_url))"
    }
   ]
  },
  { "title": "User Journey", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "User Journey",
   "type": "table",
   "description": "Displays all traces associated to the user based on the session",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "filters": [
      { "id": "456e201b", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "metricsQueryType": "range",
     "query": "{name != \"GET /prometheus/metrics\"} && {name != \"GET prometheus/metrics\"} && {span.user.name =~ \"$user\" && span.session.id =~ \"$session_id\"}",
     "spss": 94,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"tdp-frontend-rum\", user_name=~\"$user\", session_id=~\"$session_id\"}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"tdp-frontend-rum\", user_name=~\"$user\", session_id=~\"$session_id\"} | logfmt"
      }
     ]
    },
    {
     "title": "All Collected Metrics",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{service_name=\"tdp-frontend-rum\", user_name=~\"$user\", session_id=~\"$session_id\"} | logfmt"
      }
     ]
    }
   ]
  }
 ]
}