// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getSTTs = `-- name: GetSTTs :many
SELECT id, type, postal_code, name, region_id, state_id, filenames, stt_code, ssp, sample, timezone FROM stts_stt
`

func (q *Queries) GetSTTs(ctx context.Context) ([]SttsStt, error) {
	rows, err := q.db.Query(ctx, getSTTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SttsStt
	for rows.Next() {
		var i SttsStt
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PostalCode,
			&i.Name,
			&i.RegionID,
			&i.StateID,
			&i.Filenames,
			&i.SttCode,
			&i.Ssp,
			&i.Sample,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSearchIndexesSSPM1 = `-- name: GetSearchIndexesSSPM1 :many
SELECT "RecordType", "RPT_MONTH_YEAR", "CASE_NUMBER", "FIPS_CODE", "COUNTY_FIPS_CODE", "STRATUM", "ZIP_CODE", "DISPOSITION", "NBR_FAMILY_MEMBERS", "FAMILY_TYPE", "TANF_ASST_IN_6MONTHS", "RECEIVES_SUB_HOUSING", "RECEIVES_MED_ASSISTANCE", "RECEIVES_FOOD_STAMPS", "AMT_FOOD_STAMP_ASSISTANCE", "RECEIVES_SUB_CC", "AMT_SUB_CC", "CHILD_SUPPORT_AMT", "FAMILY_CASH_RESOURCES", "CASH_AMOUNT", "NBR_MONTHS", "CC_AMOUNT", "CHILDREN_COVERED", "CC_NBR_MONTHS", "TRANSP_AMOUNT", "TRANSP_NBR_MONTHS", "TRANSITION_SERVICES_AMOUNT", "TRANSITION_NBR_MONTHS", "OTHER_AMOUNT", "OTHER_NBR_MONTHS", "SANC_REDUCTION_AMT", "WORK_REQ_SANCTION", "FAMILY_SANC_ADULT", "SANC_TEEN_PARENT", "NON_COOPERATION_CSE", "FAILURE_TO_COMPLY", "OTHER_SANCTION", "RECOUPMENT_PRIOR_OVRPMT", "OTHER_TOTAL_REDUCTIONS", "FAMILY_CAP", "REDUCTIONS_ON_RECEIPTS", "OTHER_NON_SANCTION", "WAIVER_EVAL_CONTROL_GRPS", id, datafile_id, line_number FROM search_indexes_ssp_m1
`

func (q *Queries) GetSearchIndexesSSPM1(ctx context.Context) ([]SearchIndexesSspM1, error) {
	rows, err := q.db.Query(ctx, getSearchIndexesSSPM1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchIndexesSspM1
	for rows.Next() {
		var i SearchIndexesSspM1
		if err := rows.Scan(
			&i.RecordType,
			&i.RPTMONTHYEAR,
			&i.CASENUMBER,
			&i.FIPSCODE,
			&i.COUNTYFIPSCODE,
			&i.STRATUM,
			&i.ZIPCODE,
			&i.DISPOSITION,
			&i.NBRFAMILYMEMBERS,
			&i.FAMILYTYPE,
			&i.TANFASSTIN6MONTHS,
			&i.RECEIVESSUBHOUSING,
			&i.RECEIVESMEDASSISTANCE,
			&i.RECEIVESFOODSTAMPS,
			&i.AMTFOODSTAMPASSISTANCE,
			&i.RECEIVESSUBCC,
			&i.AMTSUBCC,
			&i.CHILDSUPPORTAMT,
			&i.FAMILYCASHRESOURCES,
			&i.CASHAMOUNT,
			&i.NBRMONTHS,
			&i.CCAMOUNT,
			&i.CHILDRENCOVERED,
			&i.CCNBRMONTHS,
			&i.TRANSPAMOUNT,
			&i.TRANSPNBRMONTHS,
			&i.TRANSITIONSERVICESAMOUNT,
			&i.TRANSITIONNBRMONTHS,
			&i.OTHERAMOUNT,
			&i.OTHERNBRMONTHS,
			&i.SANCREDUCTIONAMT,
			&i.WORKREQSANCTION,
			&i.FAMILYSANCADULT,
			&i.SANCTEENPARENT,
			&i.NONCOOPERATIONCSE,
			&i.FAILURETOCOMPLY,
			&i.OTHERSANCTION,
			&i.RECOUPMENTPRIOROVRPMT,
			&i.OTHERTOTALREDUCTIONS,
			&i.FAMILYCAP,
			&i.REDUCTIONSONRECEIPTS,
			&i.OTHERNONSANCTION,
			&i.WAIVEREVALCONTROLGRPS,
			&i.ID,
			&i.DatafileID,
			&i.LineNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
