// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureDataFileSummary = `-- name: EnsureDataFileSummary :exec
INSERT INTO shadow_parsers_datafilesummary (
    status, datafile_id, case_aggregates, total_number_of_records_in_file,
    total_number_of_records_created, error_report
)
VALUES ('Pending', $1, NULL, 0, 0, NULL)
ON CONFLICT (datafile_id) DO UPDATE SET
    status = EXCLUDED.status,
    case_aggregates = EXCLUDED.case_aggregates,
    total_number_of_records_in_file = EXCLUDED.total_number_of_records_in_file,
    total_number_of_records_created = EXCLUDED.total_number_of_records_created,
    error_report = EXCLUDED.error_report
`

func (q *Queries) EnsureDataFileSummary(ctx context.Context, datafileID int32) error {
	_, err := q.db.Exec(ctx, ensureDataFileSummary, datafileID)
	return err
}

const ensureProductionDataFile = `-- name: EnsureProductionDataFile :exec
INSERT INTO data_files_datafile (
    id, original_filename, slug, extension, quarter, year, section, version,
    stt_id, user_id, created_at, file, s3_versioning_id, program_type,
    is_program_audit, state
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15,
    $16
)
ON CONFLICT (id) DO UPDATE SET
    original_filename = EXCLUDED.original_filename,
    slug = EXCLUDED.slug,
    extension = EXCLUDED.extension,
    quarter = EXCLUDED.quarter,
    year = EXCLUDED.year,
    section = EXCLUDED.section,
    version = EXCLUDED.version,
    stt_id = EXCLUDED.stt_id,
    user_id = EXCLUDED.user_id,
    created_at = EXCLUDED.created_at,
    file = EXCLUDED.file,
    s3_versioning_id = EXCLUDED.s3_versioning_id,
    program_type = EXCLUDED.program_type,
    is_program_audit = EXCLUDED.is_program_audit,
    state = EXCLUDED.state
`

type EnsureProductionDataFileParams struct {
	ID               int32
	OriginalFilename string
	Slug             string
	Extension        string
	Quarter          string
	Year             int32
	Section          string
	Version          int32
	SttID            int32
	UserID           pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	File             pgtype.Text
	S3VersioningID   pgtype.Text
	ProgramType      string
	IsProgramAudit   bool
	State            string
}

func (q *Queries) EnsureProductionDataFile(ctx context.Context, arg EnsureProductionDataFileParams) error {
	_, err := q.db.Exec(ctx, ensureProductionDataFile,
		arg.ID,
		arg.OriginalFilename,
		arg.Slug,
		arg.Extension,
		arg.Quarter,
		arg.Year,
		arg.Section,
		arg.Version,
		arg.SttID,
		arg.UserID,
		arg.CreatedAt,
		arg.File,
		arg.S3VersioningID,
		arg.ProgramType,
		arg.IsProgramAudit,
		arg.State,
	)
	return err
}

const ensureProductionDataFileSummary = `-- name: EnsureProductionDataFileSummary :exec
INSERT INTO parsers_datafilesummary (
    status, datafile_id, case_aggregates, total_number_of_records_in_file,
    total_number_of_records_created, error_report
)
VALUES ('Pending', $1, NULL, 0, 0, NULL)
ON CONFLICT (datafile_id) DO UPDATE SET
    status = EXCLUDED.status,
    case_aggregates = EXCLUDED.case_aggregates,
    total_number_of_records_in_file = EXCLUDED.total_number_of_records_in_file,
    total_number_of_records_created = EXCLUDED.total_number_of_records_created,
    error_report = EXCLUDED.error_report
`

func (q *Queries) EnsureProductionDataFileSummary(ctx context.Context, datafileID int32) error {
	_, err := q.db.Exec(ctx, ensureProductionDataFileSummary, datafileID)
	return err
}

const ensureShadowDataFile = `-- name: EnsureShadowDataFile :exec
INSERT INTO shadow_data_files_datafile (
    id, original_filename, slug, extension, quarter, year, section, version,
    stt_id, user_id, created_at, file, s3_versioning_id, program_type,
    is_program_audit, state
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15,
    $16
)
ON CONFLICT (id) DO UPDATE SET
    original_filename = EXCLUDED.original_filename,
    slug = EXCLUDED.slug,
    extension = EXCLUDED.extension,
    quarter = EXCLUDED.quarter,
    year = EXCLUDED.year,
    section = EXCLUDED.section,
    version = EXCLUDED.version,
    stt_id = EXCLUDED.stt_id,
    user_id = EXCLUDED.user_id,
    created_at = EXCLUDED.created_at,
    file = EXCLUDED.file,
    s3_versioning_id = EXCLUDED.s3_versioning_id,
    program_type = EXCLUDED.program_type,
    is_program_audit = EXCLUDED.is_program_audit,
    state = EXCLUDED.state
`

type EnsureShadowDataFileParams struct {
	ID               int32
	OriginalFilename string
	Slug             string
	Extension        string
	Quarter          string
	Year             int32
	Section          string
	Version          int32
	SttID            int32
	UserID           pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	File             pgtype.Text
	S3VersioningID   pgtype.Text
	ProgramType      string
	IsProgramAudit   bool
	State            string
}

func (q *Queries) EnsureShadowDataFile(ctx context.Context, arg EnsureShadowDataFileParams) error {
	_, err := q.db.Exec(ctx, ensureShadowDataFile,
		arg.ID,
		arg.OriginalFilename,
		arg.Slug,
		arg.Extension,
		arg.Quarter,
		arg.Year,
		arg.Section,
		arg.Version,
		arg.SttID,
		arg.UserID,
		arg.CreatedAt,
		arg.File,
		arg.S3VersioningID,
		arg.ProgramType,
		arg.IsProgramAudit,
		arg.State,
	)
	return err
}

const getDataFile = `-- name: GetDataFile :one
SELECT id, original_filename, slug, extension, quarter, year, section, version,
       stt_id, user_id, created_at, file, s3_versioning_id, program_type,
       is_program_audit, state
FROM shadow_data_files_datafile
WHERE id = $1
`

func (q *Queries) GetDataFile(ctx context.Context, id int32) (ShadowDataFilesDatafile, error) {
	row := q.db.QueryRow(ctx, getDataFile, id)
	var i ShadowDataFilesDatafile
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.Slug,
		&i.Extension,
		&i.Quarter,
		&i.Year,
		&i.Section,
		&i.Version,
		&i.SttID,
		&i.UserID,
		&i.CreatedAt,
		&i.File,
		&i.S3VersioningID,
		&i.ProgramType,
		&i.IsProgramAudit,
		&i.State,
	)
	return i, err
}

const getProductionDataFile = `-- name: GetProductionDataFile :one
SELECT id, original_filename, slug, extension, quarter, year, section, version,
       stt_id, user_id, created_at, file, s3_versioning_id, program_type,
       is_program_audit, state
FROM data_files_datafile
WHERE id = $1
`

func (q *Queries) GetProductionDataFile(ctx context.Context, id int32) (DataFilesDatafile, error) {
	row := q.db.QueryRow(ctx, getProductionDataFile, id)
	var i DataFilesDatafile
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.Slug,
		&i.Extension,
		&i.Quarter,
		&i.Year,
		&i.Section,
		&i.Version,
		&i.SttID,
		&i.UserID,
		&i.CreatedAt,
		&i.File,
		&i.S3VersioningID,
		&i.ProgramType,
		&i.IsProgramAudit,
		&i.State,
	)
	return i, err
}

const getSTTs = `-- name: GetSTTs :many
SELECT id, type, postal_code, name, region_id, state_id, filenames, stt_code, ssp, sample, timezone FROM stts_stt
`

func (q *Queries) GetSTTs(ctx context.Context) ([]SttsStt, error) {
	rows, err := q.db.Query(ctx, getSTTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SttsStt
	for rows.Next() {
		var i SttsStt
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PostalCode,
			&i.Name,
			&i.RegionID,
			&i.StateID,
			&i.Filenames,
			&i.SttCode,
			&i.Ssp,
			&i.Sample,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSearchIndexesSSPM1 = `-- name: GetSearchIndexesSSPM1 :many
SELECT "RecordType", "RPT_MONTH_YEAR", "CASE_NUMBER", "FIPS_CODE", "COUNTY_FIPS_CODE", "STRATUM", "ZIP_CODE", "DISPOSITION", "NBR_FAMILY_MEMBERS", "FAMILY_TYPE", "TANF_ASST_IN_6MONTHS", "RECEIVES_SUB_HOUSING", "RECEIVES_MED_ASSISTANCE", "RECEIVES_FOOD_STAMPS", "AMT_FOOD_STAMP_ASSISTANCE", "RECEIVES_SUB_CC", "AMT_SUB_CC", "CHILD_SUPPORT_AMT", "FAMILY_CASH_RESOURCES", "CASH_AMOUNT", "NBR_MONTHS", "CC_AMOUNT", "CHILDREN_COVERED", "CC_NBR_MONTHS", "TRANSP_AMOUNT", "TRANSP_NBR_MONTHS", "TRANSITION_SERVICES_AMOUNT", "TRANSITION_NBR_MONTHS", "OTHER_AMOUNT", "OTHER_NBR_MONTHS", "SANC_REDUCTION_AMT", "WORK_REQ_SANCTION", "FAMILY_SANC_ADULT", "SANC_TEEN_PARENT", "NON_COOPERATION_CSE", "FAILURE_TO_COMPLY", "OTHER_SANCTION", "RECOUPMENT_PRIOR_OVRPMT", "OTHER_TOTAL_REDUCTIONS", "FAMILY_CAP", "REDUCTIONS_ON_RECEIPTS", "OTHER_NON_SANCTION", "WAIVER_EVAL_CONTROL_GRPS", id, datafile_id, line_number FROM shadow_search_indexes_ssp_m1
`

func (q *Queries) GetSearchIndexesSSPM1(ctx context.Context) ([]ShadowSearchIndexesSspM1, error) {
	rows, err := q.db.Query(ctx, getSearchIndexesSSPM1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShadowSearchIndexesSspM1
	for rows.Next() {
		var i ShadowSearchIndexesSspM1
		if err := rows.Scan(
			&i.RecordType,
			&i.RPTMONTHYEAR,
			&i.CASENUMBER,
			&i.FIPSCODE,
			&i.COUNTYFIPSCODE,
			&i.STRATUM,
			&i.ZIPCODE,
			&i.DISPOSITION,
			&i.NBRFAMILYMEMBERS,
			&i.FAMILYTYPE,
			&i.TANFASSTIN6MONTHS,
			&i.RECEIVESSUBHOUSING,
			&i.RECEIVESMEDASSISTANCE,
			&i.RECEIVESFOODSTAMPS,
			&i.AMTFOODSTAMPASSISTANCE,
			&i.RECEIVESSUBCC,
			&i.AMTSUBCC,
			&i.CHILDSUPPORTAMT,
			&i.FAMILYCASHRESOURCES,
			&i.CASHAMOUNT,
			&i.NBRMONTHS,
			&i.CCAMOUNT,
			&i.CHILDRENCOVERED,
			&i.CCNBRMONTHS,
			&i.TRANSPAMOUNT,
			&i.TRANSPNBRMONTHS,
			&i.TRANSITIONSERVICESAMOUNT,
			&i.TRANSITIONNBRMONTHS,
			&i.OTHERAMOUNT,
			&i.OTHERNBRMONTHS,
			&i.SANCREDUCTIONAMT,
			&i.WORKREQSANCTION,
			&i.FAMILYSANCADULT,
			&i.SANCTEENPARENT,
			&i.NONCOOPERATIONCSE,
			&i.FAILURETOCOMPLY,
			&i.OTHERSANCTION,
			&i.RECOUPMENTPRIOROVRPMT,
			&i.OTHERTOTALREDUCTIONS,
			&i.FAMILYCAP,
			&i.REDUCTIONSONRECEIPTS,
			&i.OTHERNONSANCTION,
			&i.WAIVEREVALCONTROLGRPS,
			&i.ID,
			&i.DatafileID,
			&i.LineNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataFileState = `-- name: UpdateDataFileState :exec
UPDATE shadow_data_files_datafile
SET state = $1
WHERE id = $2
`

type UpdateDataFileStateParams struct {
	State string
	ID    int32
}

func (q *Queries) UpdateDataFileState(ctx context.Context, arg UpdateDataFileStateParams) error {
	_, err := q.db.Exec(ctx, updateDataFileState, arg.State, arg.ID)
	return err
}

const updateDataFileSummaryResult = `-- name: UpdateDataFileSummaryResult :exec
UPDATE shadow_parsers_datafilesummary
SET total_number_of_records_in_file = $1,
    total_number_of_records_created = $2
WHERE datafile_id = $3
`

type UpdateDataFileSummaryResultParams struct {
	TotalNumberOfRecordsInFile  pgtype.Int4
	TotalNumberOfRecordsCreated pgtype.Int4
	DatafileID                  int32
}

func (q *Queries) UpdateDataFileSummaryResult(ctx context.Context, arg UpdateDataFileSummaryResultParams) error {
	_, err := q.db.Exec(ctx, updateDataFileSummaryResult, arg.TotalNumberOfRecordsInFile, arg.TotalNumberOfRecordsCreated, arg.DatafileID)
	return err
}

const updateDataFileSummaryStatus = `-- name: UpdateDataFileSummaryStatus :exec
UPDATE shadow_parsers_datafilesummary
SET status = $1
WHERE datafile_id = $2
`

type UpdateDataFileSummaryStatusParams struct {
	Status     string
	DatafileID int32
}

func (q *Queries) UpdateDataFileSummaryStatus(ctx context.Context, arg UpdateDataFileSummaryStatusParams) error {
	_, err := q.db.Exec(ctx, updateDataFileSummaryStatus, arg.Status, arg.DatafileID)
	return err
}

const updateProductionDataFileState = `-- name: UpdateProductionDataFileState :exec
UPDATE data_files_datafile
SET state = $1
WHERE id = $2
`

type UpdateProductionDataFileStateParams struct {
	State string
	ID    int32
}

func (q *Queries) UpdateProductionDataFileState(ctx context.Context, arg UpdateProductionDataFileStateParams) error {
	_, err := q.db.Exec(ctx, updateProductionDataFileState, arg.State, arg.ID)
	return err
}

const updateProductionDataFileSummaryResult = `-- name: UpdateProductionDataFileSummaryResult :exec
UPDATE parsers_datafilesummary
SET total_number_of_records_in_file = $1,
    total_number_of_records_created = $2
WHERE datafile_id = $3
`

type UpdateProductionDataFileSummaryResultParams struct {
	TotalNumberOfRecordsInFile  pgtype.Int4
	TotalNumberOfRecordsCreated pgtype.Int4
	DatafileID                  int32
}

func (q *Queries) UpdateProductionDataFileSummaryResult(ctx context.Context, arg UpdateProductionDataFileSummaryResultParams) error {
	_, err := q.db.Exec(ctx, updateProductionDataFileSummaryResult, arg.TotalNumberOfRecordsInFile, arg.TotalNumberOfRecordsCreated, arg.DatafileID)
	return err
}

const updateProductionDataFileSummaryStatus = `-- name: UpdateProductionDataFileSummaryStatus :exec
UPDATE parsers_datafilesummary
SET status = $1
WHERE datafile_id = $2
`

type UpdateProductionDataFileSummaryStatusParams struct {
	Status     string
	DatafileID int32
}

func (q *Queries) UpdateProductionDataFileSummaryStatus(ctx context.Context, arg UpdateProductionDataFileSummaryStatusParams) error {
	_, err := q.db.Exec(ctx, updateProductionDataFileSummaryStatus, arg.Status, arg.DatafileID)
	return err
}
