apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: {{ prometheus_url }}
    jsonData:
      httpMethod: POST
    isDefault: false
    uid: "PBFA97CFB590B2093"
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  - name: Loki
    type: loki
    access: proxy
    url: {{ loki_url }}
    jsonData:
      maxLines: 1000
    isDefault: false
    uid: "L8E80F9AEF21F6940"
