apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
    secureJsonFields: {}
    version: 2
    readOnly: true
    basicAuth: false
    basicAuthUser: ""
    withCredentials: false
    isDefault: true
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  - name: Loki
    type: loki
    access: proxy
    url: "http://loki:3100"
    editable: false
    jsonData:
      maxLines: 1000
