apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
    isDefault: false
    uid: "PBFA97CFB590B2093"
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  - name: Loki
    type: loki
    access: proxy
    url: "http://loki:3100"
    jsonData:
      maxLines: 1000
    isDefault: false
    uid: "L8E80F9AEF21F6940"
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: "http://alertmanager:9093/alerts"
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    basicAuth: false
    basicAuthUser: 
    basicAuthPassword: 
