apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
    isDefault: false
    uid: "MQFA97CFB590B2099"
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
    isDefault: false
    uid: "PQFA97CFB590B2099"
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  - name: Loki
    type: loki
    access: proxy
    url: "http://loki:3100"
    jsonData:
      maxLines: 1000
    isDefault: false
    uid: "L8E80F9AEF21F6940"
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      search:
        filters:
          - id: service-name
            operator: =
            scope: resource
            tag: service.name
          - id: span-name
            operator: =
            scope: span
            tag: name
      serviceMap:
        datasourceUid: "MQFA97CFB590B2099"
      tracesToLogsV2:
        customQuery: false
        datasourceUid: "L8E80F9AEF21F6940"
      tracesToMetrics:
        datasourceUid: "MQFA97CFB590B2099"
    isDefault: false
    uid: "celzqpsk6u2v4b"
    typeLogoUrl: "public/app/plugins/datasource/tempo/img/tempo_logo.svg"