apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
      httpMethod: POST
    isDefault: false
    uid: "PQFA97CFB590B2099"
    typeLogoUrl: "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg"
  - name: Loki
    type: loki
    access: proxy
    url: "http://loki:3100"
    jsonData:
      maxLines: 1000
    isDefault: false
    uid: "L8E80F9AEF21F6940"
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: "http://alertmanager:9093/alerts"
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
