# Local version of Docker compose, using the localdev docker build target
# instead and additionally mounts node_modules for faster builds
services:
  tdp-frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        REGISTRY_OWNER: ${REGISTRY_OWNER:-hhs}
      target: localdev
    command: sh -c "corepack prepare yarn@4.6.0 && HOST=0.0.0.0 corepack yarn start"
    ports:
      - 3000:80
    environment:
      - REACT_APP_BACKEND_HOST=http://localhost:8989
      - REACT_APP_BACKEND_URL=http://localhost:8989/v1
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    networks:
      - local

  tdp-frontend-test:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      args:
        REGISTRY_OWNER: ${REGISTRY_OWNER:-hhs}
      target: localdev
    command: sleep infinity
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    networks:
      - local
networks:
  local:
    driver: bridge
