# Local version of Docker compose, using the localdev docker build target
# instead and additionally mounts node_modules for faster builds
version: "3.4"

services:
  tdp-frontend:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      target: localdev
    command: npm run start
    ports:
      - 3000:80
    volumes:
      - ./:/home/node/app
    networks:
      - local
networks:
  local:
    driver: bridge
