# Generated by Django 3.1.1 on 2020-10-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalPermission",
            fields=[],
            options={
                "verbose_name": "global_permission",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.permission",),
        ),
    ]
