# Generated by Django 3.1.2 on 2020-10-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = []
