# Generated by Codex on 2026-08-18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0006_historicalgroup_historicalgroup_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.TextField()),
                ("event_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("note", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, max_length=64, null=True)),
                ("task_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="baselog",
            index=models.Index(
                fields=["content_type", "object_id", "-created_at"],
                name="baselog_object_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselog",
            index=models.Index(
                fields=["event_id", "-created_at"],
                name="baselog_event_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselog",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="baselog_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="baselog",
            index=models.Index(fields=["source"], name="baselog_source_idx"),
        ),
        migrations.AddIndex(
            model_name="baselog",
            index=models.Index(fields=["task_name"], name="baselog_task_name_idx"),
        ),
    ]
