# Generated by Django 5.2.14 on 2026-08-19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_baselog"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="rollout_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "Required for rollout percentage flags; leave blank for on/off "
                    "flags."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="type",
            field=models.CharField(
                choices=[
                    ("on_off", "On/off"),
                    ("random_rollout", "Random rollout"),
                ],
                default="on_off",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalfeatureflag",
            name="rollout_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "Required for rollout percentage flags; leave blank for on/off "
                    "flags."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalfeatureflag",
            name="type",
            field=models.CharField(
                choices=[
                    ("on_off", "On/off"),
                    ("random_rollout", "Random rollout"),
                ],
                default="on_off",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("rollout_percentage__isnull", True))
                    | models.Q(
                        ("rollout_percentage__gte", 0),
                        ("rollout_percentage__lte", 100),
                    )
                ),
                name="feature_flag_rollout_percentage_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="featureflag",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(("type__in", ["on_off", "random_rollout"]))
                    | models.Q(("rollout_percentage__isnull", True), ("type", "on_off"))
                    | models.Q(
                        ("rollout_percentage__isnull", False),
                        ("type", "random_rollout"),
                    )
                ),
                name="feature_flag_type_configuration",
            ),
        ),
    ]
