# %% [markdown]
#
# # PART 1 : CREATING TAN
#
# The first part of this project is to create the dataframe tan&ym (where &ym represents the year and month that the data was collected). This dataframe will be used in subsequent steps to create weighted and unweighted TANF reports, as well as time-limit reports.
#
# Of particular interest is the Work Participation Rate (WPR), which is a measure of each state's TANF recipients participation in the workforce. Significant parts of this script involve determining which adults can be included in the WPR.
#
# The base requirement for an adult to be included in the WPR is at least 20 hours of "core" work per week AND at least 30 hours of total ("core" plus "non-core") work per week for a single person. In families with at least two parents, these threshholds change to 50 hours of "core" work and 55 hours of total work for both parents combined. In certain circumstances (which are noted in the code below), these requirements can be lowered, which allows more adults to qualify for work participation.
#
# Additionally, there are certain conditions where we can "deem" hours for those who don't meet these requirements so they can be included in the WPR despite not meeting the hour threshhold. There are three ways to "deem" hours:
# 1. We can add CSWE hours to a family's "core" hours if they are in an FLSA state and [financial condition]
# 2. For teen parents in two-parent families, we are able to deem hours if they have satisfactory school attendance, or
# 3. For teen parents in two-parent families, we can also deem hours if they are enrolled in education directly related to employment.

# %%
-------------------------------
-- Step 1: Declare variables --
-------------------------------

-- this is the variable used to filter the dataframes to the current month --
DECLARE OR REPLACE ym INT DEFAULT 202408;

-- this is the name of the final TAN dataframe that's printed at the end of this report (ex: tan202408 for the table created with August 2024 data) --
DECLARE OR REPLACE tan_table_name STRING DEFAULT CONCAT('ofa_sandbox.legacy_code.tan', ym);

-- potentially define list of states and territories to iterate over --


# %%
-----------------------------------
-- Step 2: Create family dataset --
-----------------------------------

CREATE OR REPLACE TEMPORARY VIEW family AS
SELECT
	AMT_FOOD_STAMP_ASSISTANCE,
	CASE_NUMBER as CASE_ID,
	CC_AMOUNT,
	CHILD_SUPPORT_AMT,
	-- COUNTY_FIPS_CODE,
	DISPOSITION,
	FAMILY_EXEMPT_TIME_LIMITS,
	FAMILY_TYPE,
	FIPS_CODE,
	FUNDING_STREAM,
	NEW_APPLICANT,
	OTHER_AMOUNT,
	RECEIVES_SUB_CC,
	AMT_SUB_CC,
	REGION,
	RPT_MONTH_YEAR,
	SANC_REDUCTION_AMT,
	STRATUM,
	STT,
	TRANSITION_SERVICES_AMOUNT,
	TRANSP_AMOUNT,
	WORK_REQ_SANCTION,
	CASH_AMOUNT,
	ZIP_CODE,
	CASE
		WHEN FIPS_CODE IN (2,5,9,30,40,46,55,56,66) THEN 0
		ELSE 1
	END AS FLSA_STATE, -- *
  -- Minimum wage (found on the DOL's website) is used for calculations to deem hours later
  CASE
    WHEN FIPS_CODE = 54 THEN 8.75
    WHEN FIPS_CODE = 30 THEN 10.55
    WHEN FIPS_CODE = 26 THEN 10.56
    WHEN FIPS_CODE = 39 THEN 10.70
    WHEN FIPS_CODE = 5 THEN 11.00
    WHEN FIPS_CODE = 27 THEN 11.13
    WHEN FIPS_CODE = 46 THEN 11.50
    WHEN FIPS_CODE IN (32,35) THEN 12.00
    WHEN FIPS_CODE = 2 THEN 11.91
    WHEN FIPS_CODE = 51 THEN 12.41
    WHEN FIPS_CODE = 12 THEN 13.00
    WHEN FIPS_CODE = 31 THEN 13.50
    WHEN FIPS_CODE = 29 THEN 13.75
    WHEN FIPS_CODE = 15 THEN 14.00
    WHEN FIPS_CODE = 50 THEN 14.01
    WHEN FIPS_CODE = 23 THEN 14.65
    WHEN FIPS_CODE IN (4,41) THEN 14.70
    WHEN FIPS_CODE = 8 THEN 14.81
    WHEN FIPS_CODE IN (10,17,24,25,44) THEN 15.00
    WHEN FIPS_CODE = 34 THEN 15.49
    WHEN FIPS_CODE = 36 THEN 15.50
    WHEN FIPS_CODE = 9 THEN 16.35
    WHEN FIPS_CODE = 6 THEN 16.50
    WHEN FIPS_CODE = 53 THEN 16.66
    WHEN FIPS_CODE = 11 THEN 17.50
    ELSE 7.25
	END AS MIN_WAGES --*
FROM
	read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T1_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	)
WHERE
	RPT_MONTH_YEAR = ym;

# %%
----------------------------------
-- Step 3: Create adult dataset --
----------------------------------

CREATE OR REPLACE TEMPORARY VIEW adult1 AS
SELECT
  FED_OASDI_PROGRAM,
  AID_AGED_BLIND as AID_AGED_BLIND,
  DISABLED_TITLE_XIVAPDT,
  CASE_NUMBER as CASE_ID,
  CAST(COMM_SERVICES_HOP as FLOAT) as COMM_SERVICES_HOP,
  CAST(COMM_SERVICES_HOL as FLOAT) AS COMM_SERVICES_HOL,
  CAST(COMM_SERVICES_EA as FLOAT) AS COMM_SERVICES_EA,
  AGE_FIRST as AGE,
  CITIZENSHIP_STATUS,
  DEEMED_HOURS_FOR_OVERALL as NCORHRS,
  DEEMED_HOURS_FOR_TWO_PARENT as TPCORHRS,
  CURRENT_MONTH_STATE_EXEMPT,
  EARNED_INCOME,
  CAST(ED_NO_HIGH_SCHOOL_DIPL_HOP as FLOAT) AS ED_NO_HIGH_SCHOOL_DIPL_HOP,
  CAST(ED_NO_HIGH_SCHOOL_DIPL_HOL as FLOAT) AS ED_NO_HIGH_SCHOOL_DIPL_HOL,
  CAST(ED_NO_HIGH_SCHOOL_DIPL_EA as FLOAT) AS ED_NO_HIGH_SCHOOL_DIPL_EA,
  FAMILY_AFFILIATION,
  FIPS_CODE,
  CAST(JOB_SEARCH_HOP as FLOAT) AS JOB_SEARCH_HOP,
  CAST(JOB_SEARCH_HOL as FLOAT) AS JOB_SEARCH_HOL,
  CAST(JOB_SEARCH_EA as FLOAT) AS JOB_SEARCH_EA,
  CAST(JOB_SKILLS_TRAINING_HOP as FLOAT) AS JOB_SKILLS_TRAINING_HOP,
  CAST(JOB_SKILLS_TRAINING_HOL as FLOAT) AS JOB_SKILLS_TRAINING_HOL,
  CAST(JOB_SKILLS_TRAINING_EA as FLOAT) AS JOB_SKILLS_TRAINING_EA,
  MONTHS_FED_TIME_LIMIT,
  MARITAL_STATUS,
  NONCUSTODIAL_PARENT,
  CAST(OJT as FLOAT) as OJT,
  CAST(OTHER_WORK_ACTIVITIES as FLOAT) AS OTHER_WORK_ACTIVITIES,
  PARENT_MINOR_CHILD as PARENT,
  CAST(PROVIDE_CC_HOP as FLOAT) AS PROVIDE_CC_HOP,
  CAST(PROVIDE_CC_HOL as FLOAT) AS PROVIDE_CC_HOL,
  CAST(PROVIDE_CC_EA as FLOAT) AS PROVIDE_CC_EA,
  RELATIONSHIP_HOH,
  RECEIVE_SSI as RECEIVE_SSI,
  RPT_MONTH_YEAR,
  CAST(SCHOOL_ATTENDENCE_HOP as FLOAT) AS SCHOOL_ATTENDENCE_HOP,
  CAST(SCHOOL_ATTENDENCE_HOL as FLOAT) AS SCHOOL_ATTENDENCE_HOL,
  CAST(SCHOOL_ATTENDENCE_EA as FLOAT) AS SCHOOL_ATTENDENCE_EA,
  CAST(SUB_PRIVATE_EMPLOYMENT as FLOAT) AS SUB_PRIVATE_EMPLOYMENT,
  CAST(SUB_PUBLIC_EMPLOYMENT as FLOAT) AS SUB_PUBLIC_EMPLOYMENT,
  CAST(UNEARNED_SSI as FLOAT) AS UNEARNED_SSI,
  CAST(UNSUB_EMPLOYMENT as FLOAT) AS UNSUB_EMPLOYMENT,
  CAST(VOCATIONAL_ED_TRAINING_HOP as FLOAT) AS VOCATIONAL_ED_TRAINING_HOP,
  CAST(VOCATIONAL_ED_TRAINING_HOL as FLOAT) AS VOCATIONAL_ED_TRAINING_HOL,
  CAST(VOCATIONAL_ED_TRAINING_EA as FLOAT) AS VOCATIONAL_ED_TRAINING_EA,
  WORK_ELIGIBLE_INDICATOR as WEI,
  CAST(WORK_EXPERIENCE_HOP as FLOAT) AS WORK_EXPERIENCE_HOP,
  CAST(WORK_EXPERIENCE_HOL as FLOAT) AS WORK_EXPERIENCE_HOL,
  CAST(WORK_EXPERIENCE_EA as FLOAT) AS WORK_EXPERIENCE_EA,
  WORK_PART_STATUS as WORK_PART_STATUS,
  -- Check if an adult is an WEI (Work Eligible Indicator), which is a prerequiste for being included in the WPR --
  CASE
    WHEN WORK_ELIGIBLE_INDICATOR IN (1,2,3,4,5) THEN 1
    WHEN WORK_ELIGIBLE_INDICATOR = 6 AND FAMILY_AFFILIATION IN (1,2) THEN 1
    WHEN WORK_ELIGIBLE_INDICATOR = 7 AND FAMILY_AFFILIATION IN (1,2) AND CITIZENSHIP_STATUS = 1 THEN 1
    WHEN WORK_ELIGIBLE_INDICATOR = 8 AND FIPS_CODE < 66 AND ((RECEIVE_SSI != 1) AND (FED_OASDI_PROGRAM != 1) AND (AID_AGED_BLIND != 1)) THEN 1
    ELSE 0
  END AS ISWEI
FROM
	read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T2_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	)
WHERE
	RPT_MONTH_YEAR = ym AND
	FAMILY_AFFILIATION IN (1,2) AND
  AGE_FIRST NOT IN (NULL, 0, 99999999);

CREATE OR REPLACE TEMPORARY VIEW adult2 AS
SELECT
  *,
  -- If an adult is an WEI, calculate the following variables --
  -- Holiday hours (which cap at 6) --
  CASE
    WHEN ISWEI = 0 THEN 0
    WHEN WORK_EXPERIENCE_HOL + JOB_SEARCH_HOL + COMM_SERVICES_HOL + VOCATIONAL_ED_TRAINING_HOL + PROVIDE_CC_HOL > 6 THEN 6
    ELSE WORK_EXPERIENCE_HOL + JOB_SEARCH_HOL + COMM_SERVICES_HOL + VOCATIONAL_ED_TRAINING_HOL + PROVIDE_CC_HOL
  END AS SUM_CORE_HOLI,
  CASE
    WHEN ISWEI = 0 THEN 0
    WHEN JOB_SKILLS_TRAINING_HOL + ED_NO_HIGH_SCHOOL_DIPL_HOL + SCHOOL_ATTENDENCE_HOL > 6 THEN 6
    ELSE JOB_SKILLS_TRAINING_HOL + ED_NO_HIGH_SCHOOL_DIPL_HOL + SCHOOL_ATTENDENCE_HOL
  END AS SUM_NON_CORE_HOLI,
  CASE
    WHEN ISWEI = 0 THEN 0
    WHEN WORK_EXPERIENCE_HOL + COMM_SERVICES_HOL > 6 THEN 6
    ELSE WORK_EXPERIENCE_HOL + COMM_SERVICES_HOL
  END AS SUM_CSWE_HOLI,
  -- Exab hours (which cap at 4) --
  CASE
    WHEN ISWEI = 0 THEN 0
    WHEN WORK_EXPERIENCE_EA + JOB_SEARCH_EA + COMM_SERVICES_EA + VOCATIONAL_ED_TRAINING_EA + PROVIDE_CC_EA > 4 THEN 4
    ELSE WORK_EXPERIENCE_EA + JOB_SEARCH_EA + COMM_SERVICES_EA + VOCATIONAL_ED_TRAINING_EA + PROVIDE_CC_EA
  END AS SUM_CORE_EXAB,
  CASE
    WHEN ISWEI = 0 THEN 0
    WHEN JOB_SKILLS_TRAINING_EA + ED_NO_HIGH_SCHOOL_DIPL_EA + SCHOOL_ATTENDENCE_EA > 4 THEN 4
    ELSE JOB_SKILLS_TRAINING_EA + ED_NO_HIGH_SCHOOL_DIPL_EA + SCHOOL_ATTENDENCE_EA
  END AS SUM_NON_CORE_EXAB,
  CASE
    WHEN ISWEI = 0 THEN 0
    WHEN WORK_EXPERIENCE_EA + COMM_SERVICES_EA > 4 THEN 4
    ELSE WORK_EXPERIENCE_EA + COMM_SERVICES_EA
  END AS SUM_CSWE_EXAB,
  -- These WEI variables determine if a person counts as a WEI using different types of hours (work, holiday, or exab)
  CASE
    WHEN (UNSUB_EMPLOYMENT + SUB_PRIVATE_EMPLOYMENT + SUB_PUBLIC_EMPLOYMENT + WORK_EXPERIENCE_HOP + OJT + JOB_SEARCH_HOP + COMM_SERVICES_HOP + VOCATIONAL_ED_TRAINING_HOP + JOB_SKILLS_TRAINING_HOP + ED_NO_HIGH_SCHOOL_DIPL_HOP + SCHOOL_ATTENDENCE_HOP + PROVIDE_CC_HOP + OTHER_WORK_ACTIVITIES) > 0 THEN 1
    ELSE 0
  END AS WRK_WEI,
  CASE
    WHEN (WORK_EXPERIENCE_HOL + JOB_SEARCH_HOL + COMM_SERVICES_HOL + VOCATIONAL_ED_TRAINING_HOL + JOB_SKILLS_TRAINING_HOL + ED_NO_HIGH_SCHOOL_DIPL_HOL + SCHOOL_ATTENDENCE_HOL + PROVIDE_CC_HOL) > 0 THEN 1
    ELSE 0
  END AS HOL_WEI,
  CASE
    WHEN (WORK_EXPERIENCE_EA + JOB_SEARCH_EA + COMM_SERVICES_EA + VOCATIONAL_ED_TRAINING_EA + JOB_SKILLS_TRAINING_EA + ED_NO_HIGH_SCHOOL_DIPL_EA + SCHOOL_ATTENDENCE_EA + PROVIDE_CC_EA) > 0 THEN 1
    ELSE 0
  END AS EXA_WEI,
  -- NDISABLE means a person is disabled and is used for error flags later --
  CASE
    WHEN (RECEIVE_SSI = 1 AND UNEARNED_SSI > 0) OR AID_AGED_BLIND = 1 OR FED_OASDI_PROGRAM = 1 THEN 1
    ELSE 0
  END AS NDISABLE
FROM
  adult1;

CREATE OR REPLACE TEMPORARY VIEW adult AS
SELECT
  *,
  CASE
    WHEN (WRK_WEI = 1) OR (HOL_WEI = 1) OR (EXA_WEI = 1) THEN 1
    ELSE 0
  END AS WKHLEA_WEI,
  -- Hours worked --
  WORK_EXPERIENCE_HOP + COMM_SERVICES_HOP + SUM_CSWE_HOLI + SUM_CSWE_EXAB as CSWE_HRS_1,
  UNSUB_EMPLOYMENT + SUB_PRIVATE_EMPLOYMENT + SUB_PUBLIC_EMPLOYMENT + WORK_EXPERIENCE_HOP + OJT + JOB_SEARCH_HOP + COMM_SERVICES_HOP + VOCATIONAL_ED_TRAINING_HOP + PROVIDE_CC_HOP + SUM_CORE_HOLI + SUM_CORE_EXAB as HRS_WRK_1,
  -- Other hours worked --
  JOB_SKILLS_TRAINING_HOP + ED_NO_HIGH_SCHOOL_DIPL_HOP + SCHOOL_ATTENDENCE_HOP + SUM_NON_CORE_HOLI + SUM_NON_CORE_EXAB as OHRS_WRK_1,
  -- Total hours worked --
  UNSUB_EMPLOYMENT + SUB_PRIVATE_EMPLOYMENT + SUB_PUBLIC_EMPLOYMENT + WORK_EXPERIENCE_HOP + OJT + JOB_SEARCH_HOP + COMM_SERVICES_HOP + VOCATIONAL_ED_TRAINING_HOP + PROVIDE_CC_HOP + SUM_CORE_HOLI + SUM_CORE_EXAB + JOB_SKILLS_TRAINING_HOP + ED_NO_HIGH_SCHOOL_DIPL_HOP + SCHOOL_ATTENDENCE_HOP + SUM_NON_CORE_HOLI + SUM_NON_CORE_EXAB as THRS_WRK_1
FROM
  adult2;


# %%
----------------------------------
-- Step 4: Create child dataset --
----------------------------------

-- the child dataset is used to determine the youngest child in each family --

CREATE OR REPLACE TEMPORARY VIEW child AS
SELECT
	FIPS_CODE,
	MIN(AGE_FIRST) as YOUNGEST,
	CASE_NUMBER as CASE_ID,
	RPT_MONTH_YEAR
FROM
	read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T3_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	)
WHERE
	RPT_MONTH_YEAR = ym
GROUP BY
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_NUMBER;

# %%
--------------------------------------------------------------------
-- Step 5: Merge the FAMILY, ADULT, and CHILD dataframes into one --
--------------------------------------------------------------------

-- Each adult is an observation in this dataframe, which is later summarized for each family (determined by a unique CASE_ID) --

CREATE OR REPLACE TEMPORARY VIEW a1 AS
SELECT
	adult.FED_OASDI_PROGRAM,
	adult.AID_AGED_BLIND,
	adult.DISABLED_TITLE_XIVAPDT,
	adult.CASE_ID,
	adult.COMM_SERVICES_HOP,
	adult.COMM_SERVICES_HOL,
	adult.COMM_SERVICES_EA,
	adult.AGE,
	adult.CITIZENSHIP_STATUS,
	adult.ED_NO_HIGH_SCHOOL_DIPL_HOP,
	adult.ED_NO_HIGH_SCHOOL_DIPL_HOL,
	adult.ED_NO_HIGH_SCHOOL_DIPL_EA,
	adult.FAMILY_AFFILIATION,
	adult.FIPS_CODE,
	adult.JOB_SEARCH_HOP,
	adult.JOB_SEARCH_HOL,
	adult.JOB_SEARCH_EA,
	adult.JOB_SKILLS_TRAINING_HOP,
	adult.JOB_SKILLS_TRAINING_HOL,
	adult.JOB_SKILLS_TRAINING_EA,
	adult.MARITAL_STATUS,
	adult.NONCUSTODIAL_PARENT,
	adult.OJT,
	adult.OTHER_WORK_ACTIVITIES,
	adult.PARENT,
	adult.PROVIDE_CC_HOP,
	adult.PROVIDE_CC_HOL,
	adult.PROVIDE_CC_EA,
	adult.RELATIONSHIP_HOH,
	adult.RECEIVE_SSI,
	adult.RPT_MONTH_YEAR,
	adult.SCHOOL_ATTENDENCE_HOP,
	adult.SCHOOL_ATTENDENCE_HOL,
	adult.SCHOOL_ATTENDENCE_EA,
	adult.SUB_PRIVATE_EMPLOYMENT,
	adult.SUB_PUBLIC_EMPLOYMENT,
	adult.UNEARNED_SSI,
	adult.UNSUB_EMPLOYMENT,
	adult.VOCATIONAL_ED_TRAINING_HOP,
	adult.VOCATIONAL_ED_TRAINING_HOL,
	adult.VOCATIONAL_ED_TRAINING_EA,
	adult.WEI,
	adult.WORK_EXPERIENCE_HOP,
	adult.WORK_EXPERIENCE_HOL,
	adult.WORK_EXPERIENCE_EA,
	adult.WORK_PART_STATUS,
	adult.ISWEI,
	adult.SUM_CORE_HOLI,
	adult.SUM_CORE_EXAB,
	adult.SUM_NON_CORE_HOLI,
	adult.SUM_NON_CORE_EXAB,
	adult.SUM_CSWE_HOLI,
	adult.SUM_CSWE_EXAB,
	adult.WRK_WEI,
	adult.HOL_WEI,
	adult.EXA_WEI,
	adult.NDISABLE,
	adult.WKHLEA_WEI,
	adult.CSWE_HRS_1,
	adult.HRS_WRK_1,
	adult.OHRS_WRK_1,
	adult.THRS_WRK_1,
	adult.EARNED_INCOME,
	family.STRATUM,
	family.AMT_FOOD_STAMP_ASSISTANCE,
	family.CC_AMOUNT,
	family.CHILD_SUPPORT_AMT,
	family.DISPOSITION,
	family.FAMILY_TYPE,
	family.OTHER_AMOUNT,
	family.RECEIVES_SUB_CC,
	family.AMT_SUB_CC,
	family.SANC_REDUCTION_AMT,
	family.TRANSITION_SERVICES_AMOUNT,
	family.TRANSP_AMOUNT,
	family.WORK_REQ_SANCTION,
	family.CASH_AMOUNT,
	family.ZIP_CODE,
	family.FLSA_STATE,
	family.MIN_WAGES,
  child.YOUNGEST,
	-- NDEEMCOR is used to determine if a participant can have their hours deemed later if their hours are initially too low to count for the WPR --
	CASE
		WHEN ISWEI = 1 AND HRS_WRK_1 < 20 AND FLSA_STATE = 1 AND CSWE_HRS_1 > 0 AND CSWE_HRS_1 >= FLOOR((CASH_AMOUNT + CC_AMOUNT + OTHER_AMOUNT + TRANSITION_SERVICES_AMOUNT + TRANSP_AMOUNT + AMT_FOOD_STAMP_ASSISTANCE - CHILD_SUPPORT_AMT)/(5*MIN_WAGES)) THEN 1
		ELSE 0
	END AS NDEEMCOR
FROM
	ofa_sandbox.legacy_code.adult AS adult
	LEFT JOIN ofa_sandbox.legacy_code.child AS child
		ON adult.FIPS_CODE = child.FIPS_CODE AND adult.CASE_ID = child.CASE_ID
	LEFT JOIN ofa_sandbox.legacy_code.family AS family
		ON adult.FIPS_CODE = family.FIPS_CODE AND adult.CASE_ID = family.CASE_ID
WHERE
	DISPOSITION = 1;


# %%
-----------------------------------------------------------------
-- Step 6: Determine AF-related variables and calculate HOLDER --
-----------------------------------------------------------------

CREATE OR REPLACE TEMPORARY VIEW a2 AS
SELECT
	*,
	CASE
		-- NWORK_ND means to meet the work requirement without deeming hours --
		WHEN ISWEI = 1 AND HRS_WRK_1 >= 20 AND THRS_WRK_1 >= 30 THEN 1
		ELSE 0
	END AS NWORK_ND,
	-- HWK_VOC and TWK_VOC mean ________________
	CASE
		WHEN ISWEI = 1 AND HRS_WRK_1 >= 20 AND THRS_WRK_1 >= 30 THEN HRS_WRK_1 - VOCATIONAL_ED_TRAINING_HOP - PROVIDE_CC_HOL - PROVIDE_CC_EA
		ELSE 0
	END AS HWK_VOC,
	CASE
		WHEN ISWEI = 1 AND HRS_WRK_1 >= 20 AND THRS_WRK_1 >= 30 THEN THRS_WRK_1 - VOCATIONAL_ED_TRAINING_HOP - PROVIDE_CC_HOL - PROVIDE_CC_EA
		ELSE 0
	END AS TWK_VOC,
	-- AF_NCORHRS is used later to deem hours if necassary, if CSWE hours are high enough --
  CASE
		WHEN ISWEI = 1 AND HRS_WRK_1 < 20 AND FLSA_STATE = 1 AND CSWE_HRS_1 > 0 AND CSWE_HRS_1 >= FLOOR((CASH_AMOUNT + CC_AMOUNT + OTHER_AMOUNT + TRANSITION_SERVICES_AMOUNT + TRANSP_AMOUNT + AMT_FOOD_STAMP_ASSISTANCE - CHILD_SUPPORT_AMT)/(5*MIN_WAGES)) THEN 20 - CSWE_HRS_1
		ELSE 0
	END AS AF_NCORHRS
FROM
  a1;


CREATE OR REPLACE TEMPORARY VIEW a3 AS
SELECT
	*,
	-- HRS_WRK_D_CSWE is core hours worked, with DEEMED hours from CSWE
	CASE
		WHEN ISWEI = 1 AND HRS_WRK_1 < 20 AND FLSA_STATE = 1 AND CSWE_HRS_1 > 0 AND CSWE_HRS_1 >= FLOOR((CASH_AMOUNT + CC_AMOUNT + OTHER_AMOUNT + TRANSITION_SERVICES_AMOUNT + TRANSP_AMOUNT + AMT_FOOD_STAMP_ASSISTANCE - CHILD_SUPPORT_AMT)/(5*MIN_WAGES)) THEN HRS_WRK_1 + AF_NCORHRS
		ELSE 0
	END AS HRS_WRK_D_CSWE,
	-- THRS_WRK_D_CSWE is total hours work, which is core and non-core hours together, with DEEMED hours from CSWE
	CASE
		WHEN ISWEI = 1 AND HRS_WRK_1 < 20 AND FLSA_STATE = 1 AND CSWE_HRS_1 > 0 AND CSWE_HRS_1 >= FLOOR((CASH_AMOUNT + CC_AMOUNT + OTHER_AMOUNT + TRANSITION_SERVICES_AMOUNT + TRANSP_AMOUNT + AMT_FOOD_STAMP_ASSISTANCE - CHILD_SUPPORT_AMT)/(5*MIN_WAGES)) THEN THRS_WRK_1 + AF_NCORHRS
		ELSE 0
	END AS THRS_WRK_D_CSWE
FROM
  a2;

CREATE OR REPLACE TEMPORARY VIEW a4 AS
SELECT
	*,
	-- NWORK_D_CSWE means a person met the work requirement, but only by deeming CSWE hours --
	CASE
		WHEN ISWEI = 1 AND HRS_WRK_D_CSWE >= 20 AND THRS_WRK_D_CSWE >= 30 AND NDEEMCOR = 1 THEN 1
		ELSE 0
	END AS NWORK_D_CSWE,
	-- DCOR_PART is just used for tracking purposes. It represents if a person is deemed to participate and included in the WPR calculations --
	CASE
		WHEN ISWEI = 1 AND HRS_WRK_D_CSWE >= 20 AND THRS_WRK_D_CSWE >= 30 AND NDEEMCOR = 1 THEN 1
		ELSE 0
	END AS DCOR_PART
FROM
	a3;

CREATE OR REPLACE TEMPORARY VIEW a5 AS
SELECT
	*,
  -- NEXEMPT is not used in the rest of this script
	CASE
		WHEN ISWEI = 1 AND WORK_PART_STATUS >= 6 AND WORK_PART_STATUS <= 11 THEN 1
		ELSE 0
	END AS NEXEMPT,
  -- NDEEM15 means ____________________
	CASE
		WHEN ISWEI = 1 AND WORK_PART_STATUS = 15 AND AGE > 12 AND AGE < 20 AND RELATIONSHIP_HOH IN (1,2) AND (SCHOOL_ATTENDENCE_HOP + SCHOOL_ATTENDENCE_EA + SCHOOL_ATTENDENCE_HOL) > 0 THEN 1
		ELSE 0
	END AS NDEEM15,
  -- NDEEM16 means ____________________
	CASE
		WHEN ISWEI = 1 AND AGE > 12 AND AGE < 20 AND RELATIONSHIP_HOH IN (1,2) AND (ED_NO_HIGH_SCHOOL_DIPL_HOP + ED_NO_HIGH_SCHOOL_DIPL_EA + ED_NO_HIGH_SCHOOL_DIPL_HOL) >= 20 THEN 1
		ELSE 0
	END AS NDEEM16,
  -- NDEEM17 means ____________________
  CASE
		WHEN ISWEI = 1 AND WORK_PART_STATUS = 17 AND YOUNGEST >= 0 AND YOUNGEST <= 6 AND (HRS_WRK_1 >= 20 OR HRS_WRK_D_CSWE >= 20) THEN 1
		ELSE 0
	END AS NDEEM17,
  -- NLIM_SSA is not used in the rest of this script
	CASE
		WHEN ISWEI = 1 AND WORK_PART_STATUS = 15 AND AGE > 12 AND AGE < 20 AND RELATIONSHIP_HOH IN (1,2) AND (SCHOOL_ATTENDENCE_HOP + SCHOOL_ATTENDENCE_EA + SCHOOL_ATTENDENCE_HOL) > 0 THEN 1
		ELSE 0
	END AS NLIM_SSA,
  -- NLIM_EDE is not used in the rest of this script
	CASE
		WHEN ISWEI = 1 AND AGE > 12 AND AGE < 20 AND RELATIONSHIP_HOH IN (1,2) AND (ED_NO_HIGH_SCHOOL_DIPL_HOP + ED_NO_HIGH_SCHOOL_DIPL_EA + ED_NO_HIGH_SCHOOL_DIPL_HOL) >= 20 THEN 1
		ELSE 0
	END AS NLIM_EDE
FROM
    a4;

CREATE OR REPLACE TEMPORARY VIEW a6 AS
SELECT
	*,
	-- NWORK_D_WPS means that a person can be included in the WPR, but only for specific conditions, which are described in the above step (NDEEM15, NDEEM16, or NDEEM17)
	CASE
		WHEN (NDEEM15 = 1 OR NDEEM16 = 1 OR NDEEM17 = 1) AND NWORK_ND = 0 AND NWORK_D_CSWE = 0 THEN 1
		ELSE 0
	END AS NWORK_D_WPS
FROM
	a5;

CREATE OR REPLACE TEMPORARY VIEW a7 AS
SELECT
	*,
	-- NLIM_VOC represents if a person's vocational education is less than or equal to 30% of their total hours. This is used to help calculate HOLDER --
	CASE
		WHEN HWK_VOC > 0 AND HWK_VOC < 20 THEN 1
		WHEN ((NWORK_ND = 1) OR (NWORK_D_CSWE = 1) OR (NWORK_D_WPS = 1)) AND (HRS_WRK_1 + AF_NCORHRS - VOCATIONAL_ED_TRAINING_HOP - VOCATIONAL_ED_TRAINING_HOL - VOCATIONAL_ED_TRAINING_EA) > 0 AND (HRS_WRK_1 + AF_NCORHRS - VOCATIONAL_ED_TRAINING_HOP - VOCATIONAL_ED_TRAINING_HOL - VOCATIONAL_ED_TRAINING_EA) < 20 THEN 1
		-- Account for when HRS_WRK_1 has deemed hours --
		WHEN ((NWORK_ND = 1) OR (NWORK_D_CSWE = 1) OR (NWORK_D_WPS = 1)) AND (HRS_WRK_D_CSWE + AF_NCORHRS - VOCATIONAL_ED_TRAINING_HOP - VOCATIONAL_ED_TRAINING_HOL - VOCATIONAL_ED_TRAINING_EA) > 0 AND (HRS_WRK_D_CSWE + AF_NCORHRS - VOCATIONAL_ED_TRAINING_HOP - VOCATIONAL_ED_TRAINING_HOL - VOCATIONAL_ED_TRAINING_EA) < 20 THEN 1
		ELSE 0
	END AS NLIM_VOC,
  -- NDVEXEM (domestic violence exemption) is used to help calculate HOLDER --
	CASE
		WHEN ((NWORK_ND = 0) AND (NWORK_D_CSWE = 0) AND (NWORK_D_WPS = 0)) AND WORK_PART_STATUS = 9 THEN 1
		ELSE 0
	END AS NDVEXEM,
  --NDCARD1, NDCARD2, NDCARD5 mean that work requirement was met, but they are being discarded later --
	CASE
		-- the following conditions after NWORK = 1 are NDCARD1, NDCARD2, and NDCARD5 respectively --
		-- NDCARD1, NDCARD2, NDCARD5 are reset after NDCRD_PART becomes 1 --
		WHEN ((NWORK_ND = 1) OR (NWORK_D_CSWE = 1) OR (NWORK_D_WPS = 1)) AND ((WORK_PART_STATUS = 1 AND (YOUNGEST >= 0 AND YOUNGEST <= 1) AND PARENT = 2) OR (WORK_PART_STATUS = 2 AND FAMILY_AFFILIATION IN (1,2) AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0 AND (WEI >= 1 AND WEI <= 5)) OR (WORK_PART_STATUS = 5)) THEN 0
		WHEN WORK_PART_STATUS = 1 AND (YOUNGEST >= 0 AND YOUNGEST <= 1) AND PARENT = 2 THEN 1
		ELSE 0
	END AS NDCARD1,
	CASE
		-- the following conditions after NWORK = 1 are NDCARD1, NDCARD2, and NDCARD5 respectively --
		-- NDCARD1, NDCARD2, NDCARD5 are reset after NDCRD_PART becomes 1 --
		WHEN ((NWORK_ND = 1) OR (NWORK_D_CSWE = 1) OR (NWORK_D_WPS = 1)) AND ((WORK_PART_STATUS = 1 AND (YOUNGEST >= 0 AND YOUNGEST <= 1) AND PARENT = 2)  OR (WORK_PART_STATUS = 2 AND FAMILY_AFFILIATION IN (1,2) AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0 AND (WEI >= 1 AND WEI <= 5)) OR (WORK_PART_STATUS = 5)) THEN 0
		WHEN WORK_PART_STATUS = 2 AND FAMILY_AFFILIATION IN (1,2) AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0 AND (WEI >= 1 AND WEI <= 5) THEN 1
		ELSE 0
	END AS NDCARD2,
	CASE
		-- the following conditions after NWORK = 1 are NDCARD1, NDCARD2, and NDCARD5 respectively --
		-- NDCARD1, NDCARD2, NDCARD5 are reset after NDCRD_PART becomes 1 --
		WHEN ((NWORK_ND = 1) OR (NWORK_D_CSWE = 1) OR (NWORK_D_WPS = 1)) AND ((WORK_PART_STATUS = 1 AND (YOUNGEST >= 0 AND YOUNGEST <= 1) AND PARENT = 2) OR (WORK_PART_STATUS = 2 AND FAMILY_AFFILIATION IN (1,2) AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0 AND (WEI >= 1 AND WEI <= 5)) OR (WORK_PART_STATUS = 5)) THEN 0
		WHEN WORK_PART_STATUS = 5 THEN 1
		ELSE 0
	END AS NDCARD5,
	CASE
		WHEN (NWORK_ND = 1) OR (NWORK_D_CSWE = 1) OR (NWORK_D_WPS = 1) THEN 1
		ELSE 0
	END AS NWORK
FROM
	a6;

CREATE OR REPLACE TEMPORARY VIEW a8 AS
SELECT
	*,
	CASE
		-- the following conditions after NWORK = 1 are NDCARD1, NDCARD2, and NDCARD5 respectively --
		WHEN (NWORK = 1) AND ((WORK_PART_STATUS = 1 AND (YOUNGEST >= 0 AND YOUNGEST <= 1) AND PARENT = 2) OR (WORK_PART_STATUS = 2 AND FAMILY_AFFILIATION IN (1,2) AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0 AND (WEI >= 1 AND WEI <= 5)) OR (WORK_PART_STATUS = 5)) THEN 1
		ELSE 0
	END AS NDCRD_PART,
  -- HOLDER is used to determine the adults included in a family. The two adults with the highest holder values are counted as the parents of a family --
	-- If an adult is not a WEI, HOLDER is set to NULL to match the SAS results. It might be better to remove all non-WEIs from the dataset at an earlier point instead later, after the QC process iS finalized --
	CASE
		WHEN ISWEI != 1 THEN NULL
		ELSE (1000 * NWORK) + 100 * (NDCARD1 + NDCARD2 * 2 + NDCARD5 * 5) - 10 * NLIM_VOC - NDVEXEM
	END AS HOLDER
FROM
	a7;

# %%
-- DECLARE OR REPLACE tan_table_name STRING DEFAULT CONCAT('ofa_sandbox.legacy_code.tan', ym);

CREATE OR REPLACE TABLE ofa_sandbox.legacy_code.tan_test AS
SELECT
  *
FROM
  a8;


--CREATE OR REPLACE TABLE IDENTIFIER(tan_table_name) AS
--SELECT
-- 	final_af.*,
-- 	final_2p.* EXCEPT (FIPS_CODE, CASE_ID, FAMILY_TYPE, FTYPE, IS2P, N_WEI, YOUNGEST, NDISABLE, NDCARD2, NDCRD_PART, NSAMP)
--FROM
-- 	final_af FULL JOIN
-- 	final_2p
--    ON final_af.FIPS_CODE = final_2p.FIPS_CODE AND final_af.CASE_ID = final_2p.CASE_ID;

# %%
------------------------------------------------------------
-- Step 7: Create summary statistics for combined dataset --
------------------------------------------------------------

CREATE OR REPLACE TEMPORARY VIEW a9 AS
SELECT
  FIPS_CODE,
  CASE_ID,
	SUM(ISWEI) AS N_WEI,
	SUM(WRK_WEI) AS N_WRK_WEI,
	SUM(HOL_WEI) AS N_HOL_WEI,
	SUM(EXA_WEI) AS N_EXA_WEI,
	SUM(WKHLEA_WEI) AS N_WKHLEA_WEI,
	SUM(NWORK) AS NGAGED,
  SUM(CASE WHEN UNSUB_EMPLOYMENT = 0 THEN 1 ELSE 0 END) AS TPER_UNSUB_EMPLOYMENT,
  SUM(CASE WHEN SUB_PRIVATE_EMPLOYMENT = 0 THEN 1 ELSE 0 END) AS TPER_SUB_PRIVATE_EMPLOYMENT,
  SUM(CASE WHEN SUB_PUBLIC_EMPLOYMENT = 0 THEN 1 ELSE 0 END) AS TPER_SUB_PUBLIC_EMPLOYMENT,
	SUM(CASE WHEN WORK_EXPERIENCE_HOP = 0 THEN 1 ELSE 0 END) AS TPER_WORK_EXPERIENCE_HOP,
	SUM(CASE WHEN OJT = 0 THEN 1 ELSE 0 END) AS TPER_OJT,
	SUM(CASE WHEN JOB_SEARCH_HOP = 0 THEN 1 ELSE 0 END) AS TPER_JOB_SEARCH_HOP,
	SUM(CASE WHEN COMM_SERVICES_HOP = 0 THEN 1 ELSE 0 END) AS TPER_COMM_SERVICES_HOP,
	SUM(CASE WHEN VOCATIONAL_ED_TRAINING_HOP = 0 THEN 1 ELSE 0 END) AS TPER_VOCATIONAL_ED_TRAINING_HOP,
	SUM(CASE WHEN JOB_SKILLS_TRAINING_HOP = 0 THEN 1 ELSE 0 END) AS TPER_JOB_SKILLS_TRAINING_HOP,
	SUM(CASE WHEN ED_NO_HIGH_SCHOOL_DIPL_HOP = 0 THEN 1 ELSE 0 END) AS TPER_ED_NO_HIGH_SCHOOL_DIPL_HOP,
	SUM(CASE WHEN SCHOOL_ATTENDENCE_HOP = 0 THEN 1 ELSE 0 END) AS TPER_SCHOOL_ATTENDENCE_HOP,
	SUM(CASE WHEN OTHER_WORK_ACTIVITIES = 0 THEN 1 ELSE 0 END) AS TPER_OTHER_WORK_ACTIVITIES,
	SUM(CASE WHEN PROVIDE_CC_HOP = 0 THEN 1 ELSE 0 END) AS TPER_PROVIDE_CC_HOP,
	SUM(UNSUB_EMPLOYMENT) AS THRS_UNSUB_EMPLOYMENT,
	SUM(SUB_PRIVATE_EMPLOYMENT) AS THRS_SUB_PRIVATE_EMPLOYMENT,
	SUM(SUB_PUBLIC_EMPLOYMENT) AS THRS_SUB_PUBLIC_EMPLOYMENT,
	SUM(WORK_EXPERIENCE_HOP) AS THRS_WORK_EXPERIENCE_HOP,
	SUM(OJT) AS THRS_OJT,
	SUM(JOB_SEARCH_HOP) AS THRS_JOB_SEARCH_HOP,
	SUM(COMM_SERVICES_HOP) AS THRS_COMM_SERVICES_HOP,
	SUM(VOCATIONAL_ED_TRAINING_HOP) AS THRS_VOCATIONAL_ED_TRAINING_HOP,
	SUM(JOB_SKILLS_TRAINING_HOP) AS THRS_JOB_SKILLS_TRAINING_HOP,
	SUM(ED_NO_HIGH_SCHOOL_DIPL_HOP) AS THRS_ED_NO_HIGH_SCHOOL_DIPL_HOP,
	SUM(SCHOOL_ATTENDENCE_HOP) AS THRS_SCHOOL_ATTENDENCE_HOP,
	SUM(PROVIDE_CC_HOP) AS THRS_PROVIDE_CC_HOP,
	SUM(OTHER_WORK_ACTIVITIES) AS THRS_OTHER_WORK_ACTIVITIES,
	SUM(CASE WHEN WORK_EXPERIENCE_EA = 0 THEN 1 ELSE 0 END) AS TPER_WORK_EXPERIENCE_EA,
	SUM(CASE WHEN JOB_SEARCH_EA = 0 THEN 1 ELSE 0 END) AS TPER_JOB_SEARCH_EA,
	SUM(CASE WHEN COMM_SERVICES_EA = 0 THEN 1 ELSE 0 END) AS TPER_COMM_SERVICES_EA,
	SUM(CASE WHEN VOCATIONAL_ED_TRAINING_EA = 0 THEN 1 ELSE 0 END) AS TPER_VOCATIONAL_ED_TRAINING_EA,
	SUM(CASE WHEN JOB_SKILLS_TRAINING_EA = 0 THEN 1 ELSE 0 END) AS TPER_JOB_SKILLS_TRAINING_EA,
	SUM(CASE WHEN ED_NO_HIGH_SCHOOL_DIPL_EA = 0 THEN 1 ELSE 0 END) AS TPER_ED_NO_HIGH_SCHOOL_DIPL_EA,
	SUM(CASE WHEN SCHOOL_ATTENDENCE_EA = 0 THEN 1 ELSE 0 END) AS TPER_SCHOOL_ATTENDENCE_EA,
	SUM(CASE WHEN PROVIDE_CC_EA = 0 THEN 1 ELSE 0 END) AS TPER_PROVIDE_CC_EA,
	SUM(WORK_EXPERIENCE_EA) AS THRS_WORK_EXPERIENCE_EA,
	SUM(JOB_SEARCH_EA) AS THRS_JOB_SEARCH_EA,
	SUM(COMM_SERVICES_EA) AS THRS_COMM_SERVICES_EA,
	SUM(VOCATIONAL_ED_TRAINING_EA) AS THRS_VOCATIONAL_ED_TRAINING_EA,
	SUM(JOB_SKILLS_TRAINING_EA) AS THRS_JOB_SKILLS_TRAINING_EA,
	SUM(ED_NO_HIGH_SCHOOL_DIPL_EA) AS THRS_ED_NO_HIGH_SCHOOL_DIPL_EA,
	SUM(SCHOOL_ATTENDENCE_EA) AS THRS_SCHOOL_ATTENDENCE_EA,
	SUM(PROVIDE_CC_EA) AS THRS_PROVIDE_CC_EA,
	SUM(CASE WHEN WORK_EXPERIENCE_HOL = 0 THEN 1 ELSE 0 END) AS TPER_WORK_EXPERIENCE_HOL,
	SUM(CASE WHEN JOB_SEARCH_HOL = 0 THEN 1 ELSE 0 END) AS TPER_JOB_SEARCH_HOL,
	SUM(CASE WHEN COMM_SERVICES_HOL = 0 THEN 1 ELSE 0 END) AS TPER_COMM_SERVICES_HOL,
	SUM(CASE WHEN VOCATIONAL_ED_TRAINING_HOL = 0 THEN 1 ELSE 0 END) AS TPER_VOCATIONAL_ED_TRAINING_HOL,
	SUM(CASE WHEN JOB_SKILLS_TRAINING_HOL = 0 THEN 1 ELSE 0 END) AS TPER_JOB_SKILLS_TRAINING_HOL,
	SUM(CASE WHEN ED_NO_HIGH_SCHOOL_DIPL_HOL = 0 THEN 1 ELSE 0 END) AS TPER_ED_NO_HIGH_SCHOOL_DIPL_HOL,
	SUM(CASE WHEN SCHOOL_ATTENDENCE_HOL = 0 THEN 1 ELSE 0 END) AS TPER_SCHOOL_ATTENDENCE_HOL,
	SUM(CASE WHEN PROVIDE_CC_HOL = 0 THEN 1 ELSE 0 END) AS TPER_PROVIDE_CC_HOL,
	SUM(WORK_EXPERIENCE_HOL) AS THRS_WORK_EXPERIENCE_HOL,
	SUM(JOB_SEARCH_HOL) AS THRS_JOB_SEARCH_HOL,
	SUM(COMM_SERVICES_HOL) AS THRS_COMM_SERVICES_HOL,
	SUM(VOCATIONAL_ED_TRAINING_HOL) AS THRS_VOCATIONAL_ED_TRAINING_HOL,
	SUM(JOB_SKILLS_TRAINING_HOL) AS THRS_JOB_SKILLS_TRAINING_HOL,
	SUM(ED_NO_HIGH_SCHOOL_DIPL_HOL) AS THRS_ED_NO_HIGH_SCHOOL_DIPL_HOL,
	SUM(SCHOOL_ATTENDENCE_HOL) AS THRS_SCHOOL_ATTENDENCE_HOL,
	SUM(PROVIDE_CC_HOL) AS THRS_PROVIDE_CC_HOL
FROM
	a8
GROUP BY
  FIPS_CODE,
  CASE_ID;

CREATE OR REPLACE TEMPORARY VIEW a10 AS
SELECT
	a8.*,
	a9.* EXCEPT (FIPS_CODE, CASE_ID),
	CASE
		WHEN ISWEI = 1 AND PARENT = 1 THEN 1
		ELSE 0
	END AS IS2P
FROM
	a8
	LEFT JOIN a9
	ON a8.FIPS_CODE = a9.FIPS_CODE and a8.CASE_ID = a9.CASE_ID;

CREATE OR REPLACE TEMPORARY VIEW a11 AS
SELECT
	*,
	-- There are three family types (FTYPE)
	CASE
		-- Only 1 WEI --
		WHEN (N_WEI >= 1 AND IS2P = 0) OR (N_WEI = 1 AND IS2P = 1) THEN 1
		-- 2-parent family with more than 1 WEI --
		WHEN (N_WEI >= 2 AND IS2P = 1) THEN 2
		-- All other families --
		ELSE 3
	END AS FTYPE,
	CASE
		WHEN ((N_WEI >= 1 AND IS2P = 0) OR (N_WEI = 1 AND IS2P = 1)) OR ((N_WEI >= 2 AND IS2P = 1)) THEN 0
		ELSE 1
	END AS NSAMP_NO
FROM
     a10;


# %%
--------------------------------------------------------------------------
-- Step 8: Create data frame for the main primary earner of each family --
--------------------------------------------------------------------------

-- The person in each family with the largest HOLDER value is the AF --

CREATE OR REPLACE TEMPORARY VIEW pf_af AS
WITH CTA AS (
SELECT
	*, ROW_NUMBER() OVER (PARTITION BY CASE_ID ORDER BY HOLDER DESC, RELATIONSHIP_HOH DESC) AS ROWNUM
    FROM
    	a11
)
SELECT *
FROM CTA
ORDER BY
	HOLDER DESC;

-- This step only return rows with the first row number, which is the parent with the largest HOLDER value --
-- simultaneously, each variable is renamed to be AF specific --

CREATE OR REPLACE TEMPORARY VIEW final_af1 AS
SELECT
	CASE_ID,
	RPT_MONTH_YEAR,
	--COUNTY,
	STRATUM,
	ZIP_CODE,
	HOLDER,
	FTYPE,
	FAMILY_TYPE,
	N_WEI,
	IS2P,
	YOUNGEST,
	FIPS_CODE,
	NDISABLE,
	NDCARD1,
	NDCARD2,
	NDCARD5,
	NLIM_VOC,
	NDVEXEM,
	NDCRD_PART,
	NSAMP_NO,
	--NCORHRS,
	--TPCORHRS,
	WRK_WEI,
	HOL_WEI,
	EXA_WEI,
	WKHLEA_WEI,
	--SUM_CORE_HOLI,
	--SUM_CORE_EXAB,
	--SUM_CORE_NON_HOLI,
	--SUM_CORE_NON_EXAB,
	--SUM_CSWE_HOLI,
	--SUM_CSWE_EXAB,
	NEXEMPT,
	NWORK,
	NDEEMCOR,
	NDEEM15,
	NLIM_SSA,
	NDEEM16,
	NLIM_EDE,
	NDEEM17,
	DCOR_PART,
	AF_NCORHRS,
	HWK_VOC,
	TWK_VOC,
	FAMILY_AFFILIATION AS AF_FAMILY_AFFILIATION,
	NONCUSTODIAL_PARENT AS AF_NONCUSTODIAL_PARENT,
	--DOB AS AF_DOB,
	FED_OASDI_PROGRAM AS AF_FED_OASDI_PROGRAM,
	AID_AGED_BLIND AS AF_AID_AGED_BLIND,
	RECEIVE_SSI AS AF_RECEIVE_SSI,
	MARITAL_STATUS AS AF_MARITAL_STATUS,
	RELATIONSHIP_HOH AS AF_RELATIONSHIP_HOH,
	PARENT AS AF_PARENT,
	CITIZENSHIP_STATUS AS AF_CITIZENSHIP_STATUS ,
	WEI AS AF_WEI,
	WORK_PART_STATUS AS AF_WORK_PART_STATUS,
	UNSUB_EMPLOYMENT AS AF_UNSUB_EMPLOYMENT,
	SUB_PRIVATE_EMPLOYMENT AS AF_SUB_PRIVATE_EMPLOYMENT,
	SUB_PUBLIC_EMPLOYMENT AS AF_SUB_PUBLIC_EMPLOYMENT,
	WORK_EXPERIENCE_HOP AS AF_WORK_EXPERIENCE_HOP,
	OJT AS AF_OJT,
	JOB_SEARCH_HOP AS AF_JOB_SEARCH_HOP,
	COMM_SERVICES_HOP AS AF_COMM_SERVICES_HOP,
	VOCATIONAL_ED_TRAINING_HOP AS AF_VOCATIONAL_ED_TRAINING_HOP,
	JOB_SKILLS_TRAINING_HOP AS AF_JOB_SKILLS_TRAINING_HOP,
	ED_NO_HIGH_SCHOOL_DIPL_HOP as AF_ED_NO_HIGH_SCHOOL_DIPL_HOP,
	SCHOOL_ATTENDENCE_HOP AS AF_SCHOOL_ATTENDENCE_HOP,
	PROVIDE_CC_HOP AS AF_PROVIDE_CC_HOP,
	OTHER_WORK_ACTIVITIES AS AF_OTHER_WORK_ACTIVITIES,
	WORK_EXPERIENCE_EA AS AF_WORK_EXPERIENCE_EA,
	JOB_SEARCH_EA AS AF_JOB_SEARCH_EA,
	COMM_SERVICES_EA AS AF_COMM_SERVICES_EA,
	VOCATIONAL_ED_TRAINING_EA AS AF_VOCATIONAL_ED_TRAINING_EA,
	JOB_SKILLS_TRAINING_EA AS AF_JOB_SKILLS_TRAINING_EA,
	ED_NO_HIGH_SCHOOL_DIPL_EA AS AF_ED_NO_HIGH_SCHOOL_DIPL_EA,
	SCHOOL_ATTENDENCE_EA AS AF_SCHOOL_ATTENDENCE_EA,
	PROVIDE_CC_EA AS AF_PROVIDE_CC_EA,
	WORK_EXPERIENCE_HOL AS AF_WORK_EXPERIENCE_HOL,
	JOB_SEARCH_HOL AS AF_JOB_SEARCH_HOL,
	COMM_SERVICES_HOL AS AF_COMM_SERVICES_HOL,
	VOCATIONAL_ED_TRAINING_HOL AS AF_VOCATIONAL_ED_TRAINING_HOL,
	JOB_SKILLS_TRAINING_HOL AS AF_JOB_SKILLS_TRAINING_HOL,
	ED_NO_HIGH_SCHOOL_DIPL_HOL AS AF_ED_NO_HIGH_SCHOOL_DIPL_HOL,
	SCHOOL_ATTENDENCE_HOL AS AF_SCHOOL_ATTENDENCE_HOL,
	PROVIDE_CC_HOL AS AF_PROVIDE_CC_HOL,
	UNEARNED_SSI AS AF_UNEARNED_SSI,
	AGE AS AF_AGE,
	ISWEI AS AF_ISWEI,
	HRS_WRK_1 AS AF_HRS_WRK,
	OHRS_WRK_1 AS AF_OHRS_WRK,
	THRS_WRK_1 AS AF_THRS_WRK,
	CSWE_HRS_1 AS AF_CSWE_HRS,
	-- summarized variables --
	-- N_WEI,
	N_WRK_WEI,
	N_HOL_WEI,
	N_EXA_WEI,
	N_WKHLEA_WEI,
	NGAGED,
  TPER_UNSUB_EMPLOYMENT,
  TPER_SUB_PRIVATE_EMPLOYMENT,
  TPER_SUB_PUBLIC_EMPLOYMENT,
	TPER_WORK_EXPERIENCE_HOP,
	TPER_OJT,
	TPER_JOB_SEARCH_HOP,
	TPER_COMM_SERVICES_HOP,
	TPER_VOCATIONAL_ED_TRAINING_HOP,
	TPER_JOB_SKILLS_TRAINING_HOP,
	TPER_ED_NO_HIGH_SCHOOL_DIPL_HOP,
	TPER_SCHOOL_ATTENDENCE_HOP,
	TPER_OTHER_WORK_ACTIVITIES,
	TPER_PROVIDE_CC_HOP,
	THRS_UNSUB_EMPLOYMENT,
	THRS_SUB_PRIVATE_EMPLOYMENT,
	THRS_SUB_PUBLIC_EMPLOYMENT,
	THRS_WORK_EXPERIENCE_HOP,
	THRS_OJT,
	THRS_JOB_SEARCH_HOP,
	THRS_COMM_SERVICES_HOP,
	THRS_VOCATIONAL_ED_TRAINING_HOP,
	THRS_JOB_SKILLS_TRAINING_HOP,
	THRS_ED_NO_HIGH_SCHOOL_DIPL_HOP,
	THRS_SCHOOL_ATTENDENCE_HOP,
	THRS_OTHER_WORK_ACTIVITIES,
	THRS_PROVIDE_CC_HOP,
	TPER_WORK_EXPERIENCE_EA,
	TPER_JOB_SEARCH_EA,
	TPER_COMM_SERVICES_EA,
	TPER_VOCATIONAL_ED_TRAINING_EA,
	TPER_JOB_SKILLS_TRAINING_EA,
	TPER_ED_NO_HIGH_SCHOOL_DIPL_EA,
	TPER_SCHOOL_ATTENDENCE_EA,
	TPER_PROVIDE_CC_EA,
	THRS_WORK_EXPERIENCE_EA,
	THRS_JOB_SEARCH_EA,
	THRS_COMM_SERVICES_EA,
	THRS_VOCATIONAL_ED_TRAINING_EA,
	THRS_JOB_SKILLS_TRAINING_EA,
	THRS_ED_NO_HIGH_SCHOOL_DIPL_EA,
	THRS_SCHOOL_ATTENDENCE_EA,
	THRS_PROVIDE_CC_EA,
	TPER_WORK_EXPERIENCE_HOL,
	TPER_JOB_SEARCH_HOL,
	TPER_COMM_SERVICES_HOL,
	TPER_VOCATIONAL_ED_TRAINING_HOL,
	TPER_JOB_SKILLS_TRAINING_HOL,
	TPER_ED_NO_HIGH_SCHOOL_DIPL_HOL,
	TPER_SCHOOL_ATTENDENCE_HOL,
	TPER_PROVIDE_CC_HOL,
	THRS_WORK_EXPERIENCE_HOL,
	THRS_JOB_SEARCH_HOL,
	THRS_COMM_SERVICES_HOL,
	THRS_VOCATIONAL_ED_TRAINING_HOL,
	THRS_JOB_SKILLS_TRAINING_HOL,
	THRS_ED_NO_HIGH_SCHOOL_DIPL_HOL,
	THRS_SCHOOL_ATTENDENCE_HOL,
	THRS_PROVIDE_CC_HOL,
	CASE
		WHEN FTYPE IN (1,2) THEN 1
		ELSE 0
	END AS NSAMP
FROM
	pf_af
WHERE
	ROWNUM = 1;


CREATE OR REPLACE TEMPORARY VIEW final_af AS
SELECT
	*,
	-- calculate error flags - add notes later on what each of these represent --
	CASE
		WHEN FTYPE IN (1,2) AND FAMILY_TYPE = 1 AND N_WEI = 0 THEN '02'
		WHEN FTYPE IN (1,2) AND ((N_WEI >= 2 AND IS2P = 1) OR YOUNGEST > 1) AND AF_WORK_PART_STATUS = 1 THEN '03'
		WHEN FTYPE IN (1,2) AND AF_WORK_PART_STATUS = 15 AND NOT ((AF_AGE BETWEEN 12 AND 20) AND (AF_RELATIONSHIP_HOH IN (1,2)) AND ((AF_SCHOOL_ATTENDENCE_HOP + AF_SCHOOL_ATTENDENCE_EA + AF_SCHOOL_ATTENDENCE_HOL) > 0))THEN '04'
		WHEN FTYPE IN (1,2) AND AF_WORK_PART_STATUS = 16 AND NOT ((AF_AGE BETWEEN 12 AND 20) AND (AF_RELATIONSHIP_HOH IN (1,2)) AND ((AF_ED_NO_HIGH_SCHOOL_DIPL_HOP + AF_ED_NO_HIGH_SCHOOL_DIPL_EA + AF_ED_NO_HIGH_SCHOOL_DIPL_HOL) > 0))THEN '05'
		WHEN FTYPE IN (1,2) AND AF_WORK_PART_STATUS = 17 AND YOUNGEST > 6 THEN '06'
		WHEN FTYPE IN (1,2) AND AF_WORK_PART_STATUS = 9 AND AF_WEI >= 1 AND AF_WEI <= 5 AND FIPS_CODE NOT IN (6, 23, 21, 27, 39) THEN '08'
		WHEN FTYPE IN (1,2) AND FAMILY_TYPE = 3 AND N_WEI > 0 THEN '09'
		WHEN FTYPE IN (1,2) AND AF_WEI = 6 AND AF_ISWEI = 1 THEN '10'
		WHEN FTYPE IN (1,2) AND AF_WEI = 7 AND AF_CITIZENSHIP_STATUS = 1 THEN '11'
		WHEN FTYPE IN (1,2) AND (AF_WEI = 8 AND NDISABLE != 1) OR (AF_WEI = 10 AND (AF_FED_OASDI_PROGRAM != 1)) THEN '12'
		WHEN FTYPE IN (1,2) AND AF_WORK_PART_STATUS = 2 AND NDCARD2 = 0 AND NDCRD_PART = 0 THEN '13'
		WHEN FTYPE IN (1,2) AND AF_WEI = 11 AND (AF_AGE >= 20 OR AF_RELATIONSHIP_HOH IN (1,2)) THEN '14'
		ELSE '  '
	END AS AFERRFG
FROM
	final_af1;

# %%
--------------------------------------------------------------------------------
-- Step 9: Create data frames for each parent in a family, as either 1p or 2p --
--------------------------------------------------------------------------------

-- First, create the data frame for all families with at least 2 WEIs, and use ROWNUM to differentiate between the first parent (10) and the second parent (2p) (1p will have the higher holder value) --

CREATE OR REPLACE TEMPORARY VIEW pf_2p AS
WITH CTA AS (
	SELECT
		*,
		ROW_NUMBER() OVER (PARTITION BY CASE_ID ORDER BY HOLDER DESC, RELATIONSHIP_HOH DESC) AS ROWNUM
	FROM
		a11
)
SELECT
  *
FROM
  CTA
WHERE
  FTYPE = 2 AND N_WEI >= 2
ORDER BY
	HOLDER DESC;

-- Next, create a table for the first parent in the 2p families --

CREATE OR REPLACE TEMPORARY VIEW pf_2p1 AS
SELECT
	FAMILY_AFFILIATION AS P1_FAMILY_AFFILIATION,
	NONCUSTODIAL_PARENT AS P1_NONCUSTODIAL_PARENT,
	-- DOB AS P1_DOB,
	FED_OASDI_PROGRAM AS P1_RECSSDI,
	AID_AGED_BLIND AS P1_AIDABD,
	RECEIVE_SSI AS P1_RECEIVE_SSI,
	marital_status AS P1_MARITAL_STATUS,
	RELATIONSHIP_HOH AS P1_RELATIONSHIP_HOH,
	PARENT AS P1_PARENT,
	CITIZENSHIP_STATUS AS P1_CITIZENSHIP_STATUS,
	WEI AS P1_WEI,
	WORK_PART_STATUS AS P1_WORK_PART_STATUS,
	UNSUB_EMPLOYMENT AS P1_UNSUB_EMPLOYMENT,
	SUB_PRIVATE_EMPLOYMENT AS P1_SUB_PRIVATE_EMPLOYMENT,
	SUB_PUBLIC_EMPLOYMENT AS P1_SUB_PUBLIC_EMPLOYMENT,
	WORK_EXPERIENCE_HOP AS P1_WORK_EXPERIENCE_HOP,
	OJT AS P1_OJT,
	JOB_SEARCH_HOP AS P1_JOB_SEARCH_HOP,
	COMM_SERVICES_HOP AS P1_COMM_SERVICES_HOP,
	VOCATIONAL_ED_TRAINING_HOP AS P1_VOCATIONAL_ED_TRAINING_HOP,
	JOB_SKILLS_TRAINING_HOP AS P1_JOB_SKILLS_TRAINING_HOP,
	ED_NO_HIGH_SCHOOL_DIPL_HOP AS P1_ED_NO_HIGH_SCHOOL_DIPL_HOP,
	SCHOOL_ATTENDENCE_HOP AS P1_SCHOOL_ATTENDENCE_HOP,
	PROVIDE_CC_HOP AS P1_PROVIDE_CC_HOP,
	OTHER_WORK_ACTIVITIES AS P1_OTHER_WORK_ACTIVITIES,
	WORK_EXPERIENCE_EA AS P1_WORK_EXPERIENCE_EA,
	JOB_SEARCH_EA AS P1_JOB_SEARCH_EA,
	COMM_SERVICES_EA AS P1_COMM_SERVICES_EA,
	VOCATIONAL_ED_TRAINING_EA AS P1_VOCATIONAL_ED_TRAINING_EA,
	JOB_SKILLS_TRAINING_EA AS P1_JOB_SKILLS_TRAINING_EA,
	ED_NO_HIGH_SCHOOL_DIPL_EA AS P1_ED_NO_HIGH_SCHOOL_DIPL_EA,
	SCHOOL_ATTENDENCE_EA AS P1_SCHOOL_ATTENDENCE_EA,
	PROVIDE_CC_EA AS P1_PROVIDE_CC_EA,
	WORK_EXPERIENCE_HOL AS P1_WORK_EXPERIENCE_HOL,
	JOB_SEARCH_HOL AS P1_JOB_SEARCH_HOL,
	COMM_SERVICES_HOL AS P1_COMM_SERVICES_HOL,
	VOCATIONAL_ED_TRAINING_HOL AS P1_VOCATIONAL_ED_TRAINING_HOL,
	JOB_SKILLS_TRAINING_HOL AS P1_JOB_SKILLS_TRAINING_HOL,
	ED_NO_HIGH_SCHOOL_DIPL_HOL AS P1_ED_NO_HIGH_SCHOOL_DIPL_HOL,
	SCHOOL_ATTENDENCE_HOL AS P1_SCHOOL_ATTENDENCE_HOL,
	PROVIDE_CC_HOL AS P1_PROVIDE_CC_HOL,
	UNEARNED_SSI AS P1_UNEARNED_SSI,
	AGE AS P1_AGE,
	WEI AS P1_ISWEI,
	HRS_WRK_1 AS P1_HRS_WRK,
	OHRS_WRK_1 AS P1_OHRS_WRK,
	THRS_WRK_1 AS P1_THRS_WRK,
	CSWE_HRS_1 AS P1_CSWE_HRS,
 	CASE_ID AS CASE_ID,
 	-- Add in family-level financial variables
 	SANC_REDUCTION_AMT,
 	WORK_REQ_SANCTION,
  MIN_WAGES,
  CHILD_SUPPORT_AMT,
  AMT_FOOD_STAMP_ASSISTANCE,
  TRANSITION_SERVICES_AMOUNT,
  TRANSP_AMOUNT,
  OTHER_AMOUNT,
  CC_AMOUNT,
  CASH_AMOUNT,
  FLSA_STATE,
  FTYPE,
  FAMILY_TYPE,
  N_WEI,
  IS2P,
  YOUNGEST,
  FIPS_CODE,
  NDISABLE,
  NDCARD2,
  NDCRD_PART,
  RECEIVES_SUB_CC,
  AMT_SUB_CC,
  CASE
		WHEN FTYPE IN (1,2) THEN 1
		ELSE 0
  END AS NSAMP
FROM
	pf_2p
WHERE
	ROWNUM = 1;

-- Next, create a table for the second parent in the 2p families --

CREATE OR REPLACE TEMPORARY VIEW pf_2p2 AS
SELECT
	FAMILY_AFFILIATION AS P2_FAMILY_AFFILIATION,
	NONCUSTODIAL_PARENT AS P2_NONCUSTODIAL_PARENT,
	-- DOB AS P2_DOB,
	FED_OASDI_PROGRAM AS P2_RECSSDI,
	AID_AGED_BLIND AS P2_AIDABD,
	RECEIVE_SSI AS P2_RECEIVE_SSI,
	marital_status AS P2_MARITAL_STATUS,
	RELATIONSHIP_HOH AS P2_RELATIONSHIP_HOH,
	PARENT AS P2_PARENT,
	CITIZENSHIP_STATUS AS P2_CITIZENSHIP_STATUS,
	WEI AS P2_WEI,
	WORK_PART_STATUS AS P2_WORK_PART_STATUS,
	UNSUB_EMPLOYMENT AS P2_UNSUB_EMPLOYMENT,
	SUB_PRIVATE_EMPLOYMENT AS P2_SUB_PRIVATE_EMPLOYMENT,
	SUB_PUBLIC_EMPLOYMENT AS P2_SUB_PUBLIC_EMPLOYMENT,
	WORK_EXPERIENCE_HOP AS P2_WORK_EXPERIENCE_HOP,
	OJT AS P2_OJT,
	JOB_SEARCH_HOP AS P2_JOB_SEARCH_HOP,
	COMM_SERVICES_HOP AS P2_COMM_SERVICES_HOP,
	VOCATIONAL_ED_TRAINING_HOP AS P2_VOCATIONAL_ED_TRAINING_HOP,
	JOB_SKILLS_TRAINING_HOP AS P2_JOB_SKILLS_TRAINING_HOP,
	ED_NO_HIGH_SCHOOL_DIPL_HOP AS P2_ED_NO_HIGH_SCHOOL_DIPL_HOP,
	SCHOOL_ATTENDENCE_HOP AS P2_SCHOOL_ATTENDENCE_HOP,
	PROVIDE_CC_HOP AS P2_PROVIDE_CC_HOP,
	OTHER_WORK_ACTIVITIES AS P2_OTHER_WORK_ACTIVITIES,
	WORK_EXPERIENCE_EA AS P2_WORK_EXPERIENCE_EA,
	JOB_SEARCH_EA AS P2_JOB_SEARCH_EA,
	COMM_SERVICES_EA AS P2_COMM_SERVICES_EA,
	VOCATIONAL_ED_TRAINING_EA AS P2_VOCATIONAL_ED_TRAINING_EA,
	JOB_SKILLS_TRAINING_EA AS P2_JOB_SKILLS_TRAINING_EA,
	ED_NO_HIGH_SCHOOL_DIPL_EA AS P2_ED_NO_HIGH_SCHOOL_DIPL_EA,
	SCHOOL_ATTENDENCE_EA AS P2_SCHOOL_ATTENDENCE_EA,
	PROVIDE_CC_EA AS P2_PROVIDE_CC_EA,
	WORK_EXPERIENCE_HOL AS P2_WORK_EXPERIENCE_HOL,
	JOB_SEARCH_HOL AS P2_JOB_SEARCH_HOL,
	COMM_SERVICES_HOL AS P2_COMM_SERVICES_HOL,
	VOCATIONAL_ED_TRAINING_HOL AS P2_VOCATIONAL_ED_TRAINING_HOL,
	JOB_SKILLS_TRAINING_HOL AS P2_JOB_SKILLS_TRAINING_HOL,
	ED_NO_HIGH_SCHOOL_DIPL_HOL AS P2_ED_NO_HIGH_SCHOOL_DIPL_HOL,
	SCHOOL_ATTENDENCE_HOL AS P2_SCHOOL_ATTENDENCE_HOL,
	PROVIDE_CC_HOL AS P2_PROVIDE_CC_HOL,
	UNEARNED_SSI AS P2_UNEARNED_SSI,
	AGE AS P2_AGE,
	WEI AS P2_ISWEI,
	HRS_WRK_1 AS P2_HRS_WRK,
	OHRS_WRK_1 AS P2_OHRS_WRK,
	THRS_WRK_1 AS P2_THRS_WRK,
	CSWE_HRS_1 AS P2_CSWE_HRS,
  CASE_ID AS CASE_ID,
 	FTYPE,
  FAMILY_TYPE,
  N_WEI,
  IS2P,
  YOUNGEST,
  FIPS_CODE,
  NDISABLE,
  NDCARD2,
  NDCRD_PART,
	CASE
		WHEN FTYPE IN (1,2) THEN 1
		ELSE 0
	END AS NSAMP
FROM
	pf_2p
WHERE
	ROWNUM = 2;


# %%
----------------------------------------------------------------
-- Step 10: Merge the two dataframes for each parent into one --
----------------------------------------------------------------

-- First, we merge the two datasets (pf_2p1 and pf_2p2) so we can look at each family's two parents simultaneously --
-- We also calculate the required core hours and required total hours (TP_REQCORE and TP_REQALL), which are used to determine work partipation --
-- We also calculate their hours without deeming any hours (TPHRS_ND, TPOHRS_ND, and TPTHRS_ND) --

CREATE OR REPLACE TEMPORARY VIEW final_2p1 AS
SELECT
	pf_2p1.*,
	pf_2p2.* EXCEPT (FIPS_CODE, CASE_ID, FAMILY_TYPE, FTYPE, IS2P, N_WEI, YOUNGEST, NDISABLE, NDCARD2, NDCRD_PART, NSAMP),
	1 AS TPSAMP,
	-- required core hours --
	CASE
		WHEN NOT (RECEIVES_SUB_CC = 1 AND AMT_SUB_CC > 0) OR (RECEIVES_SUB_CC = 1 AND (P1_WORK_PART_STATUS = '08' OR P2_WORK_PART_STATUS = '08')) THEN 30
		ELSE 50
	END AS TP_REQCORE,
	-- required total hours --
	CASE
		WHEN NOT (RECEIVES_SUB_CC = 1 AND AMT_SUB_CC > 0) OR (RECEIVES_SUB_CC = 1 AND (P1_WORK_PART_STATUS = '08' OR P2_WORK_PART_STATUS = '08')) THEN 35
		ELSE 55
	END AS TP_REQALL,
	-- core hours before deeming --
	P1_HRS_WRK + P2_HRS_WRK AS TPHRS_ND,
	-- non-core hours before deeming --
	P1_OHRS_WRK + P2_OHRS_WRK AS TPOHRS_ND,
	-- total hours before deeming --
	P1_THRS_WRK + P2_THRS_WRK AS TPTHRS_ND
FROM
	pf_2p1
	INNER JOIN pf_2p2
	ON pf_2p1.FIPS_CODE = pf_2p2.FIPS_CODE AND pf_2p1.CASE_ID = pf_2p2.CASE_ID;

-- the subsequent tables build upon each other to calculate various financial and demographic variables --

-- first, we want to see if each family can be included in work partipation rate calculations without deeming any hours (TPWORK_ND = 1)
-- for non-qualifying families, we can deem hours in later steps. We calculate TPCWEHRs, which will be used to adjust their required hours later --

CREATE OR REPLACE TEMPORARY VIEW final_2p2 AS
SELECT
	*,
	-- TPWORK is used to calculate work rate --
	-- First, we see if TPWORK can be applied WITHOUT deeming any hours (TPWORK_ND)
	CASE
		WHEN TPHRS_ND >= TP_REQCORE AND TPTHRS_ND >= TP_REQALL THEN 1
		ELSE 0
	END AS TPWORK_ND,
	-- TPCSWEHRS is used to help deem hours later if TPWORK_ND is 0 --
	-- TPCSWEHRS is essentially the sum of other hours related to working (such as hours spend searching for jobs) --
	CASE
		WHEN NOT (TPHRS_ND >= TP_REQCORE AND TPTHRS_ND >= TP_REQALL) THEN P1_CSWE_HRS + P2_CSWE_HRS
		ELSE 0
	END AS TPCSWEHRS
FROM
	final_2p1;

-- For parents that do NOT qualify, we can deem their hours to see if they qualify for work participation later on. --
-- First, we determine if we can reduce their hours needed to qualify for WPR --
CREATE OR REPLACE TEMPORARY VIEW final_2p3 AS
SELECT
	*,
	-- recalculate the two-parent core deem hours by subtracting CSWE hours from required core hours if certain conditions are met --
	CASE
		WHEN TPWORK_ND = 0 AND (TPHRS_ND < TP_REQCORE) AND (FLSA_STATE = 1) AND (TPCSWEHRS > 0) AND (TPCSWEHRS >= FLOOR((CASH_AMOUNT + CC_AMOUNT + OTHER_AMOUNT + TRANSITION_SERVICES_AMOUNT + TRANSP_AMOUNT + AMT_FOOD_STAMP_ASSISTANCE - CHILD_SUPPORT_AMT)/(5*MIN_WAGES))) THEN TP_REQCORE - TPCSWEHRS
		ELSE 0
	END AS TPCORDMHRS,
	-- TPDEEMCOR tracks if deemed hours were necessary for a family to count in work participation rates --
	CASE
		WHEN TPWORK_ND = 0 AND (TPHRS_ND < TP_REQCORE) AND (FLSA_STATE = 1) AND (TPCSWEHRS > 0) AND (TPCSWEHRS >= FLOOR((CASH_AMOUNT + CC_AMOUNT + OTHER_AMOUNT + TRANSITION_SERVICES_AMOUNT + TRANSP_AMOUNT + AMT_FOOD_STAMP_ASSISTANCE - CHILD_SUPPORT_AMT)/(5*MIN_WAGES))) THEN 1
		ELSE 0
	END AS TPDEEMCOR
FROM
	final_2p2;

CREATE OR REPLACE TEMPORARY VIEW final_2p4 AS
SELECT
	*,
  -- TPHRS if we had to deem some hours
	CASE
		WHEN TPDEEMCOR = 1 THEN TPHRS_ND + TPCORDMHRS
		ELSE 0
	END AS TPHRS_D_CSWE,
	-- TPTHRS if we had to deem some hours
	CASE
		WHEN TPDEEMCOR = 1 THEN TPTHRS_ND + TPCORDMHRS
		ELSE 0
	END AS TPTHRS_D_CSWE
    FROM
    	final_2p3;


CREATE OR REPLACE TEMPORARY VIEW final_2p5 AS
SELECT
	*,
	--TPWORK if deemed
	CASE
		WHEN TPHRS_D_CSWE >= TP_REQCORE AND TPTHRS_D_CSWE >= TP_REQALL THEN 1
		ELSE 0
	END AS TPWORK_D_CSWE,
	-- P1_SANC and P2_SANC are used to determine TPDCARD2 later
	-- Ask Yun what "SANC" stands for later
	CASE
		WHEN (P1_WORK_PART_STATUS = 2) AND ((P1_FAMILY_AFFILIATION = 1 AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0) OR (P1_FAMILY_AFFILIATION = 2 AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0 AND P1_WEI = 2)) THEN 1
		ELSE 0
	END AS P1_SANC,
	CASE
		WHEN (P2_WORK_PART_STATUS = 2) AND ((P2_FAMILY_AFFILIATION = 1 AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0) OR (P2_FAMILY_AFFILIATION = 2 AND WORK_REQ_SANCTION = 1 AND SANC_REDUCTION_AMT > 0 AND P2_WEI = 2)) THEN 1
		ELSE 0
	END AS P2_SANC,
	-- P1_SATSCH and P2_SATSCH are "school satisfactory", which can be used to deem a minimum of 20 hours later
	CASE
		WHEN (P1_WORK_PART_STATUS IN (15,16) OR P2_WORK_PART_STATUS IN (15,16)) THEN (P1_SCHOOL_ATTENDENCE_HOP + P1_SCHOOL_ATTENDENCE_HOL + P1_SCHOOL_ATTENDENCE_EA)
		ELSE 0
	END AS P1_SATSCH,
	CASE
		WHEN (P1_WORK_PART_STATUS IN (15,16) OR P2_WORK_PART_STATUS IN (15,16)) THEN (P2_SCHOOL_ATTENDENCE_HOP + P2_SCHOOL_ATTENDENCE_HOL + P2_SCHOOL_ATTENDENCE_EA)
		ELSE 0
	END AS P2_SATSCH,
	-- P1_EDUDIR and P2_EDUCIR are "education directly related to income", which can be used to deem hours later --
	CASE
		WHEN (P1_WORK_PART_STATUS IN (15,16) OR P2_WORK_PART_STATUS IN (15,16)) THEN (P1_ED_NO_HIGH_SCHOOL_DIPL_HOP + P1_ED_NO_HIGH_SCHOOL_DIPL_HOL + P1_ED_NO_HIGH_SCHOOL_DIPL_EA)
		ELSE 0
	END AS P1_EDUDIR,
	CASE
		WHEN (P1_WORK_PART_STATUS IN (15,16) OR P2_WORK_PART_STATUS IN (15,16)) THEN (P2_ED_NO_HIGH_SCHOOL_DIPL_HOP + P2_ED_NO_HIGH_SCHOOL_DIPL_HOL + P2_ED_NO_HIGH_SCHOOL_DIPL_EA)
		ELSE 0
	END AS P2_EDUDIR,
	-- P1_TEENP and P2_TEENP designate a teen parent, who can have their hours deemed through special conditions --
	CASE
		WHEN (P1_WORK_PART_STATUS IN (15,16) OR P2_WORK_PART_STATUS IN (15,16)) AND P1_AGE > 12 AND P1_AGE < 20 AND P1_PARENT = 1 THEN 1
		ELSE 0
	END AS P1_TEENP,
	CASE
		WHEN (P1_WORK_PART_STATUS IN (15,16) OR P2_WORK_PART_STATUS IN (15,16)) AND P2_AGE > 12 AND P2_AGE < 20 AND P2_PARENT = 1 THEN 1
		ELSE 0
	END AS P2_TEENP
FROM
  final_2p4;


CREATE OR REPLACE TEMPORARY VIEW final_2p6 AS
SELECT
	*,
-- deeming hours for school satisfactory variables --
  CASE
	  WHEN P1_WORK_PART_STATUS = 15 AND P1_TEENP = 1 AND P1_RELATIONSHIP_HOH IN (1, 2) AND P1_SATSCH > 0 THEN 1
	  ELSE 0
	END AS P1_DEEM_SATSCH,
	CASE
		WHEN P1_WORK_PART_STATUS = 15 AND P1_TEENP = 1 AND P1_RELATIONSHIP_HOH IN (1, 2) AND P1_SATSCH > 0 AND P1_SATSCH <= 20 THEN 20
		WHEN P1_WORK_PART_STATUS = 15 AND P1_TEENP = 1 AND P1_RELATIONSHIP_HOH IN (1, 2) AND (P1_SATSCH > 20) THEN P1_SATSCH
		ELSE 0
	END AS P1_DMHRS_SATSCH,
  CASE
	  WHEN P2_WORK_PART_STATUS = 15 AND P2_TEENP = 1 AND P2_RELATIONSHIP_HOH IN (1, 2) AND P2_SATSCH > 0 THEN 1
	  ELSE 0
	END AS P2_DEEM_SATSCH,
	CASE
		WHEN P2_WORK_PART_STATUS = 15 AND P2_TEENP = 1 AND P2_RELATIONSHIP_HOH IN (1, 2) AND P2_SATSCH > 0 AND P2_SATSCH <= 20 THEN 20
		WHEN P2_WORK_PART_STATUS = 15 AND P2_TEENP = 1 AND P2_RELATIONSHIP_HOH IN (1, 2) AND (P2_SATSCH > 20) THEN P2_SATSCH
		ELSE 0
	END AS P2_DMHRS_SATSCH,
	-- deeming hours for education directly related to employment variables --
	CASE
		WHEN P1_WORK_PART_STATUS = 16 AND P1_TEENP = 1 AND P1_RELATIONSHIP_HOH IN (1, 2) AND P1_EDUDIR >= 20 THEN 1
		ELSE 0
	END AS P1_DEEM_EDUDIR,
	CASE
		WHEN P1_WORK_PART_STATUS = 16 AND P1_TEENP = 1 AND P1_RELATIONSHIP_HOH IN (1, 2) AND P1_EDUDIR >= 20 THEN P1_EDUDIR
		ELSE 0
	END AS P1_DMHRS_EDUDIR,
	CASE
		WHEN P2_WORK_PART_STATUS = 16 AND P2_TEENP = 1 AND P2_RELATIONSHIP_HOH IN (1, 2) AND P2_EDUDIR >= 20 THEN 1
		ELSE 0
	END AS P2_DEEM_EDUDIR,
	CASE
		WHEN P2_WORK_PART_STATUS = 16 AND P2_TEENP = 1 AND P2_RELATIONSHIP_HOH IN (1, 2) AND P2_EDUDIR >= 20 THEN P2_EDUDIR
		ELSE 0
	END AS P2_DMHRS_EDUDIR
FROM
	final_2p5;

CREATE OR REPLACE TEMPORARY VIEW final_2p7 AS
SELECT
	*,
	P1_HRS_WRK + P1_DMHRS_SATSCH + P1_DMHRS_EDUDIR + P2_HRS_WRK + P2_DMHRS_SATSCH + P2_DMHRS_EDUDIR AS TPHRS_DEEM_SATSCH_EDUDIR,
	P1_OHRS_WRK - P1_SATSCH - P1_EDUDIR + P2_OHRS_WRK - P2_SATSCH - P2_EDUDIR AS TPOHRS_DEEM_SATSCH_EDUDIR,
	P1_THRS_WRK + P1_DMHRS_SATSCH + P1_DMHRS_EDUDIR + P1_OHRS_WRK - P1_SATSCH - P1_EDUDIR + P2_THRS_WRK + P2_DMHRS_SATSCH + P2_DMHRS_EDUDIR + P2_OHRS_WRK - P2_SATSCH - P1_EDUDIR AS TPTHRS_DEEM_SATSCH_EDUDIR
FROM
	final_2p6;

CREATE OR REPLACE TEMPORARY VIEW final_2p8 AS
SELECT
	*,
	CASE
		WHEN (P1_DEEM_SATSCH = 1 OR P1_DEEM_EDUDIR = 1) AND (P2_DEEM_SATSCH = 1 OR P2_DEEM_EDUDIR = 1) THEN 1
		WHEN ((P1_DEEM_SATSCH = 1 OR P1_DEEM_EDUDIR = 1) OR (P2_DEEM_SATSCH = 1 OR P2_DEEM_EDUDIR = 1)) AND (TPHRS_DEEM_SATSCH_EDUDIR >= TP_REQCORE) AND (TPTHRS_DEEM_SATSCH_EDUDIR >= TP_REQALL) THEN 1
	END AS TPWORK_DEEM_SATSCH_EDUDIR,
	-- TPNCP is used to determine TPWORK, TPDCARD2, TPDCARD5 and TPABLE later --
	CASE
		WHEN P1_NONCUSTODIAL_PARENT = 1 OR P2_NONCUSTODIAL_PARENT = 1 THEN 1
		ELSE 0
	END AS TPNCP
FROM
	final_2p7;


CREATE OR REPLACE TEMPORARY VIEW final_2p9 AS
SELECT
	*,
	-- TPLIM_VOC is used to determine TPDCARD2 and TPDCARD5 later. CSWE deemed hours count, but SATSCH and EDUDIR deemed hours do not --
	CASE
		-- condition for when hours were NOT deemed --
		WHEN (TPHRS_ND >= TP_REQCORE AND TPTHRS_ND >= TP_REQALL) AND (TPHRS_ND - (P1_VOCATIONAL_ED_TRAINING_HOP + P2_VOCATIONAL_ED_TRAINING_HOP + P1_VOCATIONAL_ED_TRAINING_HOL + P2_VOCATIONAL_ED_TRAINING_HOL + P1_VOCATIONAL_ED_TRAINING_EA + P2_VOCATIONAL_ED_TRAINING_EA) < TP_REQCORE) OR ((TPTHRS_ND - (P1_VOCATIONAL_ED_TRAINING_HOP + P2_VOCATIONAL_ED_TRAINING_HOP + P1_VOCATIONAL_ED_TRAINING_HOL + P2_VOCATIONAL_ED_TRAINING_HOL + P1_VOCATIONAL_ED_TRAINING_EA + P2_VOCATIONAL_ED_TRAINING_EA)) < TP_REQALL) THEN 1
		-- condition for when CSWE hours WERE deemed --
		WHEN (TPHRS_D_CSWE >= TP_REQCORE AND TPTHRS_D_CSWE >= TP_REQALL) AND (TPHRS_ND - (P1_VOCATIONAL_ED_TRAINING_HOP + P2_VOCATIONAL_ED_TRAINING_HOP + P1_VOCATIONAL_ED_TRAINING_HOL + P2_VOCATIONAL_ED_TRAINING_HOL + P1_VOCATIONAL_ED_TRAINING_EA + P2_VOCATIONAL_ED_TRAINING_EA) < TP_REQCORE) OR ((TPTHRS_ND - (P1_VOCATIONAL_ED_TRAINING_HOP + P2_VOCATIONAL_ED_TRAINING_HOP + P1_VOCATIONAL_ED_TRAINING_HOL + P2_VOCATIONAL_ED_TRAINING_HOL + P1_VOCATIONAL_ED_TRAINING_EA + P2_VOCATIONAL_ED_TRAINING_EA)) < TP_REQALL) THEN 1
    ELSE 0
	END AS TPLIM_VOC,
	CASE
		WHEN TPNCP != 1 AND (P1_WORK_PART_STATUS = 7 OR P2_WORK_PART_STATUS = 7) THEN 1
		ELSE 0
	END AS TPDABLE
FROM
  final_2p8;

CREATE OR REPLACE TEMPORARY VIEW final_2p10 AS
SELECT
  *,
	-- TPWORK means that the two parents combined count for the WPR --
	CASE
		WHEN TPDABLE = 1 THEN 0
		WHEN TPWORK_ND = 1 OR TPWORK_D_CSWE = 1 OR TPWORK_DEEM_SATSCH_EDUDIR = 1 THEN 1
		ELSE 0
	END AS TPWORK,
  CASE
      WHEN ((P1_DEEM_SATSCH = 1 OR P1_DEEM_EDUDIR = 1) AND (P2_DEEM_SATSCH = 1 OR P2_DEEM_EDUDIR = 1)) OR ((P1_DEEM_SATSCH = 1 OR P1_DEEM_EDUDIR = 1 OR P2_DEEM_SATSCH = 1 OR P2_DEEM_EDUDIR = 1) AND (TPHRS_DEEM_SATSCH_EDUDIR >= TP_REQCORE AND TPTHRS_DEEM_SATSCH_EDUDIR >= TP_REQALL)) THEN 1
      ELSE 0
  END AS TPDEEM,
  CASE
      WHEN ((P1_DEEM_SATSCH = 1 OR P1_DEEM_EDUDIR = 1) AND (P2_DEEM_SATSCH = 1 OR P2_DEEM_EDUDIR = 1)) OR ((P1_DEEM_SATSCH = 1 OR P1_DEEM_EDUDIR = 1 OR P2_DEEM_SATSCH = 1 OR P2_DEEM_EDUDIR = 1) AND (TPHRS_DEEM_SATSCH_EDUDIR >= TP_REQCORE AND TPTHRS_DEEM_SATSCH_EDUDIR >= TP_REQALL)) THEN 1
      ELSE 0
  END AS TPLIMIT
FROM
  final_2p9;

--the following views are used to calculate the disregard variables--
CREATE OR REPLACE TEMPORARY VIEW final_2p11 AS
SELECT
  *,
	-- TPDCARD5 supercedes TPDCARD2, therefore we calculate it first --
	CASE
		WHEN TPDABLE = 1 THEN 0
		WHEN TPWORK = 1 AND (TPLIM_VOC = 1 OR TPLIMIT = 1) THEN 0
		WHEN (P1_WORK_PART_STATUS = 5 OR P2_WORK_PART_STATUS = 5) THEN 0
		WHEN TPNCP != 1 AND (P1_WORK_PART_STATUS = 7 OR P2_WORK_PART_STATUS = 7) THEN 0
		ELSE 0
	END AS TPDCARD5
FROM
	final_2p10;

CREATE OR REPLACE TEMPORARY VIEW final_2p12 AS
SELECT
	*,
	CASE
		-- If TPDCARD5 applies, then disregard TPDCARD2 --
		WHEN TPDCARD5 = 1 THEN 0
		WHEN TPDABLE = 1 THEN 0
		WHEN (P1_SANC = 1 OR P2_SANC = 1) THEN 1
		WHEN TPWORK = 1 AND (TPLIM_VOC = 1 OR TPLIMIT = 1) THEN 0
		WHEN TPNCP != 1 AND (P1_WORK_PART_STATUS = 7 OR P2_WORK_PART_STATUS = 7) THEN 0
		ELSE 0
	END AS TPDCARD2,
	-- TPDVEXEM is the domestic violence exception --
  CASE
    WHEN (TPWORK = 1 AND (P1_WORK_PART_STATUS = '09' OR P2_WORK_PART_STATUS = '09')) THEN 1
    ELSE 0
  END AS TPDVEXEM
FROM
	final_2p11;

CREATE OR REPLACE TEMPORARY VIEW final_2p AS
SELECT
	*,
	CASE
		WHEN TPWORK = 1 AND (TPDCARD2 = 1 OR TPDCARD5 = 1) AND TPDABLE = 1 THEN 1
		ELSE 0
	END AS TPDCRD_PART,
	-- calculating error flags

--if type_fam=2 and n_wei<2 then tperrfg='1';
--*if type_fam=2 and n_wei=1 then tperrfg='2';
--if (type_fam not eq 2)and ftype=2 then tperrfg='2';/*there are two parents in 2-p WPR*/;
--if (p1_wps = 1 or p2_wps = 1) then tperrfg='3';   /* TWO-PARENT FAMILY, NOT SINGLE CUSTODIAL PARENT FAMILY - ERROR */
--if (p1_sanc = 0 and p1_wps = 2) or (p2_wps = 2 and p2_sanc = 0) then tperrfg='4';


	CASE
		WHEN FAMILY_TYPE = 2 AND N_WEI< 2 THEN '1'
		WHEN FAMILY_TYPE != 2 AND FTYPE = 2 THEN '2'
		WHEN P1_WORK_PART_STATUS = 1 OR P2_WORK_PART_STATUS = 1 THEN '3'
		WHEN (P1_SANC = 0 AND P1_WORK_PART_STATUS = 2) OR (P2_SANC = 0 AND P2_WORK_PART_STATUS = 2) THEN '4'
		ELSE '  '
	END AS TPERRFG
FROM
  final_2p12;


# %%
--------------------------------------------------------
-- Step 11: Merge final_af and final_2p to create tan --
--------------------------------------------------------

CREATE OR REPLACE TABLE IDENTIFIER(tan_table_name) AS
SELECT
 	final_af.*,
 	final_2p.* EXCEPT (FIPS_CODE, CASE_ID, FAMILY_TYPE, FTYPE, IS2P, N_WEI, YOUNGEST, NDISABLE, NDCARD2, NDCRD_PART, NSAMP)
FROM
 	final_af FULL JOIN
 	final_2p
    ON final_af.FIPS_CODE = final_2p.FIPS_CODE AND final_af.CASE_ID = final_2p.CASE_ID;
