# %% [markdown]
#
# # PART 2: CREATING WEIGHTED SUMMARY REPORTS
#
# The second part of this project is to create the weighted TANF summary reports. First, we create the weighted file, which calculates weight (cases divided by count) for each FIPS and stratum for the reporting month. Afterwards, various employment rate metrics are summarized and multipled by weight to determine the final rates. These rates are printed in various reports.

# %%
-------------------------------
-- Step 1: Declare variables --
-------------------------------

-- this is the variable used to filter the dataframes to the current month --
DECLARE OR REPLACE ym INT DEFAULT 202408;

-- this is the name of the final TAN dataframe for the current month --
DECLARE OR REPLACE tan_table_name STRING DEFAULT CONCAT('ofa_sandbox.legacy_code.tan', ym);

-- this is the name of the final WPR dataframe for the current month --
DECLARE OR REPLACE wpr_table_name STRING DEFAULT CONCAT('ofa_sandbox.legacy_code.WPR', ym);

# %%
%python

#certain variables also need to be declared in Python
ym = "202408"

# to print out reports, these are all the FIPS codes to iterate over
# fips_list = [1,2,3]

# %%
-----------------------------------------------
-- Step 2: Calculate weights by jurisdiction --
-----------------------------------------------

-- first, we determine the number of adults by FIPS_CODE and STRATUM for a given RPT_MONTH_YEAR --

CREATE OR REPLACE TEMPORARY VIEW s1 AS
SELECT
  FIPS_CODE,
  RPT_MONTH_YEAR,
  STRATUM,
  COUNT(DISTINCT CASE_NUMBER) AS COUNT
FROM
	read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T1_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	)
WHERE
	RPT_MONTH_YEAR = ym
GROUP BY
  FIPS_CODE,
  RPT_MONTH_YEAR,
  STRATUM;

-- next, we determine the number of families (called CASES) for each FIPS_CODE for a given RPT_MONTH_YEAR --

CREATE OR REPLACE TEMPORARY VIEW s2 AS
SELECT
  FIPS_CODE,
  RPT_MONTH_YEAR,
  NUM_FAMILIES as CASES
FROM
  read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T6_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	)
WHERE
	RPT_MONTH_YEAR = ym;

-- then, we determine the number of cases ... I'm not sure how s3 is different from s2

CREATE OR REPLACE TEMPORARY VIEW s3 AS
SELECT
	FIPS_CODE,
	FAMILIES_MONTH as CASES,
	STRATUM,
	RPT_MONTH_YEAR
FROM
  read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T7_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	)
WHERE
  TDRS_SECTION_IND = 1 AND
  FAMILIES_MONTH > 0 AND
	RPT_MONTH_YEAR = ym;


CREATE OR REPLACE TEMPORARY VIEW weight1 AS
SELECT
  s1.FIPS_CODE,
  s1.RPT_MONTH_YEAR,
  s1.STRATUM,
  s1.COUNT,
  CASE
      WHEN s1.FIPS_CODE = 72 AND s1.STRATUM = 2 THEN 0
      WHEN s3.CASES IS NULL THEN s2.CASES
      WHEN s3.CASES IS NOT NULL AND s1.COUNT > s3.CASES then s1.COUNT
      WHEN s3.CASES IS NULL AND s1.COUNT > s2.CASES then s1.COUNT
      ELSE s3.CASES
  END AS CASES
FROM
	s1
    FULL JOIN
    s2
    ON
      s1.FIPS_CODE = s2.FIPS_CODE AND
      s1.RPT_MONTH_YEAR = s2.RPT_MONTH_YEAR
    FULL JOIN
    s3
    ON
      s1.FIPS_CODE = s3.FIPS_CODE AND
      s1.RPT_MONTH_YEAR = s3.RPT_MONTH_YEAR AND
      s1.STRATUM = s3.STRATUM;

-- double check this logic - there are some rows with many counts, but no cases ... --

-- print this out as weight2025.09 into a folder called WGTLIB --

CREATE OR REPLACE TEMPORARY VIEW weight AS
SELECT
  *,
  CASES/COUNT as WGHT
FROM
	weight1
WHERE
  FIPS_CODE IS NOT NULL AND
  CASES != 0;



# %%
------------------------------------------
-- Step 3: Create the weighted sum file --
------------------------------------------

-- first, we add some calculated variables that will be summed later --

CREATE OR REPLACE TEMPORARY VIEW summfle1 AS
SELECT
  *,
  -- UNSUB_EMPLOYMENT
  CASE
    WHEN AF_UNSUB_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS AF_N_UNSUB_EMPLOYMENT,
  CASE
    WHEN P1_UNSUB_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS P1_N_UNSUB_EMPLOYMENT,
  CASE
    WHEN P2_UNSUB_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS P2_N_UNSUB_EMPLOYMENT,
  -- SUB_PRIVATE_EMPLOYMENT
  CASE
    WHEN AF_SUB_PRIVATE_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS AF_N_SUB_PRIVATE_EMPLOYMENT,
  CASE
    WHEN P1_SUB_PRIVATE_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS P1_N_SUB_PRIVATE_EMPLOYMENT,
  CASE
    WHEN P2_SUB_PRIVATE_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS P2_N_SUB_PRIVATE_EMPLOYMENT,
  -- SUB_PUBLIC_EMPLOYMENT
  CASE
    WHEN AF_SUB_PUBLIC_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS AF_N_SUB_PUBLIC_EMPLOYMENT,
  CASE
    WHEN P1_SUB_PUBLIC_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS P1_N_SUB_PUBLIC_EMPLOYMENT,
  CASE
    WHEN P2_SUB_PUBLIC_EMPLOYMENT > 0 THEN 1
    ELSE 0
  END AS P2_N_SUB_PUBLIC_EMPLOYMENT,
  -- WORK_EXPERIENCE_HOP
  CASE
    WHEN AF_WORK_EXPERIENCE_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_WORK_EXPERIENCE_HOP,
  CASE
    WHEN P1_WORK_EXPERIENCE_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_WORK_EXPERIENCE_HOP,
  CASE
    WHEN P2_WORK_EXPERIENCE_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_WORK_EXPERIENCE_HOP,
  -- OJT
  CASE
    WHEN AF_OJT > 0 THEN 1
    ELSE 0
  END AS AF_N_OJT,
  CASE
    WHEN P1_OJT > 0 THEN 1
    ELSE 0
  END AS P1_N_OJT,
  CASE
    WHEN P2_OJT > 0 THEN 1
    ELSE 0
  END AS P2_N_OJT,
  -- JOB_SEARCH_HOP
  CASE
    WHEN AF_JOB_SEARCH_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_JOB_SEARCH_HOP,
  CASE
    WHEN P1_JOB_SEARCH_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_JOB_SEARCH_HOP,
  CASE
    WHEN P2_JOB_SEARCH_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_JOB_SEARCH_HOP,
  -- COMM_SERVICES_HOP
  CASE
    WHEN AF_COMM_SERVICES_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_COMM_SERVICES_HOP,
  CASE
    WHEN P1_COMM_SERVICES_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_COMM_SERVICES_HOP,
  CASE
    WHEN P2_COMM_SERVICES_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_COMM_SERVICES_HOP,
  -- VOCATIONAL_ED_TRAINING_HOP
  CASE
    WHEN AF_VOCATIONAL_ED_TRAINING_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_VOCATIONAL_ED_TRAINING_HOP,
  CASE
    WHEN P1_VOCATIONAL_ED_TRAINING_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_VOCATIONAL_ED_TRAINING_HOP,
  CASE
    WHEN P2_VOCATIONAL_ED_TRAINING_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_VOCATIONAL_ED_TRAINING_HOP,
  -- JOB_SKILLS_TRAINING_HOP
  CASE
    WHEN AF_JOB_SKILLS_TRAINING_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_JOB_SKILLS_TRAINING_HOP,
  CASE
    WHEN P1_JOB_SKILLS_TRAINING_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_JOB_SKILLS_TRAINING_HOP,
  CASE
    WHEN P2_JOB_SKILLS_TRAINING_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_JOB_SKILLS_TRAINING_HOP,
  -- ED_NO_HIGH_SCHOOL_DIPL_HOP
  CASE
    WHEN AF_ED_NO_HIGH_SCHOOL_DIPL_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,
  CASE
    WHEN P1_ED_NO_HIGH_SCHOOL_DIPL_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,
  CASE
    WHEN P2_ED_NO_HIGH_SCHOOL_DIPL_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,
  -- SCHOOL_ATTENDENCE_HOP
  CASE
    WHEN AF_SCHOOL_ATTENDENCE_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_SCHOOL_ATTENDENCE_HOP,
  CASE
    WHEN P1_SCHOOL_ATTENDENCE_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_SCHOOL_ATTENDENCE_HOP,
  CASE
    WHEN P2_SCHOOL_ATTENDENCE_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_SCHOOL_ATTENDENCE_HOP,
  -- PROVIDE_CC_HOP
  CASE
    WHEN AF_PROVIDE_CC_HOP > 0 THEN 1
    ELSE 0
  END AS AF_N_PROVIDE_CC_HOP,
  CASE
    WHEN P1_PROVIDE_CC_HOP > 0 THEN 1
    ELSE 0
  END AS P1_N_PROVIDE_CC_HOP,
  CASE
    WHEN P2_PROVIDE_CC_HOP > 0 THEN 1
    ELSE 0
  END AS P2_N_PROVIDE_CC_HOP,
  -- OTHER_WORK_ACTIVITIES
  CASE
    WHEN AF_OTHER_WORK_ACTIVITIES > 0 THEN 1
    ELSE 0
  END AS AF_N_OTHER_WORK_ACTIVITIES,
  CASE
    WHEN P1_OTHER_WORK_ACTIVITIES > 0 THEN 1
    ELSE 0
  END AS P1_N_OTHER_WORK_ACTIVITIES,
  CASE
    WHEN P2_OTHER_WORK_ACTIVITIES > 0 THEN 1
    ELSE 0
  END AS P2_N_OTHER_WORK_ACTIVITIES
FROM
  ofa_sandbox.legacy_code.tan202408;
  --IDENTIFIER(tan_table_name);


CREATE OR REPLACE TEMPORARY VIEW summfle AS
SELECT
  FIPS_CODE,
  STRATUM,
  -- the function COALESCE(VAR,0) changes values from NULL to 0, which prevents NULL values --
  SUM(COALESCE(NSAMP,0)) AS NSAMP_SUM,
  SUM(COALESCE(NWORK,0)) AS NWORK_SUM,
  SUM(COALESCE(NDCARD1,0)) AS NDCARD1_SUM,
  SUM(COALESCE(NDCARD2,0)) AS NDCARD2_SUM,
  SUM(COALESCE(NEXEMPT,0)) AS NEXEMPT_SUM,
  SUM(COALESCE(NDCARD5,0)) AS NDCARD5_SUM,
  SUM(COALESCE(NLIM_VOC,0)) AS NLIM_VOC_SUM,
  SUM(COALESCE(NLIM_SSA,0)) AS NLIM_SSA_SUM,
  SUM(COALESCE(NLIM_EDE,0)) AS NLIM_EDE_SUM,
  SUM(COALESCE(NDEEM15,0)) AS NDEEM15_SUM,
  SUM(COALESCE(NDEEM16,0)) AS NDEEM16_SUM,
  SUM(COALESCE(NDEEM17,0)) AS NDEEM17_SUM,
  SUM(COALESCE(NDISABLE,0)) AS NDISABLE_SUM,
  SUM(COALESCE(NDCRD_PART,0)) AS NDCRD_PART_SUM,
  SUM(COALESCE(NDVEXEM,0)) AS NDVEXEM_SUM,
  SUM(COALESCE(N_WEI,0)) AS N_WEI_SUM,
  SUM(COALESCE(WRK_WEI,0)) AS WRK_WEI_SUM,
  SUM(COALESCE(HOL_WEI,0)) AS HOL_WEI_SUM,
  SUM(COALESCE(EXA_WEI,0)) AS EXA_WEI_SUM,
  SUM(COALESCE(WKHLEA_WEI,0)) AS WKHLEA_WEI_SUM,
  SUM(COALESCE(NGAGED,0)) AS NGAGED_SUM,
  SUM(COALESCE(NDEEMCOR,0)) AS NDEEMCOR_SUM,
  SUM(COALESCE(NSAMP_NO,0)) AS NSAMP_NO_SUM,
  SUM(COALESCE(TPSAMP,0)) AS TPSAMP_SUM,
  SUM(COALESCE(TPWORK,0)) AS TPWORK_SUM,
  SUM(COALESCE(TPLIM_VOC,0)) AS TPLIM_VOC_SUM,
  SUM(COALESCE(TPLIMIT,0)) AS TPLIMIT_SUM,
  SUM(COALESCE(TPDCARD2,0)) AS TPDCARD2_SUM,
  SUM(COALESCE(TPDCARD5,0)) AS TPDCARD5_SUM,
  SUM(COALESCE(TPDEEM,0)) AS TPDEEM_SUM,
  SUM(COALESCE(TPDVEXEM,0)) AS TPDVEXEM_SUM,
  SUM(COALESCE(TPNCP,0)) AS TPNCP_SUM,
  SUM(COALESCE(TPDCRD_PART,0)) AS TPDCRD_PART_SUM,
  SUM(COALESCE(TPDABLE,0)) AS TPDABLE_SUM,
  SUM(COALESCE(TPDEEMCOR,0)) AS TPDEEMCOR_SUM,
  SUM(COALESCE(AF_N_UNSUB_EMPLOYMENT,0)) AS AF_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(AF_N_SUB_PRIVATE_EMPLOYMENT,0)) AS AF_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(AF_N_SUB_PUBLIC_EMPLOYMENT,0)) AS AF_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(AF_N_WORK_EXPERIENCE_HOP,0)) AS AF_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(AF_N_OJT,0)) AS AF_OJT_SUM,
  SUM(COALESCE(AF_N_JOB_SEARCH_HOP,0)) AS AF_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(AF_N_COMM_SERVICES_HOP,0)) AS AF_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(AF_N_VOCATIONAL_ED_TRAINING_HOP,0)) AS AF_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(AF_N_JOB_SKILLS_TRAINING_HOP,0)) AS AF_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(AF_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS AF_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(AF_N_SCHOOL_ATTENDENCE_HOP,0)) AS AF_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(AF_N_PROVIDE_CC_HOP,0)) AS AF_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(AF_N_OTHER_WORK_ACTIVITIES,0)) AS AF_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(P1_N_UNSUB_EMPLOYMENT,0)) AS P1_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(P1_N_SUB_PRIVATE_EMPLOYMENT,0)) AS P1_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(P1_N_SUB_PUBLIC_EMPLOYMENT,0)) AS P1_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(P1_N_WORK_EXPERIENCE_HOP,0)) AS P1_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(P1_N_OJT,0)) AS P1_OJT_SUM,
  SUM(COALESCE(P1_N_JOB_SEARCH_HOP,0)) AS P1_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(P1_N_COMM_SERVICES_HOP,0)) AS P1_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(P1_N_VOCATIONAL_ED_TRAINING_HOP,0)) AS P1_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(P1_N_JOB_SKILLS_TRAINING_HOP,0)) AS P1_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(P1_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS P1_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(P1_N_SCHOOL_ATTENDENCE_HOP,0)) AS P1_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(P1_N_PROVIDE_CC_HOP,0)) AS P1_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(P1_N_OTHER_WORK_ACTIVITIES,0)) AS P1_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(P2_N_UNSUB_EMPLOYMENT,0)) AS P2_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(P2_N_SUB_PRIVATE_EMPLOYMENT,0)) AS P2_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(P2_N_SUB_PUBLIC_EMPLOYMENT,0)) AS P2_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(P2_N_WORK_EXPERIENCE_HOP,0)) AS P2_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(P2_N_OJT,0)) AS P2_OJT_SUM,
  SUM(COALESCE(P2_N_JOB_SEARCH_HOP,0)) AS P2_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(P2_N_COMM_SERVICES_HOP,0)) AS P2_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(P2_N_VOCATIONAL_ED_TRAINING_HOP,0)) AS P2_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(P2_N_JOB_SKILLS_TRAINING_HOP,0)) AS P2_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(P2_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS P2_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(P2_N_SCHOOL_ATTENDENCE_HOP,0)) AS P2_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(P2_N_PROVIDE_CC_HOP,0)) AS P2_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(P2_N_OTHER_WORK_ACTIVITIES,0)) AS P2_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(TPER_UNSUB_EMPLOYMENT,0)) AS TPER_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(TPER_SUB_PRIVATE_EMPLOYMENT,0)) AS TPER_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(TPER_SUB_PUBLIC_EMPLOYMENT,0)) AS TPER_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(TPER_WORK_EXPERIENCE_HOP,0)) AS TPER_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(TPER_OJT,0)) AS TPER_OJT_SUM,
  SUM(COALESCE(TPER_JOB_SEARCH_HOP,0)) AS TPER_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(TPER_COMM_SERVICES_HOP,0)) AS TPER_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(TPER_VOCATIONAL_ED_TRAINING_HOP,0)) AS TPER_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(TPER_JOB_SKILLS_TRAINING_HOP,0)) AS TPER_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(TPER_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS TPER_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(TPER_SCHOOL_ATTENDENCE_HOP,0)) AS TPER_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(TPER_PROVIDE_CC_HOP,0)) AS TPER_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(TPER_OTHER_WORK_ACTIVITIES,0)) AS TPER_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(THRS_UNSUB_EMPLOYMENT,0)) AS THRS_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(THRS_SUB_PRIVATE_EMPLOYMENT,0)) AS THRS_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(THRS_SUB_PUBLIC_EMPLOYMENT,0)) AS THRS_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(THRS_WORK_EXPERIENCE_HOP,0)) AS THRS_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(THRS_OJT,0)) AS THRS_OJT_SUM,
  SUM(COALESCE(THRS_JOB_SEARCH_HOP,0)) AS THRS_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(THRS_COMM_SERVICES_HOP,0)) AS THRS_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(THRS_VOCATIONAL_ED_TRAINING_HOP,0)) AS THRS_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(THRS_JOB_SKILLS_TRAINING_HOP,0)) AS THRS_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(THRS_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS THRS_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(THRS_SCHOOL_ATTENDENCE_HOP,0)) AS THRS_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(THRS_PROVIDE_CC_HOP,0)) AS THRS_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(THRS_OTHER_WORK_ACTIVITIES,0)) AS THRS_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(AF_N_UNSUB_EMPLOYMENT,0)) AS AF_N_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(AF_N_SUB_PRIVATE_EMPLOYMENT,0)) AS AF_N_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(AF_N_SUB_PUBLIC_EMPLOYMENT,0)) AS AF_N_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(AF_N_WORK_EXPERIENCE_HOP,0)) AS AF_N_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(AF_N_OJT,0)) AS AF_N_OJT_SUM,
  SUM(COALESCE(AF_N_JOB_SEARCH_HOP,0)) AS AF_N_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(AF_N_COMM_SERVICES_HOP,0)) AS AF_N_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(AF_N_VOCATIONAL_ED_TRAINING_HOP,0)) AS AF_N_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(AF_N_JOB_SKILLS_TRAINING_HOP,0)) AS AF_N_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(AF_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS AF_N_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(AF_N_SCHOOL_ATTENDENCE_HOP,0)) AS AF_N_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(AF_N_PROVIDE_CC_HOP,0)) AS AF_N_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(AF_N_OTHER_WORK_ACTIVITIES,0)) AS AF_N_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(P1_N_UNSUB_EMPLOYMENT,0)) AS P1_N_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(P1_N_SUB_PRIVATE_EMPLOYMENT,0)) AS P1_N_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(P1_N_SUB_PUBLIC_EMPLOYMENT,0)) AS P1_N_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(P1_N_WORK_EXPERIENCE_HOP,0)) AS P1_N_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(P1_N_OJT,0)) AS P1_N_OJT_SUM,
  SUM(COALESCE(P1_N_JOB_SEARCH_HOP,0)) AS P1_N_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(P1_N_COMM_SERVICES_HOP,0)) AS P1_N_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(P1_N_VOCATIONAL_ED_TRAINING_HOP,0)) AS P1_N_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(P1_N_JOB_SKILLS_TRAINING_HOP,0)) AS P1_N_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(P1_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS P1_N_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(P1_N_SCHOOL_ATTENDENCE_HOP,0)) AS P1_N_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(P1_N_PROVIDE_CC_HOP,0)) AS P1_N_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(P1_N_OTHER_WORK_ACTIVITIES,0)) AS P1_N_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(P2_N_UNSUB_EMPLOYMENT,0)) AS P2_N_UNSUB_EMPLOYMENT_SUM,
  SUM(COALESCE(P2_N_SUB_PRIVATE_EMPLOYMENT,0)) AS P2_N_SUB_PRIVATE_EMPLOYMENT_SUM,
  SUM(COALESCE(P2_N_SUB_PUBLIC_EMPLOYMENT,0)) AS P2_N_SUB_PUBLIC_EMPLOYMENT_SUM,
  SUM(COALESCE(P2_N_WORK_EXPERIENCE_HOP,0)) AS P2_N_WORK_EXPERIENCE_HOP_SUM,
  SUM(COALESCE(P2_N_OJT,0)) AS P2_N_OJT_SUM,
  SUM(COALESCE(P2_N_JOB_SEARCH_HOP,0)) AS P2_N_JOB_SEARCH_HOP_SUM,
  SUM(COALESCE(P2_N_COMM_SERVICES_HOP,0)) AS P2_N_COMM_SERVICES_HOP_SUM,
  SUM(COALESCE(P2_N_VOCATIONAL_ED_TRAINING_HOP,0)) AS P2_N_VOCATIONAL_ED_TRAINING_HOP_SUM,
  SUM(COALESCE(P2_N_JOB_SKILLS_TRAINING_HOP,0)) AS P2_N_JOB_SKILLS_TRAINING_HOP_SUM,
  SUM(COALESCE(P2_N_ED_NO_HIGH_SCHOOL_DIPL_HOP,0)) AS P2_N_ED_NO_HIGH_SCHOOL_DIPL_HOP_SUM,
  SUM(COALESCE(P2_N_SCHOOL_ATTENDENCE_HOP,0)) AS P2_N_SCHOOL_ATTENDENCE_HOP_SUM,
  SUM(COALESCE(P2_N_PROVIDE_CC_HOP,0)) AS P2_N_PROVIDE_CC_HOP_SUM,
  SUM(COALESCE(P2_N_OTHER_WORK_ACTIVITIES,0)) AS P2_N_OTHER_WORK_ACTIVITIES_SUM,
  SUM(COALESCE(AF_WORK_EXPERIENCE_HOL,0)) AS AF_WORK_EXPERIENCE_HOL_SUM,
  SUM(COALESCE(AF_JOB_SEARCH_HOL,0)) AS AF_JOB_SEARCH_HOL_SUM,
  SUM(COALESCE(AF_COMM_SERVICES_HOL,0)) AS AF_COMM_SERVICES_HOL_SUM,
  SUM(COALESCE(AF_VOCATIONAL_ED_TRAINING_HOL,0)) AS AF_VOCATIONAL_ED_TRAINING_HOL_SUM,
  SUM(COALESCE(AF_JOB_SKILLS_TRAINING_HOL,0)) AS AF_JOB_SKILLS_TRAINING_HOL_SUM,
  SUM(COALESCE(AF_ED_NO_HIGH_SCHOOL_DIPL_HOL,0)) AS AF_ED_NO_HIGH_SCHOOL_DIPL_HOL_SUM,
  SUM(COALESCE(AF_SCHOOL_ATTENDENCE_HOL,0)) AS AF_SCHOOL_ATTENDENCE_HOL_SUM,
  SUM(COALESCE(AF_PROVIDE_CC_HOL,0)) AS AF_PROVIDE_CC_HOL_SUM,
  SUM(COALESCE(P1_WORK_EXPERIENCE_HOL,0)) AS P1_WORK_EXPERIENCE_HOL_SUM,
  SUM(COALESCE(P1_JOB_SEARCH_HOL,0)) AS P1_JOB_SEARCH_HOL_SUM,
  SUM(COALESCE(P1_COMM_SERVICES_HOL,0)) AS P1_COMM_SERVICES_HOL_SUM,
  SUM(COALESCE(P1_VOCATIONAL_ED_TRAINING_HOL,0)) AS P1_VOCATIONAL_ED_TRAINING_HOL_SUM,
  SUM(COALESCE(P1_JOB_SKILLS_TRAINING_HOL,0)) AS P1_JOB_SKILLS_TRAINING_HOL_SUM,
  SUM(COALESCE(P1_ED_NO_HIGH_SCHOOL_DIPL_HOL,0)) AS P1_ED_NO_HIGH_SCHOOL_DIPL_HOL_SUM,
  SUM(COALESCE(P1_SCHOOL_ATTENDENCE_HOL,0)) AS P1_SCHOOL_ATTENDENCE_HOL_SUM,
  SUM(COALESCE(P1_PROVIDE_CC_HOL,0)) AS P1_PROVIDE_CC_HOL_SUM,
  SUM(COALESCE(P2_WORK_EXPERIENCE_HOL,0)) AS P2_WORK_EXPERIENCE_HOL_SUM,
  SUM(COALESCE(P2_JOB_SEARCH_HOL,0)) AS P2_JOB_SEARCH_HOL_SUM,
  SUM(COALESCE(P2_COMM_SERVICES_HOL,0)) AS P2_COMM_SERVICES_HOL_SUM,
  SUM(COALESCE(P2_VOCATIONAL_ED_TRAINING_HOL,0)) AS P2_VOCATIONAL_ED_TRAINING_HOL_SUM,
  SUM(COALESCE(P2_JOB_SKILLS_TRAINING_HOL,0)) AS P2_JOB_SKILLS_TRAINING_HOL_SUM,
  SUM(COALESCE(P2_ED_NO_HIGH_SCHOOL_DIPL_HOL,0)) AS P2_ED_NO_HIGH_SCHOOL_DIPL_HOL_SUM,
  SUM(COALESCE(P2_SCHOOL_ATTENDENCE_HOL,0)) AS P2_SCHOOL_ATTENDENCE_HOL_SUM,
  SUM(COALESCE(P2_PROVIDE_CC_HOL,0)) AS P2_PROVIDE_CC_HOL_SUM,
  SUM(COALESCE(TPER_WORK_EXPERIENCE_HOL,0)) AS TPER_WORK_EXPERIENCE_HOL_SUM,
  SUM(COALESCE(TPER_JOB_SEARCH_HOL,0)) AS TPER_JOB_SEARCH_HOL_SUM,
  SUM(COALESCE(TPER_COMM_SERVICES_HOL,0)) AS TPER_COMM_SERVICES_HOL_SUM,
  SUM(COALESCE(TPER_VOCATIONAL_ED_TRAINING_HOL,0)) AS TPER_VOCATIONAL_ED_TRAINING_HOL_SUM,
  SUM(COALESCE(TPER_JOB_SKILLS_TRAINING_HOL,0)) AS TPER_JOB_SKILLS_TRAINING_HOL_SUM,
  SUM(COALESCE(TPER_ED_NO_HIGH_SCHOOL_DIPL_HOL,0)) AS TPER_ED_NO_HIGH_SCHOOL_DIPL_HOL_SUM,
  SUM(COALESCE(TPER_SCHOOL_ATTENDENCE_HOL,0)) AS TPER_SCHOOL_ATTENDENCE_HOL_SUM,
  SUM(COALESCE(TPER_PROVIDE_CC_HOL,0)) AS TPER_PROVIDE_CC_HOL_SUM,
  SUM(COALESCE(THRS_WORK_EXPERIENCE_HOL,0)) AS THRS_WORK_EXPERIENCE_HOL_SUM,
  SUM(COALESCE(THRS_JOB_SEARCH_HOL,0)) AS THRS_JOB_SEARCH_HOL_SUM,
  SUM(COALESCE(THRS_COMM_SERVICES_HOL,0)) AS THRS_COMM_SERVICES_HOL_SUM,
  SUM(COALESCE(THRS_VOCATIONAL_ED_TRAINING_HOL,0)) AS THRS_VOCATIONAL_ED_TRAINING_HOL_SUM,
  SUM(COALESCE(THRS_JOB_SKILLS_TRAINING_HOL,0)) AS THRS_JOB_SKILLS_TRAINING_HOL_SUM,
  SUM(COALESCE(THRS_ED_NO_HIGH_SCHOOL_DIPL_HOL,0)) AS THRS_ED_NO_HIGH_SCHOOL_DIPL_HOL_SUM,
  SUM(COALESCE(THRS_SCHOOL_ATTENDENCE_HOL,0)) AS THRS_SCHOOL_ATTENDENCE_HOL_SUM,
  SUM(COALESCE(THRS_PROVIDE_CC_HOL,0)) AS THRS_PROVIDE_CC_HOL_SUM,
  SUM(COALESCE(AF_WORK_EXPERIENCE_EA,0)) AS AF_WORK_EXPERIENCE_EA_SUM,
  SUM(COALESCE(AF_JOB_SEARCH_EA,0)) AS AF_JOB_SEARCH_EA_SUM,
  SUM(COALESCE(AF_COMM_SERVICES_EA,0)) AS AF_COMM_SERVICES_EA_SUM,
  SUM(COALESCE(AF_VOCATIONAL_ED_TRAINING_EA,0)) AS AF_VOCATIONAL_ED_TRAINING_EA_SUM,
  SUM(COALESCE(AF_JOB_SKILLS_TRAINING_EA,0)) AS AF_JOB_SKILLS_TRAINING_EA_SUM,
  SUM(COALESCE(AF_ED_NO_HIGH_SCHOOL_DIPL_EA,0)) AS AF_ED_NO_HIGH_SCHOOL_DIPL_EA_SUM,
  SUM(COALESCE(AF_SCHOOL_ATTENDENCE_EA,0)) AS AF_SCHOOL_ATTENDENCE_EA_SUM,
  SUM(COALESCE(AF_PROVIDE_CC_EA,0)) AS AF_PROVIDE_CC_EA_SUM,
  SUM(COALESCE(P1_WORK_EXPERIENCE_EA,0)) AS P1_WORK_EXPERIENCE_EA_SUM,
  SUM(COALESCE(P1_JOB_SEARCH_EA,0)) AS P1_JOB_SEARCH_EA_SUM,
  SUM(COALESCE(P1_COMM_SERVICES_EA,0)) AS P1_COMM_SERVICES_EA_SUM,
  SUM(COALESCE(P1_VOCATIONAL_ED_TRAINING_EA,0)) AS P1_VOCATIONAL_ED_TRAINING_EA_SUM,
  SUM(COALESCE(P1_JOB_SKILLS_TRAINING_EA,0)) AS P1_JOB_SKILLS_TRAINING_EA_SUM,
  SUM(COALESCE(P1_ED_NO_HIGH_SCHOOL_DIPL_EA,0)) AS P1_ED_NO_HIGH_SCHOOL_DIPL_EA_SUM,
  SUM(COALESCE(P1_SCHOOL_ATTENDENCE_EA,0)) AS P1_SCHOOL_ATTENDENCE_EA_SUM,
  SUM(COALESCE(P1_PROVIDE_CC_EA,0)) AS P1_PROVIDE_CC_EA_SUM,
  SUM(COALESCE(P2_WORK_EXPERIENCE_EA,0)) AS P2_WORK_EXPERIENCE_EA_SUM,
  SUM(COALESCE(P2_JOB_SEARCH_EA,0)) AS P2_JOB_SEARCH_EA_SUM,
  SUM(COALESCE(P2_COMM_SERVICES_EA,0)) AS P2_COMM_SERVICES_EA_SUM,
  SUM(COALESCE(P2_VOCATIONAL_ED_TRAINING_EA,0)) AS P2_VOCATIONAL_ED_TRAINING_EA_SUM,
  SUM(COALESCE(P2_JOB_SKILLS_TRAINING_EA,0)) AS P2_JOB_SKILLS_TRAINING_EA_SUM,
  SUM(COALESCE(P2_ED_NO_HIGH_SCHOOL_DIPL_EA,0)) AS P2_ED_NO_HIGH_SCHOOL_DIPL_EA_SUM,
  SUM(COALESCE(P2_SCHOOL_ATTENDENCE_EA,0)) AS P2_SCHOOL_ATTENDENCE_EA_SUM,
  SUM(COALESCE(P2_PROVIDE_CC_EA,0)) AS P2_PROVIDE_CC_EA_SUM,
  SUM(COALESCE(TPER_WORK_EXPERIENCE_EA,0)) AS TPER_WORK_EXPERIENCE_EA_SUM,
  SUM(COALESCE(TPER_JOB_SEARCH_EA,0)) AS TPER_JOB_SEARCH_EA_SUM,
  SUM(COALESCE(TPER_COMM_SERVICES_EA,0)) AS TPER_COMM_SERVICES_EA_SUM,
  SUM(COALESCE(TPER_VOCATIONAL_ED_TRAINING_EA,0)) AS TPER_VOCATIONAL_ED_TRAINING_EA_SUM,
  SUM(COALESCE(TPER_JOB_SKILLS_TRAINING_EA,0)) AS TPER_JOB_SKILLS_TRAINING_EA_SUM,
  SUM(COALESCE(TPER_ED_NO_HIGH_SCHOOL_DIPL_EA,0)) AS TPER_ED_NO_HIGH_SCHOOL_DIPL_EA_SUM,
  SUM(COALESCE(TPER_SCHOOL_ATTENDENCE_EA,0)) AS TPER_SCHOOL_ATTENDENCE_EA_SUM,
  SUM(COALESCE(TPER_PROVIDE_CC_EA,0)) AS TPER_PROVIDE_CC_EA_SUM,
  SUM(COALESCE(THRS_WORK_EXPERIENCE_EA,0)) AS THRS_WORK_EXPERIENCE_EA_SUM,
  SUM(COALESCE(THRS_JOB_SEARCH_EA,0)) AS THRS_JOB_SEARCH_EA_SUM,
  SUM(COALESCE(THRS_COMM_SERVICES_EA,0)) AS THRS_COMM_SERVICES_EA_SUM,
  SUM(COALESCE(THRS_VOCATIONAL_ED_TRAINING_EA,0)) AS THRS_VOCATIONAL_ED_TRAINING_EA_SUM,
  SUM(COALESCE(THRS_JOB_SKILLS_TRAINING_EA,0)) AS THRS_JOB_SKILLS_TRAINING_EA_SUM,
  SUM(COALESCE(THRS_ED_NO_HIGH_SCHOOL_DIPL_EA,0)) AS THRS_ED_NO_HIGH_SCHOOL_DIPL_EA_SUM,
  SUM(COALESCE(THRS_SCHOOL_ATTENDENCE_EA,0)) AS THRS_SCHOOL_ATTENDENCE_EA_SUM,
  SUM(COALESCE(THRS_PROVIDE_CC_EA,0)) AS THRS_PROVIDE_CC_EA_SUM
FROM
  summfle1
WHERE
  FIPS_CODE IS NOT NULL AND
  STRATUM IS NOT NULL
GROUP BY
  FIPS_CODE,
  STRATUM;


# %%
-----------------------------------------------
-- Step 4: Merge sum file with weighted file --
-----------------------------------------------

CREATE OR REPLACE TEMPORARY VIEW combo1 AS
SELECT
  weight.FIPS_CODE,
  weight.CASES,
  weight.WGHT,
  summfle.* EXCEPT (FIPS_CODE)
FROM
  summfle
    INNER JOIN weight
    ON
      summfle.FIPS_CODE = weight.FIPS_CODE AND
      summfle.STRATUM = weight.STRATUM;


CREATE OR REPLACE TEMPORARY VIEW combo AS
SELECT
  *,
  WGHT * NSAMP_SUM AS WNSAMP,
  WGHT * NWORK_SUM AS WNWORK,
  WGHT * NDCARD1_SUM AS WNDCARD1,
  WGHT * NDCARD2_SUM AS WNDCARD2,
  WGHT * NEXEMPT_SUM AS WNEXEMPT,
  WGHT * NDCARD5_SUM AS WNDCARD5,
  WGHT * NLIM_VOC_SUM AS WNLIM_VOC,
  WGHT * NLIM_SSA_SUM AS WNLIM_SSA,
  WGHT * NLIM_EDE_SUM AS WNLIM_EDE,
  WGHT * NDEEM15_SUM AS WNDEEM15,
  WGHT * NDEEM16_SUM AS WNDEEM16,
  WGHT * NDEEM17_SUM AS WNDEEM17,
  WGHT * NDCRD_PART_SUM AS WNDCRD_PART,
  WGHT * NDEEMCOR_SUM AS WNDEEMCOR,
  WGHT * N_WEI_SUM AS WN_WEI,
  WGHT * NDVEXEM_SUM AS WNDVEXEM,
  WGHT * NDISABLE_SUM AS WNDISABLE,
  WGHT * TPSAMP_SUM AS WTPSAMP,
  WGHT * TPWORK_SUM AS WTPWORK,
  WGHT * TPDCRD_PART_SUM AS  WTPDCRD_PART,
  WGHT * TPLIM_VOC_SUM AS WTPLIM_VOC,
  WGHT * TPLIMIT_SUM AS WTPLIMIT,
  WGHT * TPDCARD2_SUM AS WTPDCARD2,
  WGHT * TPDCARD5_SUM AS WTPDCARD5,
  WGHT * TPDEEM_SUM AS WTPDEEM,
  WGHT * TPDVEXEM_SUM AS WTPDVEXEM,
  WGHT * TPNCP_SUM AS WTPNCP,
  WGHT * TPDABLE_SUM AS WTPDABLE,
  WGHT * WRK_WEI_SUM AS WWRK_WEI,
  WGHT * EXA_WEI_SUM AS WEXA_WEI,
  WGHT * NGAGED_SUM AS WNGAGED,
  WGHT * TPDEEMCOR_SUM AS WTPDMCOR
FROM
  combo1;


# %%
%python

#This dataframe is called "MONTH &ym. DATA FOR WPR CALCULATIONS"

combo = spark.table('combo')

(
    combo
    .write
    .mode("overwrite")
    .option("overwriteSchema","true")
    #.saveAsTable(f'\\Volumes\\ofa_sandbox\\legacy_code\\test_df')
    .saveAsTable(f"ofa_sandbox.legacy_code.MONTH_{ym}_DATA_FOR_WPR_CALCULATIONS")
)

# %%
-----------------------------------------
-- Step 5: Create summarized sum files --
-----------------------------------------

CREATE OR REPLACE TEMPORARY VIEW stsumfl1 AS
SELECT
  FIPS_CODE,
  SUM(WNSAMP) AS AFSAMP,
  SUM(WNWORK) AS AFNWORK,
  SUM(WNDCARD1) AS AFDCARD1,
  SUM(WNDCARD2) AS AFDCARD2,
  SUM(WNEXEMPT) AS AFEXEMPT,
  SUM(WNDCARD5) AS AFDCARD5,
  SUM(WNLIM_VOC) AS AFLIM_VOC,
  SUM(WNLIM_SSA) AS AFLIM_SSA,
  SUM(WNLIM_EDE) AS AFLIM_EDE,
  SUM(WNDEEM15) AS AFDEEM15,
  SUM(WNDEEM16) AS AFDEEM16,
  SUM(WNDEEM17) AS AFDEEM17,
  SUM(WNDEEMCOR) AS AFDEEMCOR,
  SUM(WNDCRD_PART) AS ANDCRD_PART,
  SUM(WTPSAMP) AS ATPSAMP,
  SUM(WTPWORK) AS ATPWORK,
  SUM(WTPLIM_VOC) AS ATPLIM_VOC,
  SUM(WTPLIMIT) AS ATPLIMIT,
  SUM(WNDISABLE) AS ANDISABLE,
  SUM(WTPDCARD2) AS ATPDCARD2,
  SUM(WTPDCARD5) AS ATPDCARD5,
  SUM(WNDVEXEM) AS AFDVEXEM,
  SUM(WTPDVEXEM) AS ATPDVEXEM,
  SUM(WTPNCP) AS ATPNCP,
  SUM(WTPDABLE) AS ATPDABLE,
  SUM(WTPDCRD_PART) AS ATPDCRD_PART
FROM
  combo
GROUP BY
  FIPS_CODE;

CREATE OR REPLACE TEMPORARY VIEW stsumfl2 AS
SELECT
  *,
  AFLIM_VOC + AFLIM_SSA + AFLIM_EDE AS AFLIMIT,
  ATPLIM_VOC + ATPLIMIT AS ATPTOTLIM,
  AFSAMP - (AFDCARD1 + AFDCARD2 + AFDCARD5) + ANDCRD_PART AS AF_DENUM,
  ATPSAMP - (ATPDCARD2 + ATPDCARD5 + ATPNCP + ATPDABLE) + ATPDCRD_PART AS TP_DENUM,
  (AFSAMP - (AFDCARD1 + AFDCARD2 + AFDCARD5) + ANDCRD_PART) - AFDVEXEM AS AF_ADJD,
  (ATPSAMP - (ATPDCARD2 + ATPDCARD5 + ATPNCP + ATPDABLE) + ATPDCRD_PART) - ATPDVEXEM AS ATP_ADJD,
  CASE
    WHEN (AFLIM_VOC + AFLIM_SSA + AFLIM_EDE) > (0.3 * AFNWORK) and (AFNWORK > (AFLIM_VOC + AFLIM_SSA + AFLIM_EDE)) THEN (AFNWORK - (AFLIM_VOC + AFLIM_SSA + AFLIM_EDE)) / (0.7)
    ELSE 0
  END AS AFLIMWK,
  CASE
    WHEN (ATPLIM_VOC + ATPLIMIT) > (0.3 * ATPWORK)  and (ATPWORK > (ATPLIM_VOC + ATPLIMIT)) THEN (ATPWORK - (ATPLIM_VOC + ATPLIMIT)) / (0.7)
    ELSE 0
  END AS ATPLIMWK
FROM
  stsumfl1;

CREATE OR REPLACE TEMPORARY VIEW stsumfl AS
SELECT
  *,
  CASE
    WHEN AFLIMWK > 0 THEN AFLIMWK
    ELSE AFNWORK
  END AS AF_ADJN,
  CASE
    WHEN ATPLIMWK > 0 THEN ATPLIMWK
    ELSE ATPWORK
  END AS ATP_ADJN
FROM
  stsumfl2;

-- For the following code, I believe it's then recorded in a table called old.denum&fy. which I think records each rate for each state through each month --

CREATE OR REPLACE TEMPORARY VIEW allsumfl AS
SELECT
  *,
  -- the function try_divide returns NULL if the denominator is NULL --
  round(100 * try_divide(AFNWORK, AF_DENUM), 0.1) AS AF_PRATE,
  round(100 * try_divide(AFLIMWK, AF_DENUM), 0.1) AS AF_LRATE,
  round(100 * try_divide(AF_ADJN, AF_DENUM), 0.1) AS AF_ARATE,
  round(100 * try_divide(ATPWORK, TP_DENUM), 0.1) AS TP_PRATE,
  round(100 * try_divide(ATPLIMWK, TP_DENUM), 0.1) AS TP_LRATE,
  round(100 * try_divide(ATP_ADJN, TP_DENUM), 0.1) AS TP_ARATE,
  round(100 * try_divide(AF_ADJN, AF_ADJD), 0.1) AS AF_VRATE,
  round(100 * try_divide(ATP_ADJN, ATP_ADJD), 0.1) AS TP_VRATE
  -- also some variables are renamed, but I think that might need to be done later because they have variables in the names
FROM
  stsumfl;


CREATE OR REPLACE TABLE IDENTIFIER(wpr_table_name) AS
  SELECT *
FROM
  allsumfl;

-- at this point, I think the final thing to do is to bring in the rates for each month of the past year, and then add the above variables to a new dataframe --
-- need to look through the data to verify --

-- I think I should create separate table for this month's WPR rate, and then in a separate script (or later in this one), just pull in the previous year's rates into one combined file

-- afterwards, the following tables are easy to create:

-- "Month &ym. Den/Num FOR WPR CALCULATIONS"
-- this is just WPR printed out

-- "Work Particiaption Rates for TANF in &ym."
-- this is AFM&ym.WPR and TPM&ym.WPR by State

-- "NUM/DEN for TANF in &ym."
-- this is
-- AFM&ym.WRK AFM&ym.DEN AFM&ym.WPR
-- TPM&ym.WRK TPM&ym.DEN TPM&ym.WPR
-- AFM&ym.WRK AFM&ym.DEN AFM&ym.WPR
-- TPM&ym.WRK TPM&ym.DEN TPM&ym.WPR

-- "Work Particiaption Rates for TANF in &ym"
-- "with Voc. Ed in Excess Limit"
-- This is state AFM&ym.LPR and TPM&ym.LPR by State

-- "Work Particiaption Rates for TANF in &ym."
-- "Ajusted for Voc. Ed in Excess Limit with DV waiver"
-- this is state AFM&ym.APR and TPM&ym.APR by State


# %%
SELECT FIPS_CODE, COUNT(*) FROM weight GROUP BY FIPS_CODE;

-- slightly off - probably a rounding error --
-- missing values are also discarded in SQL - need to ensure that they are in the full version --

# %%
%python

df_sas = spark.read.table('ofa_sandbox.legacy_code.weight_2024_a_sas').toPandas()

# %%
%python

df_sas = df_sas[df_sas['RPT_MONTH_YEAR'] == 202408]

df_sas = df_sas[df_sas['fips'] == 8]

print(df_sas)

#two questions

#how often is this report pulled? Monthly, right?

#for 8 stratum 2, the wght is null - should this be excluded, then?

# %%
%python

df_sas.groupby(['fips']).size()
