# %% [markdown]
#
# # PART 4: CREATING TIME-LIMIT REPORTS
#
# The fourth part of this project is to create the time-limited reports, which use specific Time-limit variables.

# %%
---------------------------------------------
-- Step 1: Create the time limit variables --
---------------------------------------------

CREATE OR REPLACE TEMPORARY VIEW family AS
SELECT
  FIPS_CODE,
  CASE_NUMBER AS CASE_ID,
  REGION,
  STRATUM,
  FUNDING_STREAM AS FUNDING,
  FAMILY_TYPE AS TYPE_FAM,
  FAMILY_EXEMPT_TIME_LIMITS AS FEXMPT_TL,
  RPT_MONTH_YEAR
FROM
  read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T1_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	);

CREATE OR REPLACE TEMPORARY VIEW adult AS
SELECT
  FIPS_CODE,
  CASE_NUMBER AS CASE_ID,
  FAMILY_AFFILIATION,
  NONCUSTODIAL_PARENT,
  -- ADULT_AGE in the SAS code but this should still work
  AGE_FIRST AS AGE_1,
  MARITAL_STATUS,
  RELATIONSHIP_HOH,
  MONTHS_FED_TIME_LIMIT,
  RPT_MONTH_YEAR
FROM
	read_files(
		'/Volumes/ofa_sandbox/legacy_code/input/TANF_T2_DataSurge_2025-09-10-084149.csv',
		format => 'csv',
		header => 'true',
		sep => ','
	);

CREATE OR REPLACE TEMPORARY VIEW combo1 AS
SELECT
  family.*,
  adult.* EXCEPT (FIPS_CODE, CASE_ID, RPT_MONTH_YEAR)
  -- flag for RELATIONSHIP_HOH in (1,2) to be summed in future step
  --RELATIONSHIP_HOH in (1,2) AS RELATIONSHIP_HOH_FLAG,
  -- flag for RELATIONSHIP_HOH in (1,2) and FAMILY_AFFILIATION = 1 to be summed in future step
  --RELATIONSHIP_HOH in (1,2) AND FAMILY_AFFILIATION = 1 AS RELATIONSHIP_HOH_FAMILY_AFFILIATION_FLAG
FROM
  family
  INNER JOIN adult ON
    family.FIPS_CODE = adult.FIPS_CODE AND
    family.RPT_MONTH_YEAR = adult.RPT_MONTH_YEAR AND
    family.CASE_ID = adult.CASE_ID;

-- calculate some summary variables when are later merged into the original dataset --

CREATE OR REPLACE TEMPORARY VIEW combo2 AS
SELECT
  --*,
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_ID,
  SUM(FAMILY_AFFILIATION) AS NADULT,
  SUM(CASE WHEN RELATIONSHIP_HOH IN (1,2) THEN 1 ELSE 0 END) AS NHOH,
  SUM(CASE WHEN RELATIONSHIP_HOH IN (1,2) AND FAMILY_AFFILIATION = 1 THEN 1 ELSE 0 END) AS NHOH_REC
FROM combo1
GROUP BY
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_ID;

CREATE OR REPLACE TEMPORARY VIEW combo3 AS
SELECT
  combo1.*,
  combo2.* EXCEPT (FIPS_CODE, RPT_MONTH_YEAR, CASE_ID),
  CASE
    WHEN RELATIONSHIP_HOH IN (1,2) THEN 1
    ELSE 2
  END AS AHEAD
FROM
  combo1
  INNER JOIN combo2 ON
    combo1.FIPS_CODE = combo2.FIPS_CODE AND
    combo1.RPT_MONTH_YEAR = combo2.RPT_MONTH_YEAR AND
    combo1.CASE_ID = combo2.CASE_ID;

CREATE OR REPLACE TEMPORARY VIEW combo4 AS
WITH CTA AS (
  SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY CASE_ID ORDER BY FIPS_CODE, RPT_MONTH_YEAR, CASE_ID, RELATIONSHIP_HOH, MONTHS_FED_TIME_LIMIT DESC, NHOH_REC DESC) AS ROWNUM
  FROM
    combo3
)
SELECT
  *
FROM
  CTA
WHERE
  ROWNUM = 1
ORDER BY
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_ID,
  RELATIONSHIP_HOH,
  MONTHS_FED_TIME_LIMIT DESC,
  NHOH_REC DESC;

CREATE OR REPLACE TEMPORARY VIEW combo5 AS
SELECT
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_ID,
  SUM(CASE WHEN MONTHS_FED_TIME_LIMIT <= 0 THEN 1 ELSE 0 END) AS CM_0,
  SUM(CASE WHEN 0<MONTHS_FED_TIME_LIMIT AND MONTHS_FED_TIME_LIMIT<=12 THEN 1 ELSE 0 END) AS CM01_12,
  SUM(CASE WHEN 12<MONTHS_FED_TIME_LIMIT AND MONTHS_FED_TIME_LIMIT<=24 THEN 1 ELSE 0 END) AS CM13_24,
  SUM(CASE WHEN 24<MONTHS_FED_TIME_LIMIT AND MONTHS_FED_TIME_LIMIT<=36 THEN 1 ELSE 0 END) AS CM25_36,
  SUM(CASE WHEN 36<MONTHS_FED_TIME_LIMIT AND MONTHS_FED_TIME_LIMIT<=48 THEN 1 ELSE 0 END) AS CM37_48,
  SUM(CASE WHEN 48<MONTHS_FED_TIME_LIMIT AND MONTHS_FED_TIME_LIMIT<=59 THEN 1 ELSE 0 END) AS CM49_59,
  SUM(CASE WHEN MONTHS_FED_TIME_LIMIT = 60 THEN 1 ELSE 0 END) AS CM60,
  SUM(CASE WHEN MONTHS_FED_TIME_LIMIT>60 THEN 1 ELSE 0 END) AS OVER60M
FROM
  combo4
GROUP BY
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_ID;

CREATE OR REPLACE TEMPORARY VIEW combo6 AS
SELECT
  combo4.*,
  combo5.* EXCEPT (FIPS_CODE, RPT_MONTH_YEAR, CASE_ID)
FROM
  combo4
  INNER JOIN combo5 ON
    combo4.FIPS_CODE = combo5.FIPS_CODE AND
    combo4.RPT_MONTH_YEAR = combo5.RPT_MONTH_year AND
    combo4.CASE_ID = combo5.CASE_ID;


CREATE OR REPLACE TEMPORARY VIEW combo7 AS
SELECT
  *,
  CASE
    WHEN (NHOH > 0) AND (FEXMPT_TL NOT IN (1,2,3,4,5,6,7,8,9) OR (FEXMPT_TL = 1 AND MONTHS_FED_TIME_LIMIT > 60)) THEN "1"
    WHEN (NHOH > 0) AND (FEXMPT_TL = 2 AND NHOH_REC > 0) THEN "2"
    WHEN (NHOH > 0) AND (FEXMPT_TL = 3 AND FUNDING != 2) THEN "3"
    WHEN (NHOH > 0) AND (FEXMPT_TL = 6 AND FUNDING != 2) THEN "3"
    WHEN (NHOH > 0) AND (FEXMPT_TL IN (7,8) AND MONTHS_FED_TIME_LIMIT <= 60) THEN "5"
    WHEN (NHOH > 0) AND (FEXMPT_TL = 9 AND MONTHS_FED_TIME_LIMIT <= 60) THEN "5"
    ELSE " "
  END AS TLERRFG,
  CASE
    WHEN (NHOH > 0 AND FEXMPT_TL NOT IN (1,2,3,4,5,6,7,8,9) OR (FEXMPT_TL = 1 AND MONTHS_FED_TIME_LIMIT > 60)) AND (MONTHS_FED_TIME_LIMIT <= 60) AND NOT (FUNDING = 2) THEN 1
    WHEN (NHOH > 0) AND (FEXMPT_TL = 2 AND NHOH_REC > 0) AND (MONTHS_FED_TIME_LIMIT <= 60) THEN 1
    WHEN (NHOH > 0) AND (FEXMPT_TL NOT IN (1,2,3,4,5,6,7,8,9) OR (FEXMPT_TL = 1 AND MONTHS_FED_TIME_LIMIT > 60)) AND (MONTHS_FED_TIME_LIMIT <= 60) AND (FUNDING = 2) THEN 3
    WHEN (NHOH > 0) AND NOT (FEXMPT_TL NOT IN (1,2,3,4,5,6,7,8,9) OR (FEXMPT_TL = 1 AND MONTHS_FED_TIME_LIMIT > 60)) AND (MONTHS_FED_TIME_LIMIT <= 60) AND (FUNDING = 2) THEN 6
    WHEN (NHOH > 0) AND NOT (FEXMPT_TL NOT IN (1,2,3,4,5,6,7,8,9) OR (FEXMPT_TL = 1 AND MONTHS_FED_TIME_LIMIT > 60)) AND (MONTHS_FED_TIME_LIMIT <= 60) AND NOT (FUNDING = 2) THEN 7
    WHEN (NHOH > 0) AND (FEXMPT_TL = 2 AND NHOH_REC > 0) AND (MONTHS_FED_TIME_LIMIT > 60) THEN 7
    WHEN (NHOH > 0) AND (FEXMPT_TL = 3 AND FUNDING != 2) AND (MONTHS_FED_TIME_LIMIT <= 60) THEN 1
    WHEN (NHOH > 0) AND (FEXMPT_TL = 3 AND FUNDING != 2) AND (MONTHS_FED_TIME_LIMIT > 60) THEN 7
    WHEN (NHOH > 0) AND (FEXMPT_TL = 6 AND FUNDING != 2) AND (MONTHS_FED_TIME_LIMIT > 60) THEN 7
    WHEN (NHOH > 0) AND (FEXMPT_TL = 6 AND FUNDING != 2) AND (MONTHS_FED_TIME_LIMIT <= 60) THEN 1
    WHEN (NHOH > 0) AND (FEXMPT_TL = 4 AND MONTHS_FED_TIME_LIMIT > 60) THEN 9
    WHEN (NHOH > 0) AND (FEXMPT_TL IN (7,8) AND MONTHS_FED_TIME_LIMIT > 60) THEN 1
    WHEN (NHOH > 0) AND (FEXMPT_TL = 9 AND MONTHS_FED_TIME_LIMIT <= 60) THEN 4
    ELSE FEXMPT_TL
  END AS TLEXM
FROM
  combo6;

# %%
-------------------------------------------
-- Step 2: Create the time limit reports --
-------------------------------------------

--CREATE REPORT 'TANF TIMELIMIT ERRORFLAGS IN FY20&FY.'--
CREATE OR REPLACE TEMPORARY VIEW report1 AS
SELECT
  RPT_MONTH_YEAR AS MONTH,
  TLERRFG,
  COUNT(*) AS freq
FROM
  combo7
GROUP BY
  RPT_MONTH_YEAR,
  TLERRFG;

--CREATE REPORT 'TANF CASES REPORTED WITH TIME-LIMIT ERRORS IN FY20&FY.'--
CREATE OR REPLACE TEMPORARY VIEW report2 AS
SELECT
  RPT_MONTH_YEAR AS MONTH,
  TYPE_FAM,
  FUNDING,
  TLERRFG,
  FEXMPT_TL,
  FAMILY_AFFILIATION,
  RELATIONSHIP_HOH,
  NHOH_REC,
  MONTHS_FED_TIME_LIMIT
FROM
  combo7;

CREATE OR REPLACE TEMPORARY VIEW TLcases1 AS
SELECT
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_ID,
  SUM(CASE WHEN TLEXM = 1 THEN 1 ELSE 0 END) AS TLEX1,
  SUM(CASE WHEN TLEXM = 2 THEN 1 ELSE 0 END) AS TLEX2,
  SUM(CASE WHEN TLEXM = 3 THEN 1 ELSE 0 END) AS TLEX3,
  SUM(CASE WHEN TLEXM = 4 THEN 1 ELSE 0 END) AS TLEX4,
  SUM(CASE WHEN TLEXM = 5 THEN 1 ELSE 0 END) AS TLEX5,
  SUM(CASE WHEN TLEXM = 6 THEN 1 ELSE 0 END) AS TLEX6,
  SUM(CASE WHEN TLEXM = 7 THEN 1 ELSE 0 END) AS TLEX7,
  SUM(CASE WHEN TLEXM = 8 THEN 1 ELSE 0 END) AS TLEX8,
  SUM(CASE WHEN TLEXM = 9 THEN 1 ELSE 0 END) AS TLEX9
FROM
  combo7
GROUP BY
  FIPS_CODE,
  RPT_MONTH_YEAR,
  CASE_ID;

CREATE OR REPLACE TEMPORARY VIEW TLcases AS
SELECT
  combo7.*,
  TLcases1.* EXCEPT (FIPS_CODE, RPT_MONTH_YEAR, CASE_ID)
FROM
  combo7
  INNER JOIN TLcases1 ON
    combo7.FIPS_CODE = TLcases1.FIPS_CODE AND
    combo7.RPT_MONTH_YEAR = TLcases1.RPT_MONTH_year AND
    combo7.CASE_ID = TLcases1.CASE_ID;

-- review the following table to make sure this is what it actually should look like --

--CREATE REPORT 'TANF CASES WITH OVER 60 MONTHS ASSISTANCE IN FY20&FY.'--
CREATE OR REPLACE TEMPORARY VIEW report3 AS
SELECT
  RPT_MONTH_YEAR AS MONTH,
  STRATUM,
  MONTHS_FED_TIME_LIMIT,
  CASE_ID,
  SUM(TLEX1),
  SUM(TLEX2),
  SUM(TLEX3),
  SUM(TLEX4),
  SUM(TLEX6),
  SUM(TLEX7),
  SUM(TLEX8),
  SUM(TLEX9)
FROM
  TLcases
WHERE
  OVER60M >= 1
GROUP BY
  RPT_MONTH_YEAR,
  STRATUM,
  MONTHS_FED_TIME_LIMIT,
  CASE_ID;

-------------------------------------------
-- Step 2: Create the time limit reports --
-------------------------------------------

CREATE OR REPLACE TEMPORARY VIEW TLcases2 AS
SELECT
  *,
  CASE
    WHEN CASE_ID IS NULL THEN 0
    ELSE 1
  END AS SAMP
FROM
  TLcases
WHERE
  RPT_MONTH_YEAR IS NOT NULL;


--CREATE REPORT 'TANF CASES WITH OVER 60 MONTHS IN FY20&FY.'--
--NOTE: Need to iterate over every state or territory, or simply filter to specific states or terrotories
CREATE OR REPLACE TEMPORARY VIEW report4 AS
SELECT
  RPT_MONTH_YEAR,
  OVER60M,
  COUNT(*) AS freq
FROM
  TLcases
WHERE
  --FIPS = FIPS
  OVER60M >= 1 AND
  --In the SAS cript, it's NHOH_REC > 1, but NHOH_REC is binary so I think it should be this instead ...
  NHOH_REC >= 1
GROUP BY
  RPT_MONTH_YEAR,
  OVER60M
ORDER BY
  RPT_MONTH_YEAR,
  OVER60M;

--CREATE REPORT 'HEAD-OF-HOUSEHOLDS WITH OVER 60 MONTHS ASSISTANCE IN FY20&FY.'--
CREATE OR REPLACE TEMPORARY VIEW report5 AS
SELECT
  RPT_MONTH_YEAR,
  STRATUM,
  CASE_ID,
  MONTHS_FED_TIME_LIMIT AS FED_MONTHS,
  TLERRFG
FROM
  TLcases2
WHERE
  MONTHS_FED_TIME_LIMIT > 60 AND
  FAMILY_AFFILIATION = 1 AND
  AHEAD = 1;

--CREATE REPORT 'TANF FAMILIES RECEIVED FEDERAL ASSISTANCE OVER 60 MONTHS'--
CREATE OR REPLACE TEMPORARY VIEW report7 AS
SELECT
  FIPS_CODE,
  --I need to convert FIPS into the actual state name - can put that at the beginning of the script later
  --FIPNAME(FIPS) AS STATE,
  RPT_MONTH_YEAR,
  sum(OVER60M) as cases
FROM
  TLcases
--WHERE
--    TLERRFG IS NOT BLANK
GROUP BY
  FIPS_CODE, --replace with 'State' later on
  RPT_MONTH_YEAR;

CREATE OR REPLACE TEMPORARY VIEW TLcases3 AS
SELECT
  FIPS_CODE,
  RPT_MONTH_YEAR,
  -- could potentially rename the following varialbes with '_SUM' ending later --
  SUM(SAMP) AS SAMP,
  SUM(NADULT) AS NADULT,
  SUM(NHOH) AS NHOH,
  SUM(NHOH_REC) AS NHOH_REC,
  SUM(CM_0) AS CM_0,
  SUM(CM01_12) AS CM01_12,
  SUM(CM13_24) AS CM13_24,
  SUM(CM25_36) AS CM25_36,
  SUM(CM37_48) AS CM37_48,
  SUM(CM49_59) AS CM49_59,
  SUM(CM60) AS CM60,
  SUM(OVER60M) AS OVER60M,
  SUM(TLEX1) AS TLEX1,
  SUM(TLEX2) AS TLEX2,
  SUM(TLEX3) AS TLEX3,
  SUM(TLEX4) AS TLEX4,
  SUM(TLEX6) AS TLEX6,
  SUM(TLEX7) AS TLEX7,
  SUM(TLEX8) AS TLEX8,
  SUM(TLEX9) AS TLEX9
FROM
  TLcases2
WHERE
  RPT_MONTH_YEAR IS NOT NULL
GROUP BY
  FIPS_CODE,
  RPT_MONTH_YEAR;

# %%
---------------------------------------------------
-- Step 3: Create the time limit reports by FIPS --
---------------------------------------------------

-- Can add a WHERE clause for specific FIPS later on --

CREATE OR REPLACE TEMPORARY VIEW TLcases3 AS
SELECT
  *
FROM
  TLcases2;
--WHERE
--    FIPS = &fips.;


--CREATE REPORT 'MONTHS OF TANF FAMILIIES RECEIVED ASSISTANCE REPORTED IN FY20&FY.' --
CREATE OR REPLACE TEMPORARY VIEW report8 AS
SELECT
  RPT_MONTH_YEAR AS MONTH,
  SUM(SAMP) AS FAMILIES, --'Families',
  SUM(NADULT) AS ADULTS, --'# of Adults',
  SUM(NHOH) AS NUMHoHS, --'# of HoHs',
  SUM(NHOH_REC) AS NUMHoHRecipients, --'# of HoH recipients',
  SUM(CM_0) AS CM_0, --'0 MONTH',
  SUM(CM01_12) AS CM01_12, --'1~12 months',
  SUM(CM13_24) AS CM13_24, --'13~24 months',
  SUM(CM25_36) AS CM25_36, --'25~36 months',
  SUM(CM37_48) AS CM37_48, --'37~48 months',
  SUM(CM49_59) AS CM49_59, --'49~59 months',
  SUM(CM60) AS CM60, --'60 months',
  SUM(OVER60M) AS OVER60M --'60+ months'
FROM
  TLcases3
GROUP BY
  RPT_MONTH_YEAR;


--CREATE REPORT 'TANF CASES FEDERAL TIME LIMIT EXEMPTIONS REPORTED IN FY20&FY.' --
CREATE OR REPLACE TEMPORARY VIEW report9 AS
SELECT
  RPT_MONTH_YEAR AS MONTH,
  SUM(SAMP) AS FAMILIES,
  SUM(NADULT) AS NADULT, --'# of Adults',
  SUM(NHOH) AS NHOH, --'# of HoHs',
  SUM(NHOH_REC) AS NHOH_REC, --'# of HoH recipients',
  SUM(TLEX1) AS TLEX1,
  SUM(TLEX2) AS TLEX2,
  SUM(TLEX3) AS TLEX3,
  SUM(TLEX4) AS TLEX4,
  SUM(TLEX6) AS TLEX6,
  SUM(TLEX7) AS TLEX7,
  SUM(TLEX8) AS TLEX8,
  SUM(TLEX9) AS TLEX9
FROM
  TLcases3
GROUP BY
  RPT_MONTH_YEAR;
