# %% [markdown]
#
# # TANF - Generating Yearly Reports
#
# This script the weighted TANF summary reports to generate the yearly TANF reports.

# %%
-- this comes from the last part of the WPR file --

CREATE OR REPLACE TEMPORARY VIEW old AS
SELECT
	*
FROM
	ofa_sandbox.legacy_code.sf202408
;

# %%
CREATE OR REPLACE TEMPORARY VIEW combo AS
SELECT
	*
FROM
	old;

CREATE OR REPLACE TEMPORARY VIEW file1 AS
SELECT
	FIPS_CODE,
	RPT_MONTH_YEAR,
	SUM(WNGAGED) AS ANGAGED,
	SUM(WN_WEI) AS AN_WEI,
	SUM(WWRK_WEI) AS AWRK_WEI,
	SUM(WNSAMP) AS ANSAMP,
	SUM(WNWORK) AS ANWORK,
	SUM(WNDCARD1) AS ANDCARD1,
	SUM(WNDCARD2) AS ANDCARD2,
	SUM(WNDCARD5) AS ANDCARD5,
	SUM(WNLIM_VOC) AS ANLIM_VOC,
	SUM(WNLIM_SSA) AS ANLIM_SSA,
	SUM(WNLIM_EDE) AS ANLIM_EDE,
	SUM(WNDCRD_PART) AS ANDCRD_PART,
	SUM(WTPSAMP) AS ATPSAMP,
	SUM(WTPWORK) AS ATPWORK,
	SUM(WTPLIM_VOC) AS ATPLIM_VOC,
	SUM(WTPLIMIT) AS ATPLIMIT,
	SUM(WTPDABLE) AS ATPDABLE,
	SUM(WTPNCP) AS ATPNCP,
	SUM(WTPDCARD2) AS ATPDCARD2,
	SUM(WTPDCARD5) AS ATPDCARD5,
	SUM(WNDVEXEM) AS AFDVEXEM,
	SUM(WTPDVEXEM) AS TPDVEXEM,
	SUM(WTPDCRD_PART) AS ATPDCRD_PART,
	SUM(WNSAMP) - SUM(WNDCARD1) - SUM(WNDCARD2) - SUM(WNDCARD5) AS AFDEN,
	SUM(WNSAMP) - SUM(WNDCARD1) - SUM(WNDCARD2) - SUM(WNDCARD5) - SUM(WNDVEXEM) AS AFADJDEN,
	SUM(WTPSAMP) - SUM(WTPDCARD2) - SUM(WTPDCARD5) - SUM(WTPNCP) - SUM(WTPDABLE) AS TPDEN,
	SUM(WTPSAMP) - SUM(WTPDCARD2) - SUM(WTPDCARD5) - SUM(WTPNCP) - SUM(WTPDABLE) - SUM(WTPDVEXEM) AS TPADJDEN,
	SUM(WNLIM_VOC) + SUM(WNLIM_SSA) + SUM(WNLIM_EDE) AS AFTOTLIM,
	SUM(WTPLIM_VOC) + SUM(WTPLIMIT) AS ATPTOTLIM--,
	--CASE
	--	WHEN SUM(WNWORK) > (SUM(WNLIM_VOC) + SUM(WNLIM_SSA) + SUM(WNLIM_EDE)) AND (SUM(WNLIM_VOC) + SUM(WNLIM_SSA) + SUM(WNLIM_EDE)) > 0.3 * SUM(WNWORK) THEN (SUM(WNWORK) - (SUM(WNLIM_VOC) + SUM(WNLIM_SSA) + SUM(WNLIM_EDE))) / 0.7
	--	ELSE ANWORK
	--END AS ADJNUM
FROM
	combo
WHERE
	FIPS_CODE IS NOT NULL AND
	RPT_MONTH_YEAR IS NOT NULL
GROUP BY
	FIPS_CODE,
	RPT_MONTH_YEAR;

-- ADJNUM (adjusted number) represented when _______  --

CREATE OR REPLACE TEMPORARY VIEW file2 AS
SELECT
	*,
	CASE
		WHEN ANWORK > AFTOTLIM AND AFTOTLIM > (0.3 * ANWORK) THEN (ANWORK - AFTOTLIM)/0.7
		ELSE ANWORK
	END AS ADJNUM,
	CASE
		WHEN ATPWORK > ATPTOTLIM AND ATPTOTLIM > (0.3 * ATPWORK) THEN (ATPWORK - ATPTOTLIM) / 0.7
		ELSE ATPWORK
	END AS ADJTPNUM
FROM
	file1;

# %%
-- CREATE MONTHLY SUBSETS --

-- for each month in a year (January through December), create a different dataset --


CREATE OR REPLACE TEMPORARY VIEW monthly1 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_JAN,
	AN_WEI AS AN_WEI_JAN,
	AWRK_WEI AS AWRK_WEI_JAN,
	ANSAMP AS ANSAMP_JAN,
	ANWORK AS ANWORK_JAN,
	AFDEN AS AFDEN_JAN,
	ADJNUM AS ADJNUM_JAN,
	TPDEN AS TPDEN_JAN,
	ADJTPNUM AS ADJTPNUM_JAN,
	AFADJDEN AS AFADJDEN_JAN,
	TPADJDEN AS TPADJDEN_JAN
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 1;

CREATE OR REPLACE TEMPORARY VIEW monthly2 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_FEB,
	AN_WEI AS AN_WEI_FEB,
	AWRK_WEI AS AWRK_WEI_FEB,
	ANSAMP AS ANSAMP_FEB,
	ANWORK AS ANWORK_FEB,
	AFDEN AS AFDEN_FEB,
	ADJNUM AS ADJNUM_FEB,
	TPDEN AS TPDEN_FEB,
	ADJTPNUM AS ADJTPNUM_FEB,
	AFADJDEN AS AFADJDEN_FEB,
	TPADJDEN AS TPADJDEN_FEB
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 2;

CREATE OR REPLACE TEMPORARY VIEW monthly3 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_MAR,
	AN_WEI AS AN_WEI_MAR,
	AWRK_WEI AS AWRK_WEI_MAR,
	ANSAMP AS ANSAMP_MAR,
	ANWORK AS ANWORK_MAR,
	AFDEN AS AFDEN_MAR,
	ADJNUM AS ADJNUM_MAR,
	TPDEN AS TPDEN_MAR,
	ADJTPNUM AS ADJTPNUM_MAR,
	AFADJDEN AS AFADJDEN_MAR,
	TPADJDEN AS TPADJDEN_MAR
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 3;

CREATE OR REPLACE TEMPORARY VIEW monthly4 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_APR,
	AN_WEI AS AN_WEI_APR,
	AWRK_WEI AS AWRK_WEI_APR,
	ANSAMP AS ANSAMP_APR,
	ANWORK AS ANWORK_APR,
	AFDEN AS AFDEN_APR,
	ADJNUM AS ADJNUM_APR,
	TPDEN AS TPDEN_APR,
	ADJTPNUM AS ADJTPNUM_APR,
	AFADJDEN AS AFADJDEN_APR,
	TPADJDEN AS TPADJDEN_APR
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 4;

CREATE OR REPLACE TEMPORARY VIEW monthly5 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_MAY,
	AN_WEI AS AN_WEI_MAY,
	AWRK_WEI AS AWRK_WEI_MAY,
	ANSAMP AS ANSAMP_MAY,
	ANWORK AS ANWORK_MAY,
	AFDEN AS AFDEN_MAY,
	ADJNUM AS ADJNUM_MAY,
	TPDEN AS TPDEN_MAY,
	ADJTPNUM AS ADJTPNUM_MAY,
	AFADJDEN AS AFADJDEN_MAY,
	TPADJDEN AS TPADJDEN_MAY
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 5;

CREATE OR REPLACE TEMPORARY VIEW monthly6 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_JUN,
	AN_WEI AS AN_WEI_JUN,
	AWRK_WEI AS AWRK_WEI_JUN,
	ANSAMP AS ANSAMP_JUN,
	ANWORK AS ANWORK_JUN,
	AFDEN AS AFDEN_JUN,
	ADJNUM AS ADJNUM_JUN,
	TPDEN AS TPDEN_JUN,
	ADJTPNUM AS ADJTPNUM_JUN,
	AFADJDEN AS AFADJDEN_JUN,
	TPADJDEN AS TPADJDEN_JUN
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 6;

CREATE OR REPLACE TEMPORARY VIEW monthly7 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_JUL,
	AN_WEI AS AN_WEI_JUL,
	AWRK_WEI AS AWRK_WEI_JUL,
	ANSAMP AS ANSAMP_JUL,
	ANWORK AS ANWORK_JUL,
	AFDEN AS AFDEN_JUL,
	ADJNUM AS ADJNUM_JUL,
	TPDEN AS TPDEN_JUL,
	ADJTPNUM AS ADJTPNUM_JUL,
	AFADJDEN AS AFADJDEN_JUL,
	TPADJDEN AS TPADJDEN_JUL
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 7;

CREATE OR REPLACE TEMPORARY VIEW monthly8 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_AUG,
	AN_WEI AS AN_WEI_AUG,
	AWRK_WEI AS AWRK_WEI_AUG,
	ANSAMP AS ANSAMP_AUG,
	ANWORK AS ANWORK_AUG,
	AFDEN AS AFDEN_AUG,
	ADJNUM AS ADJNUM_AUG,
	TPDEN AS TPDEN_AUG,
	ADJTPNUM AS ADJTPNUM_AUG,
	AFADJDEN AS AFADJDEN_AUG,
	TPADJDEN AS TPADJDEN_AUG
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 8;

CREATE OR REPLACE TEMPORARY VIEW monthly9 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_SEP,
	AN_WEI AS AN_WEI_SEP,
	AWRK_WEI AS AWRK_WEI_SEP,
	ANSAMP AS ANSAMP_SEP,
	ANWORK AS ANWORK_SEP,
	AFDEN AS AFDEN_SEP,
	ADJNUM AS ADJNUM_SEP,
	TPDEN AS TPDEN_SEP,
	ADJTPNUM AS ADJTPNUM_SEP,
	AFADJDEN AS AFADJDEN_SEP,
	TPADJDEN AS TPADJDEN_SEP
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 9;

CREATE OR REPLACE TEMPORARY VIEW monthly10 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_OCT,
	AN_WEI AS AN_WEI_OCT,
	AWRK_WEI AS AWRK_WEI_OCT,
	ANSAMP AS ANSAMP_OCT,
	ANWORK AS ANWORK_OCT,
	AFDEN AS AFDEN_OCT,
	ADJNUM AS ADJNUM_OCT,
	TPDEN AS TPDEN_OCT,
	ADJTPNUM AS ADJTPNUM_OCT,
	AFADJDEN AS AFADJDEN_OCT,
	TPADJDEN AS TPADJDEN_OCT
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 10;

CREATE OR REPLACE TEMPORARY VIEW monthly11 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_NOV,
	AN_WEI AS AN_WEI_NOV,
	AWRK_WEI AS AWRK_WEI_NOV,
	ANSAMP AS ANSAMP_NOV,
	ANWORK AS ANWORK_NOV,
	AFDEN AS AFDEN_NOV,
	ADJNUM AS ADJNUM_NOV,
	TPDEN AS TPDEN_NOV,
	ADJTPNUM AS ADJTPNUM_NOV,
	AFADJDEN AS AFADJDEN_NOV,
	TPADJDEN AS TPADJDEN_NOV
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 11;

CREATE OR REPLACE TEMPORARY VIEW monthly12 AS
SELECT
	FIPS_CODE AS FIPS_CODE,
	ANGAGED AS ANGAGED_DEC,
	AN_WEI AS AN_WEI_DEC,
	AWRK_WEI AS AWRK_WEI_DEC,
	ANSAMP AS ANSAMP_DEC,
	ANWORK AS ANWORK_DEC,
	AFDEN AS AFDEN_DEC,
	ADJNUM AS ADJNUM_DEC,
	TPDEN AS TPDEN_DEC,
	ADJTPNUM AS ADJTPNUM_DEC,
	AFADJDEN AS AFADJDEN_DEC,
	TPADJDEN AS TPADJDEN_DEC
FROM
	file2
WHERE
	MOD(RPT_MONTH_YEAR, 100) = 12;


# %%
-- currently null, should run for other states to run properly --

CREATE OR REPLACE TEMPORARY VIEW stat2 AS
SELECT
	monthly1.*,
	monthly2.* EXCEPT (FIPS_CODE),
	monthly3.* EXCEPT (FIPS_CODE),
	monthly4.* EXCEPT (FIPS_CODE),
	monthly5.* EXCEPT (FIPS_CODE),
	monthly6.* EXCEPT (FIPS_CODE),
	monthly7.* EXCEPT (FIPS_CODE),
	monthly8.* EXCEPT (FIPS_CODE),
	monthly9.* EXCEPT (FIPS_CODE),
	monthly10.* EXCEPT (FIPS_CODE),
	monthly11.* EXCEPT (FIPS_CODE),
	monthly12.* EXCEPT (FIPS_CODE),
	(CASE WHEN ANSAMP_JAN > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_FEB > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_MAR > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_APR > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_MAY > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_JUN > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_JUL > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_AUG > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_SEP > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_OCT > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_NOV > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN ANSAMP_DEC > 0 THEN 1 ELSE 0 END) AS MTHS,
	(CASE WHEN TPDEN_JAN > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_FEB > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_MAR > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_APR > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_MAY > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_JUN > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_JUL > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_AUG > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_SEP > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_OCT > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_NOV > 0 THEN 1 ELSE 0 END) +
	(CASE WHEN TPDEN_DEC > 0 THEN 1 ELSE 0 END) AS TPMTHS
FROM
	monthly1 INNER JOIN
	monthly2 ON monthly1.FIPS_CODE = monthly2.FIPS_CODE INNER JOIN
	monthly3 ON monthly1.FIPS_CODE = monthly3.FIPS_CODE INNER JOIN
	monthly4 ON monthly1.FIPS_CODE = monthly4.FIPS_CODE INNER JOIN
	monthly5 ON monthly1.FIPS_CODE = monthly5.FIPS_CODE INNER JOIN
	monthly6 ON monthly1.FIPS_CODE = monthly6.FIPS_CODE INNER JOIN
	monthly7 ON monthly1.FIPS_CODE = monthly7.FIPS_CODE INNER JOIN
	monthly8 ON monthly1.FIPS_CODE = monthly8.FIPS_CODE INNER JOIN
	monthly9 ON monthly1.FIPS_CODE = monthly9.FIPS_CODE INNER JOIN
	monthly10 ON monthly1.FIPS_CODE = monthly10.FIPS_CODE INNER JOIN
	monthly11 ON monthly1.FIPS_CODE = monthly11.FIPS_CODE INNER JOIN
	monthly12 ON monthly1.FIPS_CODE = monthly12.FIPS_CODE;
