groups:
  - name: database.alerts
    rules:
      - alert: LocalDatabaseDown
        expr: last_over_time(pg_up{job="postgres-local"}[1m]) == 0 or last_over_time(up{job="postgres-local"}[1m]) == 0
        for: 1m
        labels:
          severity: CRITICAL
        annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
  - name: backend.alerts
    rules:
    - alert: LocalBackendDown
      expr: last_over_time(up{job=~"tdp-backend-local"}[1m]) == 0
      for: 10m
      labels:
        severity: ERROR
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 10 minutes."
  - name: plg.alerts
    rules:
    - alert: LocalLokiDown
      expr: last_over_time(up{job="loki"}[1m]) == 0
      labels:
        severity: ERROR
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
  - name: app.alerts
    rules:
    - alert: UpTime
      expr: avg_over_time(up[1m]) < 0.95
      for: 30m
      labels:
        severity: WARNING
      annotations:
          summary: "The {{ $labels.service }} service has a uptime warning."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment is not maintaining 95% uptime."
  - name: celery.alerts
    rules:
    - alert: LocalCeleryWorkerDown
      expr: last_over_time(up{job=~"celery-.*|celery-exporter.*"}[1m]) == 0
      for: 10m
      labels:
        severity: ERROR
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 10 minutes."

