groups:
  - name: database.alerts
    rules:
      - alert: DevDatabaseDown
        expr: last_over_time(pg_up{job="postgres-dev"}[1m]) == 0 or last_over_time(up{job="postgres-dev"}[1m]) == 0
        labels:
          severity: CRITICAL
        annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
      - alert: StagingDatabaseDown
        expr: last_over_time(pg_up{job="postgres-staging"}[1m]) == 0 or last_over_time(up{job="postgres-staging"}[1m]) == 0
        labels:
          severity: ERROR
        annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
      - alert: ProductionDatabaseDown
        expr: last_over_time(pg_up{job="postgres-production"}[1m]) == 0 or last_over_time(up{job="postgres-production"}[1m]) == 0
        labels:
          severity: CRITICAL
        annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
  - name: backend.alerts
    rules:
    - alert: DevEnvironmentBackendDown
      expr: last_over_time(up{job=~"tdp-backend.*", job!~".*prod", job!~".*staging"}[5m]) == 0
      labels:
        severity: ERROR
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 5 minutes."
    - alert: StagingBackendDown
      expr: last_over_time(up{job=~"tdp-backend-staging"}[1m]) == 0
      labels:
        severity: ERROR
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
    - alert: ProductionBackendDown
      expr: last_over_time(up{job=~"tdp-backend-prod"}[1m]) == 0
      labels:
        severity: CRITICAL
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
    - alert: DevBackendCpuUsageHigh
      expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle",job=~"node-develop"}[5m])) * 100)
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "CPU usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high CPU usage for more than 5 minutes."
    - alert: StagingBackendCpuUsageHigh
      expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle",job=~"node-staging"}[5m])) * 100)
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "CPU usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high CPU usage for more than 5 minutes."
    - alert: ProductionBackendCpuUsageHigh
      expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle",job=~"node-prod"}[5m])) * 100)
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "CPU usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high CPU usage for more than 5 minutes."
    - alert: DevBackendMemoryUsageHigh
      expr: |
        avg_over_time(
          (
            (node_memory_MemTotal_bytes{job=~"node-develop"} - node_memory_MemAvailable_bytes{job=~"node-develop"})
            / node_memory_MemTotal_bytes{job=~"node-develop"} * 100
          )[5m:]
        )
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "Memory usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high Memory usage for more than 5 minutes."
    - alert: StagingBackendMemoryUsageHigh
      expr: |
        avg_over_time(
          (
            (node_memory_MemTotal_bytes{job=~"node-staging"} - node_memory_MemAvailable_bytes{job=~"node-staging"})
            / node_memory_MemTotal_bytes{job=~"node-staging"} * 100
          )[5m:]
        )
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "Memory usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high Memory usage for more than 5 minutes."
    - alert: ProductionBackendMemoryUsageHigh
      expr: |
        avg_over_time(
          (
            (node_memory_MemTotal_bytes{job=~"node-prod"} - node_memory_MemAvailable_bytes{job=~"node-prod"})
            / node_memory_MemTotal_bytes{job=~"node-prod"} * 100
          )[5m:]
        )
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "Memory usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high Memory usage for more than 5 minutes."
    - alert: DevBackendDiskUsageHigh
      expr: |
        avg_over_time(
          (
            100 * (node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-develop"} 
            - node_filesystem_free_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-develop"})
            / node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-develop"}
          )[5m:]
        )
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "Disk usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high disk usage for more than 5 minutes."
    - alert: StagingBackendDiskUsageHigh
      expr: |
        avg_over_time(
          (
            100 * (node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-staging"} 
            - node_filesystem_free_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-staging"})
            / node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-staging"}
          )[5m:]
        )
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "Disk usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high disk usage for more than 5 minutes."
    - alert: ProductionBackendDiskUsageHigh
      expr: |
        avg_over_time(
          (
            100 * (node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-prod"} 
            - node_filesystem_free_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-prod"})
            / node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|overlay",job=~"node-prod"}
          )[5m:]
        )
      for: 5m
      labels:
        severity: WARNING
      annotations:
          summary: "Disk usage is above 80% on {{ $labels.instance }}"
          description: "The {{ $labels.instance }} instance in the {{ $labels.env }} environment has been experiencing high disk usage for more than 5 minutes."

  - name: plg.alerts
    rules:
    - alert: LokiDown
      expr: last_over_time(up{job="loki"}[1m]) == 0
      labels:
        severity: ERROR
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
    - alert: GrafanaDown
      expr: last_over_time(up{job="grafana"}[1m]) == 0
      labels:
        severity: ERROR
      annotations:
          summary: "The {{ $labels.service }} service is down."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment has been down for more than 1 minute."
  - name: app.alerts
    rules:
    - alert: UpTime
      expr: avg_over_time(up[1d]) < 0.95
      for: 30m
      labels:
        severity: WARNING
      annotations:
          summary: "The {{ $labels.service }} service has a uptime warning."
          description: "The {{ $labels.service }} service in the {{ $labels.env }} environment is not maintaining 95% uptime."
