# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 60s # Evaluate rules every 60 seconds.

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "django_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "tdp-backend-raft"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["tdp-backend-raft.apps.internal:8080"]

  - job_name: "tdp-backend-qasp"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["tdp-backend-qasp.apps.internal:8080"]

  - job_name: "tdp-backend-develop"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["tdp-backend-develop.apps.internal:8080"]

  - job_name: "tdp-backend-staging"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["tdp-backend-staging.apps.internal:8080"]

  - job_name: "tdp-backend-prod"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["tdp-backend-prod.apps.internal:8080"]

  - job_name: "celery-exporter-raft"
    static_configs:
      - targets: ["celery-exporter-raft.apps.internal:9540"]

  - job_name: postgres-dev
    static_configs:
      - targets: ["pg-exporter-dev.apps.internal:9187"]

  - job_name: postgres-staging
    static_configs:
      - targets: ["pg-exporter-staging.apps.internal:9187"]

  - job_name: postgres-production
    static_configs:
      - targets: ["pg-exporter-production.apps.internal:9187"]
