"""Schema for Tribal TANF T2 row of all submission types."""


from ...transforms import tanf_ssn_decryption_func
from ...fields import TransformField, Field
from ...row_schema import RowSchema, SchemaManager
from ... import validators
from tdpservice.search_indexes.documents.tribal import Tribal_TANF_T2DataSubmissionDocument


t2 = SchemaManager(
    schemas=[
        RowSchema(
            document=Tribal_TANF_T2DataSubmissionDocument(),
            preparsing_validators=[
                validators.hasLength(122),
                validators.notEmpty(8, 19)
            ],
            postparsing_validators=[
                validators.validate__FAM_AFF__SSN(),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.matches(1),
                    result_field="SSN",
                    result_function=validators.validateSSN(),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="RACE_HISPANIC",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="RACE_AMER_INDIAN",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="RACE_ASIAN",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="RACE_BLACK",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="RACE_HAWAIIAN",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="RACE_WHITE",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="MARITAL_STATUS",
                    result_function=validators.isInLimits(1, 5),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 2),
                    result_field="PARENT_MINOR_CHILD",
                    result_function=validators.isInLimits(1, 3),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="EDUCATION_LEVEL",
                    result_function=validators.or_validators(
                        validators.isInStringRange(0, 16),
                        validators.isInStringRange(98, 99),
                    ),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.matches(1),
                    result_field="CITIZENSHIP_STATUS",
                    result_function=validators.matches(1),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="COOPERATION_CHILD_SUPPORT",
                    result_function=validators.oneOf((1, 2, 9)),
                ),
                validators.validate__FAM_AFF__HOH__Fed_Time(),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field="EMPLOYMENT_STATUS",
                    result_function=validators.isInLimits(1, 3),
                ),
                validators.if_then_validator(
                    condition_field="FAMILY_AFFILIATION",
                    condition_function=validators.oneOf((1, 2)),
                    result_field="WORK_PART_STATUS",
                    result_function=validators.or_validators(
                        validators.isInStringRange(1, 3),
                        validators.isInStringRange(5, 9),
                        validators.isInStringRange(11, 19),
                        validators.matches("99"),
                    ),
                ),
            ],
            fields=[
                Field(
                    item="0",
                    name="RecordType",
                    friendly_name="Record Type",
                    type="string",
                    startIndex=0,
                    endIndex=2,
                    required=True,
                    validators=[],
                ),
                Field(
                    item="4",
                    name="RPT_MONTH_YEAR",
                    friendly_name="Reporting Year and Month",
                    type="number",
                    startIndex=2,
                    endIndex=8,
                    required=True,
                    validators=[
                        validators.dateYearIsLargerThan(1900),
                        validators.dateMonthIsValid(),
                    ],
                ),
                Field(
                    item="6",
                    name="CASE_NUMBER",
                    friendly_name="Case Number--TANF",
                    type="string",
                    startIndex=8,
                    endIndex=19,
                    required=True,
                    validators=[validators.notEmpty()],
                ),
                Field(
                    item="30",
                    name="FAMILY_AFFILIATION",
                    friendly_name="Family Affiliation",
                    type="number",
                    startIndex=19,
                    endIndex=20,
                    required=True,
                    validators=[validators.oneOf([1, 2, 3, 5])],
                ),
                Field(
                    item="31",
                    name="NONCUSTODIAL_PARENT",
                    friendly_name="Noncustodial Parent Indicator",
                    type="number",
                    startIndex=20,
                    endIndex=21,
                    required=True,
                    validators=[validators.oneOf([1, 2])],
                ),
                Field(
                    item="32",
                    name="DATE_OF_BIRTH",
                    friendly_name="Date of Birth",
                    type="number",
                    startIndex=21,
                    endIndex=29,
                    required=True,
                    validators=[
                        validators.dateYearIsLargerThan(1900),
                        validators.dateMonthIsValid(),
                    ],
                ),
                TransformField(
                    transform_func=tanf_ssn_decryption_func,
                    item="33",
                    name="SSN",
                    friendly_name="Social Security Number",
                    type="string",
                    startIndex=29,
                    endIndex=38,
                    required=True,
                    validators=[validators.isNumber()],
                    is_encrypted=False,
                ),
                Field(
                    item="34A",
                    name="RACE_HISPANIC",
                    friendly_name="Ethnicity/Race: Hispanic or Latino",
                    type="number",
                    startIndex=38,
                    endIndex=39,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="34B",
                    name="RACE_AMER_INDIAN",
                    friendly_name="Ethnicity/Race: American Indian or Alaska Native",
                    type="number",
                    startIndex=39,
                    endIndex=40,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="34C",
                    name="RACE_ASIAN",
                    friendly_name="Ethnicity/Race: Asian",
                    type="number",
                    startIndex=40,
                    endIndex=41,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="34D",
                    name="RACE_BLACK",
                    friendly_name="Ethnicity/Race: Black or African American",
                    type="number",
                    startIndex=41,
                    endIndex=42,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="34E",
                    name="RACE_HAWAIIAN",
                    friendly_name="Ethnicity/Race: Native Hawaiian or Other Pacific Islander",
                    type="number",
                    startIndex=42,
                    endIndex=43,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="34F",
                    name="RACE_WHITE",
                    friendly_name="Ethnicity/Race: White",
                    type="number",
                    startIndex=43,
                    endIndex=44,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="35",
                    name="GENDER",
                    friendly_name="Gender",
                    type="number",
                    startIndex=44,
                    endIndex=45,
                    required=False,
                    validators=[
                        validators.isLargerThanOrEqualTo(0),
                    ],
                ),
                Field(
                    item="36A",
                    name="FED_OASDI_PROGRAM",
                    friendly_name="Receives Disability Benefits: OASDI Program",
                    type="number",
                    startIndex=45,
                    endIndex=46,
                    required=True,
                    validators=[validators.oneOf([1, 2])],
                ),
                Field(
                    item="36B",
                    name="FED_DISABILITY_STATUS",
                    friendly_name="Receives Disability Benefits: Federal Disability Status",
                    type="number",
                    startIndex=46,
                    endIndex=47,
                    required=True,
                    validators=[validators.oneOf([1, 2])],
                ),
                Field(
                    item="36C",
                    name="DISABLED_TITLE_XIVAPDT",
                    friendly_name="Receives Disability Benefits: Permanently and Totally Disabled Under Title XIV-APDT",
                    type="string",
                    startIndex=47,
                    endIndex=48,
                    required=True,
                    validators=[
                        validators.or_validators(
                            validators.oneOf(["1", "2"]), validators.isBlank()
                        )
                    ],
                ),
                Field(
                    item="36D",
                    name="AID_AGED_BLIND",
                    friendly_name="Receives Disability Benefits: Aged, Blind, and Disabled Under Title XVI-AABD",
                    type="number",
                    startIndex=48,
                    endIndex=49,
                    required=False,
                    validators=[
                        validators.isInLimits(0, 2),
                    ],
                ),
                Field(
                    item="36E",
                    name="RECEIVE_SSI",
                    friendly_name="Receives Disability Benefits: Supplemental Security Income Under Title XVI-SSI",
                    type="number",
                    startIndex=49,
                    endIndex=50,
                    required=True,
                    validators=[
                        validators.oneOf([1, 2]),
                    ],
                ),
                Field(
                    item="37",
                    name="MARITAL_STATUS",
                    friendly_name="Marital Status",
                    type="number",
                    startIndex=50,
                    endIndex=51,
                    required=False,
                    validators=[
                        validators.isInLimits(0, 5),
                    ],
                ),
                Field(
                    item="38",
                    name="RELATIONSHIP_HOH",
                    friendly_name="Relationship to Head-of-Household",
                    type="string",
                    startIndex=51,
                    endIndex=53,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 10),
                    ],
                ),
                Field(
                    item="39",
                    name="PARENT_MINOR_CHILD",
                    friendly_name="Parent With Minor Child in the Family",
                    type="number",
                    startIndex=53,
                    endIndex=54,
                    required=False,
                    validators=[
                        validators.isInLimits(0, 3),
                    ],
                ),
                Field(
                    item="40",
                    name="NEEDS_PREGNANT_WOMAN",
                    friendly_name="Needs of a Pregnant Woman",
                    type="number",
                    startIndex=54,
                    endIndex=55,
                    required=False,
                    validators=[
                        validators.isInLimits(0, 2),
                    ],
                ),
                Field(
                    item="41",
                    name="EDUCATION_LEVEL",
                    friendly_name="Educational Level",
                    type="string",
                    startIndex=55,
                    endIndex=57,
                    required=False,
                    validators=[
                        validators.or_validators(
                            validators.isInStringRange(0, 16),
                            validators.isInStringRange(98, 99),
                        )
                    ],
                ),
                Field(
                    item="42",
                    name="CITIZENSHIP_STATUS",
                    friendly_name="Citizenship/Alienage",
                    type="number",
                    startIndex=57,
                    endIndex=58,
                    required=False,
                    validators=[validators.oneOf([0, 1, 2, 9])],
                ),
                Field(
                    item="43",
                    name="COOPERATION_CHILD_SUPPORT",
                    friendly_name="Cooperation with Child Support",
                    type="number",
                    startIndex=58,
                    endIndex=59,
                    required=False,
                    validators=[
                        validators.oneOf([0, 1, 2, 9]),
                    ],
                ),
                Field(
                    item="44",
                    name="MONTHS_FED_TIME_LIMIT",
                    friendly_name="Number of Months Countable toward Tribal Time Limit",
                    type="string",
                    startIndex=59,
                    endIndex=62,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 999),
                    ],
                ),
                Field(
                    item="45",
                    name="MONTHS_STATE_TIME_LIMIT",
                    friendly_name="Number of Countable Months Remaining Under the Tribe's Time Limit",
                    type="string",
                    startIndex=62,
                    endIndex=64,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="46",
                    name="CURRENT_MONTH_STATE_EXEMPT",
                    friendly_name="Is Current Month Exempt from the State's (Tribe's) Time Limit",
                    type="number",
                    startIndex=64,
                    endIndex=65,
                    required=False,
                    validators=[
                        validators.isInLimits(0, 2),
                    ],
                ),
                Field(
                    item="47",
                    name="EMPLOYMENT_STATUS",
                    friendly_name="Employment Status",
                    type="number",
                    startIndex=65,
                    endIndex=66,
                    required=False,
                    validators=[
                        validators.isInLimits(0, 3),
                    ],
                ),
                Field(
                    item="48",
                    name="WORK_PART_STATUS",
                    friendly_name="Work Participation Status",
                    type="string",
                    startIndex=66,
                    endIndex=68,
                    required=False,
                    validators=[
                        validators.or_validators(
                            validators.isInStringRange(0, 3),
                            validators.isInStringRange(5, 9),
                            validators.isInStringRange(11, 19),
                            validators.matches("99"),
                        )
                    ],
                ),
                Field(
                    item="49",
                    name="UNSUB_EMPLOYMENT",
                    friendly_name="Unsubsidized Employment",
                    type="string",
                    startIndex=68,
                    endIndex=70,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="50",
                    name="SUB_PRIVATE_EMPLOYMENT",
                    friendly_name="Subsidized Private-Sector Employment.",
                    type="string",
                    startIndex=70,
                    endIndex=72,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="51",
                    name="SUB_PUBLIC_EMPLOYMENT",
                    friendly_name="Subsidized Public-Sector Employment",
                    type="string",
                    startIndex=72,
                    endIndex=74,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="52",
                    name="WORK_EXPERIENCE",
                    friendly_name="Work Experience",
                    type="string",
                    startIndex=74,
                    endIndex=76,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="53",
                    name="OJT",
                    friendly_name="On-the-job Training",
                    type="string",
                    startIndex=76,
                    endIndex=78,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="54",
                    name="JOB_SEARCH",
                    friendly_name="Job Search and Job Readiness Assistance",
                    type="string",
                    startIndex=78,
                    endIndex=80,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="55",
                    name="COMM_SERVICES",
                    friendly_name="Community Service Programs",
                    type="string",
                    startIndex=80,
                    endIndex=82,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="56",
                    name="VOCATIONAL_ED_TRAINING",
                    friendly_name="Vocational Educational Training",
                    type="string",
                    startIndex=82,
                    endIndex=84,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="57",
                    name="JOB_SKILLS_TRAINING",
                    friendly_name="Job Skills Training Directly Related to Employment",
                    type="string",
                    startIndex=84,
                    endIndex=86,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="58",
                    name="ED_NO_HIGH_SCHOOL_DIPLOMA",
                    friendly_name="Education Directly Related to Employment for Individualswith no High School Diploma or Certificate of High SchoolEquivalency",
                    type="string",
                    startIndex=86,
                    endIndex=88,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="59",
                    name="SCHOOL_ATTENDENCE",
                    friendly_name="Satisfactory School Attendance for Individuals with No HighSchool Diploma or Certificate of High School Equivalency",
                    type="string",
                    startIndex=88,
                    endIndex=90,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="60",
                    name="PROVIDE_CC",
                    friendly_name="Providing Child Care Services to an Individual Who Is Participating in a Community Service Program",
                    type="string",
                    startIndex=90,
                    endIndex=92,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="61",
                    name="ADD_WORK_ACTIVITIES",
                    friendly_name="Additional Work Activities",
                    type="string",
                    startIndex=92,
                    endIndex=94,
                    required=False,
                    validators=[
                        validators.matches("00"),
                    ],
                ),
                Field(
                    item="62",
                    name="OTHER_WORK_ACTIVITIES",
                    friendly_name="Other Work Activities",
                    type="string",
                    startIndex=94,
                    endIndex=96,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="63",
                    name="REQ_HRS_WAIVER_DEMO",
                    friendly_name="Required Hours of Work under Waiver Demonstration",
                    type="string",
                    startIndex=96,
                    endIndex=98,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 99),
                    ],
                ),
                Field(
                    item="64",
                    name="EARNED_INCOME",
                    friendly_name="Amount of Earned Income",
                    type="string",
                    startIndex=98,
                    endIndex=102,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 9999),
                    ],
                ),
                Field(
                    item="65A",
                    name="UNEARNED_INCOME_TAX_CREDIT",
                    friendly_name="Amount of Unearned Income: Earned Income Tax Credit (EITC)",
                    type="string",
                    startIndex=102,
                    endIndex=106,
                    required=False,
                    validators=[
                        validators.isInStringRange(0, 9999),
                    ],
                ),
                Field(
                    item="65B",
                    name="UNEARNED_SOCIAL_SECURITY",
                    friendly_name="Amount of Unearned Income: Social Security",
                    type="string",
                    startIndex=106,
                    endIndex=110,
                    required=True,
                    validators=[
                        validators.isInStringRange(0, 9999),
                    ],
                ),
                Field(
                    item="65C",
                    name="UNEARNED_SSI",
                    friendly_name="Amount of Unearned Income: SSI",
                    type="string",
                    startIndex=110,
                    endIndex=114,
                    required=True,
                    validators=[
                        validators.isInStringRange(0, 9999),
                    ],
                ),
                Field(
                    item="65D",
                    name="UNEARNED_WORKERS_COMP",
                    friendly_name="Amount of Unearned Income: Worker's Compensation",
                    type="string",
                    startIndex=114,
                    endIndex=118,
                    required=True,
                    validators=[
                        validators.isInStringRange(0, 9999),
                    ],
                ),
                Field(
                    item="65E",
                    name="OTHER_UNEARNED_INCOME",
                    friendly_name="Amount of Unearned Income: Other",
                    type="string",
                    startIndex=118,
                    endIndex=122,
                    required=True,
                    validators=[
                        validators.isInStringRange(0, 9999),
                    ],
                ),
                Field(
                    item="-1",
                    name="BLANK",
                    friendly_name="blank",
                    type="string",
                    startIndex=122,
                    endIndex=123,
                    required=False,
                    validators=[],
                ),
            ],
        )
    ]
)
