"""Schema for Tribal TANF T2 row of all submission types."""

from django.db.models import Q

from tdpservice.parsers.dataclasses import FieldType
from tdpservice.parsers.fields import Field, TransformField
from tdpservice.parsers.row_schema import TanfDataReportSchema
from tdpservice.parsers.transforms import tanf_ssn_decryption_func, zero_pad
from tdpservice.parsers.util import get_t2_t3_t5_partial_hash_members
from tdpservice.parsers.validators import category1, category2, category3
from tdpservice.search_indexes.models.tribal import Tribal_TANF_T2

t2 = [
    TanfDataReportSchema(
        record_type="T2",
        model=Tribal_TANF_T2,
        partial_dup_exclusion_query=Q(FAMILY_AFFILIATION__in=(3, 5)),
        get_partial_dup_fields=get_t2_t3_t5_partial_hash_members,
        preparsing_validators=[
            category1.recordHasLengthOfAtLeast(122),
            category1.caseNumberNotEmpty(8, 19),
            category1.or_priority_validators(
                [
                    category1.validate_fieldYearMonth_with_headerYearQuarter(),
                    category1.validateRptMonthYear(),
                ]
            ),
        ],
        postparsing_validators=[
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_HISPANIC",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_AMER_INDIAN",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_ASIAN",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_BLACK",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_HAWAIIAN",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_WHITE",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="MARITAL_STATUS",
                result_function=category3.isBetween(1, 5, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 2, inclusive=True),
                result_field_name="PARENT_MINOR_CHILD",
                result_function=category3.isBetween(1, 3, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="EDUCATION_LEVEL",
                result_function=category3.orValidators(
                    [
                        category3.isBetween(0, 16, inclusive=True, cast=int),
                        category3.isBetween(98, 99, inclusive=True, cast=int),
                    ],
                    if_result=True,
                ),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isEqual(1),
                result_field_name="CITIZENSHIP_STATUS",
                result_function=category3.isOneOf((1, 2)),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="COOPERATION_CHILD_SUPPORT",
                result_function=category3.isOneOf((1, 2, 9)),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="EMPLOYMENT_STATUS",
                result_function=category3.isBetween(1, 3, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isOneOf((1, 2)),
                result_field_name="WORK_PART_STATUS",
                result_function=category3.orValidators(
                    [
                        category3.isBetween(1, 3, inclusive=True, cast=int),
                        category3.isBetween(5, 9, inclusive=True, cast=int),
                        category3.isBetween(11, 19, inclusive=True, cast=int),
                        category3.isEqual("99"),
                    ],
                    if_result=True,
                ),
            ),
        ],
        fields=[
            Field(
                item="0",
                name="RecordType",
                friendly_name="Record Type",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=0,
                endIndex=2,
                required=True,
                validators=[],
            ),
            Field(
                item="4",
                name="RPT_MONTH_YEAR",
                friendly_name="Reporting Year and Month",
                type=FieldType.NUMERIC,
                startIndex=2,
                endIndex=8,
                required=True,
                validators=[
                    category2.dateYearIsLargerThan(1900),
                    category2.dateMonthIsValid(),
                ],
            ),
            Field(
                item="6",
                name="CASE_NUMBER",
                friendly_name="Case Number--TANF",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=8,
                endIndex=19,
                required=True,
                validators=[category2.isNotEmpty()],
            ),
            Field(
                item="30",
                name="FAMILY_AFFILIATION",
                friendly_name="Family Affiliation",
                type=FieldType.NUMERIC,
                startIndex=19,
                endIndex=20,
                required=True,
                validators=[category2.isOneOf([1, 2, 3, 5])],
            ),
            Field(
                item="31",
                name="NONCUSTODIAL_PARENT",
                friendly_name="Noncustodial Parent Indicator",
                type=FieldType.NUMERIC,
                startIndex=20,
                endIndex=21,
                required=True,
                validators=[category2.isOneOf([1, 2])],
            ),
            Field(
                item="32",
                name="DATE_OF_BIRTH",
                friendly_name="Date of Birth",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=21,
                endIndex=29,
                required=True,
                validators=[
                    category2.intHasLength(8),
                    category2.dateYearIsLargerThan(1900),
                    category2.dateMonthIsValid(),
                    category2.dateDayIsValid(),
                ],
            ),
            TransformField(
                transform_func=tanf_ssn_decryption_func,
                item="33",
                name="SSN",
                friendly_name="Social Security Number",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=29,
                endIndex=38,
                required=True,
                validators=[category2.isNumber()],
                is_encrypted=False,
            ),
            Field(
                item="34A",
                name="RACE_HISPANIC",
                friendly_name="Hispanic or Latino",
                type=FieldType.NUMERIC,
                startIndex=38,
                endIndex=39,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="34B",
                name="RACE_AMER_INDIAN",
                friendly_name="American Indian or Alaska Native",
                type=FieldType.NUMERIC,
                startIndex=39,
                endIndex=40,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="34C",
                name="RACE_ASIAN",
                friendly_name="Asian",
                type=FieldType.NUMERIC,
                startIndex=40,
                endIndex=41,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="34D",
                name="RACE_BLACK",
                friendly_name="Black or African American",
                type=FieldType.NUMERIC,
                startIndex=41,
                endIndex=42,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="34E",
                name="RACE_HAWAIIAN",
                friendly_name="Native Hawaiian or Pacific Islander",
                type=FieldType.NUMERIC,
                startIndex=42,
                endIndex=43,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="34F",
                name="RACE_WHITE",
                friendly_name="White",
                type=FieldType.NUMERIC,
                startIndex=43,
                endIndex=44,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="35",
                name="SEX",
                friendly_name="Sex",
                type=FieldType.NUMERIC,
                startIndex=44,
                endIndex=45,
                required=False,
                validators=[
                    category2.isGreaterThan(0, inclusive=True),
                ],
            ),
            Field(
                item="36A",
                name="FED_OASDI_PROGRAM",
                friendly_name="Receives Disability Benefits: OASDI Program",
                type=FieldType.NUMERIC,
                startIndex=45,
                endIndex=46,
                required=True,
                validators=[category2.isOneOf([1, 2])],
            ),
            Field(
                item="36B",
                name="FED_DISABILITY_STATUS",
                friendly_name="Receives Disability Benefits: Other Federal Disability Status",
                type=FieldType.NUMERIC,
                startIndex=46,
                endIndex=47,
                required=True,
                validators=[category2.isOneOf([1, 2])],
            ),
            Field(
                item="36C",
                name="DISABLED_TITLE_XIVAPDT",
                friendly_name="Receives Disability Benefits: Permanently and Totally Disabled",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=47,
                endIndex=48,
                required=True,
                validators=[
                    category3.orValidators(
                        [category3.isOneOf(["1", "2"]), category3.isBlank()]
                    )
                ],
            ),
            Field(
                item="36D",
                name="AID_AGED_BLIND",
                friendly_name="Receives Disability Benefits: AABD",
                type=FieldType.NUMERIC,
                startIndex=48,
                endIndex=49,
                required=False,
                validators=[
                    category2.isBetween(0, 2, inclusive=True),
                ],
            ),
            Field(
                item="36E",
                name="RECEIVE_SSI",
                friendly_name="Receives Disability Benefits: SSI",
                type=FieldType.NUMERIC,
                startIndex=49,
                endIndex=50,
                required=True,
                validators=[
                    category2.isOneOf([1, 2]),
                ],
            ),
            Field(
                item="37",
                name="MARITAL_STATUS",
                friendly_name="Marital Status",
                type=FieldType.NUMERIC,
                startIndex=50,
                endIndex=51,
                required=False,
                validators=[
                    category2.isBetween(0, 5, inclusive=True),
                ],
            ),
            Field(
                item="38",
                name="RELATIONSHIP_HOH",
                friendly_name="Relationship to Head-of-Household",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=51,
                endIndex=53,
                required=True,
                validators=[
                    category2.isBetween(1, 10, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="39",
                name="PARENT_MINOR_CHILD",
                friendly_name="Parent With Minor Child in the Family",
                type=FieldType.NUMERIC,
                startIndex=53,
                endIndex=54,
                required=False,
                validators=[
                    category2.isBetween(0, 3, inclusive=True),
                ],
            ),
            Field(
                item="40",
                name="NEEDS_PREGNANT_WOMAN",
                friendly_name="Needs of a Pregnant Woman",
                type=FieldType.NUMERIC,
                startIndex=54,
                endIndex=55,
                required=False,
                validators=[
                    category2.isBetween(0, 2, inclusive=True),
                ],
            ),
            Field(
                item="41",
                name="EDUCATION_LEVEL",
                friendly_name="Educational Level",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=55,
                endIndex=57,
                required=False,
                validators=[
                    category3.orValidators(
                        [
                            category3.isBetween(0, 16, inclusive=True, cast=int),
                            category3.isBetween(98, 99, inclusive=True, cast=int),
                        ]
                    )
                ],
            ),
            Field(
                item="42",
                name="CITIZENSHIP_STATUS",
                friendly_name="Citizenship/Alienage",
                type=FieldType.NUMERIC,
                startIndex=57,
                endIndex=58,
                required=False,
                validators=[category2.isOneOf([1, 2, 9])],
            ),
            Field(
                item="43",
                name="COOPERATION_CHILD_SUPPORT",
                friendly_name="Cooperation with Child Support",
                type=FieldType.NUMERIC,
                startIndex=58,
                endIndex=59,
                required=False,
                validators=[
                    category2.isOneOf([0, 1, 2, 9]),
                ],
            ),
            Field(
                item="44",
                name="MONTHS_FED_TIME_LIMIT",
                friendly_name="Number of Months Countable toward Tribal Time Limit",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=59,
                endIndex=62,
                required=False,
                validators=[
                    category2.isBetween(0, 999, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="45",
                name="MONTHS_STATE_TIME_LIMIT",
                friendly_name="Number of Countable Months Remaining Under the Tribe's Time Limit",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=62,
                endIndex=64,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="46",
                name="CURRENT_MONTH_STATE_EXEMPT",
                friendly_name="Current Month Exempt from the (Tribe's) Time Limit",
                type=FieldType.NUMERIC,
                startIndex=64,
                endIndex=65,
                required=False,
                validators=[
                    category2.isBetween(0, 2, inclusive=True),
                ],
            ),
            Field(
                item="47",
                name="EMPLOYMENT_STATUS",
                friendly_name="Employment Status",
                type=FieldType.NUMERIC,
                startIndex=65,
                endIndex=66,
                required=False,
                validators=[
                    category2.isBetween(0, 3, inclusive=True),
                ],
            ),
            Field(
                item="48",
                name="WORK_PART_STATUS",
                friendly_name="Work Participation Status",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=66,
                endIndex=68,
                required=False,
                validators=[
                    category3.orValidators(
                        [
                            category3.isBetween(0, 3, inclusive=True, cast=int),
                            category3.isBetween(5, 9, inclusive=True, cast=int),
                            category3.isBetween(11, 19, inclusive=True, cast=int),
                            category3.isEqual("99"),
                        ]
                    )
                ],
            ),
            Field(
                item="49",
                name="UNSUB_EMPLOYMENT",
                friendly_name="Unsubsidized Employment",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=68,
                endIndex=70,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="50",
                name="SUB_PRIVATE_EMPLOYMENT",
                friendly_name="Subsidized Private-Sector Employment.",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=70,
                endIndex=72,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="51",
                name="SUB_PUBLIC_EMPLOYMENT",
                friendly_name="Subsidized Public-Sector Employment",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=72,
                endIndex=74,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="52",
                name="WORK_EXPERIENCE",
                friendly_name="Work Experience",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=74,
                endIndex=76,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="53",
                name="OJT",
                friendly_name="On-the-job Training",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=76,
                endIndex=78,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="54",
                name="JOB_SEARCH",
                friendly_name="Job Search and Job Readiness",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=78,
                endIndex=80,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="55",
                name="COMM_SERVICES",
                friendly_name="Community Service Programs",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=80,
                endIndex=82,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="56",
                name="VOCATIONAL_ED_TRAINING",
                friendly_name="Vocational Educational Training",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=82,
                endIndex=84,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="57",
                name="JOB_SKILLS_TRAINING",
                friendly_name="Job Skills Training",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=84,
                endIndex=86,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="58",
                name="ED_NO_HIGH_SCHOOL_DIPLOMA",
                friendly_name="Education Directly Related to Employment",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=86,
                endIndex=88,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="59",
                name="SCHOOL_ATTENDENCE",
                friendly_name="Satisfactory School Attendance",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=88,
                endIndex=90,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="60",
                name="PROVIDE_CC",
                friendly_name="Providing Child Care",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=90,
                endIndex=92,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            TransformField(
                zero_pad(2),
                item="61",
                name="ADD_WORK_ACTIVITIES",
                friendly_name="Additional Work Activities",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=92,
                endIndex=94,
                required=False,
                validators=[
                    category2.isEqual("00"),
                ],
            ),
            Field(
                item="62",
                name="OTHER_WORK_ACTIVITIES",
                friendly_name="Other Work Activities",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=94,
                endIndex=96,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="63",
                name="REQ_HRS_WAIVER_DEMO",
                friendly_name="Required Hours of Work under Waiver Demonstration",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=96,
                endIndex=98,
                required=False,
                validators=[
                    category2.isBetween(0, 99, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="64",
                name="EARNED_INCOME",
                friendly_name="Amount of Earned Income",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=98,
                endIndex=102,
                required=False,
                validators=[
                    category2.isBetween(0, 9999, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="65A",
                name="UNEARNED_INCOME_TAX_CREDIT",
                friendly_name="Amount of Unearned Income",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=102,
                endIndex=106,
                required=False,
                validators=[
                    category2.isBetween(0, 9999, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="65B",
                name="UNEARNED_SOCIAL_SECURITY",
                friendly_name="Amount of Unearned Income: Social Security",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=106,
                endIndex=110,
                required=True,
                validators=[
                    category2.isBetween(0, 9999, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="65C",
                name="UNEARNED_SSI",
                friendly_name="Amount of Unearned Income: SSI",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=110,
                endIndex=114,
                required=True,
                validators=[
                    category2.isBetween(0, 9999, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="65D",
                name="UNEARNED_WORKERS_COMP",
                friendly_name="Amount of Unearned Income: Worker's Compensation",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=114,
                endIndex=118,
                required=True,
                validators=[
                    category2.isBetween(0, 9999, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="65E",
                name="OTHER_UNEARNED_INCOME",
                friendly_name="Amount of Unearned Income: Other",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=118,
                endIndex=122,
                required=True,
                validators=[
                    category2.isBetween(0, 9999, inclusive=True, cast=int),
                ],
            ),
            Field(
                item="-1",
                name="BLANK",
                friendly_name="blank",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=122,
                endIndex=123,
                required=False,
                validators=[],
            ),
        ],
    )
]
