"""Schema for Tribal TANF T3 row of all submission types."""


from tdpservice.parsers.transforms import tanf_ssn_decryption_func
from tdpservice.parsers.fields import Field, TransformField
from tdpservice.parsers.row_schema import RowSchema, SchemaManager
from tdpservice.parsers.validators.category1 import PreparsingValidators
from tdpservice.parsers.validators.category2 import FieldValidators
from tdpservice.parsers.validators.category3 import PostparsingValidators
from tdpservice.parsers.validators.util import is_quiet_preparser_errors
from tdpservice.search_indexes.documents.tribal import Tribal_TANF_T3DataSubmissionDocument
from tdpservice.parsers.util import generate_t2_t3_t5_hashes, get_t2_t3_t5_partial_hash_members

FIRST_CHILD = 1
SECOND_CHILD = 2

child_one = RowSchema(
    record_type="T3",
    document=Tribal_TANF_T3DataSubmissionDocument(),
    generate_hashes_func=generate_t2_t3_t5_hashes,
    should_skip_partial_dup_func=lambda record: record.FAMILY_AFFILIATION in {2, 4, 5},
    get_partial_hash_members_func=get_t2_t3_t5_partial_hash_members,
    preparsing_validators=[
        PreparsingValidators.t3_m3_child_validator(FIRST_CHILD),
        PreparsingValidators.caseNumberNotEmpty(8, 19),
        PreparsingValidators.or_priority_validators([
                    PreparsingValidators.validate_fieldYearMonth_with_headerYearQuarter(),
                    PreparsingValidators.validateRptMonthYear(),
                ]),
    ],
    postparsing_validators=[
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(1),
            result_field_name="SSN",
            result_function=PostparsingValidators.validateSSN(),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_HISPANIC",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_AMER_INDIAN",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_ASIAN",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_BLACK",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_HAWAIIAN",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_WHITE",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RELATIONSHIP_HOH",
            result_function=PostparsingValidators.isBetween(4, 9, inclusive=True, cast=int),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="PARENT_MINOR_CHILD",
            result_function=PostparsingValidators.isOneOf((2, 3)),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(1),
            result_field_name="EDUCATION_LEVEL",
            result_function=PostparsingValidators.isNotEqual("99"),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(1),
            result_field_name="CITIZENSHIP_STATUS",
            result_function=PostparsingValidators.isOneOf((1, 2)),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(2),
            result_field_name="CITIZENSHIP_STATUS",
            result_function=PostparsingValidators.isOneOf((1, 2, 9)),
        ),
    ],
    fields=[
        Field(
            item="0",
            name="RecordType",
            friendly_name="Record Type",
            type="string",
            startIndex=0,
            endIndex=2,
            required=True,
            validators=[],
        ),
        Field(
            item="4",
            name="RPT_MONTH_YEAR",
            friendly_name="Reporting Year and Month",
            type="number",
            startIndex=2,
            endIndex=8,
            required=True,
            validators=[],
        ),
        Field(
            item="6",
            name="CASE_NUMBER",
            friendly_name="Case Number--TANF",
            type="string",
            startIndex=8,
            endIndex=19,
            required=True,
            validators=[FieldValidators.isNotEmpty()],
        ),
        Field(
            item="66",
            name="FAMILY_AFFILIATION",
            friendly_name="Family Affiliation",
            type="number",
            startIndex=19,
            endIndex=20,
            required=True,
            validators=[FieldValidators.isOneOf([1, 2, 4])],
        ),
        Field(
            item="67",
            name="DATE_OF_BIRTH",
            friendly_name="Date of Birth",
            type="string",
            startIndex=20,
            endIndex=28,
            required=True,
            validators=[FieldValidators.intHasLength(8),
                        FieldValidators.dateYearIsLargerThan(1900),
                        FieldValidators.dateMonthIsValid(),
                        FieldValidators.dateDayIsValid()
                        ]
        ),
        TransformField(
            transform_func=tanf_ssn_decryption_func,
            item="68",
            name="SSN",
            friendly_name="Social Security Number",
            type="string",
            startIndex=28,
            endIndex=37,
            required=True,
            validators=[FieldValidators.isNumber()],
            is_encrypted=False,
        ),
        Field(
            item="69A",
            name="RACE_HISPANIC",
            friendly_name="Hispanic or Latino",
            type="number",
            startIndex=37,
            endIndex=38,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69B",
            name="RACE_AMER_INDIAN",
            friendly_name="American Indian or Alaska Native",
            type="number",
            startIndex=38,
            endIndex=39,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69C",
            name="RACE_ASIAN",
            friendly_name="Asian",
            type="number",
            startIndex=39,
            endIndex=40,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69D",
            name="RACE_BLACK",
            friendly_name="Black or African American",
            type="number",
            startIndex=40,
            endIndex=41,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69E",
            name="RACE_HAWAIIAN",
            friendly_name="Native Hawaiian or Pacific Islander",
            type="number",
            startIndex=41,
            endIndex=42,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69F",
            name="RACE_WHITE",
            friendly_name="White",
            type="number",
            startIndex=42,
            endIndex=43,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="70",
            name="GENDER",
            friendly_name="Gender",
            type="number",
            startIndex=43,
            endIndex=44,
            required=False,
            validators=[FieldValidators.isBetween(0, 9, inclusive=True)],
        ),
        Field(
            item="71A",
            name="RECEIVE_NONSSA_BENEFITS",
            friendly_name="Received Disability Benefits: Other Federal Disability Status",
            type="number",
            startIndex=44,
            endIndex=45,
            required=True,
            validators=[FieldValidators.isOneOf([1, 2])],
        ),
        Field(
            item="71B",
            name="RECEIVE_SSI",
            friendly_name="Receives Supplemental Security Income: SSI",
            type="number",
            startIndex=45,
            endIndex=46,
            required=True,
            validators=[FieldValidators.isOneOf([1, 2])],
        ),
        Field(
            item="72",
            name="RELATIONSHIP_HOH",
            friendly_name="Relationship to Head-of-Household",
            type="string",
            startIndex=46,
            endIndex=48,
            required=False,
            validators=[FieldValidators.isBetween(0, 10, inclusive=True, cast=int)],
        ),
        Field(
            item="73",
            name="PARENT_MINOR_CHILD",
            friendly_name="Parent With Minor Child in the Family",
            type="number",
            startIndex=48,
            endIndex=49,
            required=False,
            validators=[FieldValidators.isOneOf([0, 2, 3])],
        ),
        Field(
            item="74",
            name="EDUCATION_LEVEL",
            friendly_name="Educational Level",
            type="string",
            startIndex=49,
            endIndex=51,
            required=True,
            validators=[
                FieldValidators.orValidators([
                    PostparsingValidators.isBetween(0, 16, inclusive=True, cast=int),
                    PostparsingValidators.isBetween(98, 99, inclusive=True, cast=int),
                ])
            ],
        ),
        Field(
            item="75",
            name="CITIZENSHIP_STATUS",
            friendly_name="Citizenship/Alienage",
            type="number",
            startIndex=51,
            endIndex=52,
            required=False,
            validators=[FieldValidators.isOneOf([0, 1, 2, 9])],
        ),
        Field(
            item="76A",
            name="UNEARNED_SSI",
            friendly_name="Amount of Unearned Income: SSI",
            type="string",
            startIndex=52,
            endIndex=56,
            required=True,
            validators=[FieldValidators.isBetween(0, 9999, inclusive=True, cast=int)],
        ),
        Field(
            item="76B",
            name="OTHER_UNEARNED_INCOME",
            friendly_name="Amount of Unearned Income: Other",
            type="string",
            startIndex=56,
            endIndex=60,
            required=True,
            validators=[FieldValidators.isBetween(0, 9999, inclusive=True, cast=int)],
        ),
    ],
)

child_two = RowSchema(
    record_type="T3",
    document=Tribal_TANF_T3DataSubmissionDocument(),
    generate_hashes_func=generate_t2_t3_t5_hashes,
    should_skip_partial_dup_func=lambda record: record.FAMILY_AFFILIATION in {2, 4, 5},
    get_partial_hash_members_func=get_t2_t3_t5_partial_hash_members,
    quiet_preparser_errors=is_quiet_preparser_errors(min_length=61),
    preparsing_validators=[
        PreparsingValidators.t3_m3_child_validator(SECOND_CHILD),
        PreparsingValidators.caseNumberNotEmpty(8, 19),
        PreparsingValidators.or_priority_validators([
                    PreparsingValidators.validate_fieldYearMonth_with_headerYearQuarter(),
                    PreparsingValidators.validateRptMonthYear(),
                ]),
    ],
    postparsing_validators=[
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(1),
            result_field_name="SSN",
            result_function=PostparsingValidators.validateSSN(),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_HISPANIC",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_AMER_INDIAN",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_ASIAN",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_BLACK",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_HAWAIIAN",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RACE_WHITE",
            result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="RELATIONSHIP_HOH",
            result_function=PostparsingValidators.isBetween(4, 9, inclusive=True, cast=int),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isOneOf((1, 2)),
            result_field_name="PARENT_MINOR_CHILD",
            result_function=PostparsingValidators.isOneOf((2, 3)),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(1),
            result_field_name="EDUCATION_LEVEL",
            result_function=PostparsingValidators.isNotEqual("99"),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(1),
            result_field_name="CITIZENSHIP_STATUS",
            result_function=PostparsingValidators.isOneOf((1, 2)),
        ),
        PostparsingValidators.ifThenAlso(
            condition_field_name="FAMILY_AFFILIATION",
            condition_function=PostparsingValidators.isEqual(2),
            result_field_name="CITIZENSHIP_STATUS",
            result_function=PostparsingValidators.isOneOf((1, 2, 9)),
        ),
    ],
    fields=[
        Field(
            item="0",
            name="RecordType",
            friendly_name="Record Type",
            type="string",
            startIndex=0,
            endIndex=2,
            required=True,
            validators=[],
        ),
        Field(
            item="4",
            name="RPT_MONTH_YEAR",
            friendly_name="Reporting Year and Month",
            type="number",
            startIndex=2,
            endIndex=8,
            required=True,
            validators=[],
        ),
        Field(
            item="6",
            name="CASE_NUMBER",
            friendly_name="Case Number--TANF",
            type="string",
            startIndex=8,
            endIndex=19,
            required=True,
            validators=[FieldValidators.isNotEmpty()],
        ),
        Field(
            item="66",
            name="FAMILY_AFFILIATION",
            friendly_name="Family Affiliation",
            type="number",
            startIndex=60,
            endIndex=61,
            required=True,
            validators=[FieldValidators.isOneOf([1, 2, 4])],
        ),
        Field(
            item="67",
            name="DATE_OF_BIRTH",
            friendly_name="Date of Birth",
            type="string",
            startIndex=61,
            endIndex=69,
            required=True,
            validators=[FieldValidators.intHasLength(8),
                        FieldValidators.dateYearIsLargerThan(1900),
                        FieldValidators.dateMonthIsValid(),
                        FieldValidators.dateDayIsValid()
                        ]
        ),
        TransformField(
            transform_func=tanf_ssn_decryption_func,
            item="68",
            name="SSN",
            friendly_name="Social Security Number",
            type="string",
            startIndex=69,
            endIndex=78,
            required=True,
            validators=[FieldValidators.isNumber()],
            is_encrypted=False,
        ),
        Field(
            item="69A",
            name="RACE_HISPANIC",
            friendly_name="Hispanic or Latino",
            type="number",
            startIndex=78,
            endIndex=79,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69B",
            name="RACE_AMER_INDIAN",
            friendly_name="American Indian or Alaska Natve",
            type="number",
            startIndex=79,
            endIndex=80,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69C",
            name="RACE_ASIAN",
            friendly_name="Asian",
            type="number",
            startIndex=80,
            endIndex=81,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69D",
            name="RACE_BLACK",
            friendly_name="Black or African American",
            type="number",
            startIndex=81,
            endIndex=82,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69E",
            name="RACE_HAWAIIAN",
            friendly_name="Native Hawaiian or Other Pacific Islander",
            type="number",
            startIndex=82,
            endIndex=83,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="69F",
            name="RACE_WHITE",
            friendly_name="White",
            type="number",
            startIndex=83,
            endIndex=84,
            required=False,
            validators=[FieldValidators.validateRace()],
        ),
        Field(
            item="70",
            name="GENDER",
            friendly_name="Gender",
            type="number",
            startIndex=84,
            endIndex=85,
            required=False,
            validators=[FieldValidators.isBetween(0, 9, inclusive=True)],
        ),
        Field(
            item="71A",
            name="RECEIVE_NONSSA_BENEFITS",
            friendly_name="Receives Disability Benefits: Other Federal Disability Status",
            type="number",
            startIndex=85,
            endIndex=86,
            required=True,
            validators=[FieldValidators.isOneOf([1, 2])],
        ),
        Field(
            item="71B",
            name="RECEIVE_SSI",
            friendly_name="Receives Disability Benefits: SSI",
            type="number",
            startIndex=86,
            endIndex=87,
            required=True,
            validators=[FieldValidators.isOneOf([1, 2])],
        ),
        Field(
            item="72",
            name="RELATIONSHIP_HOH",
            friendly_name="Relationship to Head-of-Household",
            type="string",
            startIndex=87,
            endIndex=89,
            required=False,
            validators=[FieldValidators.isBetween(0, 10, inclusive=True, cast=int)],
        ),
        Field(
            item="73",
            name="PARENT_MINOR_CHILD",
            friendly_name="Parent With Minor Child in the Family",
            type="number",
            startIndex=89,
            endIndex=90,
            required=False,
            validators=[FieldValidators.isOneOf([0, 2, 3])],
        ),
        Field(
            item="74",
            name="EDUCATION_LEVEL",
            friendly_name="Educational Level",
            type="string",
            startIndex=90,
            endIndex=92,
            required=True,
            validators=[
                FieldValidators.orValidators([
                    PostparsingValidators.isBetween(0, 16, inclusive=True, cast=int),
                    PostparsingValidators.isOneOf(["98", "99"])
                ])
            ],
        ),
        Field(
            item="75",
            name="CITIZENSHIP_STATUS",
            friendly_name="Citizenship/Alienage",
            type="number",
            startIndex=92,
            endIndex=93,
            required=False,
            validators=[FieldValidators.isOneOf([0, 1, 2, 9])],
        ),
        Field(
            item="76A",
            name="UNEARNED_SSI",
            friendly_name="Amount of Unearned Income: SSI",
            type="string",
            startIndex=93,
            endIndex=97,
            required=True,
            validators=[FieldValidators.isBetween(0, 9999, inclusive=True, cast=int)],
        ),
        Field(
            item="76B",
            name="OTHER_UNEARNED_INCOME",
            friendly_name="Amount of Unearned Income: Other",
            type="string",
            startIndex=97,
            endIndex=101,
            required=True,
            validators=[FieldValidators.isBetween(0, 9999, inclusive=True, cast=int)],
        ),
    ],
)

t3 = SchemaManager(schemas=[child_one, child_two])
