"""Schema for Tribal TANF T5 row of all submission types."""


from tdpservice.parsers.transforms import tanf_ssn_decryption_func
from tdpservice.parsers.fields import Field, TransformField
from tdpservice.parsers.row_schema import RowSchema, SchemaManager
from tdpservice.parsers.validators.category1 import PreparsingValidators
from tdpservice.parsers.validators.category2 import FieldValidators
from tdpservice.parsers.validators.category3 import PostparsingValidators
from tdpservice.search_indexes.documents.tribal import Tribal_TANF_T5DataSubmissionDocument
from tdpservice.parsers.util import generate_t2_t3_t5_hashes, get_t2_t3_t5_partial_hash_members


t5 = SchemaManager(
    schemas=[
        RowSchema(
            record_type="T5",
            document=Tribal_TANF_T5DataSubmissionDocument(),
            generate_hashes_func=generate_t2_t3_t5_hashes,
            should_skip_partial_dup_func=lambda record: record.FAMILY_AFFILIATION in {3, 4, 5},
            get_partial_hash_members_func=get_t2_t3_t5_partial_hash_members,
            preparsing_validators=[
                PreparsingValidators.recordHasLength(71),
                PreparsingValidators.caseNumberNotEmpty(8, 19),
                PreparsingValidators.or_priority_validators([
                    PreparsingValidators.validate_fieldYearMonth_with_headerYearQuarter(),
                    PreparsingValidators.validateRptMonthYear(),
                ]),
            ],
            postparsing_validators=[
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isEqual(1),
                    result_field_name="SSN",
                    result_function=PostparsingValidators.validateSSN(),
                ),
                PostparsingValidators.validate__FAM_AFF__SSN(),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="RACE_HISPANIC",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="RACE_AMER_INDIAN",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="RACE_ASIAN",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="RACE_BLACK",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="RACE_HAWAIIAN",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="RACE_WHITE",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="MARITAL_STATUS",
                    result_function=PostparsingValidators.isBetween(1, 5, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                    result_field_name="PARENT_MINOR_CHILD",
                    result_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isBetween(1, 3, inclusive=True),
                    result_field_name="EDUCATION_LEVEL",
                    result_function=PostparsingValidators.orValidators([
                        PostparsingValidators.isBetween(1, 16, inclusive=True, cast=int),
                        PostparsingValidators.isBetween(98, 99, inclusive=True, cast=int),
                    ]),
                ),
                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isEqual(1),
                    result_field_name="CITIZENSHIP_STATUS",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),

                PostparsingValidators.ifThenAlso(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=PostparsingValidators.isEqual(1),
                    result_field_name="REC_FEDERAL_DISABILITY",
                    result_function=PostparsingValidators.isBetween(1, 2, inclusive=True),
                ),
            ],
            fields=[
                Field(
                    item="0",
                    name="RecordType",
                    friendly_name="record type",
                    type="string",
                    startIndex=0,
                    endIndex=2,
                    required=True,
                    validators=[],
                ),
                Field(
                    item="4",
                    name="RPT_MONTH_YEAR",
                    friendly_name="reporting month and year",
                    type="number",
                    startIndex=2,
                    endIndex=8,
                    required=True,
                    validators=[
                        FieldValidators.dateYearIsLargerThan(1998),
                        FieldValidators.dateMonthIsValid(),
                    ],
                ),
                Field(
                    item="6",
                    name="CASE_NUMBER",
                    friendly_name="case number",
                    type="string",
                    startIndex=8,
                    endIndex=19,
                    required=True,
                    validators=[FieldValidators.isNotEmpty()],
                ),
                Field(
                    item="14",
                    name="FAMILY_AFFILIATION",
                    friendly_name="family affiliation",
                    type="number",
                    startIndex=19,
                    endIndex=20,
                    required=True,
                    validators=[FieldValidators.isBetween(1, 5, inclusive=True)],
                ),
                Field(
                    item="15",
                    name="DATE_OF_BIRTH",
                    friendly_name="date of birth",
                    type="string",
                    startIndex=20,
                    endIndex=28,
                    required=True,
                    validators=[FieldValidators.intHasLength(8),
                                FieldValidators.dateYearIsLargerThan(1900),
                                FieldValidators.dateMonthIsValid(),
                                FieldValidators.dateDayIsValid()
                                ]
                ),
                TransformField(
                    transform_func=tanf_ssn_decryption_func,
                    item="16",
                    name="SSN",
                    friendly_name="social security number - ssn",
                    type="string",
                    startIndex=28,
                    endIndex=37,
                    required=True,
                    validators=[FieldValidators.isNumber()],
                    is_encrypted=False,
                ),
                Field(
                    item="17A",
                    name="RACE_HISPANIC",
                    friendly_name="race hispanic",
                    type="number",
                    startIndex=37,
                    endIndex=38,
                    required=False,
                    validators=[FieldValidators.validateRace()],
                ),
                Field(
                    item="17B",
                    name="RACE_AMER_INDIAN",
                    friendly_name="race american indian",
                    type="number",
                    startIndex=38,
                    endIndex=39,
                    required=False,
                    validators=[FieldValidators.validateRace()],
                ),
                Field(
                    item="17C",
                    name="RACE_ASIAN",
                    friendly_name="race asian",
                    type="number",
                    startIndex=39,
                    endIndex=40,
                    required=False,
                    validators=[FieldValidators.validateRace()],
                ),
                Field(
                    item="17D",
                    name="RACE_BLACK",
                    friendly_name="race black",
                    type="number",
                    startIndex=40,
                    endIndex=41,
                    required=False,
                    validators=[FieldValidators.validateRace()],
                ),
                Field(
                    item="17E",
                    name="RACE_HAWAIIAN",
                    friendly_name="race hawaiian",
                    type="number",
                    startIndex=41,
                    endIndex=42,
                    required=False,
                    validators=[FieldValidators.validateRace()],
                ),
                Field(
                    item="17F",
                    name="RACE_WHITE",
                    friendly_name="race white",
                    type="number",
                    startIndex=42,
                    endIndex=43,
                    required=False,
                    validators=[FieldValidators.validateRace()],
                ),
                Field(
                    item="18",
                    name="GENDER",
                    friendly_name="gender",
                    type="number",
                    startIndex=43,
                    endIndex=44,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 9, inclusive=True)],
                ),
                Field(
                    item="19A",
                    name="REC_OASDI_INSURANCE",
                    friendly_name="receives old-age survivors and disability insurance",
                    type="number",
                    startIndex=44,
                    endIndex=45,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 2, inclusive=True)],
                ),
                Field(
                    item="19B",
                    name="REC_FEDERAL_DISABILITY",
                    friendly_name="receives federal disability",
                    type="number",
                    startIndex=45,
                    endIndex=46,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 2, inclusive=True)],
                ),
                Field(
                    item="19C",
                    name="REC_AID_TOTALLY_DISABLED",
                    friendly_name="receives aid for totally disabled",
                    type="number",
                    startIndex=46,
                    endIndex=47,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 2, inclusive=True)],
                ),
                Field(
                    item="19D",
                    name="REC_AID_AGED_BLIND",
                    friendly_name="receives from the aid to the aged, blind, and disabled program",
                    type="number",
                    startIndex=47,
                    endIndex=48,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 2, inclusive=True)],
                ),
                Field(
                    item="19E",
                    name="REC_SSI",
                    friendly_name="receives SSI",
                    type="number",
                    startIndex=48,
                    endIndex=49,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 2, inclusive=True)],
                ),
                Field(
                    item="20",
                    name="MARITAL_STATUS",
                    friendly_name="marital status",
                    type="number",
                    startIndex=49,
                    endIndex=50,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 5, inclusive=True)],
                ),
                Field(
                    item="21",
                    name="RELATIONSHIP_HOH",
                    friendly_name="relationship to head of household",
                    type="string",
                    startIndex=50,
                    endIndex=52,
                    required=True,
                    validators=[FieldValidators.isBetween(1, 10, inclusive=True, cast=int)],
                ),
                Field(
                    item="22",
                    name="PARENT_MINOR_CHILD",
                    friendly_name="parent of minor child",
                    type="number",
                    startIndex=52,
                    endIndex=53,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 2, inclusive=True)],
                ),
                Field(
                    item="23",
                    name="NEEDS_OF_PREGNANT_WOMAN",
                    friendly_name="needs of pregnant woman",
                    type="number",
                    startIndex=53,
                    endIndex=54,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 2, inclusive=True)],
                ),
                Field(
                    item="24",
                    name="EDUCATION_LEVEL",
                    friendly_name="educational level",
                    type="string",
                    startIndex=54,
                    endIndex=56,
                    required=False,
                    validators=[
                        FieldValidators.orValidators([
                            FieldValidators.isBetween(0, 16, inclusive=True, cast=int),
                            FieldValidators.isBetween(98, 99, inclusive=True, cast=int),
                        ])
                    ],
                ),
                Field(
                    item="25",
                    name="CITIZENSHIP_STATUS",
                    friendly_name="citizenship status",
                    type="number",
                    startIndex=56,
                    endIndex=57,
                    required=False,
                    validators=[
                        FieldValidators.orValidators([
                            FieldValidators.isBetween(0, 2, inclusive=True),
                            FieldValidators.isEqual(9)
                        ])
                    ],
                ),
                Field(
                    item="26",
                    name="COUNTABLE_MONTH_FED_TIME",
                    friendly_name="countable months toward federal time",
                    type="string",
                    startIndex=57,
                    endIndex=60,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 999, inclusive=True, cast=int)],
                ),
                Field(
                    item="27",
                    name="COUNTABLE_MONTHS_STATE_TRIBE",
                    friendly_name="countable months remaining under state tribe",
                    type="string",
                    startIndex=60,
                    endIndex=62,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 99, inclusive=True, cast=int)],
                ),
                Field(
                    item="28",
                    name="EMPLOYMENT_STATUS",
                    friendly_name="employment status",
                    type="number",
                    startIndex=62,
                    endIndex=63,
                    required=False,
                    validators=[FieldValidators.isBetween(0, 3, inclusive=True)],
                ),
                Field(
                    item="29",
                    name="AMOUNT_EARNED_INCOME",
                    friendly_name="Amount of Earned Income",
                    type="string",
                    startIndex=63,
                    endIndex=67,
                    required=True,
                    validators=[FieldValidators.isBetween(0, 9999, inclusive=True, cast=int)],
                ),
                Field(
                    item="30",
                    name="AMOUNT_UNEARNED_INCOME",
                    friendly_name="amount of unearned income",
                    type="string",
                    startIndex=67,
                    endIndex=71,
                    required=True,
                    validators=[FieldValidators.isBetween(0, 9999, inclusive=True, cast=int)],
                ),
            ],
        )
    ]
)
