"""Schema for Tribal TANF T5 row of all submission types."""

from django.db.models import Q

from tdpservice.parsers.dataclasses import FieldType
from tdpservice.parsers.fields import Field, TransformField
from tdpservice.parsers.row_schema import TanfDataReportSchema
from tdpservice.parsers.transforms import tanf_ssn_decryption_func
from tdpservice.parsers.util import get_t2_t3_t5_partial_dup_fields
from tdpservice.parsers.validators import category1, category2, category3
from tdpservice.search_indexes.models.tribal import Tribal_TANF_T5

t5 = [
    TanfDataReportSchema(
        record_type="T5",
        model=Tribal_TANF_T5,
        partial_dup_exclusion_query=Q(FAMILY_AFFILIATION__in=(3, 4, 5)),
        get_partial_dup_fields=get_t2_t3_t5_partial_dup_fields,
        preparsing_validators=[
            category1.recordHasLengthOfAtLeast(71),
            category1.caseNumberNotEmpty(8, 19),
            category1.or_priority_validators(
                [
                    category1.validate_fieldYearMonth_with_headerYearQuarter(),
                    category1.validateRptMonthYear(),
                ]
            ),
        ],
        postparsing_validators=[
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_HISPANIC",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_AMER_INDIAN",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_ASIAN",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_BLACK",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_HAWAIIAN",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="RACE_WHITE",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="MARITAL_STATUS",
                result_function=category3.isBetween(1, 5, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 2, inclusive=True),
                result_field_name="PARENT_MINOR_CHILD",
                result_function=category3.isBetween(1, 3, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isBetween(1, 3, inclusive=True),
                result_field_name="EDUCATION_LEVEL",
                result_function=category3.orValidators(
                    [
                        category3.isBetween(1, 16, inclusive=True, cast=int),
                        category3.isBetween(98, 99, inclusive=True, cast=int),
                    ],
                    if_result=True,
                ),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isEqual(1),
                result_field_name="CITIZENSHIP_STATUS",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
            category3.ifThenAlso(
                condition_field_name="FAMILY_AFFILIATION",
                condition_function=category3.isEqual(1),
                result_field_name="REC_FEDERAL_DISABILITY",
                result_function=category3.isBetween(1, 2, inclusive=True),
            ),
        ],
        fields=[
            Field(
                item="0",
                name="RecordType",
                friendly_name="Record Type",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=0,
                endIndex=2,
                required=True,
                validators=[],
            ),
            Field(
                item="4",
                name="RPT_MONTH_YEAR",
                friendly_name="Reporting Year and Month",
                type=FieldType.NUMERIC,
                startIndex=2,
                endIndex=8,
                required=True,
                validators=[
                    category2.dateYearIsLargerThan(1998),
                    category2.dateMonthIsValid(),
                ],
            ),
            Field(
                item="6",
                name="CASE_NUMBER",
                friendly_name="Case Number--TANF",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=8,
                endIndex=19,
                required=True,
                validators=[category2.isNotEmpty()],
            ),
            Field(
                item="14",
                name="FAMILY_AFFILIATION",
                friendly_name="Family Affiliation",
                type=FieldType.NUMERIC,
                startIndex=19,
                endIndex=20,
                required=True,
                validators=[category2.isBetween(1, 5, inclusive=True)],
            ),
            Field(
                item="15",
                name="DATE_OF_BIRTH",
                friendly_name="Date of Birth",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=20,
                endIndex=28,
                required=True,
                validators=[
                    category2.intHasLength(8),
                    category2.dateYearIsLargerThan(1900),
                    category2.dateMonthIsValid(),
                    category2.dateDayIsValid(),
                ],
            ),
            TransformField(
                transform_func=tanf_ssn_decryption_func,
                item="16",
                name="SSN",
                friendly_name="Social Security Number",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=28,
                endIndex=37,
                required=True,
                validators=[category2.isNumber()],
                is_encrypted=False,
            ),
            Field(
                item="17A",
                name="RACE_HISPANIC",
                friendly_name="Hispanic or Latino",
                type=FieldType.NUMERIC,
                startIndex=37,
                endIndex=38,
                required=False,
                validators=[category2.validateRace()],
            ),
            Field(
                item="17B",
                name="RACE_AMER_INDIAN",
                friendly_name="American Indian or Alaska Native",
                type=FieldType.NUMERIC,
                startIndex=38,
                endIndex=39,
                required=False,
                validators=[category2.validateRace()],
            ),
            Field(
                item="17C",
                name="RACE_ASIAN",
                friendly_name="Asian",
                type=FieldType.NUMERIC,
                startIndex=39,
                endIndex=40,
                required=False,
                validators=[category2.validateRace()],
            ),
            Field(
                item="17D",
                name="RACE_BLACK",
                friendly_name="Black or African American",
                type=FieldType.NUMERIC,
                startIndex=40,
                endIndex=41,
                required=False,
                validators=[category2.validateRace()],
            ),
            Field(
                item="17E",
                name="RACE_HAWAIIAN",
                friendly_name="Hawaiian or Pacific Islander",
                type=FieldType.NUMERIC,
                startIndex=41,
                endIndex=42,
                required=False,
                validators=[category2.validateRace()],
            ),
            Field(
                item="17F",
                name="RACE_WHITE",
                friendly_name="White",
                type=FieldType.NUMERIC,
                startIndex=42,
                endIndex=43,
                required=False,
                validators=[category2.validateRace()],
            ),
            Field(
                item="18",
                name="SEX",
                friendly_name="Sex",
                type=FieldType.NUMERIC,
                startIndex=43,
                endIndex=44,
                required=False,
                validators=[category2.isBetween(0, 9, inclusive=True)],
            ),
            Field(
                item="19A",
                name="REC_OASDI_INSURANCE",
                friendly_name="Received Disability Benefits: OASDI Program",
                type=FieldType.NUMERIC,
                startIndex=44,
                endIndex=45,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="19B",
                name="REC_FEDERAL_DISABILITY",
                friendly_name="Receives Disability Benefits: Other Federal Disability Status",
                type=FieldType.NUMERIC,
                startIndex=45,
                endIndex=46,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="19C",
                name="REC_AID_TOTALLY_DISABLED",
                friendly_name="Received Disability Benefits: Permanently and Totally Disabled",
                type=FieldType.NUMERIC,
                startIndex=46,
                endIndex=47,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="19D",
                name="REC_AID_AGED_BLIND",
                friendly_name="Received Disability Benefits: AABD",
                type=FieldType.NUMERIC,
                startIndex=47,
                endIndex=48,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="19E",
                name="REC_SSI",
                friendly_name="Received Disability Benefits: SSI",
                type=FieldType.NUMERIC,
                startIndex=48,
                endIndex=49,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="20",
                name="MARITAL_STATUS",
                friendly_name="Marital Status",
                type=FieldType.NUMERIC,
                startIndex=49,
                endIndex=50,
                required=False,
                validators=[category2.isBetween(0, 5, inclusive=True)],
            ),
            Field(
                item="21",
                name="RELATIONSHIP_HOH",
                friendly_name="Relationship to Head-of-Household",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=50,
                endIndex=52,
                required=True,
                validators=[category2.isBetween(1, 10, inclusive=True, cast=int)],
            ),
            Field(
                item="22",
                name="PARENT_MINOR_CHILD",
                friendly_name="Parent With Minor Child in the Family",
                type=FieldType.NUMERIC,
                startIndex=52,
                endIndex=53,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="23",
                name="NEEDS_OF_PREGNANT_WOMAN",
                friendly_name="Needs of a Pregnant Woman",
                type=FieldType.NUMERIC,
                startIndex=53,
                endIndex=54,
                required=False,
                validators=[category2.isBetween(0, 2, inclusive=True)],
            ),
            Field(
                item="24",
                name="EDUCATION_LEVEL",
                friendly_name="Educational Level",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=54,
                endIndex=56,
                required=False,
                validators=[
                    category3.orValidators(
                        [
                            category3.isBetween(0, 16, inclusive=True, cast=int),
                            category3.isBetween(98, 99, inclusive=True, cast=int),
                        ]
                    )
                ],
            ),
            Field(
                item="25",
                name="CITIZENSHIP_STATUS",
                friendly_name="Citizenship/Alienage",
                type=FieldType.NUMERIC,
                startIndex=56,
                endIndex=57,
                required=False,
                validators=[
                    category3.orValidators(
                        [
                            category3.isBetween(1, 2, inclusive=True),
                            category3.isEqual(9),
                        ]
                    )
                ],
            ),
            Field(
                item="26",
                name="COUNTABLE_MONTH_FED_TIME",
                friendly_name="Number of Months Countable Toward Tribal Time Limit",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=57,
                endIndex=60,
                required=False,
                validators=[category2.isBetween(0, 999, inclusive=True, cast=int)],
            ),
            Field(
                item="27",
                name="COUNTABLE_MONTHS_STATE_TRIBE",
                friendly_name="Number of Countable Months Remaining Under Tribe's Time Limit",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=60,
                endIndex=62,
                required=False,
                validators=[category2.isBetween(0, 99, inclusive=True, cast=int)],
            ),
            Field(
                item="28",
                name="EMPLOYMENT_STATUS",
                friendly_name="Employment Status",
                type=FieldType.NUMERIC,
                startIndex=62,
                endIndex=63,
                required=False,
                validators=[category2.isBetween(0, 3, inclusive=True)],
            ),
            Field(
                item="29",
                name="AMOUNT_EARNED_INCOME",
                friendly_name="Amount of Earned Income",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=63,
                endIndex=67,
                required=True,
                validators=[category2.isBetween(0, 9999, inclusive=True, cast=int)],
            ),
            Field(
                item="30",
                name="AMOUNT_UNEARNED_INCOME",
                friendly_name="Amount of Unearned Income",
                type=FieldType.ALPHA_NUMERIC,
                startIndex=67,
                endIndex=71,
                required=True,
                validators=[category2.isBetween(0, 9999, inclusive=True, cast=int)],
            ),
        ],
    )
]
