
set -o allexport
[[ -f ./tdrs-backend/.env.production ]] && source ./tdrs-backend/.env.production
set +o

CGHOSTNAME_BACKEND=$1

echo "Setting environment variables for $CGHOSTNAME_BACKEND from tdrs-backend/.env.production"

cf set-env $CGHOSTNAME_BACKEND ACR_VALUES $ACR_VALUES
cf set-env $CGHOSTNAME_BACKEND BASE_URL $BASE_URL
cf set-env $CGHOSTNAME_BACKEND CLIENT_ASSERTION_TYPE $CLIENT_ASSERTION_TYPE
cf set-env $CGHOSTNAME_BACKEND CLIENT_ID $CLIENT_ID
cf set-env $CGHOSTNAME_BACKEND DJANGO_SECRET_KEY $DJANGO_SECRET_KEY
cf set-env $CGHOSTNAME_BACKEND FRONTEND_BASE_URL $FRONTEND_BASE_URL
cf set-env $CGHOSTNAME_BACKEND OIDC_OP_AUTHORIZATION_ENDPOINT $OIDC_OP_AUTHORIZATION_ENDPOINT
cf set-env $CGHOSTNAME_BACKEND OIDC_OP_ISSUER $OIDC_OP_ISSUER
cf set-env $CGHOSTNAME_BACKEND OIDC_OP_JWKS_ENDPOINT $OIDC_OP_JWKS_ENDPOINT
cf set-env $CGHOSTNAME_BACKEND OIDC_OP_LOGOUT_ENDPOINT $OIDC_OP_LOGOUT_ENDPOINT
cf set-env $CGHOSTNAME_BACKEND OIDC_OP_TOKEN_ENDPOINT $OIDC_OP_TOKEN_ENDPOINT
cf set-env $CGHOSTNAME_BACKEND OIDC_RP_CLIENT_ID $OIDC_RP_CLIENT_ID
cf set-env $CGHOSTNAME_BACKEND PRIVATE_KEY $PRIVATE_KEY
cf set-env $CGHOSTNAME_BACKEND JWT_CERT_TEST $JWT_CERT_TEST
cf set-env $CGHOSTNAME_BACKEND AWS_ACCESS_KEY $AWS_ACCESS_KEY
cf set-env $CGHOSTNAME_BACKEND AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
cf set-env $CGHOSTNAME_BACKEND AWS_BUCKET $AWS_BUCKET
cf set-env $CGHOSTNAME_BACKEND AWS_REGION_NAME $AWS_REGION_NAME
cf set-env $CGHOSTNAME_BACKEND AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
cf set-env $CGHOSTNAME_BACKEND BUCKET_NAME $BUCKET_NAME
cf set-env $CGHOSTNAME_BACKEND DJANGO_AWS_ACCESS_KEY_ID $DJANGO_AWS_ACCESS_KEY_ID
cf set-env $CGHOSTNAME_BACKEND DJANGO_AWS_SECRET_ACCESS_KEY $DJANGO_AWS_SECRET_ACCESS_KEY
cf set-env $CGHOSTNAME_BACKEND DJANGO_AWS_STORAGE_BUCKET_NAME $DJANGO_AWS_STORAGE_BUCKET_NAME
cf set-env $CGHOSTNAME_BACKEND JWT_KEY $JWT_KEY
cf set-env $CGHOSTNAME_BACKEND DJANGO_SU_NAME $DJANGO_SU_NAME
