-- AUTOMATICALLY GENERATED FILE ON 2025-05-05 09:47:57
-- DO NOT EDIT - Your changes will be overwritten
-- Generated by generate_admin_views.py

-- SQL view for admin_ssp_m5 schema
-- Transformations applied:
--   * DATE_OF_BIRTH transformed to AGE calculation (as integer)

CREATE OR REPLACE VIEW "admin_ssp_m5" AS SELECT "RecordType","RPT_MONTH_YEAR","CASE_NUMBER","FAMILY_AFFILIATION","DATE_OF_BIRTH",-- Calculate AGE_FIRST: Age as of the first day of the reporting month
        CASE
            WHEN "DATE_OF_BIRTH" ~ '^[0-9]{8}$' AND
                    -- Validate year (reasonable range)
                    CAST(SUBSTRING("DATE_OF_BIRTH" FROM 1 FOR 4) AS INTEGER) BETWEEN 1900 AND
                    EXTRACT(YEAR FROM CURRENT_DATE) AND
                    -- Validate month (01-12)
                    CAST(SUBSTRING("DATE_OF_BIRTH" FROM 5 FOR 2) AS INTEGER) BETWEEN 1 AND 12 AND
                    -- Validate day (01-31)
                    CAST(SUBSTRING("DATE_OF_BIRTH" FROM 7 FOR 2) AS INTEGER) BETWEEN 1 AND 31 AND
                    -- Validate RPT_MONTH_YEAR format (YYYYMM)
                    "RPT_MONTH_YEAR"::TEXT ~ '^[0-9]{6}$'
            THEN
                -- Simple calculation: (end_date - start_date) / 365.25
                ROUND(
                    EXTRACT(EPOCH FROM (
                        -- Calculate the difference in days between last day of reporting month and birth date
                        (DATE_TRUNC('MONTH', TO_DATE(
                            SUBSTRING("RPT_MONTH_YEAR"::TEXT FROM 1 FOR 4) || '-' ||
                            SUBSTRING("RPT_MONTH_YEAR"::TEXT FROM 5 FOR 2) || '-01',
                            'YYYY-MM-DD'
                        ))) - 
                        TO_DATE(
                            SUBSTRING("DATE_OF_BIRTH" FROM 1 FOR 4) || '-' ||
                            SUBSTRING("DATE_OF_BIRTH" FROM 5 FOR 2) || '-' ||
                            SUBSTRING("DATE_OF_BIRTH" FROM 7 FOR 2),
                            'YYYY-MM-DD'
                        )
                    )) / (365.25 * 86400), -- Convert seconds to years (86400 seconds per day)
                    1  -- Round to 1 decimal place
                )
            ELSE NULL
        END AS "AGE_FIRST",-- Calculate AGE_LAST: Age as of the last day of the reporting month
        CASE
            WHEN "DATE_OF_BIRTH" ~ '^[0-9]{8}$' AND
                    -- Validate year (reasonable range)
                    CAST(SUBSTRING("DATE_OF_BIRTH" FROM 1 FOR 4) AS INTEGER) BETWEEN 1900 AND
                    EXTRACT(YEAR FROM CURRENT_DATE) AND
                    -- Validate month (01-12)
                    CAST(SUBSTRING("DATE_OF_BIRTH" FROM 5 FOR 2) AS INTEGER) BETWEEN 1 AND 12 AND
                    -- Validate day (01-31)
                    CAST(SUBSTRING("DATE_OF_BIRTH" FROM 7 FOR 2) AS INTEGER) BETWEEN 1 AND 31 AND
                    -- Validate RPT_MONTH_YEAR format (YYYYMM)
                    "RPT_MONTH_YEAR"::TEXT ~ '^[0-9]{6}$'
            THEN
                -- Simple calculation: (end_date - start_date) / 365.25
                ROUND(
                    EXTRACT(EPOCH FROM (
                        -- Calculate the difference in days between last day of reporting month and birth date
                        (DATE_TRUNC('MONTH', TO_DATE(
                            SUBSTRING("RPT_MONTH_YEAR"::TEXT FROM 1 FOR 4) || '-' ||
                            SUBSTRING("RPT_MONTH_YEAR"::TEXT FROM 5 FOR 2) || '-01',
                            'YYYY-MM-DD'
                        )) + INTERVAL '1 MONTH - 1 day') - 
                        TO_DATE(
                            SUBSTRING("DATE_OF_BIRTH" FROM 1 FOR 4) || '-' ||
                            SUBSTRING("DATE_OF_BIRTH" FROM 5 FOR 2) || '-' ||
                            SUBSTRING("DATE_OF_BIRTH" FROM 7 FOR 2),
                            'YYYY-MM-DD'
                        )
                    )) / (365.25 * 86400), -- Convert seconds to years (86400 seconds per day)
                    1  -- Round to 1 decimal place
                )
            ELSE NULL
        END AS "AGE_LAST","SSN","RACE_HISPANIC","RACE_AMER_INDIAN","RACE_ASIAN","RACE_BLACK","RACE_HAWAIIAN","RACE_WHITE","SEX","REC_OASDI_INSURANCE","REC_FEDERAL_DISABILITY","REC_AID_TOTALLY_DISABLED","REC_AID_AGED_BLIND","REC_SSI","MARITAL_STATUS","RELATIONSHIP_HOH","PARENT_MINOR_CHILD","NEEDS_OF_PREGNANT_WOMAN","EDUCATION_LEVEL","CITIZENSHIP_STATUS","EMPLOYMENT_STATUS","AMOUNT_EARNED_INCOME","AMOUNT_UNEARNED_INCOME", 
    data_files.section,
    data_files.version,
    data_files.year,
    data_files.quarter,
    stt.name AS "STT",                                                         -- Select stt_name from the stts table
    stt.stt_code AS "STT_CODE",                                                -- Select stt_code from the stts table
    stt.region_id AS "REGION"                                                  -- Select region from the stts table
FROM search_indexes_SSP_M5 M5
INNER JOIN
        data_files_datafile data_files                                             -- Join with data_files_datafile
        ON M5.datafile_id = data_files.id                              -- Join condition
    INNER JOIN (
        SELECT
            stt_id,                                                                -- Select stt_id
            section,                                                               -- Select section
            year,                                                                  -- Select fiscal_year
            quarter,                                                               -- Select fiscal_quarter
            MAX(version) AS version                                                -- Get the maximum version for each group
        FROM
            data_files_datafile                                                    -- Subquery table
        GROUP BY
            stt_id, section, year, quarter                                         -- Group by columns
    ) most_recent
        ON data_files.stt_id = most_recent.stt_id
        AND data_files.section = most_recent.section
        AND data_files.version = most_recent.version
        AND data_files.year = most_recent.year
        AND data_files.quarter = most_recent.quarter
    INNER JOIN
        stts_stt stt                                                               -- Join with the stts table (aliased as stt)
        ON data_files.stt_id = stt.id                                              -- Join condition to match stt_id
    WHERE
        data_files.year > 2020 AND                                                 -- Filter for fiscal year
        data_files.quarter in ('Q1', 'Q2', 'Q3', 'Q4')                         -- Filter for fiscal quarters
;
