server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.apps.internal:8080/loki/api/v1/push

scrape_configs:
  - job_name: ${system_env_name}
    static_configs:
    - targets:
        - localhost
      labels:
        job: ${system_env_name}
        __path__: /var/log/*log
  - job_name: ${backend_env_name}
    static_configs:
      - targets:
        - localhost
        labels:
          job: ${backend_env_name}
          __path__: /tmp/django.log
    pipeline_stages:
      - regex:
          expression:  '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?P<level>\w+) (?P<logger>\S+) (?P<message>.*)$'
      - labels:
          level:
          logger:
          message:
          time:
  - job_name: ${frontend_env_name}
    static_configs:
      - targets:
        - localhost
        labels:
          job: ${frontend_env_name}
          __path__: /var/log/nginx/access_log.log
          level: DEBUG
      - targets:
        - localhost
        labels:
          job: ${frontend_env_name}
          __path__: /var/log/nginx/error_log.log
          level: ERROR
