server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: {{ loki_push_url }}

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: {{ backend_env_name }}
    static_configs:
      - targets:
        - localhost
        labels:
          job: django
          __path__: /logs/django.log
  - job_name: {{ frontend_env_name }}
    static_configs:
      - targets:
        - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*log
  - job_name: containers
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
    - json:
        expressions:
          output: log
          stream: stream
          attrs:
    - json:
        expressions:
          tag:
        source: attrs
    - regex:
        expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
        source: tag
    - timestamp:
        format: RFC3339Nano
        source: time
    - labels:
        tag:
        stream:
        image_name:
        container_name:
        image_id:
        container_id:
    - output:
        source: output
