server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.apps.internal:8080/loki/api/v1/push

scrape_configs:
  - job_name: {{ system_env_name }}
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: {{ backend_env_name }}
    static_configs:
      - targets:
        - localhost
        labels:
          job: django
          __path__: /home/vcap/app/django.log
