server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: django
    static_configs:
      - targets:
        - localhost
        labels:
          job: django
          __path__: /logs/django.log
  - job_name: nginx
    static_configs:
      - targets:
        - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*log
