"""Schema for SSP M1 record type."""


from tdpservice.parsers.transforms import ssp_ssn_decryption_func
from tdpservice.parsers.fields import TransformField, Field
from tdpservice.parsers.row_schema import RowSchema, SchemaManager
from tdpservice.parsers import validators
from tdpservice.search_indexes.documents.ssp import SSP_M5DataSubmissionDocument
from tdpservice.parsers.util import generate_t2_t3_t5_hashes, get_t2_t3_t5_partial_hash_members


m5 = SchemaManager(
    schemas=[
        RowSchema(
            record_type="M5",
            document=SSP_M5DataSubmissionDocument(),
            generate_hashes_func=generate_t2_t3_t5_hashes,
            should_skip_partial_dup_func=lambda record: record.FAMILY_AFFILIATION in {3, 4, 5},
            get_partial_hash_members_func=get_t2_t3_t5_partial_hash_members,
            preparsing_validators=[
                validators.recordHasLength(66),
                validators.caseNumberNotEmpty(8, 19),
                validators.or_priority_validators([
                    validators.field_year_month_with_header_year_quarter(),
                    validators.validateRptMonthYear(),
                ]),
            ],
            postparsing_validators=[
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.matches(1),
                    result_field_name="SSN",
                    result_function=validators.validateSSN(),
                ),
                validators.validate__FAM_AFF__SSN(),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="RACE_HISPANIC",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="RACE_AMER_INDIAN",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="RACE_ASIAN",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="RACE_BLACK",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="RACE_HAWAIIAN",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="RACE_WHITE",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="MARITAL_STATUS",
                    result_function=validators.isInLimits(1, 5),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 2),
                    result_field_name="PARENT_MINOR_CHILD",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.isInLimits(1, 3),
                    result_field_name="EDUCATION_LEVEL",
                    result_function=validators.or_validators(
                        validators.isInStringRange(1, 16),
                        validators.isInStringRange(98, 99),
                    ),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.matches(1),
                    result_field_name="CITIZENSHIP_STATUS",
                    result_function=validators.isInLimits(1, 3),
                ),
                validators.if_then_validator(
                    condition_field_name="DATE_OF_BIRTH",
                    condition_function=validators.olderThan(18),
                    result_field_name="REC_OASDI_INSURANCE",
                    result_function=validators.isInLimits(1, 2),
                ),
                validators.if_then_validator(
                    condition_field_name="FAMILY_AFFILIATION",
                    condition_function=validators.matches(1),
                    result_field_name="REC_FEDERAL_DISABILITY",
                    result_function=validators.isInLimits(1, 2),
                ),
            ],
            fields=[
                Field(
                    item="0",
                    name="RecordType",
                    friendly_name="Record Type",
                    type="string",
                    startIndex=0,
                    endIndex=2,
                    required=True,
                    validators=[],
                ),
                Field(
                    item="3",
                    name="RPT_MONTH_YEAR",
                    friendly_name="Reporting Year and Month",
                    type="number",
                    startIndex=2,
                    endIndex=8,
                    required=True,
                    validators=[
                        validators.dateYearIsLargerThan(1998),
                        validators.dateMonthIsValid(),
                    ],
                ),
                Field(
                    item="5",
                    name="CASE_NUMBER",
                    friendly_name="Case Number",
                    type="string",
                    startIndex=8,
                    endIndex=19,
                    required=True,
                    validators=[validators.notEmpty()],
                ),
                Field(
                    item="13",
                    name="FAMILY_AFFILIATION",
                    friendly_name="Family Affiliation",
                    type="number",
                    startIndex=19,
                    endIndex=20,
                    required=True,
                    validators=[validators.isInLimits(1, 5)],
                ),
                Field(
                    item="14",
                    name="DATE_OF_BIRTH",
                    friendly_name="Date of Birth",
                    type="string",
                    startIndex=20,
                    endIndex=28,
                    required=True,
                    validators=[validators.intHasLength(8),
                                validators.dateYearIsLargerThan(1900),
                                validators.dateMonthIsValid(),
                                validators.dateDayIsValid()
                                ],
                ),
                TransformField(
                    transform_func=ssp_ssn_decryption_func,
                    item="15",
                    name="SSN",
                    friendly_name="Social Security Number",
                    type="string",
                    startIndex=28,
                    endIndex=37,
                    required=True,
                    validators=[validators.isNumber()],
                    is_encrypted=False,
                ),
                Field(
                    item="16A",
                    name="RACE_HISPANIC",
                    friendly_name="Hispanic or Latino",
                    type="number",
                    startIndex=37,
                    endIndex=38,
                    required=False,
                    validators=[validators.validateRace()],
                ),
                Field(
                    item="16B",
                    name="RACE_AMER_INDIAN",
                    friendly_name="American Indian or Alaska Native",
                    type="number",
                    startIndex=38,
                    endIndex=39,
                    required=False,
                    validators=[validators.validateRace()],
                ),
                Field(
                    item="16C",
                    name="RACE_ASIAN",
                    friendly_name="Asian",
                    type="number",
                    startIndex=39,
                    endIndex=40,
                    required=False,
                    validators=[validators.validateRace()],
                ),
                Field(
                    item="16D",
                    name="RACE_BLACK",
                    friendly_name="Black or African American",
                    type="number",
                    startIndex=40,
                    endIndex=41,
                    required=False,
                    validators=[validators.validateRace()],
                ),
                Field(
                    item="16E",
                    name="RACE_HAWAIIAN",
                    friendly_name="Native Hawaiian or Pacific Islander",
                    type="number",
                    startIndex=41,
                    endIndex=42,
                    required=False,
                    validators=[validators.validateRace()],
                ),
                Field(
                    item="16F",
                    name="RACE_WHITE",
                    friendly_name="White",
                    type="number",
                    startIndex=42,
                    endIndex=43,
                    required=False,
                    validators=[validators.validateRace()],
                ),
                Field(
                    item="17",
                    name="GENDER",
                    friendly_name="Gender",
                    type="number",
                    startIndex=43,
                    endIndex=44,
                    required=True,
                    validators=[validators.isInLimits(0, 9)],
                ),
                Field(
                    item="18A",
                    name="REC_OASDI_INSURANCE",
                    friendly_name="Received Disability Benefits: OASDI Program",
                    type="number",
                    startIndex=44,
                    endIndex=45,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="18B",
                    name="REC_FEDERAL_DISABILITY",
                    friendly_name="Received Disability Benefits: Other Federal Disability Status",
                    type="number",
                    startIndex=45,
                    endIndex=46,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="18C",
                    name="REC_AID_TOTALLY_DISABLED",
                    friendly_name="Received Disability Benefits: Permanently and Totally Disabled",
                    type="number",
                    startIndex=46,
                    endIndex=47,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="18D",
                    name="REC_AID_AGED_BLIND",
                    friendly_name="Received Disability Benefits: AABD",
                    type="number",
                    startIndex=47,
                    endIndex=48,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="18E",
                    name="REC_SSI",
                    friendly_name="Received Disability Benefits: SSI",
                    type="number",
                    startIndex=48,
                    endIndex=49,
                    required=True,
                    validators=[validators.isInLimits(1, 2)],
                ),
                Field(
                    item="19",
                    name="MARITAL_STATUS",
                    friendly_name="Marital Status",
                    type="number",
                    startIndex=49,
                    endIndex=50,
                    required=False,
                    validators=[validators.isInLimits(0, 5)],
                ),
                Field(
                    item="20",
                    name="RELATIONSHIP_HOH",
                    friendly_name="Relationship to Head-of-Household",
                    type="string",
                    startIndex=50,
                    endIndex=52,
                    required=True,
                    validators=[validators.isInStringRange(1, 10)],
                ),
                Field(
                    item="21",
                    name="PARENT_MINOR_CHILD",
                    friendly_name="Parent with Minor Child in the Family",
                    type="number",
                    startIndex=52,
                    endIndex=53,
                    required=False,
                    validators=[validators.isInLimits(0, 2)],
                ),
                Field(
                    item="22",
                    name="NEEDS_OF_PREGNANT_WOMAN",
                    friendly_name="Needs of a Pregnant Woman",
                    type="number",
                    startIndex=53,
                    endIndex=54,
                    required=False,
                    validators=[validators.isInLimits(0, 9)],
                ),
                Field(
                    item="23",
                    name="EDUCATION_LEVEL",
                    friendly_name="Educational Level",
                    type="string",
                    startIndex=54,
                    endIndex=56,
                    required=False,
                    validators=[
                        validators.or_validators(
                            validators.isInStringRange(0, 16),
                            validators.isInStringRange(98, 99),
                        ),
                        validators.notMatches("00")
                    ],
                ),
                Field(
                    item="24",
                    name="CITIZENSHIP_STATUS",
                    friendly_name="Citizenship/Immigration Status",
                    type="number",
                    startIndex=56,
                    endIndex=57,
                    required=False,
                    validators=[
                        validators.oneOf([1, 2, 3, 9]),
                    ],
                ),
                Field(
                    item="25",
                    name="EMPLOYMENT_STATUS",
                    friendly_name="Employment Status",
                    type="number",
                    startIndex=57,
                    endIndex=58,
                    required=False,
                    validators=[validators.isInLimits(0, 3)],
                ),
                Field(
                    item="26",
                    name="AMOUNT_EARNED_INCOME",
                    friendly_name="Amount of Earned Income",
                    type="string",
                    startIndex=58,
                    endIndex=62,
                    required=False,
                    validators=[validators.isInStringRange(0, 9999)],
                ),
                Field(
                    item="27",
                    name="AMOUNT_UNEARNED_INCOME",
                    friendly_name="Amount of Unearned Income",
                    type="string",
                    startIndex=62,
                    endIndex=66,
                    required=False,
                    validators=[validators.isInStringRange(0, 9999)],
                ),
            ],
        )
    ]
)
