# Generated by Django 3.2.5 on 2021-09-14 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_files', '0009_update_log_entry_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClamAVFileScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.TextField()),
                ('file_size', models.PositiveBigIntegerField(help_text='The file size in bytes')),
                ('file_shasum', models.TextField(help_text='The SHA256 checksum of the uploaded file')),
                ('result', models.CharField(choices=[('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Error')], help_text='Scan result for uploaded file', max_length=12)),
                ('data_file', models.ForeignKey(blank=True, help_text='The resulting DataFile object if this scan was clean', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='av_scans', to='data_files.datafile')),
                ('uploaded_by', models.ForeignKey(help_text='The user that uploaded the scanned file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='av_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clam AV File Scan',
            },
        ),
    ]
