# Generated by Django 3.2.5 on 2021-09-22 20:26

from django.db import migrations, models
import tdpservice.backends
import tdpservice.security.models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwaspZapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_target', models.CharField(choices=[('tdrs-backend', 'Backend'), ('tdrs-frontend', 'Frontend')], help_text='The application that was scanned', max_length=32)),
                ('html_report', models.FileField(help_text='The generated HTML ZAP Scanning Report', storage=tdpservice.backends.DataFilesS3Storage, upload_to=tdpservice.security.models.get_zap_s3_upload_path)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this scan was processed')),
                ('fail_count', models.PositiveSmallIntegerField(help_text='The number of alerts raised at FAIL level during the scan')),
                ('pass_count', models.PositiveIntegerField(help_text='The number of passed rules during the scan')),
                ('warn_count', models.PositiveIntegerField(help_text='The number of alerts raised at WARN level during the scan')),
            ],
            options={
                'verbose_name': 'OWASP ZAP Scan',
            },
        ),
    ]
