# Generated by Django 3.2.5 on 2021-09-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_files', '0009_update_log_entry_content_type'),
        ('security', '0002_owaspzapscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clamavfilescan',
            name='data_file',
            field=models.ForeignKey(blank=True, help_text='The resulting DataFile object, if this scan was clean', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='av_scans', to='data_files.datafile'),
        ),
    ]
