# Generated by Django 3.2.15 on 2025-08-21 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("security", "0003_alter_clamavfilescan_data_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEventToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            (
                                "https://schemas.openid.net/secevent/risc/event-type/account-disabled",
                                "Account Disabled",
                            ),
                            (
                                "https://schemas.openid.net/secevent/risc/event-type/account-enabled",
                                "Account Enabled",
                            ),
                            (
                                "https://schemas.openid.net/secevent/risc/event-type/account-purged",
                                "Account Purged",
                            ),
                            (
                                "https://schemas.login.gov/secevent/risc/event-type/mfa-limit-account-locked",
                                "Mfa Locked",
                            ),
                            (
                                "https://schemas.openid.net/secevent/risc/event-type/identifier-changed",
                                "Email Changed",
                            ),
                            (
                                "https://schemas.openid.net/secevent/risc/event-type/identifier-recycled",
                                "Email Recycled",
                            ),
                            (
                                "https://schemas.login.gov/secevent/risc/event-type/password-reset",
                                "Password Reset",
                            ),
                            (
                                "https://schemas.openid.net/secevent/risc/event-type/recovery-activated",
                                "Recovery Activated",
                            ),
                            (
                                "https://schemas.openid.net/secevent/risc/event-type/recovery-information-changed",
                                "Recovery Information Changed",
                            ),
                            (
                                "https://schemas.login.gov/secevent/risc/event-type/reproof-completed",
                                "Reproof Complete",
                            ),
                            ("unknown-event-type", "Unknown Event"),
                        ],
                        max_length=255,
                    ),
                ),
                ("event_data", models.JSONField()),
                ("jwt_id", models.CharField(max_length=255, unique=True)),
                ("issuer", models.CharField(max_length=255)),
                ("issued_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="securityeventtoken",
            index=models.Index(
                fields=["event_type"], name="security_se_event_t_078976_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityeventtoken",
            index=models.Index(fields=["user"], name="security_se_user_id_3fc9c6_idx"),
        ),
        migrations.AddIndex(
            model_name="securityeventtoken",
            index=models.Index(fields=["email"], name="security_se_email_73d459_idx"),
        ),
        migrations.AddIndex(
            model_name="securityeventtoken",
            index=models.Index(
                fields=["processed"], name="security_se_process_63267b_idx"
            ),
        ),
    ]
