"""Define settings classes available for environments deployed in Cloud.gov."""

import json
import logging
import os
from distutils.util import strtobool

from tdpservice.common.util import get_cloudgov_broker_db_numbers
from tdpservice.settings.common import Common

logger = logging.getLogger(__name__)


def get_json_env_var(variable_name):
    """Retrieve and serialize a JSON environment variable."""
    return json.loads(os.getenv(variable_name, "{}"))


def get_cloudgov_service_creds_by_instance_name(services, instance_name):
    """Retrieve credentials for a bound Cloud.gov service by instance name."""
    return next(
        (
            service.get("credentials", {})
            for service in services
            if service.get("instance_name") == instance_name
        ),
        {},
    )


class CloudGov(Common):
    """Base settings class for applications deployed in Cloud.gov."""

    ############################################################################
    # Variables defined in this section (denoted by a lower-case variable name)
    # will *NOT* get exposed via django.conf.settings
    # Ref: https://docs.djangoproject.com/en/3.2/topics/settings/#creating-your-own-settings  # noqa

    # Cloud.gov exposes variables for the application and bound services via
    # VCAP_APPLICATION and VCAP_SERVICES environment variables, respectively.
    cloudgov_app = get_json_env_var("VCAP_APPLICATION")
    APP_NAME = os.getenv("CGAPPNAME_BACKEND", "{}")

    cloudgov_services = get_json_env_var("VCAP_SERVICES")

    cloudgov_space = cloudgov_app.get("space_name", "tanf-dev")
    cloudgov_space_suffix = cloudgov_space.strip("tanf-")
    cloudgov_name = cloudgov_app.get("name").split("-")[
        -1
    ]  # converting "tdp-backend-name" to just "name"
    # TODO: does this break prod?
    services_basename = cloudgov_space_suffix

    database_creds = get_cloudgov_service_creds_by_instance_name(
        cloudgov_services["aws-rds"], f"tdp-db-{services_basename}"
    )
    s3_datafiles_creds = get_cloudgov_service_creds_by_instance_name(
        cloudgov_services["s3"], f"tdp-datafiles-{services_basename}"
    )
    s3_staticfiles_creds = get_cloudgov_service_creds_by_instance_name(
        cloudgov_services["s3"], f"tdp-staticfiles-{services_basename}"
    )
    keycloak_creds = get_cloudgov_service_creds_by_instance_name(
        cloudgov_services.get("user-provided", []),
        f"tdp-keycloak-{services_basename}",
    )

    ############################################################################

    INSTALLED_APPS = (*Common.INSTALLED_APPS, "gunicorn")

    ###
    # Dynamic Database configuration based on cloud.gov services
    #
    env_based_db_name = f"tdp_db_{cloudgov_name}"

    logger.debug("css: " + cloudgov_space_suffix)
    if cloudgov_space_suffix == "prod":
        db_name = database_creds["db_name"]
    else:
        db_name = env_based_db_name

    DATABASES = {
        "default": {
            "ENGINE": "django_prometheus.db.backends.postgresql",
            "NAME": db_name,
            "USER": database_creds["username"],
            "PASSWORD": database_creds["password"],
            "HOST": database_creds["host"],
            "PORT": database_creds["port"],
        }
    }

    # Username or email for initial Django Super User
    DJANGO_SUPERUSER_NAME = os.getenv(
        "DJANGO_SU_NAME", "alexandra.pennington@acf.hhs.gov"
    )

    # Localstack is always disabled in a cloud.gov environment
    USE_LOCALSTACK = False

    ###
    # Store user uploaded data files in designated S3
    #
    STORAGES = {
        "default": {
            "BACKEND": "tdpservice.backends.DataFilesS3Storage",
        },
        "staticfiles": {
            "BACKEND": "tdpservice.backends.StaticFilesS3Storage",
        },
    }
    AWS_S3_DATAFILES_ACCESS_KEY = s3_datafiles_creds["access_key_id"]
    AWS_S3_DATAFILES_SECRET_KEY = s3_datafiles_creds["secret_access_key"]
    AWS_S3_DATAFILES_BUCKET_NAME = s3_datafiles_creds["bucket"]
    AWS_S3_DATAFILES_ENDPOINT = f'https://{s3_datafiles_creds["endpoint"]}'
    AWS_S3_DATAFILES_REGION_NAME = s3_datafiles_creds["region"]

    ###
    # Store files generated by collectstatic for the admin site in designated S3
    #
    STATICFILES_STORAGE = "tdpservice.backends.StaticFilesS3Storage"
    AWS_S3_STATICFILES_ACCESS_KEY = s3_staticfiles_creds["access_key_id"]
    AWS_S3_STATICFILES_SECRET_KEY = s3_staticfiles_creds["secret_access_key"]
    AWS_S3_STATICFILES_BUCKET_NAME = s3_staticfiles_creds["bucket"]
    AWS_S3_STATICFILES_ENDPOINT = f'https://{s3_staticfiles_creds["endpoint"]}'
    AWS_S3_STATICFILES_REGION_NAME = s3_staticfiles_creds["region"]

    MEDIA_URL = (
        f"{AWS_S3_STATICFILES_ENDPOINT}/{AWS_S3_STATICFILES_BUCKET_NAME}/{APP_NAME}/"
    )

    # Cookie settings
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_DOMAIN = ".app.cloud.gov"
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"

    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REDIRECT_EXEMPT = [r"^prometheus/.*"]
    SECURE_SSL_REDIRECT = True

    # Redis
    if "aws-elasticache-redis" in cloudgov_services:
        redis_settings = cloudgov_services["aws-elasticache-redis"][0]["credentials"]
        REDIS_URI = f"rediss://:{redis_settings['password']}@{redis_settings['host']}:{redis_settings['port']}"

        brokers = get_cloudgov_broker_db_numbers(cloudgov_name)

        CELERY_BROKER_URL = REDIS_URI + "/" + brokers["celery"]
        CELERY_RESULT_BACKEND = REDIS_URI + "/" + brokers["celery"]
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            }
        }

        for c, n in brokers["caches"].items():
            CACHES[c] = {
                "BACKEND": "django.core.cache.backends.redis.RedisCache",
                "LOCATION": f"{REDIS_URI}/{n}",
                "KEY_PREFIX": f"{cloudgov_name}-{c}",  # does include "prod" for prod, can specify per env in classes below
            }

        CACHES["throttle"] = {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"{REDIS_URI}/{brokers['caches']['feature-flags']}",
            "KEY_PREFIX": f"{cloudgov_name}-throttle",
        }

    OTEL_EXPORTER_OTLP_ENDPOINT = os.getenv(
        "OTEL_EXPORTER_OTLP_ENDPOINT", "http://tempo.apps.internal:4317"
    )

    # Keycloak Sync
    KEYCLOAK_SYNC_ENABLED = bool(os.getenv("KEYCLOAK_SYNC_ENABLED", ""))
    KEYCLOAK_SERVER_URL = os.getenv(
        "KEYCLOAK_SERVER_URL", "http://keycloak.apps.internal:8080"
    )
    KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM", "tdp")
    KEYCLOAK_ADMIN_CLIENT_ID = keycloak_creds.get(
        "admin_client_id", os.getenv("KEYCLOAK_ADMIN_CLIENT_ID", "tdp-django")
    )
    KEYCLOAK_ADMIN_CLIENT_SECRET = keycloak_creds.get(
        "admin_client_secret", os.getenv("KEYCLOAK_ADMIN_CLIENT_SECRET", "")
    )
    KEYCLOAK_DJANGO_CLIENT_ID = keycloak_creds.get(
        "django_client_id", os.getenv("KEYCLOAK_DJANGO_CLIENT_ID", "tdp-django")
    )
    KEYCLOAK_DJANGO_CLIENT_SECRET = keycloak_creds.get(
        "django_client_secret", os.getenv("KEYCLOAK_DJANGO_CLIENT_SECRET", "")
    )

    # mozilla-django-oidc: derive OIDC settings from Keycloak URLs
    OIDC_RP_CLIENT_ID = KEYCLOAK_DJANGO_CLIENT_ID
    OIDC_RP_CLIENT_SECRET = KEYCLOAK_DJANGO_CLIENT_SECRET

    # In Cloud.gov, the browser-facing URL is the public Keycloak route
    KEYCLOAK_BROWSER_URL = os.getenv("KEYCLOAK_BROWSER_URL", KEYCLOAK_SERVER_URL)

    _KC_REALM_URL = f"{KEYCLOAK_SERVER_URL}/realms/{KEYCLOAK_REALM}"
    _KC_BROWSER_REALM_URL = f"{KEYCLOAK_BROWSER_URL}/realms/{KEYCLOAK_REALM}"
    KEYCLOAK_ISSUER = os.getenv("KEYCLOAK_ISSUER", _KC_BROWSER_REALM_URL)

    # Browser-facing endpoints (user's browser is redirected here)
    OIDC_OP_AUTHORIZATION_ENDPOINT = (
        f"{_KC_BROWSER_REALM_URL}/protocol/openid-connect/auth"
    )
    OIDC_OP_LOGOUT_ENDPOINT = f"{_KC_BROWSER_REALM_URL}/protocol/openid-connect/logout"

    # Server-to-server endpoints (Django backend talks to Keycloak within Docker)
    OIDC_OP_TOKEN_ENDPOINT = f"{_KC_REALM_URL}/protocol/openid-connect/token"
    OIDC_OP_USER_ENDPOINT = f"{_KC_REALM_URL}/protocol/openid-connect/userinfo"
    OIDC_OP_JWKS_ENDPOINT = f"{_KC_REALM_URL}/protocol/openid-connect/certs"

class Development(CloudGov):
    """Settings for applications deployed in the Cloud.gov dev space."""

    # https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts
    ALLOWED_HOSTS = [".app.cloud.gov", ".apps.internal"]
    CORS_ORIGIN_ALLOW_ALL = False
    CORS_ALLOWED_ORIGINS = [
        "https://tdp-frontend-raft.app.cloud.gov",
        "https://tdp-frontend-a11y.app.cloud.gov",
        "https://tdp-frontend-qasp.app.cloud.gov",
    ]
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_METHODS = (
        "GET",
        "PATCH",
        "POST",
    )


class Staging(CloudGov):
    """Settings for applications deployed in the Cloud.gov staging space."""

    ALLOWED_HOSTS = [
        "tdp-frontend-staging.acf.hhs.gov",
        "tdp-frontend-develop.acf.hhs.gov",
        ".apps.internal",
    ]
    CORS_ALLOWED_ORIGINS = [
        "https://tdp-frontend-staging.acf.hhs.gov",
        "https://tdp-frontend-develop.acf.hhs.gov",
    ]
    CORS_ORIGIN_ALLOW_ALL = False
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_METHODS = (
        "GET",
        "PATCH",
        "POST",
    )
    LOGIN_GOV_CLIENT_ID = os.getenv(
        "OIDC_RP_CLIENT_ID",
        "urn:gov:gsa:openidconnect.profiles:sp:sso:hhs:tanf-proto-staging",
    )

    # Cookie settings
    SESSION_COOKIE_DOMAIN = ".acf.hhs.gov"

    # Cloud.gov SET integration settings
    LOGIN_GOV_SET_AUDIENCE = os.getenv(
        "LOGIN_GOV_SET_AUDIENCE",
        "https://tdp-frontend-staging.acf.hhs.gov/v1/security/event-token/",
    )


class Production(CloudGov):
    """Settings for applications deployed in the Cloud.gov production space."""

    # TODO: Add production ACF domain when known
    ALLOWED_HOSTS = [
        "tanfdata.acf.hhs.gov",
        "tdp-frontend-prod.app.cloud.gov",
        ".apps.internal",
    ]

    LOGIN_GOV_CLIENT_ID = os.getenv(
        "OIDC_RP_CLIENT_ID", "urn:gov:gsa:openidconnect.profiles:sp:sso:hhs:tanf-prod"
    )
    ENABLE_DEVELOPER_GROUP = False

    # Cookie settings
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_DOMAIN = ".acf.hhs.gov"
    SESSION_COOKIE_PATH = "/;HttpOnly"

    MIDDLEWARE = ("tdpservice.middleware.SessionMiddleware", *Common.MIDDLEWARE)

    # CORS allowed origins
    CORS_ALLOWED_ORIGINS = ["https://tanfdata.acf.hhs.gov"]
    CORS_ORIGIN_ALLOW_ALL = False
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_METHODS = (
        "GET",
        "PATCH",
        "POST",
    )

    # OTEL
    OTEL_ENABLED = bool(strtobool(os.getenv("OTEL_ENABLED", "yes")))
    OTEL_EXPORTER_OTLP_ENDPOINT = os.getenv(
        "OTEL_EXPORTER_OTLP_ENDPOINT", "http://tempo.apps.internal:4317"
    )

    # Cloud.gov SET integration settings
    LOGIN_GOV_SET_AUDIENCE = os.getenv(
        "LOGIN_GOV_SET_AUDIENCE",
        "https://tanfdata.acf.hhs.gov/v1/security/event-token/",
    )
    LOGIN_GOV_WELL_KNOWN_CONFIG = os.getenv(
        "LOGIN_GOV_WELL_KNOWN_CONFIG",
        "https://secure.login.gov/.well-known/openid-configuration",
    )
