-- AUTOMATICALLY GENERATED FILE ON 2025-04-21 16:33:53
-- DO NOT EDIT - Your changes will be overwritten
-- Generated by generate_user_views.py

-- SQL view for ssp_m1 schema
-- Transformations applied:


CREATE OR REPLACE VIEW "ssp_m1" AS SELECT "RecordType","RPT_MONTH_YEAR","CASE_NUMBER","STRATUM","ZIP_CODE","DISPOSITION","NBR_FAMILY_MEMBERS","FAMILY_TYPE","TANF_ASST_IN_6MONTHS","RECEIVES_SUB_HOUSING","RECEIVES_MED_ASSISTANCE","RECEIVES_FOOD_STAMPS","AMT_FOOD_STAMP_ASSISTANCE","RECEIVES_SUB_CC","AMT_SUB_CC","CHILD_SUPPORT_AMT","FAMILY_CASH_RESOURCES","CASH_AMOUNT","NBR_MONTHS","CC_AMOUNT","CHILDREN_COVERED","CC_NBR_MONTHS","TRANSP_AMOUNT","TRANSP_NBR_MONTHS","TRANSITION_SERVICES_AMOUNT","TRANSITION_NBR_MONTHS","OTHER_AMOUNT","OTHER_NBR_MONTHS","SANC_REDUCTION_AMT","WORK_REQ_SANCTION","FAMILY_SANC_ADULT","SANC_TEEN_PARENT","NON_COOPERATION_CSE","FAILURE_TO_COMPLY","OTHER_SANCTION","RECOUPMENT_PRIOR_OVRPMT","OTHER_TOTAL_REDUCTIONS","FAMILY_CAP","REDUCTIONS_ON_RECEIPTS","OTHER_NON_SANCTION","WAIVER_EVAL_CONTROL_GRPS", 
    data_files.section,
    data_files.version,
    data_files.year,
    data_files.quarter,
    stt.name AS "STT",                                                         -- Select stt_name from the stts table
    stt.stt_code AS "STT_CODE",                                                -- Select stt_code from the stts table
    stt.region_id AS "REGION"                                                  -- Select region from the stts table
FROM search_indexes_SSP_M1 M1
INNER JOIN
        data_files_datafile data_files                                             -- Join with data_files_datafile
        ON M1.datafile_id = data_files.id                              -- Join condition
    INNER JOIN (
        SELECT
            stt_id,                                                                -- Select stt_id
            section,                                                               -- Select section
            year,                                                                  -- Select fiscal_year
            quarter,                                                               -- Select fiscal_quarter
            MAX(version) AS version                                                -- Get the maximum version for each group
        FROM
            data_files_datafile                                                    -- Subquery table
        GROUP BY
            stt_id, section, year, quarter                                         -- Group by columns
    ) most_recent
        ON data_files.stt_id = most_recent.stt_id
        AND data_files.section = most_recent.section
        AND data_files.version = most_recent.version
        AND data_files.year = most_recent.year
        AND data_files.quarter = most_recent.quarter
    INNER JOIN
        stts_stt stt                                                               -- Join with the stts table (aliased as stt)
        ON data_files.stt_id = stt.id                                              -- Join condition to match stt_id
    WHERE
        data_files.year > 2020 AND                                                 -- Filter for fiscal year
        data_files.quarter in ('Q1', 'Q2', 'Q3', 'Q4')                         -- Filter for fiscal quarters
;