# Generated by Django 5.2.14 on 2026-06-29 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("etl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etlartifact",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL Artifact",
                "verbose_name_plural": "ETL Artifacts",
            },
        ),
        migrations.AlterModelOptions(
            name="etlnoderun",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL Node Run",
                "verbose_name_plural": "ETL Node Runs",
            },
        ),
        migrations.AlterModelOptions(
            name="etlpipelinerun",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ETL Pipeline",
                "verbose_name_plural": "ETL Pipelines",
            },
        ),
        migrations.AlterModelOptions(
            name="etlqaresult",
            options={
                "ordering": ["pipeline_run_id", "id"],
                "verbose_name": "ETL QA Result",
                "verbose_name_plural": "ETL QA Results",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweight",
            options={
                "verbose_name": "Statistical Weight",
                "verbose_name_plural": "Statistical Weights",
            },
        ),
        migrations.AlterModelOptions(
            name="statisticalweightscasecount",
            options={
                "ordering": [
                    "pipeline_run_id",
                    "count_kind",
                    "stt_code",
                    "reporting_month",
                    "stratum",
                ],
                "verbose_name": "Statistical Weights Case Count",
                "verbose_name_plural": "Statistical Weights Case Counts",
            },
        ),
    ]
