###########################################################################
# GitHub Action Workflow
# On pull request or changes to scripts/commands to any branch, 
# triggers the full build and test pipeline.
# CLARIFY THIS
#
# Step 0: make PR from your branch into develop, or make changes on your 
#         branch to non-documentation files in scripts or commands.sh and 
#         push changes to your remote branch.
#
# Step 1: Makes a request to the V2 CircleCI API to initiate the project,
#         which will filter based upon build_and_test_backend and 
#         build_and_test_frontend to run the workflow/jobs listed here:
#           build-and-test:[
#             test-backend,
#             test-frontend,
#             test-e2e
#           ]
#
#         Leverages the open source GitHub Action:
#           https://github.com/promiseofcake/circleci-trigger-action
###########################################################################
name: Build and test All for PRs and when scripts/commands change
on:
  push:
    branches_ignore:
    - develop
    paths:
    - 'scripts/**'
    - 'commands.sh'
  pull_request:
    paths_ignore:
    - 'docs/**'
    - '**.md'
    - '**.txt'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
jobs:
  build_and_test_all:
    runs-on: ubuntu-latest
    name: Initiate deploy job in CircleCI
    steps:
    - uses: actions/checkout@v2
    - name: Circle CI Deployment Trigger
      id: curl-circle-ci
      uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLE_CI_V2_TOKEN }}
        project-slug: raft-tech/TANF-app
        branch: ${{ github.ref }}
        payload: '{"build_and_test_backend": true, "build_and_test_frontend": true}'
