###########################################################################
# GitHub Action Workflow
# On push to develop or master branches, triggers the make erd util pipeline.
#
# Step 0: merge to develop or master
#
# Step 1: Makes a request to the V2 CircleCI API to initiate the project,
#         which will filter based upon terraform: true flag 
#         to run the workflow/jobs listed here:
#           build-and-test:[
#             enable-versioning-for-s3-buckets
#           ]
#
#         Leverages the open source GitHub Action:
#           https://github.com/promiseofcake/circleci-trigger-action
###########################################################################
name: Run The Utility Make ERD Pipeline
on:
  push:
    branches:
      - develop
      - master
    jobs:
      make_erd:
        runs-on: ubuntu-latest
        name: Make ERD
        steps:
        - uses: actions/checkout@v2
        - name: Circle CI Deployment Trigger
          id: curl-circle-ci
          uses: promiseofcake/circleci-trigger-action@v1
          with:
            user-token: ${{ secrets.CIRCLE_CI_V2_TOKEN }}
            project-slug: raft-tech/TANF-app
            branch: ${{ github.ref }}
            payload: '{"util_make_erd": true}'