name: Build and Publish Image to GHCR

on:
  pull_request:
    branches: 
      - main
    types: 
      - opened
      - synchronize
      - reopened

env:
  BACKEND_DIR: tdrs-backend
  FRONTEND_DIR: tdrs-frontend
  BACKEND_NAME: tdp-backend
  FRONTEND_NAME: tdp-frontend

jobs:
  build-and-push-image:
    if: startsWith(github.head_ref, 'release/') || startsWith(github.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract Metadata for Backend
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ BACKEND_NAME }}
          tags: |
            type=ref,event=pr,pattern=(release|hotfix)/(?<version>v\d+\.\d+\.\d+(?:-[\w\-]+)?),group=version
            type=raw,value=latest

      - name: Extract Metadata for Frontend
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ FRONTEND_NAME }}
          tags: |
            type=ref,event=pr,pattern=(release|hotfix)/(?<version>v\d+\.\d+\.\d+(?:-[\w\-]+)?),group=version
            type=raw,value=latest

      - name: Ensure tag was extracted
        if: steps.meta_backend.outputs.tags == '' || steps.meta_frontend.outputs.tags == ''
        run: |
          echo: "Failed to extract a valid semver tag. Please check that the branch name has the correct syntax"
          exit 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BACKEND_DIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.lables }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FRONTEND_DIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.lables }}
