name: Build and Publish Image to GHCR

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  BACKEND_DIR: tdrs-backend
  FRONTEND_DIR: tdrs-frontend
  BACKEND_NAME: tdp-backend
  FRONTEND_NAME: tdp-frontend
  VERSION: ${{ github.ref_name }}

jobs:
  build-and-push-image:
    # TODO: Uncomment before merging this PR
    if: github.event.base_ref == 'refs/heads/main' || github.event.base_ref == 'refs/heads/3498-migrate-raft-ofa-to-ghcr'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure package repo is all lowercase
        id: set-registry-owner
        run: |
          echo "REGISTRY_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BACKEND_DIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.BACKEND_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.BACKEND_NAME }}:latest
          build-args: |
            REGISTRY_OWNER=${{ env.REGISTRY_OWNER }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/TANF-app
            org.opencontainers.image.description=Backend API Service for TDP.
            org.opencontainers.image.licenses=CC0-1.0

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FRONTEND_DIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.FRONTEND_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.FRONTEND_NAME }}:latest
          build-args: |
            REGISTRY_OWNER=${{ env.REGISTRY_OWNER }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/TANF-app
            org.opencontainers.image.description=Frontend Service for TDP.
            org.opencontainers.image.licenses=CC0-1.0
