name: Build and Publish Image to GHCR

on:
  push:
    branches:
      - develop
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BACKEND_DIR: tdrs-backend
  FRONTEND_DIR: tdrs-frontend
  BACKEND_NAME: tdp-backend
  FRONTEND_NAME: tdp-frontend
  DEPLOY_ENV: |
    ${{
      github.ref_name == 'develop' && 'develop' ||
      github.ref_name == 'main' && 'staging' ||
      github.ref_name == 'master' && 'production'
    }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Derive build tag
        id: meta
        run: |
          DATE=$(date +%F)
          TAG="${DATE}_build-${{ github.run_number }}_${{ github.sha }}"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BACKEND_DIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_NAME }}-${{ env.DEPLOY_ENV }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_NAME }}-${{ env.DEPLOY_ENV }}:${{ steps.meta.outputs.tag }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FRONTEND_DIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.FRONTEND_NAME }}-${{ env.DEPLOY_ENV }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.FRONTEND_NAME }}-${{ env.DEPLOY_ENV }}:${{ steps.meta.outputs.tag }}
